### ISSUE TITLE
artisan db:seed --tenant=1 throwing ReflectionException

### ISSUE THREAD

**Issue by bkintanar** [hyn/multi-tenant#100]
Seeding tenant database doesn't seem to be working. @Luceos maybe we could also add test cases for this.

```
☁  application [master] ⚡ php artisan db:seed --tenant=1
Seeding for 1: app-testin


  [ReflectionException]
  Class UsersTableSeeder does not exist


☁  application [master] ⚡
```

**Comment by bkintanar** [comment]
Idiot move. needed to run `composer dump-autoload`

**Comment by luceos** [comment]
actually: https://github.com/hyn/multi-tenant/issues/33 😀
