### ISSUE TITLE
Migration to another server

### ISSUE THREAD

**Issue by jefelon** [hyn/multi-tenant#1009]
__Description of your feature__

Imagine that I have to migrate to another server and I have 800 tenants, how should I pass the mysql users? for so many users?

__Proposed behavior__

use one user for all mysql connections

__Current behavior__

create the same accounts manually on the new server, it is unsustainable

---
__Information__

- hyn/multi-tenant version:
- laravel version:

**Comment by fletch3555** [comment]
Migrate the `system` database... run `artisan tenancy:recreate` (https://tenancy.dev/docs/hyn/5.6/commands#recreate-command) to recreate the tenant databases, database users, and tenant filesystem directories... then import the tenant databases to overwrite the ones that got created.  This will leave the users untouched and maintain access to the appropriate tenant database.
