### ISSUE TITLE
Spreading tenants over multiple servers is not working

### ISSUE THREAD

**Issue by vpratfr** [hyn/multi-tenant#1010]
We are moving our tenants to separate DB servers (we used to store their data on the same server as the system DB).

I thought the managed_by_database_connection column was meant for that purpose.

However, when creating a new tenant, we seem to have an issue when the CREATE USER statement is getting executed.

It is supposed to use the system connection as the code suggests:

```
$connection->system($event->website)->statement($user) 

// (src/Generators/Webserver/Database/Drivers/MariaDB.php)
```

However, when looking at this implementation, we noticed that this made use of the managed_by_database_connection column when not null

```
return $this->db->connection(
            $website && $website->managed_by_database_connection ?
                $website->managed_by_database_connection :
                $this->systemName()
        )
```

Am I missing something?

**Comment by fletch3555** [comment]
Are you the one I answered the other day in our forum?  If so, we can probably close this to avoid duplication.
