### ISSUE TITLE
Load providers from Tenants

### ISSUE THREAD

**Issue by Krato** [hyn/multi-tenant#102]
Hello again.

I'm trying to load custom services providers for each Tenant.

Following your [dummy-tenant-example-provider](https://github.com/hyn/dummy-tenant-website/blob/master/providers.php) it doesn't load.

I have this on my `providers.php` inside `storage/multi-tenant/3-prueba-web/providers.php`: 

``` php
<?php
/**
 * Use App::register to register any service provider
 *
 * Please note you can use this file to load any other code you wish
 */
dump("hello");
App::register('EricLagarda\Temporal\TemporalServiceProvider');
```

And in `HomeController@index' is:

``` php
if(class_exists('\Temporal')){
    $myToken = \Temporal::create('1',1); //$expireTime in minutes to expire
    dump($myToken);
} else {
    dump('Temporal is not loaded');
}
```

I'm testing this simple package: https://github.com/Krato/temporal.

But is not working. Shows `Hello`, but provider is not loading. If I have same provider in `config/app.php` it works great, but not from `tenant/providers.php`.

Thanks!

**Comment by luceos** [comment]
Can you try it with the following:

```
<?php
/**
 * Use App::register to register any service provider
 *
 * Please note you can use this file to load any other code you wish
 */
dump("hello");
use EricLagarda\Temporal\TemporalServiceProvider;
App::register(TemporalServiceProvider::class);
```

**Comment by Krato** [comment]
It's working 😀 

Thanks!
