### ISSUE TITLE
Command "tenancy:migrate" is not defined.

### ISSUE THREAD

**Issue by jonquintero** [hyn/multi-tenant#1023]
Hello, how are you? after update to support L9, I tried to run php artisan tenancy:migrate and I got:

 Command "tenancy:migrate" is not defined.

  Did you mean one of these?
      tenancy🔑update
      tenancy:recreate
      tenancy:run
And I have a module to create tenants and I got this error:

 "message": "The command "tenancy:migrate" does not exist.",
    "exception": "Symfony\Component\Console\Exception\CommandNotFoundException",
    "file": "C:\laragon\www\clowdwork-web-jwt\vendor\laravel\framework\src\Illuminate\Console\Application.php",
    "line": 190,
Any idea? Thanks

**Comment by luceos** [comment]
@jonquintero sorry to see this so late. Did you ever get this resolved?

**Comment by jonquintero** [comment]
Hi @luceos unfortunately I couldn't, I had to do a clean installation of laravel, install the package and copy the controllers, models, etc., that I already had

**Comment by luceos** [comment]
Okay but is this resolved now? After the clean install?

**Comment by jonquintero** [comment]
Yes, in clean install, everything is fine, thanks for ask

**Comment by wojtekxtx** [comment]
Although @jonquintero had it resolved, you @luceos should make sure this is no longer an issue.

**Comment by mattvb91** [comment]
After upgrading to laravel 9 im having the same issue. I can only see the following commands:

```
 tenancy
  tenancy:key:update            Update tenant users passwords.
  tenancy:recreate              Recreate all tenant databases present in the system db.
  tenancy:run                   Run commands on all tenant databases present in the system db.

```
