### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by jonquintero** [hyn/multi-tenant#1035]
Hi, any one know if this package will be updated to support Laravel 10

Thanks

- hyn/multi-tenant version: 5.8
- laravel version: 10

**Comment by ArlonAntonius** [comment]
We would love to upgrade it to Laravel 10 😄 

I will do an attempt this week to upgrade it to Laravel 10. Maybe someone from the community will beat me to it, as it might be as simple as updating the dependencies.

**Comment by jonquintero** [comment]
> We would love to upgrade it to Laravel 10 😄
> 
> I will do an attempt this week to upgrade it to Laravel 10. Maybe someone from the community will beat me to it, as it might be as simple as updating the dependencies.

Thank you for your kindness in answering

**Comment by mattvb91** [comment]
@ArlonAntonius any luck with it?

**Comment by manuleo9** [comment]
Do you have any news about this? @ArlonAntonius

**Comment by geeky3** [comment]
@ArlonAntonius  I submitted a PR to upgrade to laravel 10, but ``` CI Circle CI/CD``` fails due to php ``` 8.0 ``` in docker.

Please find screenshot attached.

![tenancy_err_2](https://user-images.githubusercontent.com/31416195/236668781-7b15b503-94f9-4fe9-bb86-3c7857fd3140.png)

![tenancy_err_1](https://user-images.githubusercontent.com/31416195/236668784-27e57e59-ba64-4cca-b4e4-95ffe88f77fd.png)

**Comment by bkintanar** [comment]
@geeky3 you can try to edit the .circleci/config.yml in your branch to fix this.

**Comment by PouleR** [comment]
@geeky3 have you also seen the PR from @ArlonAntonius ? (https://github.com/tenancy/multi-tenant/pull/1036)
Would be great if this package can be used in Laravel 10 environments

**Comment by geeky3** [comment]
Hi, Paul,
I had missed PR from  @ArlonAntonius <https://github.com/ArlonAntonius>
 completely.

So shall I cancel my PR ? (Please feel free to educate me as I am a
beginner to open source contributions).

**Comment by PouleR** [comment]
> Hi, Paul, I had missed PR from @ArlonAntonius <https://github.com/ArlonAntonius> completely. So shall I cancel my PR ? (Please feel free to educate me as I am a beginner to open source contributions).
> […](#)

I think one of them should be merged so we can upgrade to Laravel 10. @ArlonAntonius what are your plans regarding Laravel 10 and these PR's ?

**Comment by ArlonAntonius** [comment]
> > Hi, Paul, I had missed PR from @ArlonAntonius <https://github.com/ArlonAntonius> completely. So shall I cancel my PR ? (Please feel free to educate me as I am a beginner to open source contributions).
> > […](#)
> 
> I think one of them should be merged so we can upgrade to Laravel 10. @ArlonAntonius what are your plans regarding Laravel 10 and these PR's ?

I'm open to merge anything, but I think the CI should at least pass to make sure we don't break anything in a user's application 😅 I tried fixing the CI in my PR, but was unable to do so in the limited time I have.
If one of you has the time to work on it, feel free to work on it 😉

**Comment by geeky3** [comment]
@ArlonAntonius as I am new to open source I have following issue.

I am not seeing any pull request option. Is there any thing else to set in my repo ?

![Screenshot(3)](https://github.com/tenancy/multi-tenant/assets/31416195/6cbfbad7-3fea-4aaf-8dce-2893b4a6f175)

![Screenshot(2)](https://github.com/tenancy/multi-tenant/assets/31416195/39ca1303-c704-4d3b-a975-ddabb5cb3a82)

**Comment by geeky3** [comment]
@ArlonAntonius I have closed my pull request.

I see that there is already a pull request for upgrade to laravel 10 and have passed the checks.

**Comment by mattvb91** [comment]
@ArlonAntonius could you add a tag please?

**Comment by PouleR** [comment]
@jonquintero: ArlonAntonius just released a new version with Laravel 10 support!

**Comment by jonquintero** [comment]
@PouleR @ArlonAntonius Thanks for all support

**Comment by ArlonAntonius** [comment]
All of you did the work, thanks for the collaborations of all of you 😊
