### ISSUE TITLE
[2.x] Migrations running on master db

### ISSUE THREAD

**Issue by bkintanar** [hyn/multi-tenant#105]
When issuing a `php artisan multi-tenant:setup` command, it runs migration files on the master database and creates a blank database for the tenant. What should be the correct command in order not to run the migrations on the master db but instead on the tenant db?

```
☁  application [master] ⚡php artisan multi-tenant:setup --tenant=PORTAL --email=bertrand@email.com --hostname=app.local.dev --webserver=no`

Welcome to hyn multi tenancy.
Copied Directory [/vendor/hyn/multi-tenant/database/migrations] To [/database/migrations]
Publishing complete for tag []!
Copied Directory [/vendor/hyn/multi-tenant/database/migrations] To [/database/migrations]
Publishing complete for tag []!
First off, migrations for the packages will run.
Not running tenancy migration, falling back on native laravel migrate command due to missing tenant option.
Migration table created successfully.
```

**Comment by luceos** [comment]
the `--tenant` option takes either:
- `all` for all tenants
- `1` or any website ID
- `1,2,3` any comma delimited array of website ID's

See: https://github.com/hyn/multi-tenant/blob/2.x/src/Tenancy/Traits/TenantDatabaseCommandTrait.php

The above does not answer your errors though.

The SetupCommand does not run migrations automatically for tenants, but it does so for system-related packages. Which makes sense to ensure the hostnames, websites and customers table (for instance) exist before continuing the setup.

**Comment by bkintanar** [comment]
Yeah, my problem is that when I have an empty master db, and no tenant dbs then I ran multi-tenant:setup, it runs ALL the migrations into the master db, and creates these unnecessary tables in the master db. Then creates this empty tenant database.

The screenshot below which it rans migrations is referring to the master database. which runs these unrelated migration to the master db.
<img width="1114" alt="screen shot 2016-06-14 at 5 33 07 am" src="https://cloud.githubusercontent.com/assets/685928/16023987/0d0e8d64-31f2-11e6-9805-f47b274f0307.png">

**Comment by luceos** [comment]
If you want to force migrations onto the tenant use:

```
            Schema::connection(DatabaseConnection::tenantConnectionName())->create(
```

**Comment by bkintanar** [comment]
Thanks @Luceos I'll just add that on the migrations.

**Comment by luceos** [comment]
Also as said before the SetupCommand is not meant to create Tenants on the fly. You have to create your own logic to do so. The setup command is meant to install/set up your instance. Seen the number of issues related to that so far, I might actually prevent these soon.

**Comment by bkintanar** [comment]
I understand now that I need to run `php artisan migrate --tenant=` to run the migrations for the tenant.

**Comment by bkintanar** [comment]
it's now giving me `Database [tenant] not configured.` when there's no tenant created yet.

**Comment by bkintanar** [comment]
I added a try catch but I don't like the solution. :)

**Comment by luceos** [comment]
You should create a TenantObserver (called ModelObserver in L-speak) in your code that listens to the created event and then fire a queue job that runs migrations. Make that job delayed by a few seconds so the other listeners are done.
