### ISSUE TITLE
[2.x] Disable creation of tenant directories in app_storage

### ISSUE THREAD

**Issue by bkintanar** [hyn/multi-tenant#106]
I would like to request this feature, since not all multi-tenant setup would require this feature, I would like to have it turned off.

😄

**Comment by bkintanar** [comment]
should I add a `disallowed` param on tenant creation?

**Comment by luceos** [comment]
You should update the config file.

**Comment by bkintanar** [comment]
I see. thanks @Luceos

**Comment by luceos** [comment]
You can now add a new option to the setupcommand called --tenant-config with a path to a pre-filled config php file. It will be copied over the published config. Also if you leave out this option, the setup command will ask you to confirm to move on, giving you opportunity to manually edit the published files.
