### ISSUE TITLE
Installing for laravel 5.2

### ISSUE THREAD

**Issue by Trexology** [hyn/multi-tenant#107]
when i follow the guide in https://hyn.readme.io/docs/installation:
`composer require hyn/multi-tenant`
it complain that the package does not support laravel 5.1

when attempting to add `"hyn/multi-tenant": "2.*"` to composer.json
it complain the php version requirement is >= 7.0

Is that the really the requirement to use this package???

**Comment by luceos** [comment]
Yes, PHP 7 is now the standard for all upcoming releases. Multi tenancy is meant to be running on its own VM anyway, so switching that in production shouldn't be all too complicated. The downside is you probably also need to switch in development, you can use vagrant/homestead to make that working as well...

**Comment by deleugpn** [comment]
@Luceos  

> Multi tenancy is meant to be running on its own VM anyway

does this mean I'll have a problem using it on a shared host running cPanel?

**Comment by luceos** [comment]
@Deleugpn it is possible, but you are responsible to map the hostnames to your installation. Also I have never tested this on a shared environment, so you will probably run into more issues.
