### ISSUE TITLE
Override the tenant database dynamically

### ISSUE THREAD

**Issue by hisenbergguj** [hyn/multi-tenant#116]
foreach(Website::all() as $website) {
$website->database->setCurrent();
$user = User::all();
dd($user);
}
why this will return data of current website[Tenant] itself even though I have change database connection?

**Comment by luceos** [comment]
What model is User extending? It would be helpful to know more about your set up than just this.

**Comment by MithrandirDK** [comment]
Should be corrected with #174 and the added DB::purge() in setCurrent() so give it a go.
