### ISSUE TITLE
document v 5.x

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#121]
Create a new documentation tree in readme.io for version 2.x.

- [ ] Change links in code to refer to new documentation page http://laravel-tenancy.com

Some things that need documentation:
- [ ] where are 3.x and 4.x
- [ ] backward incompatibilities
- [x] compatibility with latest Laravel and PHP 7 only
- [x] replace tenant with customer where needed
- [x] replace old namespace MultiTenant with new Tenancy
- [x] replace MultiTenantServiceProvider with TenancyServiceProvider
- [x] in all github links that refer to master branch, replace master with 2.x
- [x] explain the additions to the SetupCommand
- [ ] projects applying 1.x, 2.x and 3.x
- [ ] how to scale with this package
- [ ] use cases
- [ ] queues
- [ ] scheduled jobs
- [ ] unit tests
- [ ] custom artisan commands
- [ ] the tenancy package flow:
  - [x] how is the tenant decided upon
  - [x] what is the middleware doing
  - [ ] document how global vs localized works

**Comment by MithrandirDK** [comment]
May I suggest to add documentation on the following topics:
1. Queues - anything to do differently in a multi-tenant setup
2. Scheduled jobs - anything to do differently in a multi-tenant setup
3. Unit tests - how to do them in a multi-tenant setup (see [#154](https://github.com/hyn/multi-tenant/issues/154) )
4. Custom artisan commands - how to make them multi-tenant aware (implement the --tenant=[id(s)] option)

**Comment by luceos** [comment]
@MithrandirDK good points, will append them when I have the chance.

**Comment by luceos** [comment]
obsolete, but keeping for 3.x roadmap considerations

**Comment by haxoman** [comment]
It is abviously not working with laravel 5.4, I can't install with apache 2.4, php 7.1

**Comment by luceos** [comment]
@haxoman please open a new issue to report that, I'll gladly help you make it work. Make sure to include more information, eg the version of tenancy, your `tenancy.php` and `webserver.php` config would be helpful too.

**Comment by haxoman** [comment]
@luceos 
Hi thanks for this,

well first of all, 

php artisan vendor:deploy --tag tenancy -> that one not working, even I replace deploy to publish, not working.

And I can't do anything without installing by composer require hyn/multi-tenant
So I run:
> composer require hyn/multi-tenant

and it gives me after all as following:
```
Problem 1
    - hyn/multi-tenant 2.0.1 requires laravel/framework ~5.3.0 -> satisfiable by laravel/framework[5.3.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.31, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9] but these conflict with your requirements or minimum-stability.
    - hyn/multi-tenant 2.0.0 requires laravel/framework ~5.3.0 -> satisfiable by laravel/framework[5.3.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.31, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9] but these conflict with your requirements or minimum-stability.
    - Installation request for hyn/multi-tenant ^2.0 -> satisfiable by hyn/multi-tenant[2.0.0, 2.0.1].


Installation failed, reverting ./composer.json to its original content.
```

finally, I followed your installation process at https://github.com/hyn/multi-tenant.
It doesn't make any sense, keeps giving me an error:

hope this helps

Cheers
Danny
