### ISSUE TITLE
Language folder is replaced

### ISSUE THREAD

**Issue by dakshhmehta** [hyn/multi-tenant#122]
Hello,

recently I am working on a hotel booking system, created as SaaS. When I started using hyn. My language files are broken.

While dig into the code, I found in Tenant Directory handler, we create the folders and replace the lang folder to point towards the tenant's lang folder, excluding resources/lang folder.

Now, all my languages needs to be copied manually, even after no changes to tenant specific is required.

I know one solution could be to just make 'lang' => true in exclude array of config.  But, my concern is why it isn't possible to load languages from multiple folders just like we do for configs.

**Comment by luceos** [comment]
Hi @dakshhmehta maybe we can extend the logic, so that in case the `lang` config param is a string we'll use that as a language namespace? Would that help you out?
