### ISSUE TITLE
Configuring on 2.0

### ISSUE THREAD

**Issue by Keiron-BWS** [hyn/multi-tenant#130]
I've clean installed Laravel 5.2, then pulled in multi-tenant v2 (by lowering my stability required to beta to get v2).

But when I run the setup:

`sudo php artisan multi-tenant:setup --tenant=EXAMPLE --email=foo@example.com --hostname=example.com --webserver=nginx`

All I get is:
`[Symfony\Component\Console\Exception\RuntimeException]
  The "--tenant" option does not exist.`

Am I doing something wrong here?

**Comment by bkintanar** [comment]
The docs isn't updated. You need to be using `--customer` instead of `--tenant`

**Comment by luceos** [comment]
[Updated the readme](https://hyn.readme.io/v2.0/docs/configuration#run-setup) to reflect these changes.

**Comment by bkintanar** [comment]
@Luceos that version of readme isn't published yet.

**Comment by luceos** [comment]
made it public, but not yet default 👍
