### ISSUE TITLE
Can't locate TenantModel

### ISSUE THREAD

**Issue by Keiron-BWS** [hyn/multi-tenant#131]
I might be looking in completely the wrong place here.

I'm using some existing packages, but I want then to run in all the tenant sites, the problem is they automatically use the .env database connection and clearly we want them to use the tenant connection. I "think" I've got the databases migrating correctly.

So I've tried replacing Eloquent in config/app.php
'Eloquent'  => Hyn\MultiTenant\Abstracts\Models\TenantModel::class,

That didn't seem to work, so I went for forking the packages and changing the Models to extend from the TenantModel as described here https://hyn.readme.io/v2.0/docs/eloquent-facade-tenant-system-model

But no matter what I do I can't seem to get my TenantModel.php (in app) to find it's parentModel..

`use Hyn\MultiTenant\Abstracts\Models\TenantModel as ParentModel;`

Am I doing something wrong, or barking up completely the wrong tree for what I'm trying to achieve with multi-tenant.

**Comment by bkintanar** [comment]
Actually that part of the docs is once again not updated yet. You need to be pulling in Tenancy and not MultiTenant.. so `Hyn\Tenancy\Abstracts\Models\TenantModel`.

sorry.

**Comment by Keiron-BWS** [comment]
Perfect, that works now I need to work out why it's not finding my tenant database connection

**Comment by luceos** [comment]
Updated that page in v2 readme. We're in the process of rewriting it.

**Comment by luceos** [comment]
@Keiron-BWS please open a new issue related to that tenant db connection if it's still an issue. We'll gladly assist were possible.
