### ISSUE TITLE
unable to install/update hyn package 1.0

### ISSUE THREAD

**Issue by hisenbergguj** [hyn/multi-tenant#137]
on executing following command

composer require hyn/multi-tenant

I will receive following error :   

```
Updating dependencies (including require-dev)
  - Installing hyn-me/framework (0.4.0)
    Downloading: Failed
    Failed to download hyn-me/framework from dist: The "https://api.github.com/repos/hyn-me/framework/zipball/347784b8257099c661419d280f45662a2d3497c8" file could not be downloaded (
HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing hyn-me/framework (0.4.0)
    Cloning 347784b8257099c661419d280f45662a2d3497c8

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Failed to clone https://github.com/hyn-me/framework.git via https, ssh protocols, aborting.
  - https://github.com/hyn-me/framework.git
    Cloning into 'E:\Ampps\www\managetrainings4u\SourceCode\vendor\hyn-me\framework'...
    remote: Invalid username or password.
    fatal: Authentication failed for 'https://github.com/hyn-me/framework.git/'
  - git@github.com:hyn-me/framework.git
    Cloning into 'E:\Ampps\www\managetrainings4u\SourceCode\vendor\hyn-me\framework'...
    Host key verification failed.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimi
ze-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
```

**Comment by luceos** [comment]
You still have the old package installed:

edit your composer.json file and rename `hyn-me/multi-tenant` to `hyn/multi-tenant` then do a composer update. After that change the version constraint in the file.

**Comment by luceos** [comment]
Please re-open if this was not the solution.

**Comment by appningsdev** [comment]
![composer-hynerror](https://cloud.githubusercontent.com/assets/15102213/23404442/0e7bf384-fddb-11e6-83be-0c97b33f86e1.png)
I dont think this is fixed yet or probably not working at this moment, I am trying to require 2 packages

> "hyn/multi-tenant": "1.0.1"
> "hyn/management-interface": "0.5.5"

Inmy composer.json I get the above mentioned error. and also it will fallback to github where it fails to authenticate similar like in the above bug. Kindly check my screenshot.

**Comment by luceos** [comment]
I can no longer provide support for version 1. In addition the management interface has been dropped.

**Comment by appningsdev** [comment]
Ya i knew you guys had stopped supporting the 1.x version but that is the only one compatible with Laravel 5.1 which is actually a LTS. sad to see you guys not supporting :( Atleast can u suggest me an alternative in what other way i can load this package to my existing 5.1 laravel app

**Comment by luceos** [comment]
You are still including the wrong package or you have `hyn-me/framework` in your composer file. If you require `hyn/multi-tenant:1.*` it should load `hyn/framework` not `hyn-me/framework`, see
https://github.com/hyn/multi-tenant/blob/1.x/composer.json#L19

**Comment by luceos** [comment]
Just did a test by running:

```
composer require hyn/multi-tenant:1.*
```

And it worked perfectly.

**Comment by appningsdev** [comment]
I tried what you said no luck, I even cleared composer cache and tried installing in a seperate folder freshly out of my project no luck I still get same error. Any how thank you very much i really liked your package .

**Comment by luceos** [comment]
can you post your composer.json?

**Comment by appningsdev** [comment]
here is the link https://codeshare.io/2BAKEx

**Comment by luceos** [comment]
Drop this from the composer.json and it will work:

```
    "config": {
        "preferred-install": "dist"
    }
```

**Comment by appningsdev** [comment]
Tried removing the config from composer.json! same error :( What am I doing wrong this is the first time I m facing this issue with composer

**Comment by bkintanar** [comment]
@appningsdev same error meaning it's still looking for `hyn-me/framework`?

**Comment by appningsdev** [comment]
Yes same error like in the screen shot i have posted

**Comment by bkintanar** [comment]
@appningsdev can you humor me and send me a new screenshot of the problem please...

When getting the screenshot please include the command you are running so that I can know what command you ran, and see what the error is...

Thanks

**Comment by appningsdev** [comment]
![saas-eerror](https://cloud.githubusercontent.com/assets/15102213/23447740/f8ffeb58-fe72-11e6-8ab2-204ebc5018ff.png)

**Comment by bkintanar** [comment]
@appningsdev ok. that is weird.. maybe it is a composer problem..

try this: `rm -rf vendor composer.lock`

then try to `composer update` again..

**Comment by appningsdev** [comment]
Tried that! nothing changed .
![saas-2](https://cloud.githubusercontent.com/assets/15102213/23448158/4d8956d0-fe75-11e6-8488-9b74b72dc120.png)

**Comment by bkintanar** [comment]
@appningsdev have you tried removing your home global composer directory? `~/.composer`?

I don't see why it's causing this issue.

**Comment by appningsdev** [comment]
I have never done that, how do i do it just go and delete that folder ? would that affect my project ?

**Comment by bkintanar** [comment]
it will remove any composer packages that you've installed globally. yes just delete it..

please do a backup before deleting so.

**Comment by appningsdev** [comment]
No luck!

**Comment by luceos** [comment]
@bkintanar i ran into the same issue with the old composer.json. I'm not sure why this is happening but loading the dist files results in this behaviour. Either we report this at the composer repo and hope for the best or we let this be. It's taking too much of my time already for an unsupported version.

**Comment by appningsdev** [comment]
Well is there any other alternative to your multi-tenant package compatible with Laravel 5.1.

**Comment by luceos** [comment]
Maybe this will help for seeking an [alternative](http://stackoverflow.com/questions/34201696/multiple-laravel-websites-central-codebase/34206349#34206349).

**Comment by appningsdev** [comment]
Thank you very much  :+1: .
