### ISSUE TITLE
The doc does not seem updated for "run set"

### ISSUE THREAD

**Issue by julianfox** [hyn/multi-tenant#139]
`sudo php artisan multi-tenant:setup --customer=EXAMPLE --email=foo@example.com --hostname=example.com --webserver=(nginx|apache|no)`

instead of

`sudo php artisan multi-tenant:setup --tenant=EXAMPLE --email=foo@example.com --hostname=example.com --webserver=(nginx|apache|no)`

**Comment by bkintanar** [comment]
@julianfox, thank you for pointing that out. I'm tasked on updating the docs. I'll make time this weekend to update as much docs as possible.

Cheers!

**Comment by bkintanar** [comment]
Also, you can check here: https://hyn.readme.io/v2.0/docs/configuration

It's published but currently not set as default.
