### ISSUE TITLE
The webserver command return an error when the website identifier is not correct (uppercase)

### ISSUE THREAD

**Issue by julianfox** [hyn/multi-tenant#140]
The webserver command return this error:

```
adduser: Please enter a username matching the regular expression configured
via the NAME_REGEX[_SYSTEM] configuration variable. Use the `--force-badname'
option to relax this check or reconfigure NAME_REGEX.
```

When I create website with "Exemple" identifier through create function of Hyn\Tenancy\Contracts\WebsiteRepositoryContract

Should I reformate or check the user input in my controller or there is a better solution to manage it?

**Comment by julianfox** [comment]
Same issue here: http://askubuntu.com/questions/232742/failed-to-create-user-due-to-regular-expression-error

It'll be great to add a check with this regex: NAME_REGEX="^[a-z][-a-z0-9_]*\$" on the identifier field of website model.

**Comment by luceos** [comment]
dropping support for running sites under their own user
