### ISSUE TITLE
Error with EloquentUserProvider

### ISSUE THREAD

**Issue by julianfox** [hyn/multi-tenant#141]
I just followed this recommendation:
https://hyn.readme.io/docs/eloquent-facade-tenant-system-model

But now I get this error when I try to login with a tenant hostname:
`FatalThrowableError in EloquentUserProvider.php line 114:
Type error: Argument 1 passed to Illuminate\Auth\EloquentUserProvider::validateCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of App\User given, called in /home/vagrant/contests/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php on line 387`

Otherwise the register work perfectly (the user is saved in the tenant database).

Also when I try to login through my default domain (HYN_MULTI_TENANCY_HOSTNAME) I got this error:
Database [tenant] not configured.

**Comment by julianfox** [comment]
I just fixed the first issue with:

```
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Notifications\Notifiable;

class User extends TenantModel implements AuthenticatableContract, CanResetPasswordContract
{
    use Notifiable;
    use Authenticatable, CanResetPassword;

```

**Comment by julianfox** [comment]
But I have no idea how to fix the second issue... Is it possible to login with users in the system database through the default domain ?

**Comment by luceos** [comment]
Did you manage to solve this? My apologies for the lack of response.
