### ISSUE TITLE
Error: 502 Bad Gateway

### ISSUE THREAD

**Issue by julianfox** [hyn/multi-tenant#142]
I get error: 502 Bad Gateway when I visite the url of new tenant just after creation.
The webserver command is successfully processed with a queue running as root.

I have to do:
`Vagrant reload`

For fix the issue

**Comment by luceos** [comment]
Yes vagrant works differently with the webserver because it configures webserver related stuff during provisioning. This is not something we will be supporting.

**Comment by deleugpn** [comment]
What is the proper supported way to setup a development environment with this package and achieve at least two different Hello World homepage?

**Comment by luceos** [comment]
You can use vagrant, but you'd have to apply changes to your vagrant machines when you add new hosts using `vagrant reload`. Please understand the webserver changes made by this package are reset if you provision the virtual machine anew.
