### ISSUE TITLE
How to re-run a new customer?

### ISSUE THREAD

**Issue by deleugpn** [hyn/multi-tenant#145]
I'm new to the package and I have been going through the whole documentation to try and setup my first "Hello World Hyn Multi Tenant" project. Problem is I just ran the `php artisan queue:work` without root privileges, which made the job disappear and the queue to fail.

Now I have set the `failed-table` to avoid this in the future, but I'd like to know if it's possible to setup a website that has already been added to the database and I just want to automatically run the web server configuration (job) again.

Thanks for your attention.

**Comment by luceos** [comment]
You can regenerate the webserver related files by using:

```
php artisan webserver:toolbox --update-configs
```

Hope that helps.

**Comment by luceos** [comment]
No answer so far, please re-open if needed.

**Comment by deleugpn** [comment]
Sorry I forgot to answer. That was exactly what I wanted at the time. Thanks.
