### ISSUE TITLE
502 Bad Gateway on nginx (Homstead with PHP 7)

### ISSUE THREAD

**Issue by deleugpn** [hyn/multi-tenant#146]
When trying to setup my first project, I was getting 502 Bad Gateway when trying to access the domain of the first tenant. Here is what I found at the logs:

```
2016/09/09 03:28:24 [crit] 1980#1980: *1 connect() to unix:/var/run/php5-fpm.hyn-9001.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.10.1, server: web-1.homestead.web, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.hyn-9001.sock:", host: "web-1.homestead.web"
```

Now, notice the **/var/run/php5-fpm.hyn-9001.sock**. I believe it should be something related to `php7.0-fpm` instead. I'm not really experienced in this matter, but I don't think my homestead with PHP 7 is running php5-fpm.

That can be found under **strage/webserver/fpm/*.conf** in the `listen` variable. This file was generated by the command in the documentation: 

```
sudo php artisan multi-tenant:setup --customer=EXAMPLE --email=foo@example.com --hostname=example.com --webserver=nginx
```

**Comment by julianfox** [comment]
I got the same error, the workaround is just to don't run php artisan queue:work as root on Homestead env (or Vagrant env)

If you do: `vagrant reload` that'll work too normally...

You'll got error in worker log but it's for a not implemented feature: https://github.com/hyn/multi-tenant/issues/143

**Comment by luceos** [comment]
I see, so the sock for 7 has probably changed, because it has the version hardcoded in 5.

**Comment by luceos** [comment]
Working on this in https://github.com/hyn/multi-tenant/tree/php-7-webserver

**Comment by luceos** [comment]
Merged into 2.x
