### ISSUE TITLE
Is there any management interface to setup tenants?

### ISSUE THREAD

**Issue by aisha90** [hyn/multi-tenant#148]
I am looking forward to use "hyn" but I want to make some points clear. Please tell me are there any limitations to use this package that will bound me in terms of development of application? 
Is there any ready to use interface to setup a new tenant or I have to develop it?
My application structure will be like separate database for each customer and single code base for all but each tenant will have customised application means different modules will be available for each customer, does this package support this feature? I have read somewhere, it will but I want to make it clear.
I will PHP Laravel framework and my template is built on bootstrap html5 and my database will be MySQL,   all these technologies are compatible with this package? I know Laravel is ofcourse compatible with hyn but I am asking about MySQL. 

My questions might seem stupid but there is some confusion and I want to clear them all before I jump into it. 

Thank you.

**Comment by luceos** [comment]
- What do you mean with limitations? It's MIT, do with it what you want.
- The "old" management interface is no longer supported in 2.x of this package. There are no plans yet to add one again.
- Adding tenants should be done from within your code, each use case is different.
- Separating databases and code per tenant is possible, using system and global code is also possible. So no worries.
- Frontend tech is irrelevant for this package.
- MySQL and any database Laravel 5+ support, this package supports.

If there's anything else that requires clarification or I missed something, please let us know.

**Comment by aisha90** [comment]
Thanks for the quick response. I am glad to know it will be great to use this package. My point # 1 about limitations is regarding to development, I want to ask Can I develop any type of application with whatever features with any kind of plugins in it or there are some limitations in this domain? Do you have a detailed documentation that explains how to start using it because I find this link for documentation https://hyn.readme.io/docs/eloquent-facade-tenant-system-model but I need more detailed one, if there is any please let me know I will very thankful to you.

**Comment by aisha90** [comment]
Please tell me this one also, here on this link https://hyn.readme.io/docs/requirements it is mentioned that it must be PHP 7+ and I have PHP 5.6, so it means it won't be compatible with mine PHP installation?

**Comment by luceos** [comment]
So far I've not heard someone complain that something envisioned was not possible due to using this package. There might be some tough work ahead depending on your goal, but with the help of ioc and laravel in general, you should be able to get there one way or another.

**Comment by aisha90** [comment]
Thanks so much Luceos for all your answers.
