### ISSUE TITLE
Unable to install hyn/multi-tenant

### ISSUE THREAD

**Issue by aisha90** [hyn/multi-tenant#149]
I am trying to install hyn package on my local server, I have latest version of laravel installed i-e; 5.3.8 and PHP verision 7. When I am installing it through this command "composer require hyn/multi-tenant" its saying installation failed. Here are the details

> C:\Windows\System32>cd c:\xampp\htdocs\sassApplication

c:\xampp\htdocs\sassApplication>composer require hyn/multi-tenant
Using version ^1.0 for hyn/multi-tenant
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hyn/framework 0.6.2 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.6.1 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.6.0 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.5.0 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.4.1 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.4.0 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.3.0 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.2.9 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.2.8 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.2.7 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.2.6 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.2.5 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.2.4 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.2.3 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.2.2 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.2.1 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.2.0 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.1.7 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.1.6 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.1.5 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.1.4 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - hyn/framework 0.1.3 requires laravel/framework ~5.1.0 -> satisfiable by la
ravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v
5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v
5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v
5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38,
v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.5, v5.1.6, v5.1.7, v5.
1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - Conclusion: remove laravel/framework v5.3.8
    - Conclusion: don't install laravel/framework v5.3.8
    - hyn/multi-tenant 1.0.0 requires hyn/framework \* -> satisfiable by hyn/fram
ework[0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.2.0, 0.2.1, 0.2.
2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.3.0, 0.4.0, 0.4.1, 0.5.0,
0.6.0, 0.6.1, 0.6.2].
    - hyn/multi-tenant 1.0.1 requires hyn/framework \* -> satisfiable by hyn/fram
ework[0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.2.0, 0.2.1, 0.2.
2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.3.0, 0.4.0, 0.4.1, 0.5.0,
0.6.0, 0.6.1, 0.6.2].
    - hyn/framework 0.1.0 requires illuminate/support 5.0.\* -> satisfiable by il
luminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - hyn/framework 0.1.1 requires illuminate/support 5.0.\* -> satisfiable by il
luminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - hyn/framework 0.1.2 requires illuminate/support 5.0.\* -> satisfiable by il
luminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5
.3.8
    - don't install illuminate/support v5.0.22|don't install laravel/framework v
5.3.8
    - don't install illuminate/support v5.0.25|don't install laravel/framework v
5.3.8
    - don't install illuminate/support v5.0.26|don't install laravel/framework v
5.3.8
    - don't install illuminate/support v5.0.28|don't install laravel/framework v
5.3.8
    - don't install illuminate/support v5.0.33|don't install laravel/framework v
5.3.8
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5
.3.8
    - Installation request for laravel/framework (locked at v5.3.8, required as
5.3.*) -> satisfiable by laravel/framework[v5.3.8].
    - Installation request for hyn/multi-tenant ^1.0 -> satisfiable by hyn/multi
-tenant[1.0.0, 1.0.1].

Installation failed, reverting ./composer.json to its original `content.

Here is my composer.json

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3._"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9._",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1._",
        "symfony/dom-crawler": "3.1._"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\Foundation\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\Foundation\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

Looking forward for your response.

Thank you

**Comment by aisha90** [comment]
anyone? who can help me with this issue?

**Comment by julianfox** [comment]
Try to add this version to your composer.json
`"hyn/multi-tenant": "2.0.*@dev"`

And do:
`composer update`

The version 1.0 is not compatible with Laravel 5.3

**Comment by aisha90** [comment]
Thanks @julianfox  for your reply. But please can you tell me where should I add `"hyn/multi-tenant": "2.0.*@dev"` this line in composer.json?

**Comment by julianfox** [comment]
Here

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "hyn/multi-tenant": "2.0.*@dev",
    ...
```

**Comment by luceos** [comment]
use the following in your composer.json:

```
"prefer-stable": true,
"minimum-stability": "beta",
```

Drop the last comma in case of being the last entry.

Then try installing hyn/multi-tenant again.

**Comment by aisha90** [comment]
Thank @Luceos  and @julianfox solution worked for me. hyn installed successfully. It's working like a charm. The package is just awesome. Thank you.

**Comment by julianfox** [comment]
@Luceos is it not preferable to use 2.0.*@dev only on the package instead of "minimum-stability": "beta" globally ?

**Comment by luceos** [comment]
You have to use that in combination with `prefer-stable`, in that case it's safe. Adding @dev will actually include the branch - not a tagged moment in time - because the branch has a branch-alias. If you do this any commit that we make is pulled in on an update and .. I don't work with stable branches 😄  , I work with tagging/versioning.

**Comment by julianfox** [comment]
Good to know ;-)
