### ISSUE TITLE
Simplification of the (already quite simple) multitenancy

### ISSUE THREAD

**Issue by MithrandirDK** [hyn/multi-tenant#150]
Hi and thank you for your great work on making an unobtrusive multi-tenancy solution. It works very well in my current development, however, I am wondering if I could simplify it even more.
## The Use Case

I want to build a multi-tenancy system where tenants have separate databases and separate file storage. Cache will be shared - but with a prefix to keep cached data separate.

All tenants will run on the exact same codebase with no exceptions as it is a hosted application that should be identical for each customer, except for the data.
## The Problem

Extending Hyn\Tenancy\Abstracts\Models\TenantModel for my models was an adequate solution until I wanted to use Baum for nested sets, since that _also_ expects my models to extend Baum\Node. 
## Solution?

Looking over the TenantModel code, I wonder if there is a different way to accomplish my goals.

Since I don't need my tenant systems to use the 'hyn' database for anything else than identifying the customer, I wonder if I can strip some of the code to do just that? Would that make it simpler? Write my own service provider to identify the website and fetch the website settings, then set the tenant database connection and use that throughout the system. Would that make me vulnerable to some pitfalls, you have already considered in Hyn?

I don't want to stray too far from your excellent work as it seems like a good fit - but since I don't need some of the more advanced features, maybe I can shortcut it without giving up the entire package?

Any help or guidance is much appreciated.

**Comment by luceos** [comment]
Extend the Baum\Node and set the connection manually, the same way I did on the TenantModel.

**Comment by luceos** [comment]
If you are running everything on the Tenant database anyway, you can also simply set that connection as the default in your `database.php` 👍  much easier.

**Comment by MithrandirDK** [comment]
Thank you for your reply.

Yes, I did end up with the Baum\Node extension with a manual connection, but felt it was a little too much copy-paste of rather crucial code - so I will go with the default database method, I think. (and now I see the part, I had missed about replacing the Eloquent model via facades... Same-same with database.php default connection?)

Different questions, but also related to the Hyn settings:
1) Cache prefix... can I set a per-tenant cache prefix easily?
2) PHPUnit... can I easily simulate a specific tenant for use with unit tests?

If you wish, I can make individual issues about those questions.

**Comment by luceos** [comment]
1. You'd have to do some logic there yourself, it shouldn't be too hard with a custom service provider.
2. Check the tests written for the package, they force tenancy as well. Please note terminal/cli has no way of automatically identifying tenants.

Replacing the facade class is not quite the same as setting a default, but the effect is, yes.

**Comment by MithrandirDK** [comment]
Thank you and thank you. I'll dive back in :)
