### ISSUE TITLE
Error run php artisan migrate:reset

### ISSUE THREAD

**Issue by thandonguocmo2020** [hyn/multi-tenant#153]
Step 1: After configuration 

The directory to hold your tenant websites has been created under website.
'getent' is not recognized as an internal or external command,
operable program or batch file.
'adduser' is not recognized as an internal or external command,
operable program or batch file.
Configuration successful

Step 2 : php artisan migrate:reset

 [Doctrine\DBAL\Schema\SchemaException]
##   There is no column with name 'customer_id' on table 'websites'.

I do not know how to fix it! It Seems flawed documentation on configuring and instructions using . Please help me if you know

**Comment by luceos** [comment]
Reset has no --tenant flag so it currently does not support resetting or refreshing. This is something that still needs implementation.

**Comment by thandonguocmo2020** [comment]
You can review the database structure of the table! or there's something not right leads to the use of migration not working properly reset.

There is no column with name 'customer_id' on table 'websites'.

in 2016_06_13_202803_rename_tenants_to_customers

---

   Schema::connection(DatabaseConnection::systemConnectionName())
                ->table('websites', function (Blueprint $table) {
                    $table->renameColumn('customer_id', 'tenant_id');
                    $table->foreign('tenant_id')->references('id')->on('tenants')->onDelete('cascade');

##                 });

php artisan when running a multi-tenant: setup.

I do not use --tenant because it does not exist.

 My English is not good. wish you much help ! today I have focused heavily on multi-tenant.

**Comment by thandonguocmo2020** [comment]
khi chạy php artisan migrate:reset lần nữa. tôi gặp nhiều lỗi hơn !

D:\xampp\htdocs\laravel>php artisan migrate:reset

                                                                                                                                                                   
  [Illuminate\Database\QueryException]                                                                                                                             
  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (SQL: drop table if exists `ssl_certificates`)
                                                                                                                                                                   


  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails



  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails



D:\xampp\htdocs\laravel>

**Comment by thandonguocmo2020** [comment]
when running php artisan migrate: reset again. I met many more bugs!

D: \ xampp \ htdocs \ laravel> php artisan migrate: reset
                                                                                                                                                            
  [Illuminate \ Database \ QueryException]
  SQLSTATE [23000]: Integrity constraint violation: 1451 Can not delete or update a parent row: a foreign key constraint fails (SQL: DROP TABLE IF EXISTS `ssl_certificates`)
                                                                                                                                                                   

  [Doctrine \ DBAL \ Driver \ PDOException]
  SQLSTATE [23000]: Integrity constraint violation: 1451 Can not delete or update a parent row: a foreign key constraint fails

  [PDOException]
  SQLSTATE [23000]: Integrity constraint violation: 1451 Can not delete or update a parent row: a foreign key constraint fails

D: \ xampp \ htdocs \ laravel>

**Comment by luceos** [comment]
You cannot use reset for now, it will only reset the system database not the tenant databases. If you continue running reset yes you might run into the attempt of deleting a table that has rows which causes the above error.

What are you trying to accomplish?

**Comment by luceos** [comment]
Fixed in 5.x
