### ISSUE TITLE
Storing files

### ISSUE THREAD

**Issue by MithrandirDK** [hyn/multi-tenant#155]
How do I use the media storage path for saving files?

Directory in the Hyn package has the media path with tenant-specific sub-directory and tenant_path() returns the base path to the tenant directory - but how do I get e.g. Storage::put() to use the tenant directory? As far as I can see, it will always use storage_path() which returns standard ./storage/app

I'm sorry to bug you again with another perhaps noobish question, but it is difficult to find where I am using Laravel wrong and where I use Hyn wrong.

**Comment by luceos** [comment]
This starts to become more like a support channel for Laravel questions 😄 

If you look at the [FilesystemServiceProvider](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Filesystem/FilesystemServiceProvider.php) shipped by Laravel, you will notice it will register different disks:

``` php

        $this->app->singleton('filesystem.disk', function () {
            return $this->app['filesystem']->disk($this->getDefaultDriver());
        });
        $this->app->singleton('filesystem.cloud', function () {
            return $this->app['filesystem']->disk($this->getCloudDriver());
        });
```

We can implement the same but using `filesystem.tenant`. If you're able to send in a PR for this, that would be awesome. Otherwise I'll just put this on the todo for the stable.

**Comment by MithrandirDK** [comment]
I do apologize for the many questions, but every time I stumble across something like this, I keep thinking "I could maybe make it myself and skip the complexity" but then I instantly think "Well, Hyn is _so close_ - maybe it is just a small step to go".

Currently, I am at the file storage, but next steps will be running scheduled jobs and processing queues where I also think Hyn is so close, but not quite there, yet.

Anyway, thank you for your patience and your reply - I will see, if I can get a new disk set up and make a PR for that.

**Comment by MithrandirDK** [comment]
I have created [PR#156](https://github.com/hyn/multi-tenant/pull/156)

It is not using the singleton method because that doesn't really look like it is registering the disks, rather it is putting the already configured disks into singletons.

Instead I found that we would have to dynamically add a configuration array to filesystems.disk in order to create a new disk that can be used for Storage::disk('tenant') operations.
