### ISSUE TITLE
General approach to CLI/Artisan

### ISSUE THREAD

**Issue by MithrandirDK** [hyn/multi-tenant#157]
I have considered an approach to running artisan commands for tenants and would like to propose such an approach that hopefully would make it possible to run any artisan command in a tenant context.

**Idea**
What if we could wrap artisan commands in an... artisan command?
Meaning, a general artisan command with the --tenant option that would:
1. Load the tenant websites
2. For each website fire the artisan command

**Prerequisites**
In order to do the above, we would need to be able to reset the app and put in the context of a tenant, fire the artisan command, reset again, put in the context for the next tenant and fire that.

Would that be possible?

**Thoughts on approach**
A putenv('tenant', [ID]) before running the artisan command could allow us to pick up that environment variable in e.g. TenancyRequestHelper::hostname, look up the website and from there load a connected hostname (if that is even necessary, but I thought for completeness, we probably should always have a hostname)

The key issue would be to reset the app - or instantiate a new app for each tenant. I guess that is "just" a matter of doing what the artisan file already does, but are there pitfalls, I am not considering?

To put my thought into code, I'm thinking something like the following in a Command class

```
public function fire()
{
  $websites = $this->getWebsitesFromOption();
  foreach ($websites as $website) {
    putenv('tenant', $website->id);
    $tenantApp = require_once __DIR__.'/bootstrap/app.php';
    $kernel = $tenantApp->make(Illuminate\Contracts\Console\Kernel::class);

    $status = $kernel->handle(
       $input = new Symfony\Component\Console\Input\ArgvInput,
       new Symfony\Component\Console\Output\ConsoleOutput
     );
     $kernel->terminate($input, $status);

    // do something with $status
  }
}
```

If that works, we will suddenly be able to run all artisan commands with tenancy awareness... or what? Will there be problems with passing options through from the wrapper to the actual Command to run?

It will also not work with multiple tenants for longrunning commands such as queue workers, but that will be the subject for another discussion.

**Comment by luceos** [comment]
This is a very good idea. Some feedback:
- Environment variables should be uppercase.
- If you add this, we need to refactor the existing code as well (SetupCommand and all overruled migrate commands)

Is there anything I'm missing that needs to be refactored.. @bkintanar ?

**Comment by MithrandirDK** [comment]
I have made an attempt and it seems to work pretty well.
[artisan_multi_tenant.txt](https://github.com/hyn/multi-tenant/files/489126/artisan_multi_tenant.1.txt)

I have made it on the form
artisan multi-tenant:run {commandToRun} --tenant={1,5,all} --arguments="argument1 argument2 argument3" --options="--option1=value1 --option2=value2 --option3=value3"

using a putenv('TENANT=1'); method for identifying the tenant.

Tell me what you think.

**Comment by luceos** [comment]
Seems to be a valid implementation. Allow me to consider the benefits and drawbacks of this implementation aka I need to think about this.

**Comment by MithrandirDK** [comment]
An alternative approach would be to have a helper method somewhere that resets the environment.

As I see it, it shall:
1. set the tenant database connection
2. set the tenant directory
3. set the tenant cache prefix

this happens already in TenancyEnvironment::construct() - except that the cache prefix is only set (as far as I can see) if the cache directory exists (shouldn't this be set universally? If you are not using file cache, is the cache prefix ever set to the tenant prefix?) so perhaps instead of re-instantiating the application, we can just set env('TENANT') and re-instantiate TenancyEnvironment?

I have not tried this, yet, but I feel it should work just as well as the previously suggested method. 

(Also, it seems I have somehow not included the TenantCommand class in the patch. I'll dig it out and add it)

**Comment by bkintanar** [comment]
@Luceos I just read this today. My apologies. This is a perfect idea in contrast to the current implementation that overrides the commands.

**Comment by luceos** [comment]
@MithrandirDK aren't environment variables supposed to be fixed; so trying to set them again after being set should have no effect? Might be that dotenv actually allows overwriting the variable.

**Comment by MithrandirDK** [comment]
Might be - but I agree that environment variables are supposed to be constant.

If the TenancyEnvironment approach is viable, we can pass the hostname as an optional 2nd parameter to its constructor and just set it instead of looking it up

```
public function __construct($app, $hostname = null)
    {

...

 if ($hostname) {
            $this->hostname = $hostname;
        }
        else {
            // load hostname object or default
            $this->hostname = TenancyRequestHelper::hostname(
                $this->app->make(Contracts\HostnameRepositoryContract::class)
            );
        }
```

I'll attach the TenantCommand, I made earlier, that would have to be changed, though.
[TenantCommand.txt](https://github.com/hyn/multi-tenant/files/510945/TenantCommand.txt)

**Comment by MithrandirDK** [comment]
I have collected everything in a single patch file:
[GeneralArtisanTenancyCommand.txt](https://github.com/hyn/multi-tenant/files/513152/GeneralArtisanTenancyCommand.txt)

It allows for passing a website object to TenancyEnvironment::construct() which is picked up in the hostname detection.

Caveats:
- The syntax is a little different from normal with the --options="--option1=blah" etc. 
- Since we are inputting nested arguments and options, we may experience problems with text strings in the actual command's options. I don't have a solution to this...
- I added a progress bar to give feedback on each site's processing, but if there is output from the called command, the progress bar will duplicate with progress... I guess we would just have to live with that - or leave out the progress bar entirely (but I kinda like it :) )
- Arguments and options parsing in TenantCommand::fire() could perhaps be a little more elegant? Suggestions for improvements are welcome

**Comment by MithrandirDK** [comment]
Another thing: I have not tested if we need to do something to change cache prefix and tenant directory - I needed to do a DB::purge('tenant') in order to get the instantiated database connection to reset.

**Comment by MithrandirDK** [comment]
After looking further (and sorry for spamming) I find that we do need a 
Cache::setPrefix("{$this->laravel['config']->get('cache.prefix')}-{$website->id}");
line inside the website loop

Unfortunately, there is no way (as I see it) to re-set a Filesystem disk configuration once it has been resolved... so using Storage::disk('tenant') in a console command does not look feasible... so that's another caveat :-(

**Comment by bkintanar** [comment]
@MithrandirDK no apologies necessary. you can join us on Gitter if you think you're spamming: https://gitter.im/hyn/multi-tenant

**Comment by MithrandirDK** [comment]
I finally got around to making the patch for this and have made the PR #174
