### ISSUE TITLE
How to run the tests of the package?

### ISSUE THREAD

**Issue by deleugpn** [hyn/multi-tenant#158]
I might have a solution for issue #152, but I have never contributed to any open-source project in my life. I was hoping to learn how to do that with this. Here's what I've done so far: 

```
git clone https://github.com/hyn/multi-tenant.git multi-tenant
composer install
```

After that, I tried to run `vendor/bin/phpunit`, but I get the following error: 

```
PHPUnit 5.5.5 by Sebastian Bergmann and contributors.

PHP Warning:  Uncaught require(): Filename cannot be empty

/var/www/html/hyn/multi-tenant/src/Framework/Testing/TestCase.php:28
/var/www/html/hyn/multi-tenant/src/Framework/Testing/TestCase.php:28
/var/www/html/hyn/multi-tenant/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:91
/var/www/html/hyn/multi-tenant/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:66
/var/www/html/hyn/multi-tenant/tests/HostnameModelTest.php:26

  thrown in /var/www/html/hyn/multi-tenant/src/Framework/Testing/TestCase.php on line 28
PHP Fatal error:  Hyn\Framework\Testing\TestCase::createApplication(): Failed opening required '' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/hyn/multi-tenant/src/Framework/Testing/TestCase.php on line 28
```

Analyzing the file, I know the error is here: 

```
        if (empty($app_file)) {
            if (getenv('BUILD_DIR')) {
                $app_file = realpath(getenv('BUILD_DIR') . '/vendor/laravel/laravel/bootstrap/app.php');
            } else {
                $app_file = realpath('./bootstrap/app.php');
            }
        }
        /** @var \Illuminate\Foundation\Application $app */
        $app = require $app_file;
```

It's getting to the `require $app_file;` line with the `$app_file` variable empty. What is the proper way to get around this? What does this variable mean? should I open `phpunit.xml` and add a `BUILD_DIR` variable? What value should it have? 

The underlying goal here is to be able to run all tests, write my own test-case to allow custom-views to override specific-views, change the code-base to reflect this test and make a pull request for it.

Thank you in advance.

**Comment by luceos** [comment]
The tests I wrote only work through travis, because it requires the whole laravel framework to test the integration properly. What you can do is: 
- fork the repository to your own namespace
- clone that repository
- implement the fix
- add a test that proves the fix works
- visit github (either the package page or the package in your own namespace), it will popup a button to do a pull request
- travis will pick up your PR and automatically test the build

**Comment by luceos** [comment]
and .. welcome to open source 😁

**Comment by deleugpn** [comment]
Thanks!

Although I was not able to come up with a testing code for the simple change that could simbolize the fix on issue 152, I was able to run almost all tests successfully on my local environment with the following changes: 

```
        if (empty($app_file)) {
            if (getenv('BUILD_DIR')) {
                $app_file = realpath(getenv('BUILD_DIR') . '/vendor/laravel/laravel/bootstrap/app.php');
            } elseif (getenv('BOOTSTRAP_DIR')) {
                require_once getenv('BOOTSTRAP_DIR') . '/autoload.php'; // this is to allow local testing.
                $app_file = getenv('BOOTSTRAP_DIR') . '/app.php';
            } else {
                $app_file = realpath('./bootstrap/app.php');
            }
        }
```

That way, all I had to do was setup `phpunit.xml` to point to a clean install of Laravel:

```
    <php>
        <env name="BOOTSTRAP_DIR" value="/var/www/html/hyn/clean-laravel/bootstrap/"/>
        <env name="DB_CONNECTION" value="mysql"/>
        <env name="DB_DATABASE" value="multi-tenant-test"/>
        <env name="DB_USERNAME" value="root"/>
    </php>
```

That was not enough to get full green on all tests, but it was good enough to at least be able to write a test class and run it locally to see the results without having to rely on Travis or Pull Request. For me (with small experience in TDD), it was really important to be able to run tests locally to get a better sense of what I was doing.

**Comment by luceos** [comment]
I understand, please feel free to open a PR to add this minor change, if I'm not mistaken from what you've posted this should work next to the travis configuration.

**Comment by luceos** [comment]
@Deleugpn need further help with getting a PR done? Feel free to chat me up on gitter.im/luceos or the larachat slack.

**Comment by deleugpn** [comment]
No, we can close this as I've already managed to make the PR #159. I will soon make another one with the small snippet that helps running test code locally. Maybe we can go back to this if and when we manage to run all tests locally without any error.
