### ISSUE TITLE
Support system and tenant authentication in the package

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#160]
Quite often people are asking how to implement authentication of users that are system-wide and local. This split authentication system is quite easy to hack into Laravel authentication by overriding the authentication layer. Instead of only querying the User (tenant) model, we can natively add a Admin (system) model. Additionally we should allow enabling a specific ServiceProvider in the package that handles the authentication on that level.

**Comment by luceos** [comment]
Perhaps see if we can hook into [fort](https://github.com/rinvex/fort).

**Comment by sarmad4444** [comment]
I've been handling this in my applications. In User Model, I've setup UseTenantConnection. When the hostname isn't identified (means not a tenant), the User model uses the default connection for app. Which is the app's main DB. Even the whole auth module keeps working without any fault.
