### ISSUE TITLE
Can I add multiple users of each tenant?

### ISSUE THREAD

**Issue by aisha90** [hyn/multi-tenant#161]
Is it possible to add multiple users of one tenant/customer/company and provide them unique login credentials with your hyn package?

**Comment by luceos** [comment]
A user is simply a model (most likely the User class) which has either the System or Tenant connection. This choice defines what kind of users you have, those that can log in onto one website or those that can log into the system - and based on the logica you implemented - do more than a normal user eg log into all other sites. If you want a user to be able to log in on all sites of one customer, you most likely would have to create system Users and connect them to the customer object. The whole authentication layer implementation is up to you.

Not sure whether this answers your question, I found it a bit hard to understand.

**Comment by aisha90** [comment]
Thanks for the quick reply. You answered my question very well.

**Comment by luceos** [comment]
You meant to close this, I assume.
