### ISSUE TITLE
Error when creating new customer/tenant

### ISSUE THREAD

**Issue by aisha90** [hyn/multi-tenant#167]
When I am trying to add a new tenant, its throwing this error:

php artisan multi-tenant:setup --customer=EXAMPLE3 --email=foo@example3.com --hostname=example3.com
Welcome to hyn multi tenancy.
Copied Directory [/vendor/hyn/multi-tenant/database/migrations] To [/database/migrations]
Publishing complete for tag []!
Copied Directory [/vendor/hyn/multi-tenant/database/migrations] To [/database/migrations]
Publishing complete for tag []!
First off, migrations for the packages will run.
Not running tenancy migration, falling back on native laravel migrate command due to missing tenant option.
Nothing to migrate.
sh: adduser: command not found

  [Illuminate\Database\QueryException]  
  SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'jamtak_hyn'@'localhost' to database '5-example3-c' (SQL: create database if not exists `5-example3-c`)  

  [Doctrine\DBAL\Driver\PDOException]  
  SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'jamtak_hyn'@'localhost' to database '5-example3-c'  

  [PDOException]  
  SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'jamtak_hyn'@'localhost' to database '5-example3-c' 

Is there something that I missed during installation and setup? 

Thank you,

**Comment by bkintanar** [comment]
@aisha90 is the db user `jamtak_hyn` has a grant privilege? I'm asking this because hyn needs it's db user to have this kind of permission since it creates a user for that particular tenant you are trying to create.

**Comment by aisha90** [comment]
I granted all privileges to jamtak_hyn while creating it. Is there anything else that needs to be done to grant privileges?

**Comment by aisha90** [comment]
@bkintanar Yes, you are right it seems to be permissions issue. But I am wondering what is missing.

**Comment by bkintanar** [comment]
Can you verify the things in this screenshot?

<img width="551" alt="user_managment" src="https://cloud.githubusercontent.com/assets/685928/19550095/6ecd687a-96da-11e6-904e-10acc4978b62.png">

**Comment by aisha90** [comment]
yes, here it is

![shot](https://cloud.githubusercontent.com/assets/22116649/19550216/e24a8292-96c1-11e6-90ad-5cd8711abc1f.PNG)

**Comment by bkintanar** [comment]
I dont see create user here.

**Comment by aisha90** [comment]
Ohk. so I have to make some changes from root access. Let me try this. Thanks so much.

**Comment by mortezarajabi** [comment]
I have the same issue. I double checked the installation process and every thing is ok. @aisha90 did you fix it?

**Comment by luceos** [comment]
@mortezarajabi the system user has to have root-like access to the database to create users and databases.

**Comment by mortezarajabi** [comment]
@Luceos I even set the root user on it, but didn't get the result.

**Comment by luceos** [comment]
@mortezarajabi Did you configure the connection hyn to use these credentials?

**Comment by mortezarajabi** [comment]
.ENV
![screen shot 2017-04-18 at 1 37 18 pm](https://cloud.githubusercontent.com/assets/5724986/25123252/05b914f6-243d-11e7-930a-0ce934efa53e.png)

config/database.php
![screen shot 2017-04-18 at 1 40 25 pm](https://cloud.githubusercontent.com/assets/5724986/25123324/3d9b4e7a-243d-11e7-9008-7fb2d269ab71.png)

mysql user
![screen shot 2017-04-18 at 1 42 47 pm](https://cloud.githubusercontent.com/assets/5724986/25123354/4fcf448e-243d-11e7-8aa2-e387bb621957.png)

**Comment by luceos** [comment]
Is that user created with [grant option](https://dev.mysql.com/doc/refman/5.7/en/show-grants.html)?

**Comment by mortezarajabi** [comment]
![screen shot 2017-04-18 at 2 04 39 pm](https://cloud.githubusercontent.com/assets/5724986/25124220/52286758-2440-11e7-85c5-e8fdda8dac17.png)

**Comment by luceos** [comment]
The part behind `l...` is important :D

**Comment by mortezarajabi** [comment]
It is: GRANT ALL PRIVILEGES ON *.* TO 'hyn'@'localhost' IDENTIFIED BY PASSWORD '****' WITH GRANT OPTION

**Comment by luceos** [comment]
What is the exact error you get? @mortezarajabi

**Comment by mortezarajabi** [comment]
I have created a tenant with the name of blog. It is created successfully, but when I run the artisan 
 migration command, I get
![screen shot 2017-04-18 at 3 48 41 pm](https://cloud.githubusercontent.com/assets/5724986/25128417/eb21bc4e-244e-11e7-8a51-9bc0ed0c2e68.png)

**Comment by luceos** [comment]
@mortezarajabi a major difference between your error and the one @aisha90 gives:

```
[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'jamtak_hyn'@'localhost' to database '5-example3-c' (SQL: create database if not exists 5-example3-c)
```

Your tenancy user is trying to hit a mysql permissions table, in the above paste you see the user connecting to the tenant database. I'm not sure what is causing this right now.

**Comment by mortezarajabi** [comment]
@luceos I removed every thing and reinstall them. I also create a new user and database, and  it's working now! 
Seems it was a MySql issue.

**Comment by luceos** [comment]
Glad to hear, I was not seeing a relation to the package so that should have been a pointer.

Good luck, let us know if you run into more troubles. Closing this issue it has gone too far outside of the scope of the original report.
