### ISSUE TITLE
Can I edit the prefix of customer database?

### ISSUE THREAD

**Issue by aisha90** [hyn/multi-tenant#168]
I am trying to edit the prefix of name of customer's database. For example: name of customer's database generating is 1-example-com, I want to make it as myprefix_1_ex_com.

Is it possible? If yes, from where I can edit this option?

One more thing I am getting error 

> shh: adduser command not found

when I am adding a new tenant.

Thank you

**Comment by luceos** [comment]
For version 2.x this is not possible, sadly I have been quite stupid in hardcoding that (https://github.com/hyn/multi-tenant/blob/2.x/src/Tenancy/Tenant/DatabaseConnection.php#L80).

As the upcoming version 3.x will be vastly more flexible, I will keep it in mind! If you need this for version 2.x please send in a PR if possible, thanks.

As to the adduser issue, this is a known open issue; the WebsiteUser should not be created on creating websites.

**Comment by aisha90** [comment]
Can you please refer that issue here?

**Comment by luceos** [comment]
Yes sure, wasn't able to find it that easily either: #143
