### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by bubblemedialtd** [hyn/multi-tenant#169]
When attempting to create a new user, using the following syntax:

`sudo php artisan multi-tenant:setup --customer=BUBBLEMEDIA --email=mike@bubblemedialtd.co.uk --hostname=tenants.bubblemedialtd.co.uk --webserver=apache
`

I receive the following runtime error:

`  [RuntimeException]                       
  The "--customer" option does not exist. `

**Comment by Luceos** [comment]
Which version of the package do you use?

**Comment by bubblemedialtd** [comment]
I have now upgraded to `2.x-dev` and that issue has now been resolved.

Now a different issue is occurring...

`FatalThrowableError in WebserverServiceProvider.php line 33:
Class 'Hyn\MultiTenant\Models\Website' not found`

`laravel/framework                     v5.3.23
hyn/management-interface              0.5.5   
hyn/multi-tenant                      2.x-dev dff0380
hyn/webserver                         dev-master 6338774`

**Comment by Luceos** [comment]
please don't use the 2.x-dev constraint, better use `^2.0.0-dev.1`

**Comment by bubblemedialtd** [comment]
`[UnexpectedValueException]                                                   
  Could not parse version constraint ^2.0.0-dev.1: Invalid version string "^2  
  .0.0-dev.1"  `

Says that's an invalid version, I can't see it on the packagist either. Instead I've used `^2.0.0-beta.1`

But unfortunately the problem still exists. I'm just about to wind up a brand new instance of Laravel 5.3 and see if I can replicate the issue.

**Comment by Luceos** [comment]
My apologies it should have read:

```
^2.0.0-beta.4
```

**Comment by bubblemedialtd** [comment]
Ok, fresh install..

Laravel 5.3.23
hyn/multi-tenant 2.0.0-beta.4
hyn/webserver 0.5.3
hyn/management-interface 0.5.5

I am still greeted with the following error:

`Class 'Hyn\MultiTenant\Models\Website' not found`

**Comment by Luceos** [comment]
remove both hyn/webserver and hyn/management-interface; the first is integrated into the tenancy package and the latter is not compatible with version 2

**Comment by bubblemedialtd** [comment]
Thank you @Luceos - That resolved the issue.

**Comment by Luceos** [comment]
Good to hear, let me know if you need anything else.
