### ISSUE TITLE
php artisan multi-tenant:setup error

### ISSUE THREAD

**Issue by bubblemedialtd** [hyn/multi-tenant#170]
When attempting to run:

`sudo php artisan multi-tenant:setup --customer=BUBBLEMEDIA --email=mike@bubblemedialtd.co.uk --hostname=bubblemedia.swoolo.com --webserver=apache`

I receive the following error:

`  [Illuminate\Database\QueryException]                                                      
  SQLSTATE[HY000]: General error: 1005 Can't create table 'hyn_multi_tenancy.#sql-277c_9a'  
   (errno: 121) (SQL: alter table `tenants` add constraint `tenants_reseller_id_foreign` f  
  oreign key (`reseller_id`) references `tenants` (`id`) on delete set null) `

This happens on a fresh Laravel installation.

**Comment by Luceos** [comment]
What database driver did you have installed? Seems like it cannot create a constraint.

**Comment by Luceos** [comment]
Closing, no answer.
