### ISSUE TITLE
Unrecognised option --ingroup

### ISSUE THREAD

**Issue by bubblemedialtd** [hyn/multi-tenant#171]
When running the following multi-tenant:setup call, it returns the following error.

`sudo php artisan multi-tenant:setup --customer=APPTEST2 --email=mike@bubblemedialtd.co.uk --hostname=apptest2.swoolo.com --webserver=apache`

`adduser: unrecognized option '--ingroup'`

**Comment by bubblemedialtd** [comment]
Laravel 5.3.23
Hyn 2.0.0-beta.4

**Comment by Luceos** [comment]
What OS are you using? I highly recommend using tenancy on a bare ubuntu machine.

**Comment by bubblemedialtd** [comment]
OS is bare CentOS 7.2

**Comment by bubblemedialtd** [comment]
Loading up a bare Ubuntu machine now, will try with that.

**Comment by Luceos** [comment]
`--ingroup` is part of the code that adds a user to the machine with `adduser` might be the case that option is not available on centos.

**Comment by Luceos** [comment]
Not going to support Centos, closing.
