### ISSUE TITLE
Webserver config nginx error

### ISSUE THREAD

**Issue by bubblemedialtd** [hyn/multi-tenant#172]
After creating a couple of new users and adding the virtual host directives to the `nginx.conf`, I am experiencing the following error when starting nginx:

`Nov 17 20:06:32 app.swoolo.com nginx[8382]: nginx: [emerg] the same path name "/var/www/html/storage/multi-tenant/1-apptest-sw/cache/image" used in /var/www/html/storage/webserver/nginx/1-apptest-sw.conf:8 and in /var/www/html/storage/webserver/nginx/1-apptest-sw.conf:8`

**Comment by Luceos** [comment]
That's weird it seems it's including the nginx configuration files twice.. Did you run the setup command twice?

**Comment by Luceos** [comment]
No answer, closing.
