### ISSUE TITLE
How to use multiple database with multiple website

### ISSUE THREAD

**Issue by jaydeepakbari** [hyn/multi-tenant#176]
I have installed hyn/multi-tenant package successfully now i want to make two website with separate database but i don't know how to configure this 

i read your documentation from "https://hyn.readme.io/" but there is only how to install package 

just tell how to use code with laravel 5.3 fresh installation

**Comment by luceos** [comment]
The documentation didn't help?

https://hyn.readme.io/docs/tenants

**Comment by luceos** [comment]
As discussed on Gitter.

**Comment by jaydeepakbari** [comment]
ok got it
