### ISSUE TITLE
compatibility with laravel forge

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#189]

**Comment by Thijmen** [comment]
What makes it incompatible?

**Comment by luceos** [comment]
I am not using forge so I haven't checked whether it works with it. I see no issues, but I'd like to have it verified so it can be added to the documentation.

**Comment by gbrits** [comment]
I am using *Laravel Forge* & *Laravel Nova* and the https://github.com/tenancy/hyn-nova package that is based on this original package without any compatibility or database related issues - so I can confirm that the package is compatible. The Deployment script in your site settings will just need the `php artisan tenancy:migrate` command added to it in *Laravel Forge* for continuous development on tenants. Awesome work guys, thanks a lot.

**Comment by luceos** [comment]
Thank you for confirming @gbrits
