### ISSUE TITLE
Create tenant and Migration: DatabaseConnection create method not fire

### ISSUE THREAD

**Issue by trinvh** [hyn/multi-tenant#19]
After creating a new tenant, I tried to make a migration but the following error occurs: "Access denied for user '4-sale-beeso@localhost'.
I was looking in mysql and there's no user, no new database created before.

I follow this instruction: https://hyn.me/packages/multi-tenant

Can you tell me what I missed ?

**Comment by Luceos** [comment]
@trinvh my apologies for the late reply, must have missed this in my activity feed.

How did you setup the queue runner? Is it running as root?

**Comment by Luceos** [comment]
I've updated the documentation to reflect the latest 0.8.1 release. I've also updated the installer.

**Comment by Luceos** [comment]
From my research and questions on #internals on larachat, the transaction is not committed when the observed model events are triggered. So if you system is a bit slowish, the queued job is fired before the database entries are generated, which causes that the job cannot create the database and webserver specific configurations.
