### ISSUE TITLE
Option to run only on HTTPS

### ISSUE THREAD

**Issue by dhiva** [hyn/multi-tenant#190]
Currently the apache and nginx configurations create virtual host for both port 80 and 443. I would like to have a feature to run the app only on port 443 and forward all the requests from port 80 to 443.

**Comment by luceos** [comment]
If you set `prefer_https` to true on the `Hostname` models of choice, [this logic](https://github.com/hyn/multi-tenant/blob/2.x/src/Tenancy/Models/Hostname.php#L121) will do a redirect from within the app. I hadn't considered redirection from the server level, which makes a bit more sense eventually. A good idea for 3.x
