### ISSUE TITLE
How to switch customer to his tenant-db 

### ISSUE THREAD

**Issue by federicadellamonica** [hyn/multi-tenant#191]
Good morning,
I'm new in Laravel. I have to create a multi-tenant app where every registered user, after login, connects to his tenant database. Where can I do this?
Thanks in advance. Regards.

**Comment by luceos** [comment]
That's a very broad question. Are you able to differentiate between tenants based on separated hostnames?

**Comment by federicadellamonica** [comment]
No, I'm not able yet but I don't think it's a problem. Why?

**Comment by luceos** [comment]
Well if someone tries to log in on hostname X, this package links that user to that hostname and a hostname is connected directly to a "website" or "tenant" in this case. Nevertheless, all of it is possible. You can allow system-wide users and link them manually to tenant websites, during login a middleware can then redirect automatically if need be.

**Comment by federicadellamonica** [comment]
Well, I'll try and I'll let you know. Thanks a lot!
