### ISSUE TITLE
Help with V3.x usage

### ISSUE THREAD

**Issue by mahmouddev** [hyn/multi-tenant#196]
I need any guide to how use v 3.x as i planning to use this version in developing project similar to http://swifthr.io/

**Comment by luceos** [comment]
@mahmouddev 3.x is under active development and should not be used yet.

**Comment by mahmouddev** [comment]
@Luceos then http://swifthr.io/ use 2.0 or it is custom development , i ask because  you mentioned that http://swifthr.io/ is dependent on this package

**Comment by luceos** [comment]
If I mentioned them using this package, then yes that will be either version 1 or 2. So far noone uses 3.x, because it doesn't work yet. I'm closing in on a release though.

Development can be supported over at [patreon](http://patreon.com/tenancy).

**Comment by mahmouddev** [comment]
thanks @Luceos for clarification  , is there any time schedule for 3.0 release  ?

**Comment by luceos** [comment]
No. Without any patreon pledgers, there's no reason nor motivation for me to dedicate more time on this project. You just have to be patient 😁
