### ISSUE TITLE
hyn instalation fails on Laravel 5.4.23

### ISSUE THREAD

**Issue by mihaelacmihai** [hyn/multi-tenant#206]
- hyn/framework 0.1.3 requires laravel/framework ~5.1.0 -> satisfiable by laravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38, v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.44, v5.1.45, v5.1.46, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - Conclusion: don't install hyn/multi-tenant 1.0.1
    - Conclusion: remove laravel/framework v5.4.23
    - Installation request for hyn/multi-tenant ^1.0 -> satisfiable by hyn/multi-tenant[1.0.0, 1.0.1].
    - Conclusion: don't install laravel/framework v5.4.23
    - hyn/multi-tenant 1.0.0 requires hyn/framework * -> satisfiable by hyn/framework[0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.6.1, 0.6.2].
    - hyn/framework 0.1.0 requires illuminate/support 5.0.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - hyn/framework 0.1.1 requires illuminate/support 5.0.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - hyn/framework 0.1.2 requires illuminate/support 5.0.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.4.23
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.4.23
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.4.23
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.4.23
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.4.23
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.4.23
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.4.23
    - Installation request for laravel/framework (locked at v5.4.23, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.23].

Any suggestions?

**Comment by luceos** [comment]
Currently this package has no version compatible with Laravel 5.3 or up. The upcoming 3.x version is compatible however but has not yet been released.

See #187

**Comment by xyrintech** [comment]
Is 2.x-L-5.4 is not compatible too? 
If this is compatible, then may I know how can I install with composer?
