### ISSUE TITLE
Can't migrate with error

### ISSUE THREAD

**Issue by ozstriker** [hyn/multi-tenant#208]
Hi!

I've made everything, like described at installation manual. But I have an error when trying to migrate

> [InvalidArgumentException]
> Database [lms] not configured.

.env file has:
`
TENANCY_DEFAULT_CONNECTION=mysql
TENANCY_SYSTEM_CONNECTION_NAME=lms
TENANCY_TENANT_CONNECTION_NAME=system
TENANCY_MIGRATION_CONNECTION_NAME=tenant
`
and of course default mysql configuration.

Can't get what am I doing wrong?

Thanks for your help

/S

**Comment by luceos** [comment]
Hi @ozstriker what version of tenancy do you have installed?

Also the connection `lms`, the one configured to be your system connection has to be set up in your `database.php` of your laravel installation.

**Comment by ozstriker** [comment]
I'm using 3.0 branch with Laravel 5.4

So, I should create one more connection named `lms` at database.php with all credentials?

**Comment by luceos** [comment]
First of all 3.x is under heavy development, no version has yet been tagged, I recommend against using it unless you plan the release of your application later this year.

But yes the system connection has to be configured in your database.php in order to have a working install. Good point, I'll need to update documentation to explain that.

**Comment by ozstriker** [comment]
Yup! Just started app development and it would be released much later this year :) So I can be one of beta testers for you ;)
And YES it's migrated!!

And it would be good to have some guidelines for fresh starters how to use multi-tenancy at all. I mean, how to create tenants, how to work with core and tenant tables, etc.

Anyway thanks for your help and module!

**Comment by luceos** [comment]
@ozstriker glad to have you join in then, feel free to ask questions if you need to. And if you wish for more hands on assistance access to a private discord is granted through [patreon.com/tenancy](http://patreon.com/tenancy).
