### ISSUE TITLE
Issue with Laravel 5.4

### ISSUE THREAD

**Issue by xyrintech** [hyn/multi-tenant#211]
composer require hyn/multi-tenant 
this raises an issue for installation with Laravel 5.4 

Problem 1
    - hyn/multi-tenant 2.0.1 requires laravel/framework ~5.3.0 -> satisfiable by laravel/framework[5.3.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.31, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9] but these conflict with your requirements or minimum-stability.
    - hyn/multi-tenant 2.0.0 requires laravel/framework ~5.3.0 -> satisfiable by laravel/framework[5.3.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.31, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9] but these conflict with your requirements or minimum-stability.
    - Installation request for hyn/multi-tenant 2.x -> satisfiable by hyn/multi-tenant[2.0.0, 2.0.1].

**Comment by luceos** [comment]
Support for 5.3 and up is currently in development. Branch 2.x supports 5.3.

Relates to https://github.com/hyn/multi-tenant/issues/206

**Comment by xyrintech** [comment]
I am trying to install this on Laravel 5.4 and I believe 2.x is compatible with 5.4.
If yes, then please suggest how I can install this using composer.

**Comment by luceos** [comment]
Tenancy 2.x is compatible with Laravel 5.3 (my mistake, not 5.1). It's not compatible with Laravel 5.4.

**Comment by xyrintech** [comment]
May I know which package is compatible with 5.4?
How can we install this package i.e. 5.4 one?

**Comment by BertKooij** [comment]
There is a branch named '2.x-L-5.4' which is compatible with Laravel 5.4. You can refer to this branch by using a Alias. See [https://getcomposer.org/doc/articles/aliases.md](https://getcomposer.org/doc/articles/aliases.md) for more information. 

So simply add the following information to the end of the require part in your composer file:
`"hyn/multi-tenant": "dev-2.x-L-5.4"`

**Comment by luceos** [comment]
@xyrintech @beko1997 I recommend not using that branch. It was never finished. 3.0.0-beta.1 was tagged an has support for 5.3 and up if you want to give it a try.

See https://www.patreon.com/posts/12376707
