### ISSUE TITLE
Error for migrations and seed

### ISSUE THREAD

**Issue by xyrintech** [hyn/multi-tenant#214]
php artisan migrate --tenant=all

The "--tenant" option does not exist.

**Comment by luceos** [comment]
Hello @xyrintech what version of this package do you have installed?

**Comment by xyrintech** [comment]
2.x-L-5.4

**Comment by luceos** [comment]
That branch is not supported. Please use the beta of 3.x instead: hyn/multi-tenant:3.*, see:

https://github.com/hyn/multi-tenant/issues/215#issuecomment-312799344

**Comment by luceos** [comment]
Also see the discussion here; https://github.com/hyn/multi-tenant/issues/187

**Comment by xyrintech** [comment]
I have installed this but I don't see the documentation for 3.x

May I have the documentation for this?

**Comment by luceos** [comment]
You can use the Repositories to create websites, hostnames etc.. The documentation is still on the to-do. As to settings you can check the inline documentation in the configuration files themselves, they are quite extensive.

**Comment by xyrintech** [comment]
Thanks.
