### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#215]
@haxoman reported

Hi thanks for this,

well first of all,

php artisan vendor:deploy --tag tenancy -> that one not working, even I replace deploy to publish, not working.

And I can't do anything without installing by composer require hyn/multi-tenant
So I run:

composer require hyn/multi-tenant
and it gives me after all as following:

Problem 1
    - hyn/multi-tenant 2.0.1 requires laravel/framework ~5.3.0 -> satisfiable by laravel/framework[5.3.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.31, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9] but these conflict with your requirements or minimum-stability.
    - hyn/multi-tenant 2.0.0 requires laravel/framework ~5.3.0 -> satisfiable by laravel/framework[5.3.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.31, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9] but these conflict with your requirements or minimum-stability.
    - Installation request for hyn/multi-tenant ^2.0 -> satisfiable by hyn/multi-tenant[2.0.0, 2.0.1].

Installation failed, reverting ./composer.json to its original content.
finally, I followed your installation process at https://github.com/hyn/multi-tenant.
It doesn't make any sense, keeps giving me an error:

hope this helps

Cheers
Danny

**Comment by luceos** [comment]
Environment:

> It is abviously not working with laravel 5.4, I can't install with apache 2.4, php 7.1

**Comment by luceos** [comment]
@haxoman you can solve this by editing your `composer.json` and setting these properties:

```json
    "prefer-stable": true,
    "minimum-stability": "beta"
```

Then run:

```bash
composer require hyn/multi-tenant:3.*
```

**Comment by haxoman** [comment]
oh thanks for that.

Danny

**Comment by haxoman** [comment]
Hi @Luceos, 
than for helping me, but can u have a look what I did wrong?

my composer.json

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.4.*",
        "laravel/cashier": "~6.0",
        "laravel/spark": "*@dev",
        "baum/baum": "^1.1",
        "doctrine/dbal": "^2.5",
        "guzzlehttp/guzzle": "~5.3|~6.0",
        "imagine/imagine": "^0.6.3",
        "folklore/image": "0.3.*",
        "laravelcollective/html": "^5.2.0",
        "orchestra/tenanti": "~3.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "repositories": [
        {
            "type": "path",
            "url": "./spark"
        }
    ],
    "prefer-stable": true,
    "minimum-stability": "beta"
}

```

and I did
```
composer require hyn/multi-tenant:3.*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing phpseclib/phpseclib (2.0.6)
    Downloading: 100%         

  - Installing hyn/multi-tenant (3.0.0-beta.1)
    Downloading: 100%         

phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
phpseclib/phpseclib suggests installing ext-mcrypt (Install the Mcrypt extension in order to speed up a few other cryptographic operations.)
phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

                                                   
  [InvalidArgumentException]                       
  Database connection [tenants] is not available.  
                                                   

Script php artisan optimize handling the post-update-cmd event returned with an error

Installation failed, reverting ./composer.json to its original content.

                      
  [RuntimeException]  
  Error Output:       
                      

```

I seems I need to set up tenants envioronment before installing please help me if you can.

Thanks in advance.

**Comment by haxoman** [comment]
sorry It is my bad that I used tenanti module from another module. 
I tried to use new server with all, it is completely installed.
Thanks!

**Comment by luceos** [comment]
You successfully installed version 3 now?

**Comment by haxoman** [comment]
Yes i am following ur instructions 

D

**Comment by luceos** [comment]
Okay feel free to reopen if you need more assistance.
