### ISSUE TITLE
Database [system] not configured and migration issue

### ISSUE THREAD

**Issue by xyrintech** [hyn/multi-tenant#216]
__Description__

php artisan tenancy:install 
raises error
Database [system] not configured. 

php artisan migrate --tenant=all
raises
 The "--tenant" option does not exist. 

---

__Information__

- hyn/multi-tenant version: 3.x
- laravel version: 5.4
- database driver and version: mysql
- webserver software and version: apache
- php version: 7.0

---

**Comment by luceos** [comment]
Before installing either 

- set in your `.env` a variable `TENANCY_SYSTEM_CONNECTION_NAME` with the value being the connection name you want tenancy to use to store system information like websites, hostnames etc.
- or configure the connection `system` in your `database.php`.

**Comment by xyrintech** [comment]
That is ok, but after installation too this gives an error:

php artisan migrate --tenant=all
raises
The "--tenant" option does not exist.

**Comment by xyrintech** [comment]
Also, please advise if you have any documentation for this 3 version. 
There are couple of things which are available in 2 and seems that this is no more available. 
Like - sudo php artisan multi-tenant:setup --customer=EXAMPLE --email=foo@example.com --hostname=example.com --webserver=(nginx|apache|no)

**Comment by luceos** [comment]
Yes how to run migrations is changed and needs a documentation update. It also needs to be completed, you can use the configuration file instead to specify a folder from which migrations are ran during tenant creation.

**Comment by xyrintech** [comment]
Got it, one question, how can I specify to which tenant do we need to run migrations?

Like this:
php artisan migrate --tenant=all
raises
The "--tenant" option does not exist.

**Comment by luceos** [comment]
This functionality is not yet available in the beta.

**Comment by luceos** [comment]
Migrating command has now been made available, but only in `dev-3.x` not in a tagged version.

```
php artisan migrate --tenant
```

**Comment by xyrintech** [comment]
Thanks.

**Comment by xyrintech** [comment]
It still gives the same error - The "--tenant" option does not exist.

**Comment by luceos** [comment]
What version are you on, exactly?

Verify by looking at your composer.lock file and searching for `hyn/multi-tenant` the actual version or commit hash should be mentioned.

**Comment by xyrintech** [comment]
"hyn/multi-tenant": "3.x-dev",

**Comment by luceos** [comment]
Please check your composer.lock file for the exact version. That which you mention is your constraint which allows any version that matches it.

Most likely you are not running 3.0.0-beta.2 or the changes from the 3.x branch.

**Comment by xyrintech** [comment]
Its on 3.0.0-beta.2, lemme share with you.

**Comment by xyrintech** [comment]
"name": "hyn/multi-tenant",
            "version": "3.0.0-beta.2",

**Comment by luceos** [comment]
I've tagged beta.3, the migrate command is now available under it's own prefix:

```
php artisan tenancy:migrate
```

There's no need for a `--tenant` option anymore. Separating it will prevent further conflicts with ioc and rebinding.

**Comment by xyrintech** [comment]
Is this for all tenants or specific tenant?
Also, seems to be another tenant bug in the system:

$customer = app('Hyn\Tenancy\Repositories\CustomerRepository')->create([
        'name'=> 'some-one',
        'email' => 'guess-who@some-one.org'
    ]);

Raises - Cannot pass parameter 1 by reference

**Comment by luceos** [comment]
The migrate command runs it for all tenants. If you need to do it for specific ones I guess you would have to come up with a way to group/identify them, because the UUID generator generates lengthy string :grin:

---

Related to the error, you are looking at the wrong documentation, example implementation hasn't been yet updated in the docs for 3.x. If you look at the [code](https://github.com/hyn/multi-tenant/blob/3.x/src/Repositories/CustomerRepository.php#L52) the CustomerRepository requires a Customer object.

**Comment by luceos** [comment]
@xyrintech I just found out that the CustomRepository contract wasn't registered into IoC. I just pushed a fix and a test for it. Thanks for your patience ;)

See an example creation: https://github.com/hyn/multi-tenant/blob/3.x/tests/unit-tests/Repositories/CustomerRepositoryTest.php#L39-L44

**Comment by xyrintech** [comment]
This works, but there seems to be one another bug :)
When create customer, website and hostname:

$this->customers = $app->make(CustomerRepository::class);
    $this->websites = $app->make(WebsiteRepository::class);
    $this->hostnames = $app->make(HostnameRepository::class);
    
    $customer = new Customer();
    $customer->name = 'John Doe';
    $customer->email = 'john@doe.example';
    $customer = $this->customers->create($customer);
    
    
    $website = new Website();
    $website->uuid = 'test';
    $website->customer_id = $customer->id;
    $website = $this->websites->create($website);
    
    $hostname = new Hostname();
    $hostname->fqdn = 'test.accounting-xyrin.c9users.io';
    $hostname->force_https = false;
    $hostname->website_id = $website->id;
    $hostname->customer_id = $customer->id;
    $hostname = $this->hostnames->create($hostname);


and then we try this - php artisan tenancy:migrate

then this leads to run this package's migrations in every tenant which ideally should not be there as we keep our tenant schema standalone.

**Comment by luceos** [comment]
Use the `--path` or `--realpath` options of the migrate command to point to the migration files for tenants, also store them in a different folder. That's been found to be the best solution based on implementations of 2.x.

**Comment by ghost** [comment]
I am having the same probleme here (Database [system] not configured)

+ hyn/multi-tenant version: 5.x
+ laravel version: 5.5
+ database driver and version: mysql
+ webserver software and version: apache
+ php version: 7.0

I did configure the connection system in my  database.php
I actually follow  https://laravel-tenancy.com/documentation/introduction/   
*****
on #php artisan tenancy:install
i get Error

In DatabaseManager.php line 140:
                                     
  Database [system] not configured.

**Comment by Thijmen** [comment]
@yves93 Please create another issue for that.

**Comment by leamiko** [comment]
@yves93  in config/database.php  append below, it's ok

```
'system' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
```

**Comment by swati-clarion** [comment]
I am also getting same error on 
on #php artisan tenancy:install
i get Error
In DatabaseManager.php line 140:
Database [system] not configured.

I tried by unistalling and installing hyn/multi-tenant. Still no luck. Any help is greatly appreciated.

Thanks,

**Comment by Thijmen** [comment]
You need to configure the `system` database-connection in your `database.php`.

**Comment by swati-clarion** [comment]
I already tried this:
'system' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

Also cleared config cache using php artisan config:cache . Still same error on php artisan tenancy:install

**Comment by luceos** [comment]
@swati-clarion please post your full database.php config. And next time, please do create a new issue.

**Comment by swati-clarion** [comment]
Thanks for help.

I uninstalled and installed hyn/multi-tenant. Then added 'system' => [
'driver' => 'mysql',
'host' => env('DB_HOST', '127.0.0.1'),
'port' => env('DB_PORT', '3306'),
'database' => env('DB_DATABASE', 'forge'),
'username' => env('DB_USERNAME', 'forge'),
'password' => env('DB_PASSWORD', ''),
'unix_socket' => env('DB_SOCKET', ''),
'charset' => 'utf8mb4',
'collation' => 'utf8mb4_unicode_ci',
'prefix' => '',
'strict' => true,
'engine' => null,
],
in database.php. This sorted the issue.
