### ISSUE TITLE
Single Domain but with prefix Database

### ISSUE THREAD

**Issue by xyrintech** [hyn/multi-tenant#219]
__Description__

Is it possible to use this package for single domain but with different or prefix database?

---

**Comment by luceos** [comment]
Can you explain? You need to run one tenant that uses a different database?

**Comment by xyrintech** [comment]
What I mean is that I want to allow users to use one domain (not any subdomain) and in the back-end this package maintains the data in the single database but with prefix with it. 

Think of what Quickbooks is doing. 
They have one domain which people use to access and the user can see their own concerned data.

**Comment by luceos** [comment]
That's very much possible. You would need to [disable hostname auto-identification](https://github.com/hyn/multi-tenant/blob/3.x/assets/configs/tenancy.php#L105) though and then create your own logic to switch between the tenants. The code is there though, you would just have to write it; as 3.x is beta there aren't many helpers yet.

For instance you could use the [Connection](https://github.com/hyn/multi-tenant/blob/3.x/src/Database/Connection.php) class to manually set the current tenant connection.

Please let me know if you need more information.

**Comment by xyrintech** [comment]
Do you mean is it going to be available with helpers in version 3 in future?
One more question, how can we select the tenant in commands? Let's say I have a command to send email after every 10 minutes then how can we execute the command on every tenant. (Considering we have emails table consisting of all the email store in there).

**Comment by luceos** [comment]
The helpers will make the process of manual implementation easier, that implementation is already possible though.

Commands can have different implementation depending on the goal you try to achieve. You mention a cronjob (automated recurring) command. I'd suggest looping over all tenants to see whether they have mails listed to be send.

**Comment by xyrintech** [comment]
Got it.
Well, how can we loop through the tenants? Do we have any helper function within this package to get the list of tenants which can further select and loop through it?

**Comment by xyrintech** [comment]
The helpers will make the process of manual implementation easier, that implementation is already possible though.

Would it be possible to help me out to understand, like how this is possible?
I have looked into the Connection, the functions are very tightly bounded with each other. So, bit confused about the context how this make it easier.

**Comment by luceos** [comment]
There is actually a recent implementation of switching tenants to set their connection. The custom [MigrateCommand does it](https://github.com/hyn/multi-tenant/blob/3.x/src/Database/Console/MigrateCommand.php#L61-L69):

```php
        $this->websites
            ->query()
            ->chunk(10, function (Collection $websites) {
                $websites->each(function ($website) {
                    $this->connection->set($website, $this->connection->migrationName());

                    parent::fire();
                });
            });
```

**Comment by xyrintech** [comment]
Got it. 
I am still confused for this. 
How and when we gonna use this? :)

**Comment by luceos** [comment]
You'll have to switch database to access the emails table you mentioned earlier. Once you've switched the database connection of the tenant you can retrieve the rows in that table using your Eloquent models and run your email sending logic.

As an example;

```php
        $this->websites
            ->query()
            ->chunk(10, function (Collection $websites) {
                $websites->each(function ($website) {
                    $this->connection->set($website); // sets the tenant connection

                    $email = \App\Email::first(); // retrieves the first Email row, you could use a query or whatever
                    $this->send($email); // custom code to send mails using your Eloquent Email model
                });
            });
```

**Comment by xyrintech** [comment]
now this becomes more clear. 
How and when we need to switch the connections too? The reason I wanted to know this because, the package is completely dependent on the connection.

**Comment by luceos** [comment]
> How and when we need to switch the connections too?

That depends on your implementation. I don't know 😄 

> The package is completely dependent on the connection.

Yes the tenancy package depends on the tenant connection to be set for the Eloquent models to work.

**Comment by xyrintech** [comment]
Got it. :)
