### ISSUE TITLE
Error create a customer

### ISSUE THREAD

**Issue by Shin97** [hyn/multi-tenant#226]
Description

Why i try to create a customer error

```
$customer = app('Hyn\Tenancy\Contracts\CustomerRepositoryContract')->create(
            ['name' => $name,
                'email' => $mail]);

        $website = app('Hyn\Tenancy\Contracts\WebsiteRepositoryContract')->create(
            ['identifier' => $site,
                'customer_id' => $customer->id]);

        $hostname = app('Hyn\Tenancy\Contracts\HostnameRepositoryContract')->create(
            ['hostname' => 'some-hostname.org',
                'website_id' => $website->id,
                'customer_id' => $customer->id
            ]);
```

__Error log__

Class Hyn\Tenancy\Contracts\CustomerRepositoryContract does not exist
--
in Container.php (line 729)
at ReflectionClass->__construct('Hyn\\Tenancy\\Contracts\\CustomerRepositoryContract')in Container.php (line 729)
at Container->build('Hyn\\Tenancy\\Contracts\\CustomerRepositoryContract')in Container.php (line 608)
at Container->resolve('Hyn\\Tenancy\\Contracts\\CustomerRepositoryContract')in Container.php (line 575)
at Container->make('Hyn\\Tenancy\\Contracts\\CustomerRepositoryContract')in Application.php (line 728)
at Application->make('Hyn\\Tenancy\\Contracts\\CustomerRepositoryContract')in helpers.php (line 106)
at app('Hyn\\Tenancy\\Contracts\\CustomerRepositoryContract')in TenantController.php (line 22)
at TenantController->addCustomer(object(Request))
at call_user_func_array(array(object(TenantController), 'addCustomer'), array(object(Request)))in Controller.php (line 55)
at Controller->callAction('addCustomer', array(object(Request)))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(TenantController), 'addCustomer')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 574)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 576)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 535)
at Router->dispatchToRoute(object(Request))in Router.php (line 513)
at Router->dispatch(object(Request))in Kernel.php (line 174)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Request.php (line 111)
at Request->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 149)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)

```

**Comment by luceos** [comment]
What version of hyn/multi-tenant do you run?

Please the github issue template exists for a reason 😬

**Comment by luceos** [comment]
I'm guessing you're using the unfinished documentation for 3.x. The actual Repository contract is now:

```
Hyn\Tenancy\Contracts\Repositories\HostnameRepository
```
