### ISSUE TITLE
BindingResolutionException

### ISSUE THREAD

**Issue by Shin97** [hyn/multi-tenant#229]
__Description__

I want to  create a new tenant website , 

        $customer = app('Hyn\Tenancy\Contracts\Repositories\CustomerRepository')->create(
            ['name' => $name, 'email' => $mail]);

        $website = app('Hyn\Tenancy\Contracts\Repositories\WebsiteRepository')->create(
            ['identifier' => $site, 'customer_id' => $customer->id]);

        $hostname = app('Hyn\Tenancy\Contracts\Repositories\HostnameRepository')->create(
            ['hostname' => 'some-hostname.org',
                'website_id' => $website->id,
                'customer_id' => $customer->id
         ]);

But  have error

BindingResolutionException
Target [Hyn\Tenancy\Contracts\Repositories\CustomerRepository] is not instantiable.

---

__Information__

- hyn/multi-tenant version:3.0.1
- laravel version:5.4.27
- database driver and version: mysql
- webserver software and version: apache
- php version:7.1

---

__tenancy.php config__

        /** Hyn tenancy providers */
        Hyn\Tenancy\Providers\TenancyProvider::class,
        Hyn\Tenancy\Providers\WebserverProvider::class,

---

__Error log__

BindingResolutionException
Target [Hyn\Tenancy\Contracts\Repositories\CustomerRepository] is not instantiable.
in Container.php (line 895)
at Container->notInstantiable('Hyn\\Tenancy\\Contracts\\Repositories\\CustomerRepository')in Container.php (line 735)
at Container->build('Hyn\\Tenancy\\Contracts\\Repositories\\CustomerRepository')in Container.php (line 608)
at Container->resolve('Hyn\\Tenancy\\Contracts\\Repositories\\CustomerRepository')in Container.php (line 575)
at Container->make('Hyn\\Tenancy\\Contracts\\Repositories\\CustomerRepository')in Application.php (line 728)
at Application->make('Hyn\\Tenancy\\Contracts\\Repositories\\CustomerRepository')in helpers.php (line 106)
at app('Hyn\\Tenancy\\Contracts\\Repositories\\CustomerRepository')in AppServiceProvider.php (line 35)
at AppServiceProvider->register()in Application.php (line 574)
at Application->register(object(AppServiceProvider))in ProviderRepository.php (line 75)
at ProviderRepository->load(array('Illuminate\\Auth\\AuthServiceProvider', 'Illuminate\\Broadcasting\\BroadcastServiceProvider', 'Illuminate\\Bus\\BusServiceProvider', 'Illuminate\\Cache\\CacheServiceProvider', 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'Illuminate\\Cookie\\CookieServiceProvider', 'Illuminate\\Database\\DatabaseServiceProvider', 'Illuminate\\Encryption\\EncryptionServiceProvider', 'Illuminate\\Filesystem\\FilesystemServiceProvider', 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider', 'Illuminate\\Hashing\\HashServiceProvider', 'Illuminate\\Mail\\MailServiceProvider', 'Illuminate\\Notifications\\NotificationServiceProvider', 'Illuminate\\Pagination\\PaginationServiceProvider', 'Illuminate\\Pipeline\\PipelineServiceProvider', 'Illuminate\\Queue\\QueueServiceProvider', 'Illuminate\\Redis\\RedisServiceProvider', 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider', 'Illuminate\\Session\\SessionServiceProvider', 'Illuminate\\Translation\\TranslationServiceProvider', 'Illuminate\\Validation\\ValidationServiceProvider', 'Illuminate\\View\\ViewServiceProvider', 'Laravel\\Tinker\\TinkerServiceProvider', 'App\\Providers\\AppServiceProvider', 'App\\Providers\\AuthServiceProvider', 'App\\Providers\\EventServiceProvider', 'App\\Providers\\RouteServiceProvider', 'Dimsav\\Translatable\\TranslatableServiceProvider', 'Dingo\\Api\\Provider\\LaravelServiceProvider', 'Tymon\\JWTAuth\\Providers\\JWTAuthServiceProvider', 'igaster\\laravelTheme\\themeServiceProvider', 'Hyn\\Tenancy\\Providers\\TenancyProvider', 'Hyn\\Tenancy\\Providers\\WebserverProvider'))in Application.php (line 549)
at Application->registerConfiguredProviders()in RegisterProviders.php (line 17)
at RegisterProviders->bootstrap(object(Application))in Application.php (line 208)
at Application->bootstrapWith(array('Illuminate\\Foundation\\Bootstrap\\LoadEnvironmentVariables', 'Illuminate\\Foundation\\Bootstrap\\LoadConfiguration', 'Illuminate\\Foundation\\Bootstrap\\HandleExceptions', 'Illuminate\\Foundation\\Bootstrap\\RegisterFacades', 'Illuminate\\Foundation\\Bootstrap\\RegisterProviders', 'Illuminate\\Foundation\\Bootstrap\\BootProviders'))in Kernel.php (line 160)
at Kernel->bootstrap()in Kernel.php (line 144)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)

**Comment by luceos** [comment]
Try those calls in the `boot` method of your AppServiceProvider instead of the `register` I assume you do now.

Hope that works.

**Comment by Shin97** [comment]
I try calls in the boot , but have same error

**Comment by luceos** [comment]
Okay are you able to copy the code I need to reproduce this specific error? An [MVCE](https://stackoverflow.com/help/mcve) would even be better. Eg:

- Is the AppServiceProvider registered after the Tenancy ones?

I'm not sure where this comes from, hence my odd request ;)

Another thing I noticed is you use MySQL, that driver is not supported. Either use MariaDB or PostgreSQL. Otherwise you can't create users for your databases.

**Comment by Shin97** [comment]
This my AppServiceProvider  code :

```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
        //Multi-tenancy
        $name = 'test';
        $mail = 'test@mail.com.tw';
        $site = 'test.com';

        $customer = app('Hyn\Tenancy\Contracts\Repositories\CustomerRepository')->create(['name' => $name, 'email' => $mail]);

        $website = app('Hyn\Tenancy\Contracts\Repositories\WebsiteRepository')->create(['identifier' => $site, 'customer_id' => $customer->id]);

        $hostname = app('Hyn\Tenancy\Contracts\Repositories\HostnameRepository')->create(
            ['hostname' => 'some-hostname.org',
                'website_id' => $website->id,
                'customer_id' => $customer->id
            ]);


        Schema::defaultStringLength(191);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {

    }
}
```

**Comment by BertKooij** [comment]
Which version of Multi-Tenant are you using? I had a similar problem but it was fixed in: https://github.com/hyn/multi-tenant/commit/2f4cf589f2c2a1acf9f4fef5a4fef732e3b2204d

I am unsure whether this is released yet in one of the beta releases.

**Comment by luceos** [comment]
@beko1997 thanks for that, forgot about it. It's not yet tagged:

https://github.com/hyn/multi-tenant/compare/3.0.0-beta.3...3.x

I'll tag a new version.

**Comment by luceos** [comment]
Tagged 3.0.0-beta.4 can you confirm it now works @Shin97.

Closing this until you have confirmed it's not working.
