### ISSUE TITLE
moving multi-tenant laravel from localhost to sever: Database [tenant] not configured.

### ISSUE THREAD

**Issue by froid24** [hyn/multi-tenant#233]
__Description__

I have build a web app using hyn and laravel 5.3 on my computer (local). Everything works, so now I wanted to move it to a server. I uploaded the source code, changed the user/pass for the hyn db connection (and other laravel-related configs). Copied the database hyn_multi_tenancy and emptied the customers. hostnames and websites tables.

I tried to add a tenant using the setup step in the documentation:

sudo php artisan multi-tenant:setup --customer=EXAMPLE --email=foo@example.com --hostname=example.com --webserver=apache

but a strange thing happens: 
it does not create the tenant database, no customer/website/hostname is added in the hyn database tables, instead it just adds all the tables (articles, roles etc.) inside the hyn_multi_tenancy database... then it gives the following errors in the shell:
![image](https://user-images.githubusercontent.com/26799334/28830917-d9ff0a2c-76e0-11e7-8b5d-41caf45b67a9.png)

Thank you so much for pointing me in the right direction...
---

__Actual behavior__

..

__Expected behavior__

..

---
__Information__

- hyn/multi-tenant version: 2.0.0
- laravel version: 5.3
- database driver and version:
- webserver software and version:
- php version:

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by luceos** [comment]
Some questions to identify possible causes;

- Are the multi-tenant configuration files in your code base too?
- Is the system connection configured?
- Is the tenant connection _not_ configured?
- Does the system connection user have the necessary rights, eg almost root access?

**Comment by froid24** [comment]
Figured it out... Yes, everything was configured, but the db connections were defined with 127.0.0.1 and for some reason on the production server that didn't work. Changing that to localhost solved it. Maybe this will save some time for other people.

Thanks.
Cheers!
