### ISSUE TITLE
Laravel 5.4 with mysql 5.7

### ISSUE THREAD

**Issue by haxoman** [hyn/multi-tenant#235]
Hi I have succefully installed the multi-tenant system and about to start. 
Had couple of issues to install but all solved, just one thing I got it in my mind is,
the instruction says it won't work with mysql, would it be impossible at all?

Thanks in advance.

__Information__

- hyn/multi-tenant version: 4.x
- laravel version: 5.4
- database driver and version: mysql 5.7
- webserver software and version: apache2 latest
- php version: 7.1 (latest)

---

**Comment by luceos** [comment]
The drawback of MySQL vs MariaDB is that MySQL doesn't allow usernames and databases that are longer than 16 characters. Tenancy uses a UUID generated specifically for the Website to name both user and database, that uuid looks like: `25769c6c-d34d-4bfe-ba98-e0ee856f3e7a`

In the tenancy.php you can specify a different Generator, which should implement `Hyn\Tenancy\Contracts\Website\UuidGenerator` if you create a custom one that generates a unique UUID limited to 16 characters, you should be fine.

**Comment by haxoman** [comment]
Thanks so much.

Danny
