### ISSUE TITLE
Database does not get created when using Redis as queue driver. 

### ISSUE THREAD

**Issue by abiodunjames** [hyn/multi-tenant#236]
Thanks for this awesome package.  I have an issue with creating tenant with Redis queue driver. 
It seems jobs are not fired with Redis driver.
It works when you set queue driver to 'database' or 'sync'.

**Comment by luceos** [comment]
Hello. I don't understand why you deleted the whole issue template. Now I have to ask each question specifically;

- What version of Laravel?
- What version of tenancy?
- Any logs?

**Comment by abiodunjames** [comment]
@luceos   My sincere apology. Am using laravel 5.3, tenancy version 2.0 . No error logs of any kind. I got a successful response in terminal

**Comment by luceos** [comment]
This is most likely an issue with your redis. Did you find a cause in the meantime? Perhaps the redis log can be of use.
