### ISSUE TITLE
Tenant wrong connection

### ISSUE THREAD

**Issue by albanny** [hyn/multi-tenant#237]
__Description__

Teanant only connects to main database, so accessing from subdomain app is connected only on server database

---

__Information__

- hyn/multi-tenant version: 3.*
- laravel version:5.4
- database driver and version: 10.1.25-MariaDB-1
- webserver software and version: Apache/2.4.18 (Ubuntu)
- php version:7.1

---

**Comment by luceos** [comment]
Can you clarify your set up. This is far too little to go on and provide valuable feedback from.

**Comment by albanny** [comment]
Everything looks ok configured, i dont know if im missing something here, when i connect to example.mydomain.com is not connecting to example database, just the main database.
I have configured Eloquent for tenant but seems not to be working for me ('Eloquent'  => Hyn\Tenancy\Abstracts\Models\TenantModel::class,).

I made anothere laravel instalation and installed hyn/multi-tenant version: 2.* and when extending model to Hyn\Tenancy\Abstracts\Models\TenantModel its working fine but not in version 3.*

**Comment by luceos** [comment]
I'll look into it. Thanks for reporting!

**Comment by Versoo** [comment]
Hi @albanny, I have that same problem. Do you found some solution?

**Comment by albanny** [comment]
Hi @Versoo , i did get back to version 2 which is stable version, didn't have much time to check on it.

**Comment by luceos** [comment]
Verified working by using a test.

**Comment by sharabh** [comment]
I am having the same issue, it's not picking up tenant database. Instead of it, it's using the main database. Any suggestions.

hyn/multi-tenant version: 3.*
laravel version:5.5
webserver software and version: Apache/2.4.18 (Ubuntu)
php version:7.1

**Comment by julesbloemen** [comment]
In my Tenant Models I just set the connection. And working fine.

`protected $connection = 'tenant';`

**Comment by sharabh** [comment]
@julesbloemen I am using 'Eloquent' => Hyn\Tenancy\Abstracts\Models\TenantModel::class, in config/app.php. so I think I don't need this. but I tried your suggestion and it didn't help.

**Comment by luceos** [comment]
@sharabh are you able to identify what connection your model uses?

**Comment by sharabh** [comment]
It's using the connection named tenant which was manually created in database.php file

**Comment by sharabh** [comment]
also tried to switch to MariaDB from mysql but it didn't help.

**Comment by luceos** [comment]
@sharabh you can't configure the tenant connection settings in the database.php manually, they are set automatically during run time.

Nevertheless the code should override those during code execution. I'd love to hear more about your set up.

**Comment by sharabh** [comment]
@luceos Looks like it's not overriding tenant connection when I try to remove it from database.php I get an error. PLease let me know what kind of information you need to help me in resolving the issue.

**Comment by luceos** [comment]
@sharabh This is interesting, did you modify anything about how tenant identification works?

Also can you give me the information about your versions? Laravel and multi-tenant?

**Comment by sharabh** [comment]
We changed the settings in tenancy.php and webserver.php only, we are following https://hyn.readme.io/v3.0/docs/

Laravel version 5.5
Multi-tenant version 3.0

**Comment by luceos** [comment]
Could you try moving to `5.x` on `hyn/multi-tenant`? I've dropped development on 3.x and 4.x and as you're using Laravel 5.5 you should be on the 5.x version anyway.. I think the 3.x version you are using is pretty outdated, as the latest 3.x version is fixed to Laravel 5.3.

**Comment by sharabh** [comment]
just updated it to 5.0.0-beta.8, should I run any command after the update?

**Comment by luceos** [comment]
@sharabh no, not likely. The 5.x code is based on the 3.x code. You might need to change some classes etc which have been renamed.

**Comment by sharabh** [comment]
I am just uninstalled it and re-installing it from scratch, hope that will work

**Comment by luceos** [comment]
@sharabh let me know if it did. Feel free to create a new issue if you encounter any issues.
