### ISSUE TITLE
question about PHP version

### ISSUE THREAD

**Issue by dneykov** [hyn/multi-tenant#240]
Hi,

I'm wondering why this package requires php version 7.1 while laravel 5.5 support 7.0?
Thanks.

**Comment by luceos** [comment]
Because php 7.1 offers optional return type hinting and it's the latest stable version. As tenancy is meant for a clean hosting environment anyway you should be able to easily configure php 7.1 with ondrej's ppa.

**Comment by luceos** [comment]
On the other hand it might make it easier for 5.5 users to install...

I'll consider it. It would require additional tests though.

**Comment by luceos** [comment]
There, version 5.x is compatible with php 7.0 and up.
