### ISSUE TITLE
Tenant database connection example

### ISSUE THREAD

**Issue by haxoman** [hyn/multi-tenant#241]
__Description__

Hi 
I have successfully installed multi-tenant for my existing system which is running laravel 5.4.
and I have excuted some example code from your new web site.

$tenancy = app(Hyn\Tenancy\Environment::class);
$tenancy->website();            // resolves the currently active website
$tenancy->hostname();           // resolves the currently active hostname
$tenancy->customer();           // resolves the currently active customer

$tenancy->hostname($hostname);  // sets the currently active hostname
$tenancy->identifyHostname();   

all these of above codes are working fine for me, thanks for this. I can resolve all data by my domain name, however one question to get help.

I could not be able to find out any example of how to connect tenant db. it looks magically happen, but can you give me some sample usage, so I can use a code from my controller.

$tenant_db = app(Database::class);
then I can use $tenant_db->get()->model_of_tenant(); // something like that.

Would it be fine to ask you? 

Thanks in advance.

---

__Information__

- hyn/multi-tenant version: 3.x
- laravel version: 5.4
- database driver and version: mysql 5.7
- webserver software and version: apache 2.4
- php version: php 7.1+

---

**Comment by luceos** [comment]
The easiest way once your Tenant is globally identified:

```php
$connection = app(Hyn\Tenancy\Database\Connection::class);
$tenantConnection = $connection->get();
```

See [Connection::get](https://github.com/hyn/multi-tenant/blob/5.x/src/Database/Connection.php#L104-L107).

**Comment by haxoman** [comment]
thanks for that,
One last question, it may be silly question,

basically I have system database and all tenants shared the exactly same database as system db except the user table,

so I will use all the same queries in controller level as it is, but still needs a user session from system db. Is there anyway, I can use same query machanism but can switch it to tenant db?

for example,
I have existing query like:
$file = File::find(4);

then can it be switched tenant once tenant is globally identified or

if ($tenantExists) {
    switch_db($tenant);
    File::find(4);
}

Would it be something similar usage?

Thanks in advance.

**Comment by luceos** [comment]
I'm pretty unsure what you are exactly asking, so here's a wild guess.

You can force queries onto a specific connection from any Model class using the `on()` method, eg:

```php
$connection = app(Hyn\Tenancy\Database\Connection::class);

$file = File::on($connection->tenantName())->find(4);
$file = File::on($connection->systemName())->find(4);
```

In case you're looking more to manually identify tenants, disable the option in the `tenancy.php` configuration file and run the `hostname()` method on the `Environment` class (make sure to load it via ioc).

Hope this helps.

**Comment by haxoman** [comment]
Thanks for that, helpful. I will try more with ur suggestions.

**Comment by haxoman** [comment]
Just one quick question,
hostname is working only with FQDN, however, Would it be possible like, "www.domain.dom/group/unique_id/", wouldn't it be accepted?
so if I store "www.domain.dom/group/unique_id/" in table hostnames.fqdn, it would not seem recognise it and gives and error "Trying to get property of non-object". 

I also tried to use prefix in tenant.php that is not working. like
prefix = "group" in tenancy.php it won't affect global routes file.
 
Hope it would not be hard to understand. 
Just let me know if any possibilities, otherwise, I may try another way in server side.

Thanks 
Danny

**Comment by luceos** [comment]
@haxoman 

- Hostname has to be a FQDN it cannot hold any path segment, it doesn't work if you manually hack it into the database either because the hostname is matched against the requested domain. Unless you also override the tenancy identification, disable the auto identification and do it manually.
- Seems that the path prefix is not yet fully working, I'll look into that asap.

**Comment by haxoman** [comment]
Yes You are right, I try to check more and only FQDN is working for this. I may can use mod_rewrite to make all with sub-domain.
however, it will be better if I can override,  your class, "src/Jobs/HostnameIdentification.php".
It is a bit hard for me is, I don't really much know about the laravel and how to override a package file. I know it is not your responsibilities, but if you can give me how to override identification, it would be great, just few lines of sample usage will work for me.
 
Thanks again.

**Comment by luceos** [comment]
Okay so:

- [disable auto identification from the tenancy.php configuration](https://github.com/hyn/multi-tenant/blob/5.x/assets/configs/tenancy.php#L105)
- create a service provider in your app that does your logic for identifying the tenant hostname and call the hostname method on the Environment to switch tenant:
```php
<?php

namespace App\Providers;

use Hyn\Tenancy\Environment;
use Illuminate\Support\ServiceProvider;

class TenancyProvider extends ServiceProvider
{
    public function register() {
        // .. do your identification logic here and set a variable $hostname
        $this->app->make(Environment::class)->hostname($hostname);
    }
}
```

^ untested..

**Comment by haxoman** [comment]
thanks for that, but so many errors when I do php artisan config:cache... :(
I did, set to false auto identification, then create service provider as you gave.
then add service provider to config/app.php
then php artisan config:cache

it gives:

[Illuminate\Contracts\Container\BindingResolutionException]          
  Target [Hyn\Tenancy\Contracts\CurrentHostname] is not instantiable.

.. sorry, but you know a lot of people using multi-tenancy with same url base, but different path, like what linkedin do for profile page with unique url. believe or not. :)

I may dig into more in it, but my skill level, I doubt myself to make proper overriding it.

Thanks for your help!

**Comment by luceos** [comment]
You might need to add `$defer = true` as property on the TenancyProvider to make it load after all other code. And possibly use the `boot` method instead of the `register` one.

If your knowledge of Laravel is limited, you might best look at writing a simple app first.

Please also note that LinkedIN user pages are not tenants, they are .. user profiles. The database comes from the same database not separate ones and information about those users is also stored in the same database.

**Comment by haxoman** [comment]
Hi

I just use my service provider to override hostnameIdentifiaction.php that actually identify hostname so,
It seems works, and I added it to boot() otherwise so many errors comes with register().

Thanks,

Danny

**Comment by xyrintech** [comment]
@haxoman Would it be possible to share a sample of your code?
