### ISSUE TITLE
Suggestion: MySQL support

### ISSUE THREAD

**Issue by dneykov** [hyn/multi-tenant#243]
In README is mentioned that MySQL is not supported because users are limited to 16 characters. But with MySQL 5.7 users can be up to 32 characters.

So my suggestion is instead of uuid for username for tenant database is to use md5()

Greetings,
Daniel

**Comment by luceos** [comment]
Hello namesake :)

The documentation is flawed it seems. The UUID generator creates usernames/databases of length 36, not 32. So sadly MySQL is still no option (per default).

If you still need to use MySQL you can quite easily create your own UUID generator and add it to the config file. Feel free to send me a PR with a MD5 Generator, I would be willing to merge it.

**Comment by jonathan-bird** [comment]
A simple solution @luceos is to remove hyphens. This is common practice to get it to work.

The generator would simply str_replace to reduce to 32 length:
`return str_replace('-', '', Uuid::uuid4()->toString());`

**Comment by luceos** [comment]
That might be a good idea.. I'd have to look into this or feel free to submit a PR @jonathan-bird

**Comment by jonathan-bird** [comment]
I just replaced your one sha generator file. Super simple. I can PR but not
sure if you want to change the filename specific for mysql.

**Comment by luceos** [comment]
I think creating a separate `MySQLShaGenerator` would be best ;)

I'll then document to use that one.

**Comment by luceos** [comment]
Fixed in 5.0.1, see https://laravel-tenancy.com/documentation/introduction/requirements for MySQL support.
