### ISSUE TITLE
Question: rollback option for tenancy?

### ISSUE THREAD

**Issue by julesbloemen** [hyn/multi-tenant#245]
__Description__

I was wondering if there is an option to rollback the migrations for a tenancy. php artisan tenancy:migrate works great but could not find an rollback command?

---

__Information__

- hyn/multi-tenant version: 4.*
- laravel version: 5.4
- database driver and version: mysql
- webserver software and version: apache 
- php version: php 7.1

**Comment by luceos** [comment]
Hello @julesbloemen ; yes the rollback feature is not yet implemented. In addition it won't be implemented in 4.x or lower. You'd have to move to Laravel 5.5 LTS and tenancy 5.x to be able to use that feature once I release it in the coming weeks.

**Comment by julesbloemen** [comment]
Thanks! We will be upgrading soon :)

**Comment by luceos** [comment]
Good to hear, it's actually a smart decision with 5.5 being an LTS. 😁
