### ISSUE TITLE
Can't seem to run php artisan down(maintenance mode) or up for each tenant

### ISSUE THREAD

**Issue by bekee** [hyn/multi-tenant#250]
__Description__
For each tenant, how possible is it to execute php artisan down to turn the tenant into maintenance mode and php artisan up

**Comment by luceos** [comment]
You can set a value to `$hostname->under_maintenance_since`. The [HostnameActions](https://github.com/hyn/multi-tenant/blob/5.x/src/Middleware/HostnameActions.php) middleware will take care of the rest. If you want to put all tenants into maintenance, use the global artisan command.
