### ISSUE TITLE
Allow Hostname to match wildcards

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#251]
relates to #377 

We need to create a stricter hostname validator, but should still allow for wildcard hostnames.

**Comment by luceos** [comment]
Awaiting tests on #639.

**Comment by ArlonAntonius** [comment]
We just merged and tagged a new version that includes the feature discussed in this PR:
- Adding regex validation to HostnameValidator

If this doesn't actually solve your issue, you can always contact us through our channel(s):
- [Discord](https://laravel-tenancy.com/chat)
