### ISSUE TITLE
Tenancy Storage put file

### ISSUE THREAD

**Issue by julesbloemen** [hyn/multi-tenant#259]
__Description__

Hi!,

I was just wondering if the Tenant Storage should be working in the 5.X version.

In the Storage folder the needed folders are created but how to store files to a specific tenant folder? 

`Storage::disk('tenancy')->put('test.txt', 'test')` just  puts it in the root of de storage/tenancy/tenant folder.

Or should we fetch the tenantID from the database before hand? 

Would love to hear! 

Regards from Nijmegen

---

__Information__

- hyn/multi-tenant version: 5.0.0-beta.8
- laravel version: 5.5.4
- database driver and version: mysql
- webserver software and version: apache2
- php version: php7.1

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by luceos** [comment]
Hello @julesbloemen 👍 

```php
// implements Illuminate\Contracts\Filesystem\Filesystem
$directory = app(Hyn\Tenancy\Website\Directory::class);
```

> Note to self; needs documentation?

**Comment by maelga** [comment]
**"Class App\Http\Controllers\Hyn\Tenancy\Database\Connection does not exist"**

This is the error message I get when I add `$directory = app(Hyn\Tenancy\Website\Directory::class);` in my controller.
I have spent hours trying to fix what looks like a namespace issue but the issue remains.
Any idea how to solve this? 

I am trying to get files uploaded by a tenant user to store in the corresponding tenant folder `app/tenancy/tenants/abcxyz123`

**Comment by Thijmen** [comment]
@maelga You need to import it, your IDE (eg. PHPStorm) can do that for you.

**Comment by fletch3555** [comment]
@maelga, it's trying to load it by "relative" namespace.  You need to add `\` at the front of your class namespace.

**Comment by Nowi5** [comment]
Just use with a leading slash: $directory = app(\Hyn\Tenancy\Website\Directory::class);
The documentation need to be updated as well. https://laravel-tenancy.com/docs/hyn/5.2/filesystem

In addition; how do I get the path from the current tenant folder?
