### ISSUE TITLE
No tenant disk config in the version 5

### ISSUE THREAD

**Issue by julianfox** [hyn/multi-tenant#262]
__Description__
It seems to don't have tenant disk config setup in the version 5

__Actual behavior__
When I use 'tenant' as disk for example:
`$file->storeAs($destination_path, $new_file_name, 'tenant');`

I got: Driver [] is not supported.

---
__Information__
- hyn/multi-tenant version: 5
---

**Comment by luceos** [comment]
I don't think that disk is automatically set. There is a `tenant.disk` in IoC though. What would be better is using the Directory functionality to store files inside a tenant directory:

http://tenancy.dev/documentation/implementation/directory

But having an automatic disk makes sense too.
