### ISSUE TITLE
Create event for tenant database migration 

### ISSUE THREAD

**Issue by julianfox** [hyn/multi-tenant#265]
__Description__
Useful for database seeding

**Comment by luceos** [comment]
What would be the benefit of an event versus the existing way of [auto running migrations for tenants](https://github.com/hyn/multi-tenant/blob/5.x/assets/configs/tenancy.php#L160-L164).

**Comment by julianfox** [comment]
I meant an event after the auto migrations, like database/migrated.
In this way, we can listen it for do database seeding.

Or may be we can add an option for auto running database seeding for tenants ?

**Comment by Thijmen** [comment]
@julianfox, I think this will be available when https://github.com/hyn/multi-tenant/pull/271 gets merged :-)

**Comment by Thijmen** [comment]
Now available; https://github.com/hyn/multi-tenant/commit/0648eb3b117b5eea6bd168e2ef04f057fc81291e

**Comment by luceos** [comment]
Just wait for it to be tagged, I'm still cleaning up the code 😁
