### ISSUE TITLE
SQL user too long

### ISSUE THREAD

**Issue by Thijmen** [hyn/multi-tenant#269]
__Description__

After creating a fresh install of laravel and a fresh installation of multi-tenant, I get this error when I create a new website:
```sql
Illuminate\Database\QueryException with message 'SQLSTATE[HY000]: General error: 1470 String 'cf6dc515-338f-4fef-a5e8-9831cc29b601' is too long for user name (should be no longer than 16) (SQL: GRANT ALL ON `cf6dc515-338f-4fef-a5e8-9831cc29b601`.* TO `cf6dc515-338f-4fef-a5e8-9831cc29b601`@'127.0.0.1' IDENTIFIED BY 'f48158a6907f1fc5c50c62993f534c07')'
```

I run these commands with `php artisan tinker`:
```php
use Hyn\Tenancy\Models\Website;
use Hyn\Tenancy\Contracts\Repositories\WebsiteRepository;

$website = new Website;
app(WebsiteRepository::class)->create($website);
```

---

__Actual behavior__

The database gets created correctly, but creating the SQL-user is not working because of the length of the username

__Expected behavior__

I expected that the user would be created correctly. Apparently, my setup of MariaDB wont allow me to use usernames longer than 16 characters.

---
__Information__

- hyn/multi-tenant version: 5.0.2
- laravel version: 5.5.14
- database driver and version: MariaDB, 10.2.9
- webserver software and version: Laravel Valet
- php version:7.0.22

---

**Comment by Thijmen** [comment]
Is it possible to generate my own unique sql-user names?

**Comment by Thijmen** [comment]
Closed, my solution was to alter mysql.users and increase length for the username.

**Comment by luceos** [comment]
pretty weird i thought mariadb 10+ allows longer usernames by default?

**Comment by Thijmen** [comment]
Yeh I thought so, but I upgraded from MySQL to MariaDB. You keep the structure of the 'mysql'-database.

**Comment by Kristories** [comment]
I know this is an old thread, but this will be useful for someone who is having a problem with this issue.

Enable this flag in case you're using a driver that does not support database username or database name with a length of more than 32 characters. This should be enabled for **MySQL**, but not for **MariaDB** and **PostgreSQL**.

`config.php`
```php
// 'uuid-limit-length-to-32'  => env('LIMIT_UUID_LENGTH_32', false),
'uuid-limit-length-to-32'  => env('LIMIT_UUID_LENGTH_32', true),
```

Or by `.env`

```env
LIMIT_UUID_LENGTH_32=true
```
