### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by Thijmen** [hyn/multi-tenant#270]
In one of my migrations, I also seed the created table because I have a relation that depends on it.
How do I make sure, when running 
```php
$website = new Website;
app(WebsiteRepository::class)->create($website);
```
That a model that I create in a migration is using the right connection? My model extends from `\Hyn\Tenancy\Abstracts\TenantModel`.
For full context, I use this in my migration:
```php
MyModel::create([
    'name' => 'N/A',
]);
```

**Comment by luceos** [comment]
Two suggestions:

1. Temporarily set the connection of the model to use the tenant migration one.
2. Never ever use models in migrations! Use raw db queries. The reason for this is simple, at some point your code (and so your models) change, your migrations or what they are supposed to do are not. You'd have to go back to those old migrations to patch them up, which is not a good idea because they already ran. Migrations therefor should never contain models, but raw queries 😁

**Comment by Thijmen** [comment]
Okay, for the purpose I had, I could used `DB::table()->insert()`. Now, I have a model with JSON-data in it. How would you do that? How can I set the connection of the model to the tenant migration one?

Also, out of scope question: can I seed also?

**Comment by luceos** [comment]
`DB::connection('tenant')` in case you run `tenancy:migrate` there's no need to specify the connection, you should be able to use `tenancy:migrate:seed` :) Let me know how that works out for you.

**Comment by Thijmen** [comment]
Hmm, seems to me that there is no command like `php artisan tenancy:migrate:seed`. However, there is `php artisan tenancy:db:seed`. I am not sure how I can tell tenancy which website-id to use.

What I would like is, that when I create a new website (and thus a new database), my seeds gets also seeded.

**Comment by luceos** [comment]
I see that's related to #265

**Comment by Thijmen** [comment]
Yeah, that'd be great! Is there a WIP? I'd love to contribute!
Another question: how does multi-tenant know the password of the created database? I don't see where it's stored. I suggest combination of app-key and website id?

**Comment by luceos** [comment]
@Thijmen 

- There's no WIP but what I think needs doing is:
  - Add an event when migrations have ran which is triggered in the listener that runs the migration.
  - Add a configuration setting to specify a path for seeders for seeding when tenants are created, the same way the migration configuration works.
  - Add a listener with a lower priority than the one that runs the migration for new tenants and run the seed command.
- The password is auto generated, check here: https://github.com/hyn/multi-tenant/blob/5.x/assets/configs/tenancy.php#L152-L158

**Comment by Thijmen** [comment]
Great, I'll take a look and try to create this.

**Comment by luceos** [comment]
That would be great @Thijmen if you need any assistance, feel free to join discord at https://laravel-tenancy.com/chat

**Comment by Thijmen** [comment]
There, I contributed! Yay! Thanks for merging.
