### ISSUE TITLE
Migration name mixup

### ISSUE THREAD

**Issue by wertmenschen** [hyn/multi-tenant#275]
I just stumbled over this by accident and think it's an issue, maybe I'm wrong (doesn't cause any problems for me because it defaults to the same value at both locations):

config/tenancy.php:
```'tenant-migration-name' => env('TENANCY_MIGRATION_CONNECTION_NAME', Connection::DEFAULT_MIGRATION_NAME),```

I don't find "tenant-migration-name" anywhere again, but:

Database/Connection.php:
```
public function migrationName(): string
    {
        return $this->config->get('tenancy.db.migration-connection-name', static::DEFAULT_MIGRATION_NAME);
    }
```

Regards Sebastian

**Comment by luceos** [comment]
Thanks totally missed that, changed and will push asap. Have some other important changes coming in that need a new tag anyway.
