### ISSUE TITLE
Documentation proposal: use another path for the migrations path example 

### ISSUE THREAD

**Issue by wertmenschen** [hyn/multi-tenant#277]
I was a little confused by the example proposed for tenant specific migrations (https://laravel-tenancy.com/documentation/implementation/migrations): `storage/app/tenancy/migrations`. I usually have nothing within the storage path in my repository, but I think the migrations should belong there. So maybe something like `database/tenancy/migrations` (which is in the repository by default) would be a better and clearer example?

Also I was a little confused by the term "tenant specific" first - does it mean "regarding ONE specific tenant" or "regarding ALL tenants"? I know it's the latter but maybe there is some better way to say it.

**Comment by luceos** [comment]
I've also considered moving the default location to a folder directly inside of base_path. Your points are valid though. Any suggestion is welcome, feel free to PR.

**Comment by S43534** [comment]
...didn't realize there is a repository for the documentation. Here you go: https://github.com/hyn/laravel-tenancy.com/pull/2 (sorry, I used another account - it's still me :-) )

**Comment by luceos** [comment]
Reopened as a reminder to move the default tenancy location.

**Comment by luceos** [comment]
database/migrations/tenant is the new location
