### ISSUE TITLE
php artisan tenancy:migrate does run from main migration folder

### ISSUE THREAD

**Issue by julesbloemen** [hyn/multi-tenant#283]
__Description__

When running php artisan tenancy:migrate from the command line it tries to run the migration from the main folder instead of the tenantmigration folder.

Creating a new tenant does run the migration from the correct folder. 

Any ideas why?

---

__Actual behavior__

migrations from mainfolder are used

__Expected behavior__

migrations from tenantfolder should be used :)

---
__Information__

- hyn/multi-tenant version: 5.0.4
- laravel version: 5.5
- database driver and version: mysql
- webserver software and version: apache2
- php version: 7.1

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by Thijmen** [comment]
It is expected behaviour when running `php artisan migrate` on the main migration folder. However, when you run `php artisan tenancy:migrate` it will migrate from the tenancy-migration folder.

**Comment by julesbloemen** [comment]
Sorry, Did not check my text.. But I ran` php artisan tenancy:migrate` and then it checks the `migration` folder. I just noticed when I add the` --path="database/clientmigrations" `it does work.

**Comment by luceos** [comment]
tenancy:migrate now takes into consideration the configuration set at `tenancy.db.tenant-migration-path` 😬
