### ISSUE TITLE
Database connections

### ISSUE THREAD

**Issue by huzzi** [hyn/multi-tenant#285]
I have a 3 separate database connections as follows:
- tenancy-tenant
- tenancy-system
- tenancy-migration

When I run the install (php artisan tenancy:install) the **tenancy-system** gets populated and the **tenancy-migration** database is empty.

When I create a new tenant using the code below, a new database is created.

`$website = new Website;`
`app(WebsiteRepository::class)->create($website);`
`$hostname = new Hostname;`
`$hostname->fqdn = 'multi2.local';`
`app(HostnameRepository::class)->attach($hostname, $website);`

My question is when is the **tenancy-tenant** and **tenancy-migration** get used?

Thanks

**Comment by luceos** [comment]
Good question!

- tenancy-system is the system connection where hostnames, websites and customers are stored.
- tenancy-tenant is the tenant connection, it is set whenever you switch to a tenant; per default this is done whenever you identify a specific tenant, for instance by hostname.
- tenancy-migration is the connection used to run short lived, mass mutations on tenant databases. It prevents re-using the tenant connection and as such disconnect your app unwillingly from the tenant specific database while running a mutation on another tenant.

Does this help?

**Comment by huzzi** [comment]
Yes, it does. Thank you

**Comment by luceos** [comment]
Needs documentation ;)

**Comment by Thijmen** [comment]
Closing as tenancy-migration is no longer present.
