### ISSUE TITLE
Running default migrations even though in tenancy.php config `tenant-migrations-path` has been set

### ISSUE THREAD

**Issue by AbhijeetSomwanshi** [hyn/multi-tenant#286]
__Description__

I am trying to run tenants specific auto migrations while creating a tenant. I also have added seeder to add a record to tenant's 'users' table. But it's running the default system migrations.

---

__Actual behavior__
 
Its running default migrations from the folder 'database/migrations'

__Expected behavior__

This should run the migrations from the folder specified in the config.

---
__Information__

- hyn/multi-tenant version: "5.*"
- laravel version: "5.5.*"
- database driver and version: "mysql"
- webserver software and version: "apache"
- php version: "7.0"

---

__tenancy.php config__

```php
        /**
         * The tenant migrations to be run during creation of a tenant. Specify a directory
         * to run the migrations from.
         */
'tenant-migrations-path' => 'storage/app/tenancy/migrations',

      /**
         * Seeds the newly created tenant database based on this Seeder.
         *
         * @info requires tenant-migrations-path to be in use.
         *
         * @warn specify a valid fully qualified class name.
         * @example App\Seeders\AdminSeeder::class
         */
'tenant-seed-class' => App\Seeders\TenantSeeder::class,
```

**Comment by luceos** [comment]
I think I've answered this on discord. The `tenant-migrations-path` has to be an absolute path.

**Comment by luceos** [comment]
Modified the config to explain absolute path.
