### ISSUE TITLE
Feature request. Validator unique checks the maindatabase instead of tenant.

### ISSUE THREAD

**Issue by julesbloemen** [hyn/multi-tenant#290]
__Description__

Would be a nice feature to have the Validator look into the tenant tables instead of the main database.

Currently have solved this like this :) seems to be a okay workarround :)

`'username' => 'required|string|min:6|unique:tenant.users',`

---

__Actual behavior__

..

__Expected behavior__

..

---
__Information__

- hyn/multi-tenant version:
- laravel version:
- database driver and version:
- webserver software and version:
- php version:

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by luceos** [comment]
Use tenant connection 👍

**Comment by Nowi5** [comment]
See https://laravel-tenancy.com/docs/hyn/5.2/validation
