### ISSUE TITLE
If tenancy.json is deleted after the installation the hostname identification fails

### ISSUE THREAD

**Issue by juhasev** [hyn/multi-tenant#297]
__Description__

The package assumes that tenancy.json file is located in the projects root folder. However if this file is removed the application will die mysteriously when identifying hostnames. This is because Environment.php _construct() fails to do anything because it is checking for two separate concerns at the same time.

__Actual behavior__

Line 38: Environment.php

The following test:

 if ($this->installed() && config('tenancy.hostname.auto-identification'))

Fails to execute anything which causes exception thrown later on in the chain:

 "message": "Target [Hyn\\Tenancy\\Contracts\\CurrentHostname] is not instantiable.",
    "exception": "Illuminate\\Contracts\\Container\\BindingResolutionException",
    "file": "/home/vagrant/Code/platform/vendor/laravel/framework/src/Illuminate/Container/Container.php",
    "line": 918

__Expected behavior__

"message": "tenancy.json is missing",
    "exception": "Hyn\\Tenancy\\Exceptions\\InstallationException",
    "file": "/home/vagrant/Code/platform/vendor/hyn/multi-tenant/src/Environment.php"

Suggested fix would be to modify the installed() method in Environment.php to the following:

  /**
     * Check if Tenancy has been installed
     *
     * @throws Exceptions\InstallationException
     * @return bool
     */

    public function installed(): bool
    {
        if (!file_exists(base_path('tenancy.json'))) {
            throw new \Hyn\Tenancy\Exceptions\InstallationException('tenancy.json is missing');
        } else {
            return true;
        }
    }

Maybe add \Hyn\Tenancy\Exceptions\InstallationException for these types of errors.

---
__Information__

- hyn/multi-tenant version: 5.*
- laravel version: 5.5
- database driver and version: MySQL
- webserver software and version: NgInx
- php version: 7.1

**Comment by luceos** [comment]
The reason this was added is auto discovery and service provider registration. Throwing an exception by default will cause the `tenancy:install` command to fail too.

An alternative solution is to write a file to bootstrap/cache after a test whether the system connection has the required tables. Not sure if that's a better solution.

**Comment by Thijmen** [comment]
I think this is a good aproach and should be kept this way.

**Comment by luceos** [comment]
I also believe there is currently no better way to improve this. Closing for that reason.

**Comment by chrissound** [comment]
Is there a solution to this issue? Has it been fixed already as it's closed?

**Comment by fletch3555** [comment]
Yes, being closed means it's resolved.  `hyn/multi-tenant` no longer makes use of the `tenancy.json` file.

**Comment by forlomax** [comment]
fletch3555 how did you resolve this. i have done  'abort-without-identified-hostname' => false,
but still get the error Target [Hyn\Tenancy\Contracts\CurrentHostname] is not instantiable.

**Comment by fletch3555** [comment]
@forlomax, that's unrelated to this issue. Please open a new one with all relevant information

**Comment by luceos** [comment]
The installation command was removed, this issue is no longer valid. For any further question open a new issue and provide all relevant information.
