### ISSUE TITLE
Seeding for a specific Website is not working

### ISSUE THREAD

**Issue by dgruseck** [hyn/multi-tenant#306]
__Description__

If I try to execute a Seeder manually with:
```bash
php artisan tenancy:db:seed --class=...Seeder --website_id=5
```
the following error shows up
```
Database [tenant] not configured.
```
shows up
---

__Actual behavior__

The seeder tries to use the configured tenant connection

__Expected behavior__

The seeder should use the connection from the website given by the website_id

---
__Information__

- hyn/multi-tenant version: 5.0.8
- laravel version: 5.5.19
- database driver and version: mysql 5.7
- webserver software and version: apache 2.4
- php version: 7.1

**Comment by ashokgelal** [comment]
Like I mentioned on Discord#support channel, I'm having this exact same issue but in a different way. What I'm doing: create a customer => create a website => create a hostname => auto run tenant migrations and seeds (this is where the problem begins)

**Comment by ashokgelal** [comment]
Repro: https://github.com/ashokgelal/tenancy-repro

**Comment by luceos** [comment]
This needs a test that proves it won't work.

**Comment by dgruseck** [comment]
The problem is maybe related to the fact that I'm using tenant models (model with trait UsesTenantConnection) in the Seeder, because normal DB Statements are working.

Seeder:
```php
public function run()
    {
        TenantModel::updateOrCreate([
            'name' => 'test'
        ]);
    }
```
