### ISSUE TITLE
Add More Love To MySQL DB In clean-local-dbs.sh

### ISSUE THREAD

**Issue by bkintanar** [hyn/multi-tenant#308]
__Description__

MySQL DB has a 32 character limit in database name. Running `clean-local-dbs.sh` doesn't consider this.

---

__Actual behavior__

Running `clean-local-dbs.sh` on MySQL database driver will not find the databases since the REGEX will look for Uuids with dashes on it.
__Expected behavior__

Dashes in REGEX should be optional to catch db names created in MySQL.

---
__Information__

- hyn/multi-tenant version: 5.x
- laravel version: 5.5
- database driver and version: MySQL 5.7.19
- webserver software and version: N/A
- php version: 7.1

---

**Comment by luceos** [comment]
Ouch, good point. But this shouldn't be the default. Either allow for an `argv` or `env` to be set before running the script?

**Comment by bkintanar** [comment]
Yes. I think the `env` route is better, we can pickup the `DB_DATABASE`, `DB_USERNAME`, and `DB_PASSWORD` along the way instead of suggesting a default.

**Comment by luceos** [comment]
dashes are optional already since 30/01/2018
