### ISSUE TITLE
Make cache handling better for tenants

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#309]
Currently the Laravel cache will use the same cache key for all tenants. This can and will cause issues in the long run. The config key for tenants should be automatically changed and the ability to disable overriding the cache key should be configurable inside tenancy.php

**Comment by joshjacks** [comment]
Would below be an example of this issue or have I misunderstood? 

Authenticate as tenant A

```
public function getMessageCountAttribute() {
    return Cache::rememberForever('message_count', function() {
       return Message::count();
    });
}
```

Authenticate as tenant B

```
public function getMessageCountAttribute() {
    // whoops! Will get tenant A's message_count
    return Cache::rememberForever('message_count', function() {
       return Message::count();
    });
}
```

**Comment by luceos** [comment]
@Maveriks this is exactly the issue 🎉 👍  . 

Saving a specific key not unique per tenant will overwrite the cache with that key. I think it would be great to modify either the config (early) or to overload or modify the Cache registry to modify the logic. I haven't done any further research but this should be possible by investigating into the inner workings of the Cache registry.

**Comment by joshjacks** [comment]
Thanks for clarifying, @luceos !

I was looking into it last night and thought that we could just change the cache prefix in config.

The issue arises if I want to cache something at the system level. It wouldn't cache cross-tenant. The best solution I can immediately see is adding a Cache::onTenant()->remember.... helper method.

Possibly even have a config option so it defaults to onTenant but then can use ::onSystem().

Happy to hear your thoughts / better ideas on this. If you are happy with this solution I can go ahead and implement it.

**Comment by luceos** [comment]
Your suggested solution has a slight drawback, you won't be able to use the helper or ioc bound registry. Comparing to previous implementations like Directory, I'm not too happy about its implementation so let's not get into the habit of creating new classes for existing Laravel functionality..

How about we set up a new cache store, that's pretty comparable with how the database modifications work. I wouldn't set up a system cache store though, that's something for the developer to decide on. What do you think?

**Comment by joshjacks** [comment]
Okay, yes I agree. Will do some work on this solution when I have some spare time and make a PR. 😄

**Comment by luceos** [comment]
That would be greatly appreciated! 👍

**Comment by jeitnier** [comment]
I don't know a ton about the internals of the IOC but from what I can tell there is a catch 22 here...I sort of made progress on this today by disabling auto discovery of "hyn/multi-tenant" ("spatie/laravel-permission" also but that's sorta unrelated).

I created a custom cache driver but I had to manually load the Hyn service providers after the custom cache provider because the Hyn providers are using the Cache layer, so you basically get the whole `Driver [driver_name] is not supported` because of order of loading. But we need the Hyn providers to determine the current hostname or similar, but they aren't resolved yet.

**Comment by luceos** [comment]
@jeitnier what the database resolving does is add a database connection to the config. The proposed solution for a tenant aware cache would be comparable, which is to add a cache store to the config during runtime. Completely implementing a new Cache Driver seems over the top from my perspective, as long as we haven't attempted the suggested solution overriding any core logic isn't making sense.

**Comment by joshjacks** [comment]
Having looked into this, I'm not really sure of the best solution.

For Redis (which I guess is one of the most popular Laravel caching solutions) it seems very frowned upon to use multiple databases on one instance. Especially when these databases could easily end up numbering 100+.

Creating multiple instances seems to be the suggested solution however the viability of this depends greatly on how the application is designed. For example certain hosting solutions may not allow multiple instances. From what I can find AWS elasticache, for example, does not support multiple instances.

### Upshot (tl;dr)

My current thoughts are that this is probably something best left to the user. Of course I am open to hearing your thoughts and seeing if we can work out a better solution.

### More reading

[Issues with multiple Redis databases](https://stackoverflow.com/a/16243787)

[Elasticache doesn't support multiple instances](https://stackoverflow.com/a/36813957)

**Comment by jeitnier** [comment]
This is what I ended up doing, rolling my own solution. Added a `CachServiceProvider` with these contents in `boot` method:

```
public function boot()
{
    Cache::extend('redis_tenancy', function ($app) {
        if (PHP_SAPI === 'cli') {
            $uuid = $app['config']['driver'];
        } else {
            // ok, this is basically a hack to set the redis cache store
            // prefix to the UUID of the current website being called
            $fqdn = $_SERVER['SERVER_NAME'];
            
            $uuid = DB::table('hostnames')
                ->select('websites.uuid')
                ->join('websites', 'hostnames.website_id', '=', 'websites.id')
                ->where('fqdn', $fqdn)
                ->value('uuid');
        }

        return Cache::repository(new RedisStore(
            $app['redis'],
            $uuid,
            $app['config']['cache.stores.redis.connection']
        ));
    });
}
```

Doesn't require a new Cache driver, as I'm just manually implementing the existing Redis driver. All I wanted to do is override the default prefix, which this lets me do by setting a custom cache driver in `config/cache.php`.

```
'redis' => [
    'driver' => 'redis_tenancy',
    'connection' => 'default',
],
```

Maybe not the most elegant solution but it works and has been reliable for me.

**Comment by luceos** [comment]
@jeitnier interesting solution indeed. Would you allow me to push this to our documentation?

@Maveriks that's a perfectly valid point, perhaps showing a few suggestions in docs would be a great starting point for any user?

**Comment by jeitnier** [comment]
Absolutely, go for it.

**Comment by bkintanar** [comment]
Thanks @jeitnier, this has now been added to the documentation.

**Comment by surgiie** [comment]
@jeitnier @luceos 

I followed your solution but i get `  Driver [redis_tenancy] is not supported.` whenever i try running any artisan command. Any ideas? My cache service provider is included in `config/app.php`

**Comment by surgiie** [comment]
Anyone have any idea on `Driver [redis_tenancy] is not supported.`  error? Did anyone have this issue.
Really like this package setup and would like to use it, but caching is important in this particular application..

**Comment by fletch3555** [comment]
@surgiie, if you're not getting a response, it's likely because this issue was closed 3.5 months ago.  You're welcome to open your own issue, which would prompt you to provide all the necessary information for us to properly track your issue through resolution.

**Comment by jeitnier** [comment]
@surgiie Please provide your `config/cache.php` and your `app/Providers/CacheServiceProvider.php` file please. I haven't worked on my project that uses this package in months due to being super busy, but I'll try to help how I can. I have logs where I experienced this issue too, so I'm sure it's probably an easy fix.

**Comment by surgiie** [comment]
@jeitnier Thank you any help would be greatly appreciated.

My `config/cache.php`:


```

<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Cache Store
    |--------------------------------------------------------------------------
    |
    | This option controls the default cache connection that gets used while
    | using this caching library. This connection is used when another is
    | not explicitly specified when executing a given caching function.
    |
    | Supported: "apc", "array", "database", "file", "memcached", "redis"
    |
    */

    'default' => env('CACHE_DRIVER', 'file'),

    /*
    |--------------------------------------------------------------------------
    | Cache Stores
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the cache "stores" for your application as
    | well as their drivers. You may even define multiple stores for the
    | same cache driver to group types of items stored in your caches.
    |
    */

    'stores' => [

        'apc' => [
            'driver' => 'apc',
        ],

        'array' => [
            'driver' => 'array',
        ],

        'database' => [
            'driver' => 'database',
            'table' => 'cache',
            'connection' => null,
        ],

        'file' => [
            'driver' => 'file',
            'path' => storage_path('framework/cache/data'),
        ],

        'memcached' => [
            'driver' => 'memcached',
            'persistent_id' => env('MEMCACHED_PERSISTENT_ID'),
            'sasl' => [
                env('MEMCACHED_USERNAME'),
                env('MEMCACHED_PASSWORD'),
            ],
            'options' => [
                // Memcached::OPT_CONNECT_TIMEOUT  => 2000,
            ],
            'servers' => [
                [
                    'host' => env('MEMCACHED_HOST', '127.0.0.1'),
                    'port' => env('MEMCACHED_PORT', 11211),
                    'weight' => 100,
                ],
            ],
        ],

        'redis' => [
            'driver' => 'redis_tenancy',
            'connection' => 'default',
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Cache Key Prefix
    |--------------------------------------------------------------------------
    |
    | When utilizing a RAM based store such as APC or Memcached, there might
    | be other applications utilizing the same cache. So, we'll specify a
    | value to get prefixed to all our keys so we can avoid collisions.
    |
    */

    'prefix' => env(
        'CACHE_PREFIX',
        str_slug(env('APP_NAME', 'laravel'), '_').'_cache'
    ),

];
```

and CacheServiceProvider(which is added in `config/app.php`):

```

<?php

namespace App\Providers;

use Illuminate\Cache\RedisStore;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\ServiceProvider;

class CacheServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        Cache::extend('redis_tenancy', function ($app) {
            if (PHP_SAPI === 'cli') {
                $uuid = $app['config']['driver'];
            } else {
                // ok, this is basically a hack to set the redis cache store
                // prefix to the UUID of the current website being called
                $fqdn = $_SERVER['SERVER_NAME'];

                $uuid = DB::connection('system')->table('hostnames')
                    ->select('websites.uuid')
                    ->join('websites', 'hostnames.website_id', '=', 'websites.id')
                    ->where('fqdn', $fqdn)
                    ->value('uuid');
            }

            return Cache::repository(new RedisStore(
                $app['redis'],
                $uuid,
                $app['config']['cache.stores.redis.connection']
            ));
        });
    }
}

```

Whenever i run any php artisan command:

```
In CacheManager.php line 107:
                                            
 Driver [redis_tenancy] is not supported. 

```

**Comment by jeitnier** [comment]
@surgiie It looks to me like your `boot` method isn't being called, possibly your `CacheServiceProvider` class isn't instantiated properly. What's your `config/app.php` look like?

Ensure the load order is like this:

```
App\Providers\CacheServiceProvider::class,

Hyn\Tenancy\Providers\TenancyProvider::class,
Hyn\Tenancy\Providers\WebserverProvider::class,
```

If `App\Providers\CacheServiceProvider::class,` is after, it won't work, you'll get that error.

**Comment by surgiie** [comment]
@jeitnier This worked. My problem was the auto discover feature. I set `hyn\tenancy` to not be discovered in my `composer.json`. However im noticing that when i `dd(config('cache.prefix'));`, it is still outputting `laravel_cache` which is the default prefix. `redis_tenancy` is the new driver set. The query in the `CacheServiceProvider` is returning the uuid, because i `dd` that out to confirm that it wasnt any  issues there. Did you have this issue as well or am i missing something?

**Comment by surgiie** [comment]
@jeitnier Cache however seems to be working properly for each tenant though. So it is working i  think. Thanks!

**Comment by vigiplus** [comment]
Hello,

@jeitnier @Maveriks @surgiie @bkintanar @luceos 

I was asking if it's easier to set config('cache.prefix', $uuid) in boot method in AppServiceProvider.php file?

Thanks

**Comment by luceos** [comment]
@zomax i'm curious what the max length of the key is.. The UUID is pretty long and as such you might get a truncated key value on cache drivers that don't support long keys.

**Comment by Luis-Sejer** [comment]
- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ]
