### ISSUE TITLE
SQLite implementation - unit testing

### ISSUE THREAD

**Issue by juhasev** [hyn/multi-tenant#312]
__Description__
Currently the package does not support SQLite. This means that you cannot run SQLite backed unit tests against any part of the code that uses Tenancy because tenancy will force MySQL connection and cause your tests to execute in development database instead.

---

__Actual behavior__

Forces MySQL connection (default) in the middle of the test suite regardless what is in phpunit.xml

There was 1 error:

1) Tests\Feature\JoinTest::admin_creates_tenant
Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.websites' doesn't exist (SQL: select count(*) as aggregate from `websites` where `uuid` = 4f9b8380bbe84c1)

__Expected behavior__

Should not override system database connection setup by PHPUnit and use SQLite instead. If an unsupported driver is in use the tenancy should throw an exception out of the box. Currently there is no driver implementation for SQlite.

---
__Information__

- hyn/multi-tenant version: latest
- laravel version: 5.5
- database driver and version: MySQL 5.7, SQLlite 2.8.17
- php version: 7.1

---

**Comment by luceos** [comment]
Have you tried configuring your system connection to use sqlite too? I'm very curious now whether the package is compatible with a SQLite driver now 😊

**Comment by juhasev** [comment]
Hi Daniel,

Did you update the package or something? I could give it an another shot
later today.

Thanks, Juha

**Comment by bkintanar** [comment]
Last release was 5.0.13 which was 2 days ago.

**Comment by luceos** [comment]
@juhasev no, nothing added to support this. Just curious whether compatibility is already existing..

I think it won't work because there's no pgsql driver support.

**Comment by juhasev** [comment]
I found a solution that works with SQLlite. So the basic idea is that you disable "Tenancy" completely and build all your tests so that they can be run against a single "tenant" database in memory. All of my application logic happens in "tenant" databases so this works quite nicely but if your application requires testing in the "system" database this solution will not work but similar approach could be taken to cover those tests. In an ideal world it would be nice to see tenancy package to adopt a proper "out of the box" solution.

1) Modify you composer.json and make sure the following is there preventing tenancy from auto loading itself (reason: this prevents tenancy overriding whatever database settings are specified in phpunit.xml)

```
  "extra": {
        "laravel": {
            "dont-discover": [
              "hyn/multi-tenant"
            ]
        }
    },
```
  
2) In your TestCase.php you need to run migrations manually. In order to use RefreshDatabase and DatabaseMigrations traits you will have to override methods that call artisan command to migrate databases or do this manually in the setup method instead.

```
public function setUp()
{
        // Important
        parent::setUp();

        // Run migrations from tenant folder
        // Note: tenancy default is database/migrations/tenant)
        Artisan::call('migrate', [
            '--path' => 'database/migrations_tenant',
            '--database' => 'sqlite'
        ]);
}
```
3) Lastly you need to modify your AppServiceProvider.php to register() method to register TenancyProvider and WebserverProvider classes only when not testing.
      
```
public function register()
{
        // Do not register Tenancy when in testing
        if ($this->app->environment()!=="testing") {
            $this->app->register(TenancyProvider::class);
            $this->app->register(WebserverProvider::class);
        }
}
```
4) Remove all DatabaseMigration and RefreshDatabase traits from the tests if you chose to handle migrations manually in test's setUp() method.

**Comment by luceos** [comment]
I don't think supporting sqlite is going to be something that makes sense for this package, mainly because it does not work with constraints.

**Comment by SolStis86** [comment]
@luceos  I know this package is becoming defunct soon to be replaced by tenancy but one of the key reasons for using sqlite is the speed advantage when running tests.  Do you have any recommendations to improves the speed of tests over mysql as tearing up and down is significantly slow.  It may be my setUp and tearDowns but its good to see sqlite support in the new version.

**Comment by luceos** [comment]
I'd be willing to merge the sqlite driver as a pr.
