### ISSUE TITLE
Document Validation on both Validator and FormRequest

### ISSUE THREAD

**Issue by bkintanar** [hyn/multi-tenant#317]
When using Validation Rules that touches the databases like `unique` and `exists`, one should add the `tenant.` db connection to correctly check the correct tenant db connection respectively.

**Comment by markandrewkato** [comment]
Hi! How can I implement this one? I'm confused and tried to put 

=> 'unique:connection.tenant,coupons,code'

but this doesn't work. Any help?

**Comment by bkintanar** [comment]
@markandrewkato that's supposed to be `unique:connection.table,column` so in your case, you need to use `unqiue.tenant.coupons,code`

**Comment by markandrewkato** [comment]
@bkintanar Got it working. Thank you very much!

**Comment by luceos** [comment]
@bkintanar can we prioritize a Validation section for the docs that states this behavior?

**Comment by bkintanar** [comment]
@luceos of course. 👍

**Comment by bkintanar** [comment]
Docs has now been [added](https://laravel-tenancy.com/docs/hyn/5.x/validation#exists-and-unique-validation-rule). Closing this.
