### ISSUE TITLE
Using Storage::class per tenant (Media)

### ISSUE THREAD

**Issue by ghost** [hyn/multi-tenant#318]
I was struggling with retrieving media from Tenant storage. Since i wasn't using the (Nginx) webserver integration, i had to mimic this behavior. 

__Description__
When retrieving files from storage, by default you fetch the system storage directory. If you like to call upon Tenant specific storage, you can solve this by e.g. a Route definition like this:

```
Route::get('/media/{filename}', function ($filename)
{
    return Storage::disk('tenant')->get("media/{$filename}");
});
```
---
__Information__

- hyn/multi-tenant version: 5.0*
- laravel version: 5.5
- database driver and version: Mysql
- webserver software and version: Nginx
- php version: 7+

---

__tenancy.php config__

```php
'media' => [
            /**
             * Mounts the assets directory with (static) files for public use.
             */
            'enabled' => true,
        ]

```

**Comment by luceos** [comment]
If we could find an unobtrusive way to add this route and controller functionality per default we could in fact always use this fallback. The webserver will first run a check whether a file exists and only then forward the reuqest to the controller/php.

**Comment by luceos** [comment]
Fallback controller already exists, so does the disk.
