### ISSUE TITLE
Backup / restore of tenants

### ISSUE THREAD

**Issue by ghost** [hyn/multi-tenant#322]
__Description__

In case of an issue with your server, the system database and tenant db's will be backupped. After setting up a new server, you will pull the repository and reinstall the application. Run composer update and your NPM packages, if any. 

---

__Actual behavior__

This results in the behavior of a fresh installation and your databases need to be recreated from scratch too. Since you don't know the username and password? One way to recreate them, is the use of > vendor/hyn/multi-tenant/src/Providers/Tenants/PasswordProvider.php which will create the password. In your system db, you have the UUID's of your websites and this should do the trick? Thanks, @bkintanar for thinking with me!

__Expected behavior__

This needs a bit of documentation because at the time of emergency you don't want to spend this on finding this solution ;)

---
__Information__

- hyn/multi-tenant version: all
- laravel version: all
- database driver and version: all
- webserver software and version: all
- php version: all

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by Thijmen** [comment]
I agree, it should be documented. We have it on our roadmap and we will notify you on this issue when we added the documentation. If you want to help, feel free to create a pull request @ https://github.com/hyn/laravel-tenancy.com

**Comment by bkintanar** [comment]
For the past two days, @Develeapment and I created a solution. As long as you have the system db intact, it can regenerate the tenant dbs with the command we created.
