### ISSUE TITLE
php artisan migrate takes so long

### ISSUE THREAD

**Issue by haxoman** [hyn/multi-tenant#323]
__Description__

I have one apache2 server with php7.1 and mysql 5.7, and
When I create a new tenant, migration process will take upto 1 to 2 mins, whereas my local server in c9, it takes around 5 secs. and all db and tables ready.

having same apache configuration, only differences is my live server uses opcache in php.ini

Is there any advise for it?

I don't actually use webserver.php in config, since I only need new tenant db, and it works so well in my development server, only live site would have this long time.
---

__Information__

- hyn/multi-tenant version: 3.x
- laravel version: 5.4
- database driver and version: mysql 5.7
- webserver software and version: apache2
- php version: 7.1

---

**Comment by Thijmen** [comment]
What are the server specs? Is it really different? Is it also slow prior to tenancy?
