### ISSUE TITLE
Local setup issue - Undefined variable: host

### ISSUE THREAD

**Issue by maelga** [hyn/multi-tenant#324]
__Description__

..When running `php artisan tenancy:install` I get the following error:
Is there something to change to the default tenancy.php or webserver.php?
>   [Illuminate\Database\QueryException]
>   Undefined variable: host (SQL: select * from information_schema.tables where table_schema = tenancy and table_name
>   = migrations)
> 
>   [ErrorException]
>   Undefined variable: host

---

__Actual behavior__

..Installation fails

__Expected behavior__

..Migration(s) should be created I believe

---
__Information__

- hyn/multi-tenant version: 5.0.13
- laravel version: 5.5.19
- database driver and version: MySQL 5.7.19
- webserver software and version: Apache 2.4.27 
- php version:  7.0.23

---

__tenancy.php config__

```php

```Default. No change to the file.

__webserver.php config__

```php

```Default. No change to the file.

---

__Error log__

```text
  [Illuminate\Database\QueryException]
  Undefined variable: host (SQL: select * from information_schema.tables where table_schema = tenancy and table_name
  = migrations)

  [ErrorException]
  Undefined variable: host
```

**Comment by bkintanar** [comment]
Check your database.php file and check on your tenant db connection. Make sure host is set.

**Comment by Thijmen** [comment]
Read the documentation and make sure you add your new connection to `database.php`.

**Comment by hiteshchavda** [comment]
On website, "[requirements](https://laravel-tenancy.com/documentation/introduction/requirements)" page show that you need to add `system` connection. and it does not contain 'host' and 'port' configuration. 

it should be as follow 
```
       'system' => [
          'driver' => 'mysql', // or pgsql in case you use PostgreSQL
          'username' => 'tenancy',
          'database' => 'tenancy',
          'password' => 'someRandomPassword',
          // Remaining settings required for this specific driver.

          'host' => env('DB_HOST'),    
          'port' => env('DB_PORT')
        ],
```

**Comment by luceos** [comment]
It does say `// Remaining settings required for this specific driver.` 😁
