### ISSUE TITLE
Comments in nginx config talks names Apache

### ISSUE THREAD

**Issue by pedzed** [hyn/multi-tenant#327]
Minor issue as can be seen in the comments:
https://github.com/hyn/multi-tenant/blob/0e7e51801c038c5a969b0a6ce8568c6924b5965f/assets/configs/webserver.php#L125-L187

Where Apache is named, it should be nginx.

**Comment by Thijmen** [comment]
Feel free to create a PR for this, @pedzed!

**Comment by pedzed** [comment]
@luceos Did you also change the other ones? There is more than one occurrence.

**Comment by luceos** [comment]
@Thijmen patched that up, I incidentally totally missed that 😊
