### ISSUE TITLE
Configuration is inconsistent with Laravel conventions

### ISSUE THREAD

**Issue by pedzed** [hyn/multi-tenant#328]
It is a Laravel convention to use `snake_case` in the configuration files. However, `kebab-case` is used by this package which goes against the Laravel conventions.

Proposal: change all `kebab-case` configuration items to `snake_case`.

**Comment by pedzed** [comment]
A problem is that many people already do have the current config as `kebab-case`. To stay backwards compatible, we could alias all `kebab-case` config items to `snake_case` (i.e. both get accepted, but the former will be deprecated).

**Comment by luceos** [comment]
I personally find kekab-case easier to read, but am willing to pick this up in future major versions in case enough people approve of this change.
