### ISSUE TITLE
What can i do next?thank you

### ISSUE THREAD

**Issue by syl5005** [hyn/multi-tenant#342]
I have installed hyn/tenant (by Getting started:Requirements,Installation,Configuration),then I want to create a new website,a new hostname,a new tenant.But,i am not  familiar with hyn/tenant,i don't know the way to create.

Please help me .Thank you.
..

---

__Actual behavior__

..

__Expected behavior__

..

---
__Information__

- hyn/multi-tenant version:
- laravel version:5.5.0
- database driver and version:Mysql 7.1
- webserver software and version:Nginx 1.12.1
- php version:

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by Thijmen** [comment]
Please read this carefully, you need to use the repository to create a new tenant. https://laravel-tenancy.com/documentation/implementation/repositories

**Comment by luceos** [comment]
If you're still stuck, feel free to join us on discord chat at https://laravel-tenancy.com/chat
