### ISSUE TITLE
artisan tenancy:migrate:refresh   (without --path migrates all system db(s) into the website/tenant dbs

### ISSUE THREAD

**Issue by Racherik** [hyn/multi-tenant#343]
Description

Executing "php artisan tenancy:migrate:refresh" results in  tenant db(s) receiving all the table migrations that are associated system table migrations.

Actual behavior

When executing "php artisan tenancy:migrate:refresh" all tenant db(s) receive the table migrations that are associated or part of the system table migrations.  when running  "php artisan tenancy:migrate:refresh --path=database/tenancy/migrations" the scope of executed migrations is limited only to the tenancy migrations.

Expected behavior

Executing "php artisan tenancy:migrate:refresh" should only invoke migrations that reference the tenancy db(s)

**Comment by luceos** [comment]
Tenant related commands always require a path. I'm a bit confused here, you expect the refresh command to understand the difference between a system and tenant migration by itself? Could you clarify so I can get my head around this?

**Comment by fletch3555** [comment]
I'm mobile, so forgive me if I'm mistaken, but isn't there a config that identifies the tenant migration folder. That controls which migrations are run automatically when a new website is created.  Shouldn't that config be used automatically when running any "tenancy:migrate:*" commands?  The path option can alter that behavior, but I think it should be the default.

**Comment by luceos** [comment]
The issue with refresh is that it uses the path option directly. Then it calls rollback/reset native commands with that path. The path is a relative path not an absolute path, the auto-migrate path is an absolute path.

The refresh command should either be removed or fully implemented. As it's mostly a proxy around rollback and reset I'm not sure it's worth overriding so much and possibly lose a lot of native logic.

**Comment by Racherik** [comment]
I think I follow.  After playing around with hyn, it makes sense why the "--path" option is what it is. 
Thanks.  I'm good with the way it is for the time being.
