### ISSUE TITLE
The command "/etc/init.d/nginx configtest" failed when creating new website

### ISSUE THREAD

**Issue by ReinierB** [hyn/multi-tenant#347]
__Description__

The php script to create a new tenant website reports the following error:

The command "/etc/init.d/nginx configtest" failed.

Exit Code: 1(General error)

Working directory: /home/vagrant/Code/cff/public

### Output:
================
 * Testing nginx configuration
   ...fail!

### Error Output:
================

__Actual behavior__
The tenant database has been created, including the tenant folder and the tenant nginx  .config file. However the nginx .config file is not complete:

Here are the contents of the file:

  Auto generated Apache configuration
       @author: hyn/multi-tenant
       @see: http://laravel-tenancy.com
       @time: 14:29:11 12-12-2017
       @website  id: 47
       @website  uuid: fb1396bbdadf445fbce6ee215f382908

    
       No hostnames found
    

that' all there is in this file.....

The remaining part of the website creation is abandoned, the hostname has not been created and the hostname is not attached to the website.

As a result, the new tenant web site cannot be accessed.

__Expected behavior__

..

---
__Information__

A few days ago, the code ran without any problem. After that I have upgraded to Hyn/multi-tenancy 5.0.15.

It might have something to do with access rights. 

If I run "/etc/init.d/nginx configtest" manually from the command prompt, it returns an error.  But if I run 
"sudo /etc/init.d/nginx configtest", it reports no errors in the nginx config files.

Trying to find a solution, I added "sudo" in the webserver.php file in the nginx section like this:
  original code   "'test-config' => '/etc/init.d/nginx configtest', 
  changed code 'test-config' => 'sudo /etc/init.d/nginx configtest',

Then, this error did not occur, but the next error appeared instead:

"The command "systemctl restart nginx" failed."

Adding "sudo" to this line in the webserver.php file did not work.

- hyn/multi-tenant version: 5.0.15
- laravel version: 5.5
- database driver and version: MariaDB 10.2
- webserver software and version: nginx version: nginx/1.13.3
- php version: 7.1
- vagrant 2.01 with laravel/homestead (virtualbox, 5.0.1)

I have removed the laravel/homestead box completely and reinstalled a new one. That did not help either.

__tenancy.php config__

As attached

__webserver.php config__

As attached

__Error log__

As attached

TenantController.php: see attachment

```
[error.zip](https://github.com/hyn/multi-tenant/files/1552086/error.zip)

**Comment by luceos** [comment]
The easiest solution is to run your website creation logic inside a Queue job where the Queue is run with elevated permissions.

In your example you're adding sudo to the command, this assumes the current web user has elevated permissions, if that is the case that's a very huge security risk (in production). Hence the use of a queue for these tasks. I'll possible need to document this and offer some kind of example.

**Comment by mah3uz** [comment]
@luceos thanks for your reply, I am facing same problem with apache. I am new in Laravel if you can point how I gain elevated permissions on Queue it would be a help. Here is my error
``` ProcessFailedException
The command "apache2ctl graceful" failed. Exit Code: 1(General error) Working directory: /var/www/html/classypos/public Output: ================ httpd not running, trying to start Action 'graceful' failed. The Apache error log may have more information. Error Output: ================ (13)Permission denied: AH00072: make_sock: could not bind to address [::]:80 (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80 no listening sockets available, shutting down AH00015: Unable to open logs ```

**Comment by luceos** [comment]
@mah3uz you can create a queue with elevated permissions by adding a new queue with a specific name inside your queue.php then configuring supervisor to run only that user as root. The laravel documentation should help you here, if not please create a new issue or join us on discord.

**Comment by ekontiki89** [comment]
@luceos  @ReinierB  Hello, I have the same problem, as they solved it if you could give me the example, I'm trying to use it in homestead of  laravel

**Comment by t-grm** [comment]
You can also simply add www-data to the sudoers file, allowing it to only run nginx configtest & nginx reload with elevated permissions.

`www-data ALL=(ALL:ALL) NOPASSWD:/usr/sbin/service nginx configtest,/usr/sbin/service nginx reload`

**Comment by asdullahsiddique** [comment]
Same error with me!

**Comment by lakshmajee** [comment]
Anybody solved this issue. I have created queue still same problem. Following is the queu configuration that i 'm using
```bash
[program:tenant-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/blog/artisan queue:work --tries=3
autostart=true
autorestart=true
user=lakshmaji
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/html/logs/tenant-worker.log

```

Do I need  to replace user name with **root** instead of system admin or **www-data** (nginx server root)

**Comment by t-grm** [comment]
Try using my answer replacing www-data with lakshmaji

**Comment by lakshmajee** [comment]
@ThomasGRIM , no my system admin name not working for me. But this works for all other queues that i have implemented earlier.

**Comment by luceos** [comment]
Moved to docs repo.

**Comment by paulcanning** [comment]
I'm experiencing this issue in a fresh install. Any help on getting past it?

My website creation code is super basic:

```
namespace App\Http\Controllers;

use Hyn\Tenancy\Contracts\Repositories\HostnameRepository;
use Hyn\Tenancy\Models\Website;
use Hyn\Tenancy\Repositories\WebsiteRepository;

class CreateWebsite
{
    public function index()
    {
        $website = new Website;
        app(WebsiteRepository::class)->create($website);

        $hostname = new Hostname;
        $hostname->fsdn = request('fqdn');
        app(HostnameRepository::class)->attach($hostname, $website);
    }
}
```

**Comment by t-grm** [comment]
@paulcanning you have a typo: $hostname->fqdn, not fsdn

**Comment by paulcanning** [comment]
Haha oops! Although, is that enough to stop the configtest? I'd have thought to see a different error about the incorrect method call.

**Comment by luceos** [comment]
@paulcanning what is the command you configured and can you run that command successfully? If so, make sure the user running the app has permission to run that command as well, you can update your sudoers file to allow permissions like that.

**Comment by paulcanning** [comment]
@luceos I put my code in the opening post. That's all's I'm trying to run.

The app is running on Homestead and I'm pretty sure the vagrant user has permissions.

**Comment by luceos** [comment]
In `webserver.php` you can configure the command to check the config of nginx. Try to run this command yourself and see if it works. If it works you need to make sure the user running your app has the correct permissions to run the command by itself (eg adding it to the sudoers).

See https://github.com/hyn/multi-tenant/blob/a7366833639b67551357b444cdc8c61e3e027a9e/assets/configs/webserver.php#L168-L174
