### ISSUE TITLE
Create tutorial for Laravel passport implementation

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#348]
I'd like to see a practical step by step tutorial how you can implement Laravel passport like this:

- all tenant websites of one customer can authenticate via one specific tenant website
This requires you to replace the customer model and register the passport server url.

A tutorial of good quality can expect a months patron donations to be paid in return. Contact me on chat for details.

**Comment by Nizari** [comment]
I got stuck here too. The overal setup looks amazing. However, once you want to add 3th party composer packages with their own models, you now either have to extend them all or either I'm missing something in the documentation.

However, already much respect for your hard work!

**Comment by Nizari** [comment]
He Luceos, what is the status of this issue? Are there already people working on this (according to your knowledge)?

**Comment by luceos** [comment]
So far no one has expressed an interest yet. I am aware that extending third party models is tedious, I'll look into a solution for this but that is not inside the scope of this issue.

**Comment by Nizari** [comment]
At least for now, you'll get my Patreon support :). Inspiring code 👍

**Comment by luceos** [comment]
Moved to docs repo.
