### ISSUE TITLE
In DatabaseManager.php line 140:    I am getting the error of Database [tenant] not configured.

### ISSUE THREAD

**Issue by prakash-pokhrel** [hyn/multi-tenant#350]
__Description__

I am getting the error of 
Database [tenant] not configured.
---

__Actual behavior__

..

__Expected behavior__

To run tenant migration

---
__Information__

- hyn/multi-tenant version:5.*
- laravel version:5.5
- database driver and version:
- webserver software and version:
- php version: 7

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by luceos** [comment]
An exception trace would be extremely helpful here. Please re-open when you've appended that.

**Comment by code2prog** [comment]
php artisan config:clear may help
