### ISSUE TITLE
Improve testing to accommodate for phpunit implementation testing

### ISSUE THREAD

**Issue by AustinMaddox** [hyn/multi-tenant#355]
I posted this in the Discord support channel and was asked to create an issue here.
> Is there any documentation on phpunit testing with this package? Seems somehow I need to tell phpunit to create a new tenant and then set that tenant active and then run the tests against them. Is that the right approach?

To which @luceos responded...
> @AustinMaddox it's pretty easy actually :blush: but you have to make sure the system database exists. By default during local tests it tries to use your local mariadb instance with username root and no password and a database called tenancy. Please note tests will clutter your db easily because it creates a tenant for every test, you can clean up by running: `bash tests/scripts/clean-local-dbs.sh && vendor/bin/phpunit -vv` the clean script will delete all databases matching the default regex and it will use the same system database to drop and recreate.

And I responded...
> @luceos Thanks, I guess I just figured that was the wrong approach since it slows down the unit testing so much and, as you say, clutters the testing database. Also, I can't seem to use the RefreshDatabase trait on my tests, which would be nice.
I wrote something which feels very "hacky" to force the use of a single "test-tenant" to speed up my unit testing process. If you could, offer suggestions, that would be helpful. The gist is here: https://gist.github.com/AustinMaddox/f083cac499ac02597a783d9ebf49e306
---

__Actual behavior__
Upon running `vendor/bin/phpunit`, the package creates a new tenant for each test resulting in tons of databases being created and cluttering up things. Also, it doesn't seem that the `RefreshDatabase` trait can be used.
..

__Expected behavior__
Would love to hear others possible solutions and/or strategies for unit testing an application with this package installed. Some additional documentation is needed for whatever strategy is preferred. I would think the ability to force a single tenant to be used throughout the test run would result in the highest performance since hundreds of databases wouldn't need to be created, migrated, seeded, etc.
..

---
__Information__

- hyn/multi-tenant version: 5.0.17
- laravel version: 5.5
- database driver and version: mysql 5.7.16
- webserver software and version: NGiNX 1.10.x
- php version: 7.1.x

---

__tenancy.php config__

Unchanged from default. Probably not applicable.

__webserver.php config__

Unchanged from default. Probably not applicable.

---

**Comment by Thijmen** [comment]
I have big migrations and my tenants also have some big seeders. In my case I use docker to test them with CI and let Docker clean the mess afterwards. No need for cleaning databases up on my side! But I see why this would be handy. Following.

**Comment by juhasev** [comment]
I already posted something similar [https://github.com/hyn/multi-tenant/issues/312]. PHP Unit just doesn't play along well and all testing should be done in sqlite in memory database. What this package needs is away tell Tenancy that we are unit testing and this means the following:

1) We are using configurable testing driver which means Tenancy shall not overwrite DB_DATABASE configuration so you can set this to "sqlite" or whatever you want.

2) Tenancy performs "tenant" only migrations to the given database while supporting standard laravel traits like RefreshDatabase or DatabaseMigrations.

This would allow all of your application logic to be tested using in memory driver for speed. Also this would avoid any clean up efforts after testing is done. And not to forget that your build server won't need MySQL, MariaDB or any of that... Win win all the way.

**Comment by luceos** [comment]
We indeed need to keep the database cleaner by running tests with the same (renewed) tenant. This requires its tenant folder, tenant database and system entries to be removed. I'd gladly merge a PR for this.

**Comment by spacemudd** [comment]
>Would love to hear ... strategies for unit testing

Currently I settled for using Docker to spin up new fresh instances of database servers until a better solution is set in place.

So basically I have a `.env.testing` take the disposable db server connection. After running my tests multiple times, I can dispose the server and spin a new one:

`docker run --name testing-mariadb -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=tenancy -e MYSQL_USER=tenancy -e MYSQL_PASSWORD=secret -p 33065:3306 -d mariadb:10.1`

**Comment by dluague** [comment]
After all the digging in the Laravel core I came up with this solution which will delete tanants databases after the test and able to use RefreshDatabase trait.

```php
<?php

namespace Tests;

use App\Website;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Facade;
use Illuminate\Support\Facades\Schema;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, RefreshDatabase;

    protected $connectionsToTransact = ['system'];

    public function setUp()
    {
    	if (! $this->app) {
            $this->refreshApplication();
        }

        $this->dropAllTenants();

        $this->setUpTraits();

        foreach ($this->afterApplicationCreatedCallbacks as $callback) {
            call_user_func($callback);
        }

        Facade::clearResolvedInstances();

        Model::setEventDispatcher($this->app['events']);

        $this->setUpHasRun = true;   	    	    	
    }    

    protected function dropAllTenants()
    {
    	Website::all()->each(function ($item) {
    		DB::statement("drop database if exists {$item->uuid}");
    	});
    }
}
```

**Comment by luceos** [comment]
I've already pushed code to 5.2 that removes tenant databases, but ONLY those that were created during the tests. Otherwise if you are developing locally you might be deleting too much.

You can see the changes I made in the trait: https://github.com/hyn/multi-tenant/blob/5.x/tests/traits/InteractsWithTenancy.php

**Comment by spacemudd** [comment]
@luceos Do you want people to dance for you? Cause that's how you get people to dance for you. Awesome code. 👌

**Comment by luceos** [comment]
@spacemudd if you visit Laracon EU, you can dance for me 🤗 Hugs afterwards btw 😁 

Thanks, it's always hard to create something which seems clear, understandable and still does what it has to do, without bordering on a hack. Luckily we can get inspiration from great people in our Laravel community.
