### ISSUE TITLE
Delete Nginx conf file on customer delete.

### ISSUE THREAD

**Issue by vikas5914** [hyn/multi-tenant#358]
__Description__

Is there any way to delete the Nginx config file when customer website gets deleted. ?

---

__Actual behavior__

nginx config is not geetting deleteed 

__Expected behavior__

nginx config should get deleted. 
---
__Information__

- hyn/multi-tenant version: 2.x (We are planning to upgrade but we need to solve this)
- laravel version: 5.3.x
- database driver and version: 
- webserver software and version: Nginx 1.10.3
- php version: 7.1.12

**Comment by Thijmen** [comment]
We currently do not have this as far as I know, but you can listen for the event and implement it on your own.

OR you could create a great PR for this :-)

**Comment by vikas5914** [comment]
Thanks for the reply. I will look into the event.

**Comment by luceos** [comment]
The Servant should be able to take care of that now:

https://github.com/hyn/multi-tenant/blob/981db5ff905a69515f1c7381dd8f9cb75c5546f5/src/Listeners/Servant.php#L125-L143
