### ISSUE TITLE
Disk null setting does not work as intended

### ISSUE THREAD

**Issue by juhasev** [hyn/multi-tenant#359]
__Description__

Leaving disk -setting as null will not result into intended behavior. For example my default disk is s3 in filesystems.php and files appear in my local filesystem instead. If you set the tenancy disk to s3 in tenancy.php the file upload to S3 as intended.

  /**
         * Specify the disk you configured in the filesystems.php file where to store
         * the tenant specific files, including media, packages, routes and other
         * files for this particular website.
         *
         * @info If not set, **will revert to the default filesystem.**
         */
        'disk' => null,
..

---
__Information__

- hyn/multi-tenant version: 5.0.17
- laravel version: 5.5
- php version: 7.1

**Comment by luceos** [comment]
Using tenancy with S3 can cause unintended side effects. The package requires a local file system for many of the tenant specific directories. Nevertheless this is a bug.

**Comment by juhasev** [comment]
This far no issues with S3, everything works storing, listing and settings files without a problem. Why do you say that? Everything is going thru Fly system either way so really your application should not know the difference right?

**Comment by luceos** [comment]
There are some files that cannot be included from a cloud storage, for instance [routes.php](https://github.com/hyn/multi-tenant/blob/5.x/src/Listeners/Filesystem/LoadsRoutes.php#L40), [translations](https://github.com/hyn/multi-tenant/blob/5.x/src/Listeners/Filesystem/LoadsTranslations.php#L44) and the [vendor](https://github.com/hyn/multi-tenant/blob/5.x/src/Listeners/Filesystem/LoadsVendor.php#L39). In fact only the configs remain 😊 

This is unrelated to the other assets your application might use.

**Comment by luceos** [comment]
Much has changed since 5.0. If anyone can confirm this is still an issue, I'll reopen.
