### ISSUE TITLE
document how to scale

### ISSUE THREAD

**Issue by Luceos** [hyn/multi-tenant#36]
- what is the effect of the continuous 2 db connections
- how can you optimize the webserver to allow for one system connection and one tenant connection, add that to the installer too
- any ideas how to seperate tenancy over multiple machines

**Comment by dakshhmehta** [comment]
Hello,

First of all thanks for great package. I am starting SaaS application, and actively going to involve in this project.

Hope to have good support from package community.

Also, regarding scaling, to separate machines to host database, I think DNS link can be used directly or using private networking between servers.. Just a random thought in my mind

**Comment by Luceos** [comment]
Using native Laravel functionality any set up theoretically is possible and should result in no issues. The last point noted is primarily concerning assets and other files.

@dakshhmehta thanks for committing to the project and let me know if I can assist you in any way. You can find me on [gitter](https://gitter.im/luceos).

**Comment by luceos** [comment]
see #121
