### ISSUE TITLE
Can't connect to public website

### ISSUE THREAD

**Issue by bobkosse** [hyn/multi-tenant#362]
I succesfully installed the multi-tenant  package. Creating new tenants works fine. I get a nice subdomain for my tenant and can access the application by that subdomain.

My problem is I can't figure out how to create a public website in front of it. So what I want to do:
- domain.com (->public website)
- tenant_1.domain.com (-> application for tenant 1)
...
- tenant_n.domain.com (-> application for tenant n)

the tenant domains are all working but when I try to open a route to my domain.com I get a Page Not Found. All my routes only seems to work on the tenant sub-domains.

What do I need to do to get routes working on the domain.com so customers can read about my product and register for an account?

Regards,
Bob

**Comment by Thijmen** [comment]
I think you can archieve this by 'Sub-Domain Routing' https://laravel.com/docs/5.5/routing#route-group-sub-domain-routing

**Comment by bobkosse** [comment]
I worked out a solution (I don't know if it is a good one so I would appreciatie it if someone could do a small review on my approach!

## Disable autodiscover
In composer I filled the dont-discover block like this:
```
"extra": {
        "laravel": {
            "dont-discover": [
                "hyn/multi-tenant"
            ]
        }
    },
```

## Register providers
Then in ```config/app.php``` I only added the Webserver provider in the providers array like this:
```
Hyn\Tenancy\Providers\WebserverProvider::class,
```

For the TenancyProvider I created my own override and registered that in the provider array like this:
```
App\Providers\CustomTenancyProvider::class,
```

## Custom Tenancy Provider
Then I created the ```CustomTenancyProvider``` like this:

```
<?php
namespace App\Providers;

use Illuminate\Contracts\Http\Kernel;
use Hyn\Tenancy\Providers\TenancyProvider;
use Hyn\Tenancy\Middleware\EagerIdentification;
use \App\Http\Middleware\PublicSite;

class CustomTenancyProvider extends TenancyProvider
{
    protected function registerMiddleware()
    {
        /** @var Kernel|\Illuminate\Foundation\Http\Kernel $kernel */
        $kernel = $this->app->make(Kernel::class);

        $kernel->prependMiddleware(EagerIdentification::class);
        $kernel->prependMiddleware(PublicSite::class);
    }
}
```

So, actually it is a simple override of the ```Hyn\Tenancy\Providers\TenancyProvider```. In the registerMiddleware()``` method is where the magic happens. I only replaced the HostnameActions middleware (```$kernel->prependMiddleware(Middleware\HostnameActions::class);```) with my own middleware class (```$kernel->prependMiddleware(PublicSite::class);```).

## PublicSite middleware
In public site the real magic for the (sub)domain issue happens:
```
<?php

namespace App\Http\Middleware;

use Hyn\Tenancy\Middleware\HostnameActions;
use Illuminate\Http\Request;
use Hyn\Tenancy\Contracts\CurrentHostname;
use Closure;

class PublicSite extends HostnameActions
{
  /**
   * @param Request $request
   * @param Closure $next
   * @return RedirectResponse
   */
  public function handle(Request $request, Closure $next)
  {
      $hostname = app(CurrentHostname::class);

      if ($hostname != null) {
          if ($hostname->under_maintenance_since) {
              return $this->maintenance($hostname);
          }

          if ($hostname->redirect_to) {
              return $this->redirect($hostname);
          }

          if (!$request->secure() && $hostname->force_https) {
              return $this->secure($hostname, $request);
          }
      } 

      return $next($request);
  }
}
```

This simple middleware class just extends the ```Hyn\Tenancy\Middleware\HostnameActions``` middleware and overrides the ```handle(Request $request, Closure $next)``` method.

The real fix was in the 'else' part of the if statement. In that statement there was the line:
```$this-abort($request)```

which causes the 'Page not found' exception. By removing the entire else part, the method will return with ```$next($request)``` so the routing will processed in stead of abort.

Is this the correct way of doing this of am I missing some import points here? 
Anyway, if my 'workaround' is the way to go with this issue, I hope it helps other developers!

**Comment by luceos** [comment]
If you look at what that abort function actually does you will see that it only triggers a 404 when the configuration variable tenancy.hostname.abort-without-identified-hostname is set to true. Perhaps you should try that first before overriding the whole service provider..

Hope this helps.

**Comment by bobkosse** [comment]
@luceos, thank you! I really looked over that. I tried and it works like a charm! Thanks again!

**Comment by alexhiggins** [comment]
The remaining issue would be if you were to visit a tenant that does not exist with ABORT_WITHOUT_IDENTIFICATION=false

```
 InvalidArgumentException
Database [tenant] not configured.
```

Where as if ABORT_WITHOUT_IDENTIFICATION=true you cannot visit other routes.

If i wanted to view the bottom route it would just 404. I think it would be ideal you were able to apply the tenant middleware to the route group you wanted.

```
Route::group(['domain' => '{team}.laravel.test'], function () {
    Route::get('/', 'HomeController@index');
});

Route::get('/', function () {
    return view('welcome');
});
```

**Comment by luceos** [comment]
@alexhiggins set it to false and then add your own middleware. It's a few lines of code really 😊  You can also add the middleware to your own kernel, give it a name and apply it to a group. I'm not sure what the issue is exactly, unless I miss where tenancy lacks such flexibility.

**Comment by engineerpros** [comment]
@luceos @bobkosse I think this should be added in as a feature that we can exclude some routes which are isolated from tenant identification. Generally in every application we need such routes not only for public but also for business logic.
