### ISSUE TITLE
Using custom domains for tenant subdomains

### ISSUE THREAD

**Issue by arunbabucode** [hyn/multi-tenant#370]
First of all, this package is super awesome. I have now a clear separation of each of my tenant applications. 

Now am looking for a feature something like the client can point their existing domain to my application. The condition is, suppose if l have tenant_1.example.com and tenant_2.example.com, the tenant_1 owns a domain called tenantcompany.com, they should be able to do some CNAME forwarding kind of thing, so that, tenantcompany.com reaches tenant_1.example.com. Am not talking about the redirection, I need something like the entire application and its routes of tenant_1.example.com available for tenantcompany.com. So that, their end customers think, it's the tenant-company's application rather than tenant_1.example.com. 

I didn't find any relevant articles matching my requirement. I have seen a few SaaS companies doing the feature which am looking. Please guide me if this is possible with this wonderful package.

**Comment by luceos** [comment]
Just create a new hostname with a fqdn of the custom domain and connect that to the website, tenancy takes care of the logic in the app. Make sure the DNS is properly configured though. A cname to that subdomain should be enough :smile:

**Comment by arunbabucode** [comment]
So can I keep both? Like the application should be accessible over tenant_1.example.com as well as tenantcompany.com (in case the IT guy mess around with the CNAME redirection)

**Comment by luceos** [comment]
Yes you can! 😁
