### ISSUE TITLE
DirectoryGenerator - add public permissions to tenant storage folder

### ISSUE THREAD

**Issue by lucianobosco** [hyn/multi-tenant#371]
Hi, I'm facing some issues when uploading files.
In my case I want to upload a file into media folder but I'm getting this error: "Impossible to create the root directory".
Also when a file is trying to be deleted I get the following error: "Operation not permitted"
As I see the tenant folder using the random ID only has system permissions for read/write so I'm not able to upload/delete any file/folder.
I know that this can be done manually but I'd like to set up everything automatically.

This is how it's done so far:
`
$file = $request->file('image');
$file_name = $file->getClientOriginalName();
$stored = Storage::disk('tenant')->put('media',$file,'public');`

This is supposed to create a media folder and put the file inside it which works fine if I set permissions manually.

Is there a way to overwrite the "created" method within "DirectoryGenerator" class?
Please let me know if I'm wrong, but this is the code line that should be changed in some way:
`$stat = $this->filesystem()->makeDirectory($event->website->uuid);`

Thanks in advance

**Comment by jeitnier** [comment]
Why not just create a Laravel event listener to listen on the DirectoryGenerator event? And inside the listener just do 

```
public function handle(DirectoryCreated $event)
{
    // create a media directory in the tenant directory
    $event->filesystem->makeDirectory($event->website->uuid . '/media');
}
```

You can set whatever permissions you want on the media folder via `makeDirectory`.

**Comment by luceos** [comment]
@jeitnier good point haven't even considered that. That might be a very suitable solution.

**Comment by luceos** [comment]
I think this is more an issue with the file permissions and the requirements of your webserver/php permissions than the package.

Closing for that reason.
