### ISSUE TITLE
How can someone override the connection strings to be used when connecting to a tenant database?

### ISSUE THREAD

**Issue by gkarugi** [hyn/multi-tenant#372]
__Description__
I needed clarification on how can I override the tenant connection config, Where are these configs stored? 

Because when using Azure MySql, the database user generated needs to be appended with the Azure Mysql server name so as to successfully connect to the database. 

I have gone through the  ` Hyn\Tenancy\Database\Connection::class`  but I have not gotten very far.

---

__Actual behavior__
The tenant's database credentials are generated and stored in some location. Everything works as expected locally, but when testing the application hosted on azure, there is a problem with connecting to the tenant database.

Currently, I can see the tenant website UUID, the tenant database and the tenant database user are using the same name

__Expected behavior__

A way to override how the database connection strings are generated

---
__Information__

- hyn/multi-tenant version: 5.0.17
- laravel version: 5.5
- database driver and version: mysql server 5.7
- webserver software and version: Microsoft-IIS/10.0
- php version: 7.1

**Comment by luceos** [comment]
Listen to this event: https://github.com/hyn/multi-tenant/blob/5.x/src/Database/Connection.php#L259

And use mode bypass. Or if it's a minor change you can use the event triggered after the defaults are loaded. The tenant connection is using the system connection for its defaults.

**Comment by gkarugi** [comment]
Thanks for that. I  now understand the process. 
Let me try that.

**Comment by luceos** [comment]
If you need more information please re-open.
