### ISSUE TITLE
404 Not Found When loading non tenant website.

### ISSUE THREAD

**Issue by tangaye** [hyn/multi-tenant#373]
I know a similar [issue](https://github.com/hyn/multi-tenant/issues/357) (#357) had been submitted. I did take a look through the thread, but found little or no help to solve my problem.

It's my first time using the package and as a first time user I went through the [docs](https://laravel-tenancy.com/documentation) and got help on installing and setting up the package, but I found little or no help on how to implement it into a project. Don't blame me I'm not that clever. :neutral_face:  :pensive:

So, I google for ways on how to implement the package into a project and luckily I found this tutotial on [medium](https://medium.com/@ashokgelal/writing-a-full-featured-multi-tenant-laravel-app-from-scratch-a0e1a7350d9d) which utilizes this package. [This is the repository for the project.](https://github.com/ashokgelal/townhouse)

All through the tutorial I didn't experience that much problems; his methods were a bit easy to understand, but I don't know if his methods will still be compatible when the project is updated. Pray it does!

I can access all the sub domains or tenants website but I cannot access the admin panel or view. Ex: I can access a.test.com, b.test.com but not test.com.
When I try to access test.com I get:

> Sorry, the page you are looking for could not be found.

Here is my web.php

    Route::get('/', function () {
        return view('welcome');
    });
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => 'tenancy.enforce'], function () {
        Auth::routes();
    });

For test case I simply want the non tenant website to also access the `welcome view` but as is the case only the **tenants** can access all other views.
Please let me know if there are other files you will love to take a look at. Thanks.

**Comment by ReinierB** [comment]
I ran into the same problem. This solved it for me:

(in config/tenancy.php)

        'early-identification' => env('TENANCY_EARLY_IDENTIFICATION', true),
        'abort-without-identified-hostname' => false,

**Comment by tangaye** [comment]
@ReinierB  Did follow the same tutorial on medium? I ask because I tried and yet still no luck. Here is what I did in tenancy.php

    'early-identification' => env('TENANCY_EARLY_IDENTIFICATION', false),
    'abort-without-identified-hostname' => env('TENANCY_ABORT_WITHOUT_IDENTIFIED_HOSTNAME', true),

 and in .env

    TENANCY_EARLY_IDENTIFICATION=true
    TENANCY_ABORT_WITHOUT_IDENTIFIED_HOSTNAME=false

If you didn't follow the same tutorial can you please show me how I can get this done properly.

**Comment by fletch3555** [comment]
In `config/tenancy.php`...

- `abort-without-identified-hostname` requires the requested hostname (e.g. `test.com`) to exist as a row in the `system`.`hostnames` table.  If you don't want to do this, you will need to set it to false (either directly in the config file, or by setting `TENANCY_ABORT_WITHOUT_IDENTIFIED_HOSTNAME` in your `.env`).
- `early-identification` tells the package to try to detect the hostname early in every request.  It does this through the `HostnameActions` middleware that is loaded by the `TenancyServiceProvider`.  If you disable this, Hostname detection will not occur until the first attempt to resolve `Environment` from the Laravel service container (i.e. `app(Environment::class)`).  Think of this as the tenancy equivalent of "eager loading".  You likely don't want to disable this, but there are reasons you would.

Hope this helps explain it.

**Comment by tangaye** [comment]
@fletch3555 you are right. I realize that when I manually insert  `domain.com` into the **hostnames table** everything works fine. Is this the only way around?
I tried setting `TENANCY_ABORT_WITHOUT_IDENTIFIED_HOSTNAME=false` yet no luck, I also set `TENANCY_EARLY_IDENTIFICATION=false` and still got the same error.
Just so you know I will love tenancy to be eager loaded so that things can speed up a bit.

**IMPORTANT UPDATE:**
If manually inserting `domain.com` is the only way to go and won't cause harm in the future I will love to restrict tenants or customers access to specific views. For example a customer shouldn't be allow to see the admin dashboard or other views associated with the admin.
How would I seperate customers routes from system routes?

**Comment by luceos** [comment]
@nathansiafa you could create a custom middleware and apply it to the "dashboard" routes. The middleware could check whether any tenant was identified and trigger a nuke meltdown.

Seems this issue was resolved, feel free to re-open if need be.

**Comment by joset1ag0** [comment]
documentation on this type of error and few

**Comment by luceos** [comment]
@josetiagobispo if you have a question please create a new issue. Replying to an issue this old has no use. The issue is about a fallback route, you can check the documentation which offers a few solutions:

https://laravel-tenancy.com/docs/hyn/5.x/fallback
