### ISSUE TITLE
How to handle media files if not using the webserver configurations?

### ISSUE THREAD

**Issue by arunbabucode** [hyn/multi-tenant#374]
The setup I am currently using is without enabling the webserver configurations. Everything works perfect related to the database, now am looking to manage the media files. From the documentation, I came to understand, it will work only if am enabled webserver configurations. My development machines are in mac environment and my production environment is in Linux.

 Since the default webserver configurations shipped with this package prefer to use Linux config, I preferred not to hardcode the nginx host locations and fpm locations on my mac env. So the best possible configuration I can think of is reading them from a .env file in the application. However, I am a bit sceptical about doing the same since the configs can vary from both environments (and valet on top of it on my development machine). 

So is there any way access the media files without enabling the websever configurations? I am looking to enable the "public" config on the filessystem and use it. Is there any security concerns in the same? Also is the websever configurations are necessary at any point?

**Comment by Thijmen** [comment]
You can create a route which fetches a media item, eg. `Storage::disk('tenant')->file()->download()`.

**Comment by luceos** [comment]
Using any part of the webserver code is optional. We'll be making it a separate package in a future release. @Thijmen is giving the correct solution here, feel free to re-open if needed.
