### ISSUE TITLE
Using base url without tenant connection

### ISSUE THREAD

**Issue by getrightnl** [hyn/multi-tenant#375]
__Description__

I'm trying to achieve the following. I have a base url with www.example.com / example.com this is a landings page. When a customer enters a register form I post the data to a route. The controller for this route will make a new tenant new-tenant.example.com. When I run my application as it is now on www.example.com it says page not found. It is trying to lookup a tenant, but this should not be a tenant, but the base for my application. Is there a possibility to switch off tenant connection for www.example.com? And use normal connection / database? Is there some middleware? Thanks in advance.

**Comment by luceos** [comment]
You can disable the abort, see https://github.com/hyn/multi-tenant/blob/5.x/assets/configs/tenancy.php#L138

If you have any further questions feel free to re-open.

**Comment by getrightnl** [comment]
Thanks! Exactly what I needed 👍  @luceos

**Comment by getrightnl** [comment]
@luceos sorry thought this should work. But when I set this setting I still get the following error Target [Hyn\Tenancy\Contracts\CurrentHostname] is not instantiable.

**Comment by luceos** [comment]
Enable early identification in the tenancy.php configuration file.

**Comment by richardkeep** [comment]
I enabled it. Same problem persists. Still shows Target Hyn\Tenancy\Contracts\CurrentHostname is not instantiable. I am using a multi-tenant application to fall back to a default hostname

**Comment by luceos** [comment]
@richardkeep create your own issue please, especially when existing issues are closed and reference this issue if you think it's related. For your question you might get a faster solution joining discord https://laravel-tenancy.com/chat
