### ISSUE TITLE
Set eager identification to default and test ci runs

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#376]
Currently eager identification is disabled by default. We'll need to switch that. Let's make sure our tests are corrected for this:

https://github.com/hyn/multi-tenant/blob/afa8c2e759b85fbdd647dea041919bc6df43681f/assets/configs/tenancy.php#L129

**Comment by mintunitish** [comment]
I am confused what needs to be done here? Can you elaborate a little?

**Comment by luceos** [comment]
What has to be done is:

- [ ] set the default value from `false` to `true`
- [ ] go through the tests whether early identification was dynamically set or assumed and update to reflect the change
- [ ] make sure tests are green/okay
