### ISSUE TITLE
Patch HostnameValidator to disallow ports

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#377]
HostnameValidator should be more strict. Maybe look at existing regexes? Make sure it still allows for the punycode domains.

**Comment by luceos** [comment]
Awaiting tests on PR #639.

**Comment by ArlonAntonius** [comment]
We just merged and tagged a new version that includes the feature discussed in this PR:
- Adding regex validation to HostnameValidator

If this doesn't actually solve your issue, you can always contact us through our channel(s):
- [Discord](https://laravel-tenancy.com/chat)
