### ISSUE TITLE
seperate users using fpm sock

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#38]
- use the servername as pool name
- connect to sock in configs
- see: https://www.linode.com/docs/websites/apache/running-fastcgi-php-fpm-on-debian-7-with-apache
- http://www.rackspace.com/knowledge_center/article/installing-nginx-and-php-fpm-setup-for-php-fpm

**Comment by Luceos** [comment]
https://www.digitalocean.com/community/tutorials/how-to-optimize-nginx-with-php-pools-on-an-ubuntu-13-04-vps
