### ISSUE TITLE
"Real path already exists" when installing or composer updating the package L5.6

### ISSUE THREAD

**Issue by snips11** [hyn/multi-tenant#381]
I am getting the following response in the terminal when running a composer update or trying to do a tenancy:install.

> > @php artisan package:discover
> 
>                                               
>   An option named "realpath" already exists.  
>                                               
> 
> Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

I have also tried to manually set up the service providers by using dont-discover in composer.json. Composer is fully up to date and update runs fine without the package in composer.json file. I gather this could be because this version is not L5.6 compatible quite yet?

**Comment by luceos** [comment]
Please post all relevant information as requested when opening an issue. Otherwise this will be a wild goose chase 😞

**Comment by snips11** [comment]
@luceos it was a totally fresh install of Laravel 5.6 and this was the first package installed so there isn't a great deal more I can supply. The error below appears in the terminal when installing and then again when any other artisan command or composer updates are run. I have installed on a 5.5 version and all works fine.

Sorry I cant supply more detail, is there anything I could look for to supply to you to help find the issue?

```

@php artisan package:discover

An option named "realpath" already exists.

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

**Comment by Thijmen** [comment]
You already said it, it works on 5.5 and not on 5.6 If you look at https://github.com/hyn/multi-tenant/blob/5.x/composer.json you'll see that we only support 5.5 now, we dont have support for 5.6 yet.

**Comment by snips11** [comment]
Okay thanks, should have checked there @Thijmen but also wanted to help and supply the specific issue i was having as well. Do you have an expected date for L5.6? Will install on 5.5 and upgrade or will crack on with some other bits if it's due soon. Thanks! :)

**Comment by Thijmen** [comment]
As it's open-source, feel free to start it yourself @snips11 ! :-) I myself am quite busy, maybe @luceos gets a bit of time to work on 5.6.

**Comment by snips11** [comment]
Good idea! Will give it a shot over the weekend!
