### ISSUE TITLE
Class App\Http\Controllers\Hyn\Tenancy\Database\Connection does not exist

### ISSUE THREAD

**Issue by maelga** [hyn/multi-tenant#382]
__Description__

I am trying to get files uploaded by a tenant user to store in the corresponding tenant folder app/tenancy/tenants/abcxyz123.

I have this in my controller to retrieve the current tenant folder and store the file in that folder :
`			$directory = app(Hyn\Tenancy\Website\Directory::class);
			$path = $request->file('file')->store( $directory->path() );
`

---

__Actual behavior__

I get this error:
**"Class App\Http\Controllers\Hyn\Tenancy\Database\Connection does not exist"**

__Expected behavior__

This looks like a namespace issue, but after hours spent trying to solve it, I need your help.

---
__Information__

- hyn/multi-tenant version: 
- laravel version:
- database driver and version:
- webserver software and version:
- php version:

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by gkarugi** [comment]
Change this:
 `$directory = app(Hyn\Tenancy\Website\Directory::class); $path = $request->file('file')->store( $directory->path() );` 

to 

`$directory = app(\Hyn\Tenancy\Website\Directory::class); $path = $request->file('file')->store( $directory->path() );`

**Comment by Thijmen** [comment]
What @gkarugi says, or do the proper import.

**Comment by maelga** [comment]
> ...or do the proper import.

@Thijmen What do you mean with "proper import"?

**Comment by gkarugi** [comment]
What @Thijmen is saying is use proper imports for the `Directory` and `Connection` classes.  i.e

`use Hyn\Tenancy\Website\Directory;`
`use Hyn\Tenancy\Database\Connection;`

**Comment by maelga** [comment]
Thank you very much for your help!
