### ISSUE TITLE
Tenancy database RefreshCommand migrates the system migrations in the websites

### ISSUE THREAD

**Issue by Dayvisson** [hyn/multi-tenant#385]
__Description__

The command **tenancy:migrate:refresh** runs:

- **migrate:reset** and   **migrate** 

 instead

-  **tenancy:migrate:reset** and **tenancy:migrate**

---

__Actual behavior__

This migrates the system migrations in the websites.

__Expected behavior__

The problem is the trait **MutatesMigrationCommands**  calls the parent:handle()  that is migrate:refresh that calls the defaults  **migrate:reset** and   **migrate**.

We should build a custom handle for Hyn\Tenancy\Database\Console\Migrations\RefreshCommand that calls the **tenancy:migrate:reset** and **tenancy:migrate** command.

I will try to send a PR to solve this.

---
__Information__

- hyn/multi-tenant version: 5.0.17
- laravel version: 5.5.25
- database driver and version: mysql 5.7
- webserver software and version: nginx 1.13.3
- php version: 7.1.11

**Comment by luceos** [comment]
Thanks that must have been an oversight. Would love to see a PR!

**Comment by Dayvisson** [comment]
Well, I'm working here and I may have found an alternative way to fix this issue.

Cause, if we choose rewrite the handle method from **Illuminate\Database\Console\Migrations\RefreshCommand** we have also to rewrite the methods **runRollback** and **runReset** and I don't know if this is the best way.

So, I rewrote just the handle method from the trait MutatesMigrationCommands, addind the path option. This way we're still runing the migrate:reset and migrate commands, but now  looking in the right paths.

I'll send the pull request now, the you can show this alternative.

**Comment by luceos** [comment]
Will be part of 5.1.3.
