### ISSUE TITLE
No commands defined in tenant namespace

### ISSUE THREAD

**Issue by swati-clarion** [hyn/multi-tenant#391]
I successfully installed tenancy using php artisan tenancy:install

The class CreateTenant is also created at app\Console\Commands\CreateTenant.php

I also added these in providers in app.php
// Hyn multi tenancy.
    Hyn\Tenancy\Providers\Tenants\ConfigurationProvider::class,
    Hyn\Tenancy\Providers\TenancyProvider::class,
    // Hyn multi tenancy webserver integration.
    Hyn\Tenancy\Providers\WebserverProvider::class,

and added this in Kernel.php,

protected $commands = [
        // Commands\CreateTenant::class
	'App\Console\Commands\CreateTenant'
 ];

But when I run php artisan tenant:create gc  gc@example.com , I get error "There are no commands defined in "tenant" namespace. 

I have cleared config cache many times, but still same error. Please guide what am I missing here.

Thanks

**Comment by luceos** [comment]
I am sorry, I did not write that CreateTenant command. Feel free to double check the `$signature` property on that command.

**Comment by mallu266** [comment]
HI i am also getting the same error, but not getting how to fix.

**Comment by mallu266** [comment]
Hi

I am also getting the error as below

**Commant**: php artisan tenant:create test test@gmail.com 
                                                          
**Error:**  There are no commands defined in the "tenant" namespace.  
                                                            
  Did you mean one of these?                                
      tenancy                                               
      tenancy:db                                            
      tenancy:migrate

**Comment by swati-clarion** [comment]
Hi ,

You can follow this tutorial and use createTenant Class from this tutorial. This will sort above issue.

https://medium.com/@ashokgelal/a-full-featured-multi-tenant-app-with-laravel-part-1-4049a3cc229d

Thanks,

**Comment by mallu266** [comment]
@swati-clarion
I Have followed the same document earlier but still am getting this error....
tried to clear all cache aswell..
Tried a new install too...

**Comment by luceos** [comment]
@mallu266 this is not an issue with this package. This package offers no tenant create command. In case you have any troubles I'd suggest double checking the tutorial.

**Comment by Altafyanto** [comment]
Hi  Luceos,
i run command php artisan tenancy:install ,this problem output this command There are no commands defined in the "tenancy" namespace. i follow instruction step by step document instalation on https://laravel-tenancy.com/docs/hyn/5.x/installation,please problem solving this issues.
thank you

**Comment by luceos** [comment]
@Altafyanto please create a new issue, it's not related to this one.

---

Any questions related to commands prefixed with `tenant:` are unrelated to this package.
