### ISSUE TITLE
Directory->path issue for Windows 

### ISSUE THREAD

**Issue by lucian-dragomir** [hyn/multi-tenant#393]
__Description__

The method Directory->path is not identifying correctly the path prefix in windows environments due to the DIRECTORY_SEPARATOR constant that is different then the separator used when returning the tenant files when called "$this->directory->files($path)" in the LoadsConfigs class.

---

__Actual behavior__

curently the config files are returned using always the unix path separator in LoadConfigs->readConfigurationFiles and are not identified correctly when trying to match tenant prefix in Directory->path function

__Expected behavior__

compare prefix using always the unix separator

`public function path(string $path = null, $local = false) : string
    {
        $prefix = sprintf(
            "%s%s",
            $this->getWebsite()->uuid,
             //this is the part for proposed fix            

             //DIRECTORY_SEPARATOR
            "/"
        );`

---

**Comment by luceos** [comment]
Yes, we were onto this one, I just pushed a commit about it and will take it along for 5.1.0
