### ISSUE TITLE
Route middleware

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#396]
Let's create a middleware that can be applied to routes to identify whether the request is on a tenant website.

Having this middleware allows the application to easily pass requests to another layer, eg the landing page (see the docs).

**Comment by ernes87lp** [comment]
Here you have a tutorial to enforce tenancy https://medium.com/@ashokgelal/a-full-featured-multi-tenant-app-with-laravel-part-4-tenancy-aware-authentication-e0ee37270bc8
It creates a simple middleware to achieve that.

**Comment by visualcookie** [comment]
That's a great idea, as my application won't have any CMS likes features, but the Tenants have. For now seperating them is quite hard to get, from the documentation.

Maybe it could be clearified a bit more for this "not"-so-special case.

**Comment by luceos** [comment]
Docs already have information on how to set up a landing page using three methodologies.
