### ISSUE TITLE
requesting 5.6

### ISSUE THREAD

**Issue by impactcolor** [hyn/multi-tenant#397]
Hi documentation says it's for 5.5 but I tried installing it via composer and got this error:
    - hyn/multi-tenant 5.1.0 requires laravel/framework 5.6.* -> satisfiable by laravel/framework[5.6.x-dev, v5.6.0, v5.6.1, v5.6.2, v5.6.3, v5.6.4, v5.6.5] but these conflict with your requirements or minimum-stability.

**Comment by luceos** [comment]
5.5 and 5.6 are both supported, you must be referring to the readme (i've missed), see the actual documentation : https://laravel-tenancy.com/documentation/introduction/requirements

From the composer error it seems you do not have 5.6 installed.

Use hyn/multi-tenant `5.0.*` for laravel `5.5.*`, use `5.1.*` for laravel `5.6.*`
