### ISSUE TITLE
Unable to run on Windows OS

### ISSUE THREAD

**Issue by anil1712** [hyn/multi-tenant#398]
__Description__

Hi,
I have Windows PC (W10 OS), I am unable to run it on windows over XAMPP, can some help me to run this on the same.
..

---

__Actual behavior__
Not working anymore

..

__Expected behavior__

..

---
__Information__

- hyn/multi-tenant version:
- laravel version:
- database driver and version:
- webserver software and version:
- php version:

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by fletch3555** [comment]
Do you take a computer to a repair shop, put it on the desk, and say "it's broken"...?

We're going to need a lot more information about WHAT's not working, what you've tried (whether it worked or not), version numbers for everything, etc.

**Comment by anil1712** [comment]
Yeah, you are right, so let me.
I followed the documentation and did all the configuration but I got stuck in Apache configuration, so I needed help to configure it with XAMPP.
One more thing, Actually I have created vhost (domain: example.com) in apache and whenever I try to hit that domain in the browser then its redirecting to `https://example.com`

**Comment by luceos** [comment]
Did you create a tenant hostname with `force_ssl` set to true? If not this is a configuration issue of your server and unrelated to this package.

**Comment by anil1712** [comment]
Ok, I will check the `force_ssl` things but can you explain how to configure apache something like [this](https://laravel-tenancy.com/documentation/webserver/apache)  for windows

**Comment by luceos** [comment]
@anil1712 I'm sorry but this issue is related to server management, not the configuration of this package (on Windows).
