### ISSUE TITLE
Override Connection Resolver in the Eloquent Model

### ISSUE THREAD

**Issue by bkintanar** [hyn/multi-tenant#400]
```
[4:39 AM] luceos: this would remove the need of the trait and you could potentially use a config file having a mapping of class to connections to resolve a connection
[4:39 AM] luceos: https://github.com/illuminate/database/blob/master/Eloquent/Model.php#L1156
[4:39 AM] luceos: that is actually an instance of db which is the connection manager
[4:39 AM] luceos: so by overriding that class and re-injecting it by setting it on the model
[4:39 AM] luceos: you can pretty much do anything related to the connections
[4:39 AM] luceos: https://github.com/tenancy/tenancy/blob/master/src/Eloquent/ConnectionResolver.php
```

**Comment by luceos** [comment]
The problem with this approach is that the Connection Resolver is unaware of what class the connection is being requested. One could use a debug backtrace to resolve that, which is pretty hacky.

**Comment by luceos** [comment]
My initial thought was to replace the connection resolver for Model (by illuminate), but it might as well be possible to replace the Resolver only for the specific models you need to replace it in..

**Comment by luceos** [comment]
Another option is to use Model Observers as suggested by Bryse on discord.

**Comment by luceos** [comment]
Done in 5.1.9

**Comment by luceos** [comment]
I was assuming one cannot identify the model being overridden with the custom Connection Resolver. But what we have to do is only call the static method for these classes.

**Comment by felagund18** [comment]
Connection Resolver is being reset by 'Illuminate\Database\DatabaseManager'. I think that using connectionResolver is not useful anymore while forcing to use tenant connection on third-party package models...

It was not working on
php - 7.2.8
laravel - 5.7.5

___
```
class Base {
	protected static $prop;

	public static function setProp($prop)
	{
		static::$prop = $prop;
	}

	public static function getProp()
	{
		return static::$prop;
	}
}

class A extends Base { }
class B extends Base { }

A::setProp('prop1');
echo 'A-'.A::getProp().PHP_EOL;

B::setProp('prop2');
echo 'B-'.B::getProp().PHP_EOL;

echo '------'.PHP_EOL;
echo 'A-'.A::getProp().PHP_EOL;
echo 'B-'.B::getProp().PHP_EOL;
```
It prints
```
A-prop1
B-prop2
------
A-prop2
B-prop2
```

**Comment by luceos** [comment]
It completely depends on the loading order of things. If you have an issue with this please create a new issue and report what error you run into @felagund18 . Thank you.
