### ISSUE TITLE
multi-tenancy support for lumen-framework 

### ISSUE THREAD

**Issue by lucian-dragomir** [hyn/multi-tenant#401]
Hi,

Would it be possible / do you plan to add support for hyn/multi-tenant for lumen framework?
I am interested to create an application having multi-tenancy features without using the entire laravel framework (currently each hyn/multi-tenant package is bounded it's corresponding laravel version).

Are any workarounds available to use multi-tenancy in a lumen setup ?
 
Thank you,
Lucian

**Comment by luceos** [comment]
Hello Lucian,

This would most likely need some investigation. I'm not saying no, I'm just not sure it's feasible..

Thanks,

Daniël.

**Comment by luceos** [comment]
I was considering requiring a deeper level of requirement here, eg using laravel/framework. But Lumen doesn't use the framework at all. The only valid way of doing this then would be either to drop the requirement completely or put the constraint on any of the packages used by both Laravel and Lumen 🤔

**Comment by luceos** [comment]
Not pursuing.

**Comment by Marko298** [comment]
I have a small fork where I added support for lumen but I haven`t tested it fully (main features works fine) https://github.com/Marko298/multi-tenant
