### ISSUE TITLE
MongoDB compatibility using jenssegers/laravel-mongodb

### ISSUE THREAD

**Issue by misterdoak** [hyn/multi-tenant#405]
Hi,
I'd like to use your package to setup a multitenant architecture. But I only have MongoDB....

I try to provide my own Models (through tenancy.inc) compatible with jenssegers/laravel-mongodb Eloquent implementation. Sounds like a good option but for now i'm stuck with CustomerContract, HostnameContract and WebsiteContract because they use return type hinting : BelongsTo and HasMany. laravel-mongodb has its own implementation of BelongsTo and HasMany and I can't override return type hinting by extending interface. Consequently I have no possibility to respect these contracts according to repositories...

Any idea? 

Thanks a lot!

Alan

**Comment by Thijmen** [comment]
We have no support for MongoDB as of yet and we do not provide the ability to override those interfaces. However, we'd gladly look into a PR which adds support for MongoDB!

**Comment by luceos** [comment]
Feel free to reopen when considering a pr. @misterdoak
