### ISSUE TITLE
abort-without-identified-hostname flag

### ISSUE THREAD

**Issue by redroses** [hyn/multi-tenant#406]
I am using wamp v3.
configured hosts to use 
127:0:0:1 mml
127:0:0:1 abc.mml
127:0:0:1 xyz.mml

http://abc.mml/anyroute works
http://mml/anyroute - 404 error

until I changed abort-without-identified-hostname from true to false.

is this the expected behavior?

basically in production I would like:

https://mysite.com for all users to go and register
as well as faqs, about, etc not to worry about tenancy
The user registers at https://mysite.com/register
From there a tenant is created - abc.mysite.com

Am I going about this correct?
Should I do it another way?

How should a site differentiate between tenant site and global site?

Thanks
Randy

**Comment by fletch3555** [comment]
The app wasn't able to identify `mml` as a hostname, so having that config set to true is doing exactly what it's supposed to do.

You have a few options.

1. You can look into the "Fallback" functionality: https://laravel-tenancy.com/docs/hyn/5.x/fallback
2. You can leave that config set to `false` and implement the abort functionality yourself
3. Or you can simply add that domain to the `hostnames` table without associating it to any tenants/websites.  This will allow the hostname resolution to succeed and let your routes be handled appropriately.

I'm sure there are other options that I've missed.  Ultimately, it's up to you how you do it.

**Comment by redroses** [comment]
Thanks
