### ISSUE TITLE
database migrations override

### ISSUE THREAD

**Issue by redroses** [hyn/multi-tenant#407]
Is it possible to override the 3 default migrations: customers, hostnames, websites.
I know artisan tenant:migrate command migrates the system database using assets/migrations.
I thought artisan migrate would use the custom one's I created in the project's migrations folder.
It did not.
The php artisan vendor:publish --tag=tenancy gives me config files, but no migration files to override.
I copied the default migrations, but they do not get used.
Why do I want to do this?
Changing the size of fields, adding custom fields, adding cashier.
Yes, I could use alter migrations. But just starting the project, I would prefer to get all the columns in the create table migration.
Can I do this?

**Comment by bkintanar** [comment]
Those 3 migration files are the ones needed for multi-tenant to work. as long as you only add fields and modify fields that you added, I think you'll just do fine.

**Comment by redroses** [comment]
How can I do this?
It uses the migrations in the hyn/multi-tenant package.
How do I get it to ignore the migrations in hyn and use the one's in my project?

**Comment by fletch3555** [comment]
Your best bet is to leave the package migrations as-is and let the package define what it needs.  If you need to add/change things, then create new "alter" migrations in your app

**Comment by redroses** [comment]
i found php artisan migrate --path="database/migrations" which uses the project migrations.
i had never done that before. it worked.
thanks all for your help.

**Comment by Krato** [comment]
@luceos Why not to publish the migrations and use it from the normal folder?

This will be useful if we want to change some relations.

Regards!

**Comment by luceos** [comment]
@Krato feel free to copy the migrations to the normal folder and modify them. If you do just don't run `php artisan tenancy:install` 👍

**Comment by Krato** [comment]
@luceos Yes sure I did it. But when I call `php artisan migrate:status` the app still waiting for the tenancy migrations on the vendor folders. Thats the problem I think so.

<img width="563" alt="migrations" src="https://user-images.githubusercontent.com/74367/40363432-ce70d9fc-5dcf-11e8-9a2b-ea0514344960.png">

**Comment by luceos** [comment]
That's because you renamed them. You changed the dates on those 🤷‍♂️
