### ISSUE TITLE
MediaManager is not returning Content-Type Header

### ISSUE THREAD

**Issue by f0reclone** [hyn/multi-tenant#408]
__Description__
Currently the MediaManager is just returning the binary content of the file without the right Content-Type Header.

__Fix__
Change the __invoke function in Media Manager to add the Header with the mimeType provided by Storage:
`use Illuminate\Support\Facades\Storage;`

```
public function __invoke(string $path)
    {
        $path = "$path";
        if ($this->directory->exists($path)) {
            return response($this->directory->get($path))->header('Content-Type', Storage::disk('tenant')->mimeType( $path));

        }

        return abort(404);
    }
```

- hyn/multi-tenant version: 5.0.0
- laravel version: 5.5
- database driver and version: -
- webserver software and version: NGINX
- php version: 7.0.0

**Comment by luceos** [comment]
@f0reclone a PR would be gratefully accepted 👍
