### ISSUE TITLE
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

### ISSUE THREAD

**Issue by xyrintech** [hyn/multi-tenant#418]
Getting this issue for Laravel 5.6

**Comment by luceos** [comment]
Feel free to add more information 👍

**Comment by xyrintech** [comment]
composer require hyn/multi-tenant

Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In DatabaseManager.php line 140:
                                     
  Database [system] not configured.  
                                     

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by xyrintech** [comment]
@luceos Added description.

**Comment by luceos** [comment]
```
Database [system] not configured.
```

Read the requirements:

https://laravel-tenancy.com/docs/hyn/5.x/requirements

**Comment by aminalali8** [comment]
any solution for this ?

**Comment by luceos** [comment]
@aminalali8 please create an issue of your own filling out all required information.

The error that the system connection is not configured relates to the requirement to set up a connection called `system` inside your `config/database.php`.

**Comment by umakantsharmacedcoss** [comment]
i have the same issue, fixed by changing `mysql` to `system` in `config/database.php`

Thanks @luceos
