### ISSUE TITLE
Issue while installing this package

### ISSUE THREAD

**Issue by xyrintech** [hyn/multi-tenant#419]
- hyn/multi-tenant version: 5.1
- laravel version: 5.6
- database driver and version: default
- webserver software and version: default
- php version: 7.1

composer require hyn/multi-tenant

raise error:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In DatabaseManager.php line 140:
                                     
  Database [system] not configured.  
                                     

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by luceos** [comment]
read the comment on the previous issue, please do not duplicate the same issues..

https://github.com/hyn/multi-tenant/issues/418

This is not a bug, please read the requirements in the docs 😄
