### ISSUE TITLE
document the flow of the tenancy system

### ISSUE THREAD

**Issue by Luceos** [hyn/multi-tenant#42]
How is the tenant decided, what effect has the middleware.. etc
- [x] how is the tenant decided upon
- [x] what is the middleware doing
- [ ] document how global vs localized works

**Comment by thinusn** [comment]
This would be very helpful.

**Comment by deleugpn** [comment]
Subscribing to this.

**Comment by luceos** [comment]
The documentation is already mentioning part of this; https://hyn.readme.io/v2.0/docs/tenant-identification.

**Comment by luceos** [comment]
closing this in favor of #121
