### ISSUE TITLE
Trying to figure it out on Documentation

### ISSUE THREAD

**Issue by xyrintech** [hyn/multi-tenant#420]
Please suggest if this package supports accessing the web application on one domain but with prefix tables in single database. 

Like abc.com as domain. 
A user belongs to 2 tenants company_1 and company_2.
One database has tables with company_1_... and company_2_... prefix.

**Comment by luceos** [comment]
Yes that's possible. Please understand that the prefix method is implemented, but a) it has no code coverage and b) is not recommended. However if you encounter any issues while using it, feel free to report them.

You can configure the prefix method in the `tenancy.php` configuration file under the key `db`.
