### ISSUE TITLE
Revisit Documentation

### ISSUE THREAD

**Issue by bkintanar** [hyn/multi-tenant#422]
I think the documentation is somewhat behind already. There's a need to revisit the entire documentation and check all pages for what is still working and what new things needed to be added.

#### Getting Started
- [ ] [Requirements](https://laravel-tenancy.com/docs/hyn/5.x/requirements)
- [ ] [Installation](https://laravel-tenancy.com/docs/hyn/5.x/installation)
- [ ] [Configuration](https://laravel-tenancy.com/docs/hyn/5.x/configuration)

#### Tenant Principles
- [ ] [Concepts](https://laravel-tenancy.com/docs/hyn/5.x/concepts)
- [ ] [Structure](https://laravel-tenancy.com/docs/hyn/5.x/structure)
- [ ] [Identification](https://laravel-tenancy.com/docs/hyn/5.x/identification)
- [ ] [Fallback](https://laravel-tenancy.com/docs/hyn/5.x/fallback)
- [ ] [#432] [Middleware](https://laravel-tenancy.com/docs/hyn/5.x/middleware)

#### Implementation
- [ ] [Models](https://laravel-tenancy.com/docs/hyn/5.x/models)
- [ ] [Repositories](https://laravel-tenancy.com/docs/hyn/5.x/repositories)
- [ ] [Filesystem](https://laravel-tenancy.com/docs/hyn/5.x/filesystem)
- [x] [#423] [Migrations](https://laravel-tenancy.com/docs/hyn/5.x/migrations)
- [ ] [Connections](https://laravel-tenancy.com/docs/hyn/5.x/connections)
- [ ] [Queues](https://laravel-tenancy.com/docs/hyn/5.x/queues)
- [ ] [Events](https://laravel-tenancy.com/docs/hyn/5.x/events)
- [ ] [Cache](https://laravel-tenancy.com/docs/hyn/5.x/cache)
#### Webserver
- [ ] [Apache](https://laravel-tenancy.com/docs/hyn/5.x/apache)
- [ ] [Nginx](https://laravel-tenancy.com/docs/hyn/5.x/nginx)
#### Tutorials
- [ ] [Full-featured app](https://laravel-tenancy.com/docs/hyn/5.x/full-featured-tutorial)
- [ ] [Spatie permission](https://laravel-tenancy.com/docs/hyn/5.x/spatie-laravel-permission)

**Comment by luceos** [comment]
Obsolete for now.
