### ISSUE TITLE
Revisit migration page in documentation

### ISSUE THREAD

**Issue by bkintanar** [hyn/multi-tenant#423]
Link: https://laravel-tenancy.com/docs/hyn/5.x/migrations

- [x] verify all migration related commands are documented
- [x] give one example (and explain) of how to run commands against all tenants, default behavior
- [x] give one example (and explain) of how to run commands against specific tenants

**Comment by luceos** [comment]
Added three todos in your start post.

**Comment by bkintanar** [comment]
@luceos what other things we can do with the migrations.md file here?
