### ISSUE TITLE
Hello, I'm looking for best strategy to overwrite default hostname behaviour

### ISSUE THREAD

**Issue by wukis** [hyn/multi-tenant#425]
Hello,

first of all thank you for this awesome package, this is a huge contribution to the community. 

I'm looking for a way to swap out default behavior for  hostnames:

- tenant1.basedomain.com
...
- tenantN.basedomain.com

into:

- basedomain.com/tenant1
...
- basedomain.com/tenantN

I could not find anything similar to this approach. Ofcourse I can override service provider and etc., but isn't there a better way?

**Comment by jeremyj11** [comment]
Just commenting - it's a bad idea to have different tenants using the same basedomain as by default php sessions are per domain... meaning a user logged into basedomain.com/tenant1 could potentially just change their url to basedomain.com/tenantN and be already logged in / have access...

**Comment by wukis** [comment]
@jeremyj11 - this is actually a concern that I didn't think about. I was kind of thinking that without subdomain it would be great to give "personal space" for each tenant through route.

**Comment by luceos** [comment]
@wukis it's possible but you'll have to do the tenant identification yourself, which might be pretty easy using the request path.
