### ISSUE TITLE
Documentation Many To Many Relationship with Pivot Table in Tenant Database

### ISSUE THREAD

**Issue by f0reclone** [hyn/multi-tenant#426]
Hello, last night I wanted to use a belongsToMany Relationship with two Models
User -> in Tenant Database
Role -> in System Database
user_roles Pivot Tabe -> in Tenant Database

To resolve this, the following topic on Stackoverflow helped me:
https://stackoverflow.com/questions/25142968/belongstomany-relationship-in-laravel-across-multiple-databases

```
$database = $this->getConnection()->getDatabaseName();
return $this->belongsToMany('App\Role', "$database.user_roles");
```
The code above can be used in the Class that uses the Tenant Connection (User)
In the other class (Role) just use tenancy or whatever you renamed it to as your database name.

**Comment by luceos** [comment]
I guess adding a method to the trait would make more sense than having to specify the database name every time. Good thing to have an issue though 👍

**Comment by Punksolid** [comment]
Hi, I have almost the same issue, User is in the system database, and roles and permissions in the tenant database. I'm using spatie-permission package to do so.
But even after that I explicitly used UsesTenantConnection::class in 'Role' and 'Permission' extended models, and UsesSystemConnection::class in User model. It stills tries to look for permissions table in the main database. 

I see that the configs aren't loaded in the vendor package. So there is a registrar that isnt loading properly.

I don't know how to force more that I want to use the tenant database in this package.

The further I could go on this in my code is this
app/Permission.php
```php
    protected static function getPermissions(array $params = []): Collection
    {
        return app(PermissionRegistrar::class)
            ->getPermissions($params);
    }
```
The relationship is explicitly putted in this model this way
```php
        $database = $this->getConnection()->getDatabaseName();
        $table_name = config('permission.table_names.role_has_permissions');

        return $this->belongsToMany(
            Role::class,
            "$database.$table_name"
        );
```

The config spatie permission file is using explicitly my models. Te tenancy config file is also explicitly forcing Permission and Role to use the tenant database. 


Even tho PermissionRegistrar::class that is in vendor is not loading the current connection. Any advice on how to pass the current connection? I don't know what else to do.

P.D. Other models works correctly

Thanks

**Comment by angelmartz** [comment]
I have relationships between MySQL and MSSQL, working fine just modify one attribute on Models

protected $connection = 'mysql'

How can I change with this package?

**Comment by angelmartz** [comment]
Check this
https://laravel.com/docs/5.8/database#using-multiple-database-connections

```php
class SomeController extends BaseController {

    public function someMethod()
    {
        $someModel = new SomeModel;

        $someModel->setConnection('mysql'); // non-static method

        $something = $someModel->find(1);

        $something = SomeModel::on('mssql')->find(1); // static method

        return $something;
    }

}
```

**Comment by ArlonAntonius** [comment]
Going to close this,

Thank you very much for the info, it will be used for sure!
