### ISSUE TITLE
SAVEPOINT Exception when using transactions on ubuntu

### ISSUE THREAD

**Issue by redroses** [hyn/multi-tenant#427]
Has anyone come across SAVEPOINT issue using multi-tenant?

Any help or guidance would be appreciated.

The exact same code 

WORKS on
windows 7 or 10.
mysql 5.7.9
apache 2.4.33
php 7.1.15

FAILS on
ubuntu 17.10
mysql  5.7.21
apache 2.4.33
PHP 7.1.16

with SAVEPOINT exception when using DB:

DB::beginTransaction();
		try {
                        // *** This calls the hyn multitenant code
			$customer = Customer::createCustomer($input);
                       .....

this is some of exception trace

[2018-04-20 12:22:38] local.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT trans    2 does not exist
  3 [2018-04-20 12:22:38] local.ERROR: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1305 S    AVEPOINT trans2 does not exist in /usr/webapps/laravel/mymemberlocker/vendor/doctrine/dbal/lib/Doctrine/DB    AL/Driver/PDOConnection.php:60
  4 Stack trace:
  5 #0 /usr/webapps/laravel/mymemberlocker/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(60)    : PDO->exec('ROLLBACK TO SAV...')

**Comment by luceos** [comment]
Haven't done any research yet. But would you be able to use a lower MySQL Version on the failing instance? Just to see whether it's related to the MySQL version.

**Comment by mnuhell** [comment]
Hi, That happened to me the other day, in my case it was because when you do a refreshdatabase there is a trace in the database or the tenant has not been erased correctly.

**Comment by bkintanar** [comment]
@mnuhell can you define what you mean about the database has not been erased correctly? and what MySQL version were you using?

**Comment by mnuhell** [comment]
@bkintanar
 
Mysql version:  5.7.18

When some data is not deleted correctly or the seeder does not run correctly and there is some trace in the database and then you run the tests again.

**Comment by redroses** [comment]
I've rewritten the code to not use transactions for the method that's causing the problem.
Basically the problem exists when trying to use transactions before calling 
app(CustomerRepository::class)->create($customer);
app(WebsiteRepository::class)->create($website);
app(HostnameRepository::class)->attach($hostname, $website);

and only on the newer version of mysql on ubuntu.

I am pausing work on trying to figure this out for now and will revisit when I get the following to work.
I am having a similar problem when trying to seed the newly created tenant database and am going to open a new issue for it.

**Comment by redroses** [comment]
Now WORKS.
Because of savepoint errors, I removed the transaction logic.
The hyn/tenancy package must be doing commits.
The system database always committed the customer, hostname, website data.
The tenant database does not.
Wrapping the tenant specific code in a transaction solved this.

public function setupCustomer(Registration $registration, array $data) {
		try {
			$customer = $this->createCustomer($registration, $data);
                        // customer, website, hostname records now exist.
			try {
				DB::connection('tenant')->beginTransaction();
				$this->seedDefaultData();
				$this->createUser($data);
				DB::connection('tenant')->commit();
			} catch (Exception $e) {
				DB::connection('tenant')->rollback();
				throw $e;
			}
			return $customer;
		} catch (Exception $e) {
			throw $e;
		}
	}

The savepoint error must have occurred when I tried to wrap the system customer creation in a transaction:
This failed with the savepoint error.

public function setupCustomer(Registration $registration, array $data) {
          try {
                DB::connection('system')->beginTransaction();
		$customer = $this->createCustomer($registration, $data);

		// tenant db connection - customer created
		DB::connection('tenant')->beginTransaction();
		$this->seedDefaultData();
		$this->createUser($data);

		DB::connection('system')->commit();
		DB::connection('tenant')->commit();
  	} catch (Exception $e) {
                    DB::connection('system')->rollback();
		    DB::connection('tenant')->rollback();
		   throw $e;
	}

**Comment by redroses** [comment]
Note:
I would still like to be able to wrap both DBs in a transaction and commit or roll them back together.
Right now I have to cleanup the system tables if the tenant transaction gets an exception.
This is because it is getting commited automatically - or I just don't know how to set it up properly.

**Comment by luceos** [comment]
Transactions are always connection-based (eg per database) and not global if I'm not mistaken. There would be no way of solving this by using Laravel natively. Perhaps some helper function would work or a third party package exists that can do this.
