### ISSUE TITLE
Tenant Database Connection not initialized in Ubuntu

### ISSUE THREAD

**Issue by reneenistler** [hyn/multi-tenant#429]
Good afternoon,
I have installed hyn multi-tenant package.  
I am able to successfully create the customer, hostname and website records in the system database both locally and in my cloud environment.  However, on my local windows environment I have also successfully created a tenant database, tenant user account (named the same as the tenant database), migrated the tenant tables ,  seeded the tenant tables and created a user in the tenant user table.  
On my Ubuntu cloud environment, the tenant tables are migrated to the tenant database but DOES NOT seed the tenant tables and DOES NOT create the tenant user in Ubuntu.  

Questions.
1) Where are the tenant database connection parameters stored/located? (eg driver, host, port, etc)
2) Can you confirm that there is not a Tenant database connection to CREATE the tenant database or migrate tenant tables?
3) A tenant database connection is required to run the tenant seeders and create the tenant user, how do I connect to the tenant database?
4) What version of mysql is recommended or tested up through with the hyn multi tenancy package? 
Is there something in MySQL version 5.7.21 that is causing issue in the Ubuntu environment?
Any help you can provide is greatly appreciated.

Local Environment:
windows 10
mysql 5.7.9
apache 2.4.33
php 7.1.15

Cloud Environment:
ubuntu 17.10
mysql 5.7.21
apache 2.4.33
PHP 7.1.16

**Comment by bkintanar** [comment]
@reneenistler thank you for your interest and in using this package.

1. if you look at [MariaDB.php](https://github.com/hyn/multi-tenant/blob/5.x/src/Generators/Webserver/Database/Drivers/MariaDB.php) you will see how the database is being created. Tenancy doesn't store database user/password anywhere but calculates the password by using your APP_KEY. See the [DefaultPasswordGenerator](https://github.com/hyn/multi-tenant/blob/5.x/src/Generators/Database/DefaultPasswordGenerator.php) to know how this is being calculated.
2. Tenancy uses the system connection to create tenant databases.
3. Can you explain more on what you mean by this?
4. Tenancy is tested to run with the latest MySQL, MariaDB, and PostgreSQL.

**Comment by reneenistler** [comment]
bkintanar - thank you for your speedy response.
3. So my code is accurately using the system connection to create the tenant database and migrate the tenant tables BUT it is failing to connect to the tenant database to run the tenant seeds and create the tenant user.  How do I manually connect (invoke a tenant connection) within my PHP code to connect to the tenant database so I can run the seeders and create a user?

Also I am a little puzzled how the exact same code works Locally but not in my Ubuntu environment.  Thoughts?
Thanks in advance
R

**Comment by fletch3555** [comment]
@reneenistler, how did you create the databases on your remote/ubuntu environment?  If you did so as a database backup/restore, then the users wouldn't have been created.  You can run `artisan tenancy:recreate` ([ref](https://github.com/hyn/multi-tenant/blob/5.x/src/Commands/RecreateCommand.php))to recreate the DB users and databases, then re-run your DB restore to populate the tables

**Comment by luceos** [comment]
@reneenistler 

- Creating database users is taken care of by the package. It requires a system database user with grant permission though, see the [requirements](https://laravel-tenancy.com/docs/hyn/5.x/requirements).
- You can directly use a tenant connection by ioc resolving the Connection class: `Hyn\Tenancy\Database\Connection`.
- For seeding you can use the package command `tenancy:db:seed`, run `php artisan help tenancy:db:seed` for its signature.

**Comment by redroses** [comment]
I am trying to also get a tenant connection manually.

$customer = Customer::find(1);
$connection = TenantDomainUtil::setTenantConnection($customer);
dd(Country::code('USA')->first());

InvalidArgumentException
Database [tenant] not configured.

class TenantDomainUtil {
....
public static function setTenantConnection(Customer $customer) {
		$hostname = $customer->hostnames->first();
		if ($hostname) {
			$connection = app(Connection::class);
			$connection->set($hostname->fqdn);
		}
}
.....
}

**Comment by reneenistler** [comment]
Luceos, thanks for the reply.

- The Tenant database and the associated database User Account is correctly created on Ubuntu.  The system connection is performing all tasks accurately.  

Fully automated Logic based on user registration/verification:
1) The user completes a form providing email, name and Stripe payment info. The System Connection creates the registration in the system database correctly.  
2) Upon confirmation of email address, the system connection creates the customer, website, hostname in the system database. It also creates the Tenant database and the db User Account that matches the database name (per your bullet 1 above). Then the tenant tables are migrated. Works perfectly in both environments.
The next step is, using the Tenancy Connection, to automatically 1) seed the tenant tables and 2) create the tenant user in the tenant users table.  This last step is the piece that is not working in Ubuntu.  Seems that the tenancy connection works Locally on Windows 10 but not in Ubuntu.
I did update locally to MYSQL 5.7.21 and the process still works Locally on Windows... so I don't think it is related to MYSQL version.

**Comment by redroses** [comment]
I see from issue Tenant database connection example #241

The easiest way once your Tenant is globally identified:

$connection = app(Hyn\Tenancy\Database\Connection::class);
$tenantConnection = $connection->get();

See Connection::get.

I realize tenant is globally identified from browser 'domain.site.com'.
From domain the tenant is found.

However, when in code, how do I set the correct tenant based on the customer?

**Comment by luceos** [comment]
@redroses please don't spam an issue of another user even when you collaborate. With the complexity at hand this is causing a lot of confusion.

@reneenistler are you and @redroses discussing the same issue aka are you working on the same project? Please stick to one issue and not two. 

#428 also discusses windows and ubuntu.

**Comment by luceos** [comment]
> The next step is, using the Tenancy Connection, to automatically 1) seed the tenant tables and 2) create the tenant user in the tenant users table. This last step is the piece that is not working in Ubuntu. Seems that the tenancy connection works Locally on Windows 10 but not in Ubuntu.
I did update locally to MYSQL 5.7.21 and the process still works Locally on Windows... so I don't think it is related to MYSQL version.

You can easily use the auto migrate and seed ability the package ships with.

As mentioned in #428 you are saying "Seems that the tenancy connection works Locally on Windows 10 but not in Ubuntu." But you don't explain what is "not working", are you getting an error, even when debug is enabled?

**Comment by reneenistler** [comment]
Hello,
Yes I am working with Redroses. We tabled the SAVEPOINT issue discussed on #428 and indicated we would create a new issue for the Tenacy Connection described in this issue.
By not working, I mean that the code to run tenant seeds and create user are not returning any results.  No errors are MySQL or Laravel logs that indicate why the code is not successful.

**//RegisterController - calls postVerification function ... Triggering Error message on Ubuntu** 
public function postVerification(Request $request) {
		$input = $this->sanitizeInput($request);

		$validationRegistration = new Registration();
		$validator = $this->validator($input, $validationRegistration->validatable['verification']);
		$validator->validate();

		$registration = null;

		try {
			// not using transactions. use cleanup on exception
			$registration = Registration::where('email', '=', $input['email'])->first();
			if (!$registration) {
				throw new MML('No registration found for the email address.');
			}
			$registrationService = resolve(RegistrationService::class);
			$customer = $registrationService->setupCustomer($registration, $input);
			$registration->delete();
			$customer->notify(new SubscriberVerifiedNotification($input['subdomain']));
			MessageUtil::displaySuccess("Your email address {$request->input('email')} is verified. Your subscription is now active.", 'Email Verified, Subscription Active');
			return TenantDomainUtil::siteRedirect('login', $input['subdomain']);
		} catch (Exception $e) {
			Log::error($e->getMessage());
			Log::error($e);
			$this->cleanupRegistration($registration);
			MessageUtil::displayError("Your email address {$input['email']} could not be verified. Subscription could not be activated. You have to subscribe again.", 'Email Not Verified, Subscription Not Created');
			return redirect('/');
		}
	}

**//RegistrationService  --> SeedDefaultData and CreateUser functions not working in Ubuntu**
class RegistrationService {

	public function __construct() {
		//
	}

	public function setupCustomer(Registration $registration, array $data) {
		try {
			$customer = $this->createCustomer($registration, $data);
			$this->seedDefaultData();
			$this->createUser($data);
			return $customer;
		} catch (Exception $e) {
			throw $e;
		}
	}

	/**
	 * createCustomer
	 * 1) Creates customer, hostname, website
	 * 2) Creates stripe subscription
	 * These tables are in mymemberlocker database.
	 */
	private function createCustomer(Registration $registration, array $data) {

		$customer = Customer::createCustomer($data);

		if (!$customer) {
			throw new MyMemberLockerException('Customer account could not be created for the email address.');
		}

		// Add stripe subscription to customer
		SubscriptionUtil::createStripeSubscription($customer, $registration);

		if (!$customer->subscribed(config('services.stripe.subscription'))) {
			throw new MyMemberLockerException('Subscription could not be created for the email address.');
		}

		return $customer;
	}

	/**
	 * seedDefaultData
	 * Seeds the newly created database with default data.
	 * These tables are in the new database.
	 */
	private function seedDefaultData() {
		$tenantSeeder = new TenantDatabaseSeeder();
		$tenantSeeder->run();
	}

	/**
	 * createUserAccount
	 * 1) Creates user account
	 * 2) Creates stripe subscription
	 * These tables are in the new database.
	 */
	private function createUser(array $data) {
		User::createSubscriber($data);
		Preference::createDefault();
	}

}

**//Create Customer -- Works in both environments - The System Tables are populated**
public static function createCustomer(array $data): Customer {
		// create a customer
		$customer = new Customer;
		$customer->email = $data['email'];
		$customer->name = $data['business_name'];
		$customer->active = true;

		app(CustomerRepository::class)->create($customer);

		// associate the customer with a website
		$website = new Website;
		$website->customer()->associate($customer);
		app(WebsiteRepository::class)->create($website);

		// associate the website with a hostname
		$hostname = new Hostname;
		$baseUrl = config('app.url_base');
		$hostname->fqdn = "{$data['subdomain']}.{$baseUrl}";
		$hostname->subdomain = "{$data['subdomain']}";
		$hostname->customer()->associate($customer);
		app(HostnameRepository::class)->attach($hostname, $website);
		// make hostname current
		app(Environment::class)->hostname($hostname);

		return $customer;
	}

**Comment by luceos** [comment]
Have you tried logging that it actually hits that code?

**Comment by redroses** [comment]
solved in SAVEPOINT Exception when using transactions on ubuntu #427
not wrapping tenant db code in a transaction.

Thank you all for your help in this.
Sorry it took us so long to figure it out.

**Comment by luceos** [comment]
Glad you figured it out 👍
