### ISSUE TITLE
Multi-Tenant Configuration on Ubuntu 17.10

### ISSUE THREAD

**Issue by redroses** [hyn/multi-tenant#431]
For anyone interested.
I am using the latest hyn/multi-tenant package.
Ubuntu 17.10

The following configuration works to get multi-tenant working for me: DNS, apache config, laravel .env

Replace mydomain.com with your domain.
Assuming main site where clients register is mydomain.com
Each client logs in at clientsubdomain.mydomain.com 

DNS Records
A       mydomain.com
CNAME   www.mydomain.com
CNAME   *.mydomain.com

apache configuration
/etc/apache2/sites-enabled

mydomain.conf
```
<VirtualHost *:80>
    ServerName mydomain.com
    ServerAlias www.mydomain.com
    ServerAdmin support@mydomain.com
    DocumentRoot /var/www/html/mydomain

    <Directory "/var/www/html/mydomain">
        Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
        Options FollowSymLinks
        AllowOverride None
        Require all granted

        RewriteEngine On

        # Remove www
        RewriteCond %{HTTP_HOST} ^www\.
        RewriteRule ^(.*)$ http://mydomain.com/$1 [R=301,L]

        # Redirect Trailing Slashes If Not A Folder...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^(.*)/$ /$1 [L,R=301]

        # Handle Front Controller...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]

        # Handle Authorization Header
        RewriteCond %{HTTP:Authorization} .
        RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    </Directory>
</VirtualHost>
```
tenant.conf
```
<VirtualHost *:80>
    #ServerName mydomain.com
    ServerAlias *.mydomain.com
    ServerAdmin support@mydomain.com
    DocumentRoot /var/www/html/mydomain

    Header set Access-Control-Allow-Origin "*"

    <Directory "/var/www/html/mydomain">
        Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
        Options FollowSymLinks
        AllowOverride None
        Require all granted

        RewriteEngine On

        # Redirect Trailing Slashes If Not A Folder...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^(.*)/$ /$1 [L,R=301]

        # Handle Front Controller...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]

        # Handle Authorization Header
        RewriteCond %{HTTP:Authorization} .
        RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    </Directory>
</VirtualHost>
```
.env file
```
APP_URL_BASE=mydomain.com                     
APP_URL=http://${APP_URL_BASE}
TENANT_APACHE_ENABLED=false
```

**Comment by luceos** [comment]
You could have used mass virtual host configuration to catch all requests to the server and forward them to the app with `UseCanonicalName Off` see https://httpd.apache.org/docs/2.4/vhosts/mass.html

In addition the package already generates apache configurations, are these lacking? If so I'd like to hear how.

**Comment by redroses** [comment]
Thanks. I will take a look at mass virtual host config.

I initially started using the package to generate the configs.
Couple of things.
1. Copied server.blade and vhost.blade into views/webserver/apache
    Did not see a way to get them into views/vendor: ie php artisan vendor:publish view.
    Changed webserver.apache2.view => ''webserver.apache.vhost'
2. Tried changing     
    from webserver.apache2.paths.vhosts-files =>storage_path() . 'app/tenancy/webserver/apache2/'
    to webserver.apache2.paths.vhosts-files => '/etc/apache2/tenants-enabled/'
    still kept writing vhosts files to the app/tenancy/webserver/apache dir
    did a search on 'vhost-files' and never saw where the package was using it.
3. Each of my new subdomains created a new conf file in app/tenancy/webserver/apache2.
    When a new conf file is created an apache restart is required - provided by the package.
    I looked for a way to have the vhosts known in advance. 
    Since the package detects the subdomain and  sets the tenant db correctly from the url, a dynamic vhost would work I thought.
4. So I experimented and came up with the above solution.
   This way no new conf files are required for a new subdomain. No apache restart is required.

I will investigate the link you sent to see if I can use that way instead.
Thanks.

**Comment by redroses** [comment]
From what I can see  mass virtual host configuration is if I want different html directories:
abc.mysite.com --> /var/www/html/abc
xyz.mysite.com --> /var/www/html/def
then using wild cards apache will forward to abc or def index.php (html) accordingly.

This is not my case. Running the same code.
Using the package to set the tenant db, handle file uploads to the correct tenant directory, etc.
The code is the same, db and file storage is unique.
FYI: we are moving our app from one database using tenant_id to this package for storing tenants in multiple dbs.

However, thanks lucios, my tenant.conf is a duplication.
I disabled it and now just have one conf file. 
Solution now is pretty simple. Seems to work. We'll see as we add more tenants how it fares.

mysite.conf
<VirtualHost *:80>
    ServerName mysite.com
    ServerAlias *.mysite.com
    ServerAdmin support@mysite.com
    DocumentRoot /var/www/laravel/mysite

    Header set Access-Control-Allow-Origin "*"

    <Directory "/var/www/laravel/mysite">
        Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
        Options FollowSymLinks
        AllowOverride None
        Require all granted

        RewriteEngine On

        # Remove www
        RewriteCond %{HTTP_HOST} ^www\.
        RewriteRule ^(.*)$ http://mysite.com/$1 [R=301,L]

        # Redirect Trailing Slashes If Not A Folder...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^(.*)/$ /$1 [L,R=301]

        # Handle Front Controller...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]

        # Handle Authorization Header
        RewriteCond %{HTTP:Authorization} .
        RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    </Directory>
</VirtualHost>

**Comment by redroses** [comment]
Thanks luceos and all who replied on this forum. We were struggling to switch from single db to multi db.
For now seems like we can move on building our app.
Thanks again all for your timely responses. It was a great help.

**Comment by luceos** [comment]
No problem, good luck with your app; if there's anything else please let us know!
