### ISSUE TITLE
Feature Request : Blade Helpers

### ISSUE THREAD

**Issue by waiel** [hyn/multi-tenant#435]
**This is more of a feature request than an issue**

Is it possible to have multiple helpers that can identify the tenant or help in identifying the current customer as it helps to build a custom interface for tenants. 

Some quick helper examples:
* identify if the current session is a tenant  
* identify the tenant session host name, subdomain or FQDN  
* identify current tenant customer 

more helpers would be awesome  👍 
Thanks

**Comment by mintunitish** [comment]
@luceos I am going to start working on this. Anything that I should consider before implementing it?

**Comment by fletch3555** [comment]
I'm not sure we need blade helpers for all of this.  This (mostly) sounds like logic that should be in a controller or service class, which can already use `app(CurrentHostname::class)`.  Once you have the hostname, you can get the current Customer or Website (tenant) object through relations.

**Comment by luceos** [comment]
I guess additional helpers would be helpful in some cases; but perhaps we can just add those to the Facade and make that available per default in views?

**Comment by luceos** [comment]
As Laravel is also stepping away from helpers, let's not do this in this package. You can bind any variable into a view anyway.
