### ISSUE TITLE
add sentry for error reporting to docs site

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#437]
And while you're at it, fix

https://laravel-tenancy.com/docs/tenancy/1.x/t/tenant

**Comment by bkintanar** [comment]
that link shows whoops at work.

**Comment by luceos** [comment]
Hence a bug report 👍 😊

**Comment by mintunitish** [comment]
Will like to work on fixing it.

**Comment by luceos** [comment]
@mintunitish although very much appreciated, it would pretty much be impossible as the documentation website is a private repository and not accessible. I'm considering open sourcing it, but that won't be any time soon.

That's also the reason this issue has someone assigned.

**Comment by luceos** [comment]
This was done.
