### ISSUE TITLE
Maintenance mode on hostnames is cached and not released on manual DB edits

### ISSUE THREAD

**Issue by satyago** [hyn/multi-tenant#440]
Maintenance mode activation / deactivation only works by using the Repositories provided with the package as the cache invalidation is otherwise not handled.

If someone edits the database directly, maintenance mode is triggered, but a consecutive change is not picked up. Hence, modifying or removing the timestamp has no effect and maintenance stays active.

Adding an additional check and resetting the cache might influence performance in a bad way so I don't really know what to do other than inserting another DB column or not cache the maintenance timestamp at all.

---

__Actual behavior__

Maintenance timestamp for hostnames is cached

__Expected behavior__

Maintenance mode timestamp ignored from cache

---
__Information__

- hyn/multi-tenant version: 5.1
- laravel version: 5.6

**Comment by Nowi5** [comment]
Yes, this need to be changed indeed. Same issue.

**Comment by luceos** [comment]
@Nowi5 this was fixed with the Hostname Listener, see the commit linked:

https://github.com/hyn/multi-tenant/commit/786b12b4323c4e67c99c2207a6fff453dd5ce766
