### ISSUE TITLE
Password reset table on tenant database

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#443]
It's possible to force the password reset entries to be saved on the tenant connection. In order to do so update the `auth.php` file and add the `connection` key like this:

```php
    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
            'connection' => 'tenant',
        ],
    ],
```

**Comment by luceos** [comment]
Connection is also something we can configure on the session, if using driver database.

**Comment by luceos** [comment]
Moved to docs repo.

**Comment by moisesh18** [comment]
Hi. What if we want to change password of user in system connection?
