### ISSUE TITLE
Add Grant to system database

### ISSUE THREAD

**Issue by redroses** [hyn/multi-tenant#444]
Trying to GRANT REFERENCES ON systemDB.* TO the new user created when creating a new tenant DB.
This allows me to reference a foreign key in another DB.
Cannot figure out where to put this.

I see that MariaDB created() creates the user and database. Then GRANT ALL ON newTenantDB.* TO this new user. I would then like to  GRANT REFERENCES ON systemDB.* TO this new user.

1. Do I override MariaDB? Where?

2. Or Do I listen for Events\Database\Creating from DatabaseGenerator
```
    public function created(Events\Websites\Created $event)
    {
        if (!config('tenancy.db.auto-create-tenant-database', true)) {
            return;
        }

        if ($this->mode !== Connection::DIVISION_MODE_SEPARATE_DATABASE) {
            return;
        }

        $config = $this->connection->generateConfigurationArray($event->website);

        $this->configureHost($config);

        **$this->emitEvent(
            new Events\Database\Creating($config, $event->website)
        );**

        if (!$this->driver($config)->created($event, $config, $this->connection)) {
            throw new GeneratorFailedException("Could not generate database {$config['database']}, one of the statements failed.");
        }

        $this->emitEvent(
            new Events\Database\Created($config, $event->website)
        );
    }
```
3. Or do you suggest something else.

**Comment by luceos** [comment]
If you're interested in increasing the user permissions I'd say listen to Created and run the query in addition..

**Comment by redroses** [comment]
Thanks.
The Created event works.
For anyone else needing to get FKs working across DBs, below is what is working for me.

```
namespace App\Listeners;

use Hyn\Tenancy\Events\Database\Created;
use DB;

class TenantDbCreatedListener {

	public function __construct() {
		//
	}

	public function handle(Created $event) {
		$dbname = DB::connection('system')->getDatabaseName();
		DB::connection('system')->statement("GRANT REFERENCES ON {$dbname}.* TO '{$event->config['username']}'@'{$event->config['host']}'");
	}

}
```

**Comment by fletch3555** [comment]
@redroses, just an FYI, triple-backticks (```) on the lines before and after a code block will autoformat that block.  Right now, only part of your snippets are being formatted since it's relying on the indentation.

**Comment by bkintanar** [comment]
Fixed indentation for everyone.
