### ISSUE TITLE
Can we use this package with same link but multiple databases behind?

### ISSUE THREAD

**Issue by xyrintech** [hyn/multi-tenant#445]
I have a requirement to use same link for the application but different databases for each tenant. 
Will this package solve the purpose for this requirement?

I tried to find out in the documentation but unfortunately I do not see any such option. 

I just want to make sure that I am am understanding this package in a complete manner. So, that's why I am writing this over here. 

If this package solves the purpose of above mentioned requirement then it would be great if you can share the documentation for this. Thanks.

**Comment by luceos** [comment]
Hello @xyrintech can you clarify what a link is? Are you curious whether it is possible to run the application and all tenants on the same hostname?

If so the answer is yes, but you would need to create some logic of your own to switch/identify the tenant. Your use case is exactly the reason why the successor was started, it allows for a more flexible way of tenant selection and configuration.

Please let me know if you have any other questions or this answer does not suffice.

**Comment by xyrintech** [comment]
Hello @luceos Thanks for the clarification. 
This really helps. 

Would it be possible for you to share a approach for the logic thing you mentioned? 

Link is like abc.com and the same link for accessing the tenant data. 

I am making a stateless web app using APIs. I can use headers to share the tenant ID in order to access the tenant. 

I am just wondering to use this package and looking forward hearing from you.

**Comment by luceos** [comment]
Yes, in fact using the header is something I already natively support in the successor. But I recommend using the current stable version. You could for instance create a middleware that does something like this:

```php
<?php

namespace App\Http\Middleware;

use Hyn\Tenancy\Events\Hostnames\Identified;
use Hyn\Tenancy\Models\Website;

class IdentifiesTenant
{
    public function handle($request, Closure $next)
    {
        $website = Website::where('uuid', $request->header('uuid'))->first();

        dispatch(new Identified($website ? $website->hostnames()->first() : null));

        return $next($request);
    }
}
```

Hope this example helps.

It's a bit of a nuisance that the Hostname is now technically seen as a tenant, it's on the roadmap to make the Website the tenant though.

**Comment by xyrintech** [comment]
Got it. 
Lemme try this out :)

**Comment by xyrintech** [comment]
I am using User.php instead of Customer.php

tenancy.php
`'customer' => \App\User::class,`

```
private function registerTenant($name, $email, $password)
    {
        // create a customer
        $customer = new User;
        $customer->name = $name;
        $customer->email = $email;
        $customer->password = bcrypt($password);
        app(CustomerRepository::class)->create($customer);
        // associate the customer with a website
        $website = new Website;
        $website->customer()->associate($customer);
        app(WebsiteRepository::class)->create($website); 
        // associate the website with a hostname
        $hostname = new Hostname;
        $baseUrl = config('app.url_base');
        $hostname->fqdn = "{$name}.{$baseUrl}";
        $hostname->customer()->associate($customer);
        app(HostnameRepository::class)->attach($hostname, $website);
        return $hostname;
    }
```

Getting the following error in WebsiteRepository at 

`$this->validator->save($website);`

It seems that this is not identifying the users table which should come from tenancy.php

**Comment by xyrintech** [comment]
`dispatch(new Identified($website ? $website->hostnames()->first() : null));`

Getting 2 issues
1) Also, I tried middleware thing but this gives 404 error. Only those links work which exists in hostnames table. Like the request do not come upto middleware, it seems that it checks the hostname and then it comes to web.php or api.php file. I need all the request to come to api.php / web.php and then with this middleware we can identify the tenant.
2) error : {"message":"Cannot pass parameter 1 by reference","status_code":500} in above code.

**Comment by luceos** [comment]
WebsiteValidator;

Indeed it seems the website validator does not take into account that a different customer object is being used. I must confess the Customer object and its functionality is a bit old fashioned. I would suggest not replacing the `'customer'` model entry in the config. There's also no actual need to use the CustomerRepository. Just relate the website to the User, it's much easier and gives you a higher level of flexibility.

Dropping the Customer object is in fact also on the roadmap 👍 

1. 404 this in fact is pretty normal if you have [`abort-without-hostname`](https://github.com/hyn/multi-tenant/blob/5.x/assets/configs/tenancy.php#L138) is enabled. If you want a fallback (landing page) check the [documentation on fallbacks](https://laravel-tenancy.com/docs/hyn/5.x/fallback).
2. please provide full backtraces for errors

**Comment by xyrintech** [comment]
Got it.
Well, I tried database approach. 
But this gives an error on creating a tenant: 

QLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `084714c7ad274045b2e494d3225b66e9`@'127.0.0.1' IDENTIFIED BY '593d' at line 1 (SQL: CREATE USER IF NOT EXISTS `084714c7ad274045b2e494d3225b66e9`@'127.0.0.1' IDENTIFIED BY '593d7bd7b9ed837c88f114efa26fba83')

```
<?php
namespace App\Console\Commands;
use App\User;
use Hyn\Tenancy\Contracts\Repositories\CustomerRepository;
use Hyn\Tenancy\Contracts\Repositories\HostnameRepository;
use Hyn\Tenancy\Contracts\Repositories\WebsiteRepository;
use Hyn\Tenancy\Environment;
use Hyn\Tenancy\Models\Customer;
use Hyn\Tenancy\Models\Hostname;
use Hyn\Tenancy\Models\Website;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Hash;
class CreateTenant extends Command
{
    protected $signature = 'tenant:create {name} {email}';
    protected $description = 'Creates a tenant with the provided name and email address e.g. php artisan tenant:create boise boise@example.com';
    public function handle()
    {
        $name = str_random();
        $email = str_random();
        if ($this->tenantExists($name, $email)) {
            $this->error("A tenant with name '{$name}' and/or '{$email}' already exists.");
            return;
        }
        $hostname = $this->registerTenant($name, $email);
        app(Environment::class)->hostname($hostname);
        // we'll create a random secure password for our to-be admin
        $password = str_random();
        $this->addAdmin($name, $email, $password);
        $this->info("Tenant '{$name}' is created and is now accessible at {$hostname->fqdn}");
        $this->info("Admin {$email} can log in using password {$password}");
    }
    private function tenantExists($name, $email)
    {
        return Customer::where('name', $name)->orWhere('email', $email)->exists();
    }
    private function registerTenant($name, $email)
    {
        // create a customer
        $customer = new Customer;
        $customer->name = $name;
        $customer->email = $email;
        app(CustomerRepository::class)->create($customer);
        // associate the customer with a website
        $website = new Website;
        $website->customer()->associate($customer);
        app(WebsiteRepository::class)->create($website);
        // associate the website with a hostname
        $hostname = new Hostname;
        $baseUrl = config('app.url_base');
        $hostname->fqdn = "{$name}.{$baseUrl}";
        $hostname->customer()->associate($customer);
        app(HostnameRepository::class)->attach($hostname, $website);
        return $hostname;
    }
    private function addAdmin($name, $email, $password)
    {
        $admin = User::create(['name' => $name, 'email' => $email, 'password' => Hash::make($password)]);
        return $admin;
    }
}
```

**Comment by luceos** [comment]
@xyrintech I'd love to help you out, but every time you post (yet another) issue you fail to post a backtrace. Further questions about issues you have need to have a backtrace. My time is as precious as yours. If you need more in depth support feel free to ask for help from experienced developers on our discord.
