### ISSUE TITLE
Get current Tenant

### ISSUE THREAD

**Issue by aBuder** [hyn/multi-tenant#446]
How I get the current tenant in Laravel 5.6 Controller.

**Comment by fletch3555** [comment]
`app(CurrentHostname::class)` will get you the currently identified `Hostname` (with the correct config settings at least.  If you need the current `Website`(the "Tenant"), then you can just use `app(CurrentHostname::class)->website` if you need the Website

**Comment by luceos** [comment]
Or alternatively use:

```php
\Hyn\Tenancy\Facades\TenancyFacade::website();
```
*or*
```php
app(\Hyn\Tenancy\Environment::class)->website();
```

**Comment by Nowi5** [comment]
Why do we have something easy like that in a kind of FAQ within documentation?

**Comment by luceos** [comment]
@Nowi5 because we're only human. Feel free to suggest so or create a PR.

**Comment by luceos** [comment]
@bkintanar please move, 😍

**Comment by Nowi5** [comment]
See https://github.com/tenancy/docs/pull/49
