### ISSUE TITLE
Multiple hostnames on a tenant

### ISSUE THREAD

**Issue by hawkfx** [hyn/multi-tenant#449]
Hi.

I made an app using this package, all works amazing.

But I've something I want to achieve, I can do it right now but requieres manually work.

I give my customers a subdomain like:

username.appdomain.com

I want to give them the possibility to add a CNAME to their subdomain.

I can add a hostname using:

$hostname = new Hostname;
$baseUrl = config('app.url_base');
$hostname->fqdn = "{$name}.{$baseUrl}";
$hostname->customer()->associate($customer);
app(HostnameRepository::class)->attach($hostname, $website);

So I can add X number of hostnames to a tenant, but the nginx configuration only writes the last name:

    server {

    listen 80;

    # server hostnames
    server_name last_host_name;

It can be possible when I add a new hostname to do something like:

server_name first_fqdm second_fqdm third_fqdm;

Right now I'm modifying this manually but all works perfectly with the identification.

**Comment by luceos** [comment]
It should generate a server block for each hostname, see https://github.com/hyn/multi-tenant/blob/5.x/assets/generators/webserver/nginx/vhost.blade.php

Can you verify that only one has been generated?

**Comment by hawkfx** [comment]
You are right, please close this issue.

I had the issue, uninstalled and installed again and worked.

**Comment by hawkfx** [comment]
I've one more question

I see in server.blade.php

´´´php
@if(isset($ssl))
    listen {{ array_get($config, 'ports.https', 443) }} ssl;
    ssl_certificate_key {{ $ssl->pathKey }};
    ssl_certificate {{ $ssl->pathPem }};
    @endif
´´´

How I can pass the $ssl variable to make the .conf?

**Comment by luceos** [comment]
It should be removed. It's better to rely on a native let's encrypt binary in your server.

**Comment by hawkfx** [comment]
The thing, is that for example

I installed a wildcard ssl certificate for my domain, so any subdomain get it too.

Now when a client put the CNAME i've to install the SSL on my server too so their CNAME gets the SSL, it can be easier to specified there, or no?

**Comment by luceos** [comment]
@hawkfx once the domain is added in the vhost and it resolves, you can let let's encrypt automation handle the certificates as well. Much easier than this package taking on such huge responsibility..
