### ISSUE TITLE
How to force "media" folder creation on tenant

### ISSUE THREAD

**Issue by hawkfx** [hyn/multi-tenant#450]
__Description__

Hi.

Right now I'm doing this to create a Tenant:

```php
$customer = new Customer;
        $customer->name = $name;
        $customer->email = $email;
        app(CustomerRepository::class)->create($customer);

        // associate the customer with a website
        $website = new Website;
        $website->customer()->associate($customer);
        app(WebsiteRepository::class)->create($website);

        // create media dir
        $tenancy = app('tenancy.disk');
        $tenancy->makeDirectory('media');

        // associate the website with a hostname
        $hostname = new Hostname;
        $baseUrl = config('app.url_base');
        $hostname->fqdn = "{$name}.{$baseUrl}";
        $hostname->customer()->associate($customer);
        app(HostnameRepository::class)->attach($hostname, $website);
```
---

__Actual behavior__

The problem is that this piece of code:

```php
$tenancy = app('tenancy.disk');
$tenancy->makeDirectory('media');
```

Don't get created, what I want to achieve is that make the dir, so the nginx file includes 

location ~* ^/media/(.+)$ {
        alias {{ $media }}/$1;
    }

---
__Information__

- hyn/multi-tenant version: 5.1.11
- laravel version: 5.6 
- database driver and version: mysql
- webserver software and version: nginx
- php version: 7.2

---

**Comment by luceos** [comment]
> Don't get created, what I want to achieve

What's the return value of that call? Any errors in your logs? What are the file permissions like?

**Comment by luceos** [comment]
No response, stale.
