### ISSUE TITLE
Logout not clear session and user already logged in

### ISSUE THREAD

**Issue by aBuder** [hyn/multi-tenant#453]
After call the route logout the session would not cleared in cookie and the user already loggedin.
Should I have to call an other route?

Laravel: 5.6
hyn\multi-tenant: ^5.1

`{{ route('logout') }}`

![bildschirmfoto 2018-05-12 um 17 19 05](https://user-images.githubusercontent.com/1265139/39958839-9e2cec64-5608-11e8-8aca-3977ebe8e4aa.png)

**Comment by luceos** [comment]
What's your session driver?

Slightly more information can go a long way 😇

**Comment by aBuder** [comment]
@luceos 

I use the file driver

> 'driver' => env('SESSION_DRIVER', 'file'),

**Comment by aBuder** [comment]
I solved the problem. It was my mistake.

**Comment by luceos** [comment]
Please explain the solution for others having the same issue
