### ISSUE TITLE
How to override global configuration files based on tenant?

### ISSUE THREAD

**Issue by jrichmo93** [hyn/multi-tenant#454]
I would like to set config files based upon which tenant is connected. How can I do this?

**Comment by jrichmo93** [comment]
Documentation was a little confusing, but it seems I need to create a config directory within the tenant directory in storage/app/tenancy/tenants/uuid.

**Comment by luceos** [comment]
@jrichmo93 can you explain how we can improve the documentation or what you found confusing?
