### ISSUE TITLE
Doctrine support

### ISSUE THREAD

**Issue by kennaar** [hyn/multi-tenant#457]
I found an issue about a year old about the package being targeted at eloquent. Has this changed in the meantime? 
If not, would it be trivial to adapt the package, override a few classes in order to fully support the official laravel-doctrine package? I haven't researched in great detail yet but it seems to me that the most difficult part would be adapting the migration commands.

Thanks in advance.

**Comment by luceos** [comment]
@knnnrd hello and thanks for your interest in this package. 

This package is targeted at Laravel, the primary reason for this is that multi tenancy is a very complex concept if you want to integrate it into any framework without impacting its core functionality. I've been able to integrate with Laravel by adding only onto it; extending and reconfiguring.

If you are asking whether this package would consider supporting different frameworks - like Symfony - the answer will be no. If you are wondering whether I'd consider supporting Doctrine when used inside Laravel, then yes, but we won't be creating that logic.

If you want to use doctrine inside Laravel the best way to work with this package is most likely to create a separate package adding the Doctrine support. I would gladly modify this package to offer the flexibility needed to do so.

I think allowing a PR against this package with Doctrine support does not make much sense as I have no (recent) experience with Doctrine, which would make supporting that feature pretty hard.

**Comment by luceos** [comment]
As to implementation (sorry i totally went by that question):

- models (hostname, website, customer)
- repositories (hostname, website, customer)
- database generators
- every migrate related command
- recreate command

from the top of my head 👍

**Comment by kennaar** [comment]
@luceos My question was indeed about supporting Doctrine while using Laravel. Multi framework support would be difficult, if not impossible IMO. So currently your preference would be a separate package that extends classes from this one to support Doctrine _instead_ of Eloquent?

**Comment by luceos** [comment]
> So currently your preference would be a separate package that extends classes from this one to support Doctrine instead of Eloquent?

Yes. 

In theory every item I've listed earlier is interchangeable. If, however, you encounter any issue or see ways to improve the package, I'd be more than willing to work on a solution.

**Comment by luceos** [comment]
Closing this as there's no action needed from our side. Feel free to open/respond with any requests @knnnrd
