### ISSUE TITLE
Remote database, multiple web servers, HAProxy?

### ISSUE THREAD

**Issue by jordanbardsley7** [hyn/multi-tenant#458]
Will this package work if I have an application sitting on multiple web servers behind HAProxy with a database on AWS? Thanks!

**Comment by luceos** [comment]
Yes, but you'll need to write a custom database driver for AWS. 

Full (per default) cloud support is something I aim for in the successor https://github.com/tenancy/tenancy; but that one is still under heavy development.

**Comment by jordanbardsley7** [comment]
Sweet! I'll definitely look into that.

I took a quick look at the MariaDB driver. For example, say I have 3 web servers and they're multi-tenant. When creating a new tenant and creating a new database user for that tenant, how can I whitelist ip's for all 3 web servers? From what I quickly looked at it uses the database ip/host that's defined in the configuration. This is for a remote database.

https://github.com/hyn/multi-tenant/blob/5.x/src/Generators/Webserver/Database/Drivers/MariaDB.php#L38

**Comment by luceos** [comment]
Best way is probably to either:

- create one user for each web server `<uuid>-web01@<some.ip>`
- create one user that allows any server, which is closer to what is is now, except for allowing all hosts `%`

**Comment by jordanbardsley7** [comment]
Hmm, yeah I was thinking about allowing connections from all hosts to the database then whitelisting IP's using an AWS security group or something. Is there a way to set that wildcard through the code, like in the configuration or something? If not, i'd be happy to create a PR proposing a way to create multiple users with specified IP's.

**Comment by luceos** [comment]
No need to PR, just listen to the `Hyn\Tenancy\Events\Database\ConfigurationLoaded` event and modify the `$configuration` array (it's an entry from `database.connections`).

**Comment by jordanbardsley7** [comment]
Sweet!
