### ISSUE TITLE
Error when leaving server actions empty or set to NULL

### ISSUE THREAD

**Issue by TheTechnoMan** [hyn/multi-tenant#460]
__Description__

When you set the values of the webserver actions to either NULL or an empty string you get either of this 2 exceptions:

**NULL:** 
```
Type error: Argument 1 passed to Symfony\Component\Process\Process::prepareWindowsCommandLine() must be of the type string, null given
And if it is empty you get a command error
In Process.php line 222:
```

**Empty string:**

 The command "" failed.

  Exit Code: 1(General error)

  Working directory: B:\laragon\www\Laravel\XX

  Output: ================

  Error Output: ================

---
__Information__

- hyn/multi-tenant version: 5.1.12
- laravel version: 5.6.22
- database driver and version:
- webserver software and version:
- php version: 7.1.11

---

**Comment by luceos** [comment]
We need to check the config value and if `true`, `false` or `null` return that exact value instead in the Generators.
