### ISSUE TITLE
Foreigne key error for PREFIX mode

### ISSUE THREAD

**Issue by xyrintech** [hyn/multi-tenant#464]
ant version: 
- laravel version: 5.x
- database driver and version: mysql
- php version: 7.2

Seems that there is an issue with foreigne keys when we use prefix mode. Ex:

`SQLSTATE[HY000]: General error: 1005 Can't create table 'tenancy.#sql-4a31_351' (errno: 121) (SQL: alter table `2_invoice_emails` add constraint `invoice_emails_invoice_id_foreign` foreign key (`invoice_id`) references `2_invoices` (`id`))`

**Comment by luceos** [comment]
I guess it's time to formally drop support for the prefix method @bkintanar, @fletch3555, what do you think?

**Comment by fletch3555** [comment]
Either drop or put significant effort into fixing.  I'm not personally invested in either, though I could see the benefit it may provide for those that choose to use it.  I think best practice should be to separate your tenant data, but that doesn't always work for everyone.

Likely going to come down to executive decision unless someone else provides a solid argument one way or the other.

**Comment by bkintanar** [comment]
hmm.. if we want to cover a larger user base, then I say support it. If we want to cater for those who would deploy this in a more scalable setup, which I think should support separation of tenant data, then drop it.

**Comment by luceos** [comment]
Thank you both @fletch3555 @bkintanar , I might have jumped to a conclusion too soon. Looking at this issue more closely I noticed the migration mentioned is not one shipped with the package:

```
SQLSTATE[HY000]: General error: 1005 Can't create table 'tenancy.#sql-4a31_351' (errno: 121) (SQL: alter table2_invoice_emailsadd constraintinvoice_emails_invoice_id_foreignforeign key (invoice_id) references2_invoices(id))
```

This error states that `invoice_emails.invoice_id` cannot have a foreign key constraint. I guess this foreign key constraint is going to `invoices.id`? This is most commonly caused when you don't make the `invoice_id` column `unsigned`, which is a necessity when creating a constraint on an Auto Increment column.

**This is not an issue with this package!**

To solve you will need to update your migration to make the column unsigned, like I [did in the migrations too](https://github.com/hyn/multi-tenant/blob/5.x/assets/migrations/2017_01_01_000005_tenancy_hostnames.php#L32-L33).

Hope that helps @xyrintech

**Comment by xyrintech** [comment]
Actually the problems occurs with prefix mode. 
Reason being, the foreign key names are considered same as default in laravel.
It works on separate tenant data. 

I am using unsigned for foreign keys.

**Comment by luceos** [comment]
@xyrintech can you post both the migration files?

**Comment by xyrintech** [comment]
Mode: prefix
The first tenant works completely fine, the issue occurs when we need to create more than one tenants in same database (prefix mode)

Error:

```
SQLSTATE[HY000]: General error: 1005 Can't create table 'tenancy.#sql-a27_e7' (errno: 121) (SQL: alter table `2_permissions` add constraint `permissions_inherit_id_foreign` foreign key (`inherit_id`) references `2_permissions` (`id`))

  at /home/ubuntu/workspace/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table 'tenancy.#sql-a27_e7' (errno: 121)")
      /home/ubuntu/workspace/laravel/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:143

  2   PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table 'tenancy.#sql-a27_e7' (errno: 121)")
      /home/ubuntu/workspace/laravel/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:141

  Please use the argument -v to see more details.
```

```
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePermissionsTable extends Migration
{

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('permissions', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('inherit_id')->unsigned()->nullable()->index();
            $table->string('name')->index();
            $table->string('slug')->index();
            $table->text('description')->nullable();
            $table->timestamps();
        });
        
        Schema::table('permissions', function (Blueprint $table) {
            $table->foreign('inherit_id')->references('id')->on('permissions');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('permissions');
    }

}

```

**Comment by luceos** [comment]
So the issue is caused because the foreign key constraint name is the same.

You can pass a custom name as second argument in `foreign()`:

```php

    /**
     * Specify a foreign key for the table.
     *
     * @param  string|array  $columns
     * @param  string  $name
     * @return \Illuminate\Support\Fluent
     */
    public function foreign($columns, $name = null)
    {
        return $this->indexCommand('foreign', $columns, $name);
    }
```

**Comment by xyrintech** [comment]
Got it. That's what I thought.

**Comment by luceos** [comment]
@xyrintech to be blunt, I'd prefer you do your research first and then ask for (priority) support on the issue tracker. Thanks for taking that into consideration.
