### ISSUE TITLE
Who i get related models of all customers?

### ISSUE THREAD

**Issue by jobcerto** [hyn/multi-tenant#465]
I have an admin dashboard (admin.domain.test), and everthing works fine. I can get all customers, access all models of the system connection...

It's there an way of accessing of one tenant (customerX.domain.test) inside another tenant (customerY.domain.test)?

I try identifying the current hostname, but the currentHostname is the actual domain hehe (customerX.domain.test). 

UPDATE: I'm using the multi-database, not the prefix type!

**Comment by luceos** [comment]
Do you want to access multiple tenant connections from your admin dashboard or do you want to access another tenant database from within a tenant?

The whole point of this package is not allowing inter-tenant connections 🤷‍♂️ ; it is possible though.. 

Either way you can create a helper class that sets a `database.connections` entry with a custom name and fill the array on runtime with the array given by the `Connection::generateConfigurationArray()` method. You can resolve the Connection class through IoC.

**Comment by jobcerto** [comment]
Hi, my english is sucks, but i want to access all tentants from the admin dashboard, but my admin is saved in the hostnames table.

**Comment by luceos** [comment]
@jobcerto and what is blocking you from querying the Hostname model, see https://laravel-tenancy.com/docs/hyn/5.x/repositories#querying ?

**Comment by jobcerto** [comment]
I have tried all ways i can think about hehe! 
To make simples: Is there an example of how to get users or other data from all tenants in an admin dashboard?
```php
Customer::with('randomTenantTableWithCustomerId')->get();
```

again, thanks for the paciency!

**Comment by luceos** [comment]
You really can't query all tenant databases at once. Suggestions proposed before is some cron that creates intermediate (system) tables, looping over all tenant databases or using redis or other kind of cache to store and load the necessary tables.

**Comment by jobcerto** [comment]
THANKS! I totally forget about cron and redis! Mirroring statistical data and basic informations should already solve my life!

Thanks for the help!

I i'm closing this o/
