### ISSUE TITLE
Issues with PHPUnit tests

### ISSUE THREAD

**Issue by TheTechnoMan** [hyn/multi-tenant#466]
__Description__

Hello,

as already explained in the chat, I am trying to run PHPUnit tests with a fixed mysql connection.

---

__Actual behavior__

1) Exception is being thrown. See tracktrace: https://pastebin.com/raw/ry5uZeFB
2) System database is being wiped

__Expected behavior__

The tests use the specified database connection that acts as the tenant database. The `RefreshDatabase` trait should wipe this test database, not the system database. All models have the `UsesTenantConnection `trait on them.

---
__Information__

- hyn/multi-tenant version: 5.1.12
- laravel version: 5.6.22
- php version: 7.1.11

---

__tenancy.php config__

Default config.

__PHPUnit config__

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="vendor/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>

        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="DB_CONNECTION" value="mysql_testing"/>
        <env name="TENANCY_AUTO_HOSTNAME_IDENTIFICATION" value="false"/>
    </php>
</phpunit>

```

**Comment by luceos** [comment]
`mysql_testing` is your `system` connection during tests?

**Comment by TheTechnoMan** [comment]
Not quite sure if I understand you correctly, but at this time the system connection is not being changed during tests, currently it uses the one that is being used when not running a test. If I missunderstood something, please let me know.

`mysql_testing` should be the equivalent to a tenant database. Maybe it works better if we do it the other way around: What should be done to have a fixed testing database act like a tenant? Meaning that all tenant models use that fixed database connection and get/post requests (created by phpunit) also use the data from that same database connection (which in my case is called mysql_testing).

Thanks

**Comment by luceos** [comment]
So the trace is about not being able to connect with user tenant locally without password. I'm not sure how to solve this without seeing actual code of the tests in use.

**Comment by TheTechnoMan** [comment]
Yes, the main question seems to be: Why is it changing to such a connection (that does not exist). The same issue can be found here: https://github.com/hyn/multi-tenant/issues/462#issuecomment-391044056 - so it does not appear to be specific to phpunit.

**Comment by luceos** [comment]
So the tenant connection clones the system connection data and then overrides database and username keys of the array. However your code seems to force it to `tenant`, any results when grepping through your code?

**Comment by TheTechnoMan** [comment]
The stacktrace from the above comment does not show much, beside

```
#18 B:\\laragon\\www\\Laravel\\Main\\app\\Repositories\\DbConfigRepository.php(25): Illuminate\\Database\\Eloquent\\Model::__callStatic('get', Array)
#19 B:\\laragon\\www\\Laravel\\Main\\app\\Providers\\AppServiceProvider.php(23): App\\Repositories\\DbConfigRepository->get()
#20 [internal function]: App\\Providers\\AppServiceProvider->boot()
```

There is a `App\Interfaces\ConfigRepositoryInterface` that is bound to `App\Repositories\DbConfigRepository` like

```
 $this->app->bind(
            \App\Interfaces\ConfigRepositoryInterface::class,
            \App\Repositories\DbConfigRepository::class
        );
```

and the `get()` method of this repository just does:

```
  public function get()
    {
        try {
            $config = Config::get()->pluck('value', 'config');
            return $config;
        } catch (QueryException $e) {
            # Looks like that the table
            # does not exist yet
            return null;
        }
    }
```

The `Config` model has the `UsesTenantConnection` trait on it. Not sure if it actually has something todo with above method, I just don't see anything else sticking out in the stacktrace. :(

Not sure what you mean with "grepping through your code"

**Comment by luceos** [comment]
So your boot method tries to set/load a table from the tenant even when no tenant was identified. Which is always the case in CLI and thus also in tests. And as you're only catching the QueryException, not the PDOException (I believe it's that one) your code halts.

**Comment by TheTechnoMan** [comment]
So, for the tests, how should the process actually look like? Set up a tenant in the `setUp()` method in the test and switch to that one?

Besides that, there are 2 points that are still unclear to me:
1) Why does it reset/wipe the **system** database?
2) Regarding the vhost creation: Why does the creation of the apache vhost work, but nginx throws the exception?

**Comment by luceos** [comment]
Setting up your tests like that makes sense. Feel free to look at the tests that the package uses.

1. No clue yet.
2. No idea yet, let's fix one issue at a time, they might be related.

**Comment by luceos** [comment]
No reply.
