### ISSUE TITLE
PgSQL driver attempts to resolve tenant connection even if unneeded

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#467]
https://github.com/hyn/multi-tenant/blob/5.x/src/Generators/Webserver/Database/Drivers/PostgreSQL.php#L88

We should either do a check whether the connection is up, if possible. Or do a try catch block around that line only.

trace: https://pastebin.com/WQSUbhbW

**Comment by rlsteelman** [comment]
Subscribing.

~214Coder
