### ISSUE TITLE
add forward compatibility for laravel 5.2 and up

### ISSUE THREAD

**Issue by Luceos** [hyn/multi-tenant#47]

**Comment by joelcuevas** [comment]
How far is this in the roadmap? 

BTW, you have a great package!

**Comment by Luceos** [comment]
Hello @joelcuevas. Thank you, I hope it's useful to you as well. Related to this issue, I have little time these past few months, so it has not been prioritized.

**Comment by bkintanar** [comment]
@Luceos I know you're busy with https://github.com/flarum/flarum and other projects. But when do you think this would be ready for 5.2+? Or maybe you could point us which files do you think needs change in the https://github.com/hyn/framework.

Thanks!

**Comment by Luceos** [comment]
Hello @bkintanar actually I stepped down as Flarum community manager for now due to a switch in job (and location). That's what's consuming my time right now. What I would do is change the version constraint in hyn/framework to match 5.2 and install tenancy on a created project. Then it's up to the tests to point to the issues ; `vendor/bin/phpunit` should help you with that.

If you are willing to start with this I would be more than inclined to help you out where I can. And my apologies to everyone waiting for this, everything is upside down at this moment 😁

**Comment by bkintanar** [comment]
Hi @Luceos thank you for your reply and I'm sorry to hear that you're busy than usual. I haven't done anything except modified composer.json and required laravel/framework ~5.2.0. then required laravel/laravel ~5.2.0 in the terminal as what is shown below. I then ran phpunit. So what's next? Do I need to test hyn/webserver as well? But the travis returned build failure on the last build.

This is my result:
<img width="1037" alt="screen shot 2016-06-07 at 3 04 31 pm" src="https://cloud.githubusercontent.com/assets/685928/15848900/18d8c932-2cc2-11e6-90e1-50f74a1b706b.png">

**Comment by Luceos** [comment]
You should probably set up a proper environment where you also include hyn/multi-tenant as a checkout/clone. You can do this by setting up Laravel, then configure your composer.json to have a "repositories - path" key linking to those clones and then require the package. It might be difficult to get this running, but it's certainly possible. I should probably make the package more monolythic.

**Comment by bkintanar** [comment]
I've added to PRs for this. Please review.

**Comment by luceos** [comment]
Thank you @bkintanar for doing most of the research! This is D O N E ! Newsletter coming in.

**Comment by bkintanar** [comment]
Not a problem @Luceos. Glad to be of help.
