### ISSUE TITLE
Database password

### ISSUE THREAD

**Issue by engineerpros** [hyn/multi-tenant#470]
I have created the website and hostname with my own users. Also, I have created the unique ID as per my preferences, that means I am using my own logic for uuid. 

Not sure whether its a bug or an something I am missing, I am trying to connect to the database but it always gives me a password error. 

Ex. 
`9nvAm2y1MuvNrJbp` - this is the UUID of a record in website. I have manually created the mysql username - [9nvAm2y1MuvNrJbp](url) with same password as username - `9nvAm2y1MuvNrJbp`
But this package seems to be using some other, in this case mentioned its using - `960118aea56599f9ac2dc5775a7fa3ba`

Not sure where this password is coming from. Would it be possible to advise the reason for this. 

My logic to create the website and hostname, I am using users table rather than customers table. 

       
```
private function registerTenant($name)
    {
        // Create website
        $website = new Website;
        $website->user_id = $this->user->id;
        $website->uuid = str_random();
        $website->save();
        
        // Associate the website with a hostname
        $hostname = new Hostname;
        $baseUrl = config('app.url_base');
        $hostname->fqdn = "{$name}.{$baseUrl}";
        $hostname->website_id = $website->id;
        $hostname->user_id = $this->user->id;
        $hostname->save();
        
        // Final host
        return $hostname;
    }
```

**Comment by luceos** [comment]
The password is a combination of the website UUID and the App Key, as the app key is randomly generated per instance it's one of the safest ways to create randomized credentials.

Hope this helps. You are still able to override this logic by listening to the related ConfigurationLoading/Loaded events.

**Comment by engineerpros** [comment]
Thanks, this really helps. Great work (Y)

BTW, I am exploring your package. Is there anyway we can avoid tuning this package build in migrations? 

I have reviewed the tenancy.php and docs on your website. I realised that we can setup the tenant migrations folder but nothing for existing migrations. 

Also, do you feel that using User.php instead of Customer.php (\Hyn\Tenancy\Models\Customer::class) will have any impact on the website considering that I am working on stateless web application which will be accessed through API.

**Comment by luceos** [comment]
- avoid tuning the built-in migrations; sure add your own additive migrations
- existing migrations for the system connection can go in the default database/migrations folder
- I'd recommend using User::class, the Customer::class is losing importance with each release as well.

**Comment by xyrintech** [comment]
Noted, thanks.

**Comment by engineerpros** [comment]
That's really very helpful information, thanks @luceos
