### ISSUE TITLE
InvalidArgumentException thrown when using Custom Disk (Dropbox)

### ISSUE THREAD

**Issue by bkintanar** [hyn/multi-tenant#471]
I've installed https://github.com/benjamincrozat/laravel-dropbox-driver to use as my Storage solution. I managed to set it up correctly I did the following to test it.

Setup dropbox as default filesystem.
```
'default' => env('FILESYSTEM_DRIVER', 'dropbox'),
```
Added dropbox in filesystem.disks
```
'dropbox' => [
    'driver' => 'dropbox',
    'token' => env('DROPBOX_TOKEN'),
],
```

Updated tenancy.disk
```
'disk' => 'dropbox',
```

```
$ php artisan tenancy:tinker --website_id=1 // to use tinker with website_id:1
Running Tinker on website_id: 1

>>> $directory = app(Hyn\Tenancy\Website\Directory::class);
=> Hyn\Tenancy\Website\Directory {#2581}

>>> $directory->setWebsite(Hyn\Tenancy\Models\Website::find(1));
=> Hyn\Tenancy\Website\Directory {#2581}

>>> $file = file_get_contents(storage_path('login-logo.png'));
... prints out the file in binary. 0.o

>>> $directory->put('/media/login-logo.png', $file);
=> true
```

I checked dropbox and saw the file

<img width="617" alt="media_-_dropbox" src="https://user-images.githubusercontent.com/685928/40609240-a1721eb8-62a0-11e8-896d-e3856074f6a5.png">

The site breaks. Doesn't get pass `Hyn\Tenancy\Listeners\Filesystem\ActivatesDisk resolve` 

```
Throws InvalidArgumentException
Driver [dropbox] is not supported.
```

<img width="1456" alt="whoops__there_was_an_error_" src="https://user-images.githubusercontent.com/685928/40609608-c2947964-62a1-11e8-821e-1a84dc53bca1.png">

**Comment by luceos** [comment]
I'm not really sure how to move forward with this:

- any solution will be NBC
- the Directory class should be removed because it's a hack
- any non-local disks might break inclusion of files, eg the vendor/config functionality

**Comment by luceos** [comment]
Please retest on current version and reopen if still valid.
