### ISSUE TITLE
artisan route:list problem

### ISSUE THREAD

**Issue by martin55** [hyn/multi-tenant#472]
Hi, I would like to ask if it's somehow possible to get working **artisan route:list** for specific tenant. Now when run getting error:

> InvalidArgumentException  : Database [tenant] not configured.
>   at /project/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:140
>     136|         // If the configuration doesn't exist, we'll throw an exception and bail.
>     137|         $connections = $this->app['config']['database.connections'];
>     138|
>     139|         if (is_null($config = Arr::get($connections, $name))) {
>     140|             throw new InvalidArgumentException("Database [{$name}] not configured.");
>     141|         }
>     142|
>     143|         return $config;
>     144|     }
>   Exception trace:
>   1   Illuminate\Database\DatabaseManager::configuration("tenant")
>       /project/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:103
>   2   Illuminate\Database\DatabaseManager::makeConnection("tenant")
>       /project/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:74

__Information__

- hyn/multi-tenant version: 5.1.13
- laravel version: 5.6
- database driver and version: mysql 5.7
- webserver software and version: nginx
- php version: 7.1

**Comment by luceos** [comment]
What exact version of hyn/multi-tenant are you using? Check the `composer.lock` file please.

**Comment by martin55** [comment]
5.1.13 , updated also above

**Comment by bkintanar** [comment]
@martin55 mine works just fine. do you have a route that uses closures?

**Comment by martin55** [comment]
No I don't,  only group closures.  Thanks I will test on the fresh install and come back. Maybe I forget something during laravel upgrade.

**Comment by martin55** [comment]
Fixed the problem though I still don't know exactly why it was throwing that error. I had one wrong class initialization in contructor of controller ( class contructor was containing query for assignment of initial values). 

Thanks for fast responses I think you can close this.
