### ISSUE TITLE
Non-php files parsed by the LoadsConfig directory listener

### ISSUE THREAD

**Issue by athiffau** [hyn/multi-tenant#477]
I ran into a small problem during development where non-php files were being parsed by the LoadsConfig listener.

__background__

During development I tend to keep non-code files such as readme files, implementation backup files (.php.bak) and todo list. With the current implementation, if these files contain actual php code the content is actually interpreted even though the file extension is not .php.   

__Actual behavior__

Create a file called access.php.bak in a tenant's config folder with the following content:

```
<?php
$error = 1/0;
```

Now watch the application fail.

__Expected behavior__

The file access.php.bak should be ignored because of its extension.

__Modification__

I added one line of code :  

```
LoadConfigs->readConfigurationFiles(...)
{
   foreach (...) {
       if ( pathinfo($file, PATHINFO_EXTENSION) !== 'php') continue;
       ...
```

__Information__

- hyn/multi-tenant version: 5.1.11
- laravel version: 5.6
- database driver and version:
- webserver software and version: nginx 1.11.9
- php version: 7.1

**Comment by fletch3555** [comment]
I think this could be made much more dynamic.  If we modify the `files()` method in [Directory.php](https://github.com/hyn/multi-tenant/blob/5.x/src/Website/Directory.php), we can provide a search term to return only files matching that term (i.e. `*.php`).  That will limit the files being returned, and therefore make that foreach in `LoadConfigs` more efficient.

**Comment by athiffau** [comment]
I agree with @fletch3555 that the 'fix' I showed is not adequate for production. This is why I didn't make a PR with this change.  I just wanted to show a way to replicate the issue and show where the fix should happen to help avoid someone else having to spend the time I did to find this out.

**Comment by luceos** [comment]
Nice. Moving these unused config files to another folder would be a solution too. But I agree, let's update the listener to only use php files.
