### ISSUE TITLE
Google Chrome forces HTTPS

### ISSUE THREAD

**Issue by eumanito** [hyn/multi-tenant#479]
Why google chrome is forcing open with https:// schema?
The force_https param is false on my database.
Using in Firefox is alright.

I did clear the cache, no changes.

__Information__

- hyn/multi-tenant version: 5.x
- laravel version: 5.6
- database driver and version: MySQL 5.7.19
- webserver software and version: apache 2.4.27
- php version: 7.1.9
- Google Chrome version: 66.0.3359.181 64bits

**Comment by fletch3555** [comment]
Can you clarify what you mean by "forcing open with https://"? Are you seeing redirects in the browser dev tools' networking tab? or is Chrome just complaining that it's not http?

If you see redirects, it should tell you what triggered it.  If not, then it's not laravel doing it

**Comment by luceos** [comment]
What domain are you using? I guess the dev pre-configured with valet?

**Comment by eumanito** [comment]
@fletch3555 I'am not seeing redirects in the browser dev tools' networking tab. Chrome is "forcing".

My .env
APP_URL_BASE=nuvo.dev
APP_URL=http://${APP_URL_BASE}

@luceos the domain is nuvo.dev in localhost (windows 10, apache 5.7.19 with virtual host)

**Comment by fletch3555** [comment]
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by eumanito** [comment]
Thanks @fletch3555, it's working!
