### ISSUE TITLE
Change template of Password reset

### ISSUE THREAD

**Issue by aBuder** [hyn/multi-tenant#481]
How I can change the Email template for password reset. At the moment the would be displayed not the url of the tenant. As link it should be displayed https://tenant.easyInvent.net/resets/...

![bildschirmfoto 2018-06-03 um 07 59 00](https://user-images.githubusercontent.com/1265139/40883735-581847b6-6704-11e8-9e55-5928c64fb149.png)

**Comment by luceos** [comment]
Change the config setting app.url during runtime before sending the password reset mail.

```
config(["app" =>... ]);
```

Sorry on mobile

**Comment by aBuder** [comment]
But how I can set there the url of tenants it should look like this {$this->hostname->fqdn}

tenant1.domain.com/resets/...
tenant2.domain.com/resets/...
tenant3.domain.com/resets/...
...

**Comment by bkintanar** [comment]
@aBuder you can pass the fqdn when creating the reset password. and you can add it to the blade file.

**Comment by aBuder** [comment]
@bkintanar Sounds good, but where I find the email template? Should I have to publish an vendor?

**Comment by bkintanar** [comment]
Yes.

`php artisan vendor:publish --tag=laravel-mail`

**Comment by aBuder** [comment]
Sorry for the stupid question: How I can set it here? Or should it be better to set in Controller, but where I find the controller?

messages.blade.php
```
@component('mail::layout')
    {{-- Header --}}
    @slot('header')
        @component('mail::header', ['url' => config('app.url')])
            {{ config('app.name') }}
        @endcomponent
    @endslot

    {{-- Body --}}
    {{ $slot }}

    {{-- Subcopy --}}
    @isset($subcopy)
        @slot('subcopy')
            @component('mail::subcopy')
                {{ $subcopy }}
            @endcomponent
        @endslot
    @endisset

    {{-- Footer --}}
    @slot('footer')
        @component('mail::footer')
            &copy; {{ date('Y') }} {{ config('app.name') }}. All rights reserved.
        @endcomponent
    @endslot
@endcomponent
```

header.blade.php

```
<tr>
    <td class="header">
        <a href="{{ $url }}">
            {{ $slot }}
        </a>
    </td>
</tr>

```

**Comment by bkintanar** [comment]
Look for the Controller that calls that template and in that template where it says `@component('mail::header', ['url' => config('app.url')])` you can change it with your URL.

**Comment by aBuder** [comment]
I don't find an controller :(

**Comment by bkintanar** [comment]
You need to publish those as well. Kindly check the Laravel docs on how to do that.

https://laravel.com/docs/5.6/passwords#resetting-routing

**Comment by aBuder** [comment]
Works as designed :)

**Comment by luceos** [comment]
@aBuder the easiest way would have to listen to the `Identified` event and set the `app.url` configuration to the `fqdn` of the tenant. That would have cost you one listener, I'm planning on adding this to a next release as an option to enable

`override.app-url`
