### ISSUE TITLE
Drop Customer for 5.2.x

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#483]
In order to get to release 5.2.x one of the things to tackle is dropping the Customer object and all code related to that, including:

- [x] Relationships in other models
- [x] Repository
- [x] Config keys
- [x] Tests

Even though the Customer class has helped implementation, I think we need to keep a very small footprint in this package. Removing unnecessary classes will also eventually help us make our docs more transparent.

**Comment by spacemudd** [comment]
Is there any tips to prepare for 5.2? Because I'm about to begin coding a large app and right now I'm using customer logic and I'd love to have a smooth update.
