### ISSUE TITLE
Drop all code related to SSL

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#488]
Somewhere in an older version I hoped to have integrated a native Lets Encrypt client. As there are sufficient alternatives to handle SSL certificate generation outside of code, there's no longer a need to use it.

- [ ] drop the vhost references to ssl
- [ ] see if migrations, models and other code still reference ssl

**Comment by mintunitish** [comment]
@luceos Any hints about where to start?

**Comment by luceos** [comment]
I already searched the code for ssl and as far as I can tell this issue was already resolved. It requires one last scan to see everything is cleaned up.

**Comment by luceos** [comment]
Just checked, nothing left.
