### ISSUE TITLE
PHP Test tenant pages and logic

### ISSUE THREAD

**Issue by aBuder** [hyn/multi-tenant#495]
Hi,

this in serval question. How I can test my multi tenant web application. I would like to test login page, and all the login that is behind the login page, like forms etc.

**Comment by luceos** [comment]
This is a very good question. I guess the implementation would not differ too much from the default Laravel implementation, except that you would need to force identification of a tenant. We could write a doc for that.

**Comment by aBuder** [comment]
@luceos That would be great. Yes I would like to setup an tenant and test all functions that an tenant should do. 

- login
- logout
- password reset
- dashborad route
- and all my specific logic and routes that are in my app build like ( create an room, list all rooms, edit an room and so on )

It would be really helpful if there would be an quick documentation or tutorial.

Thx for help, the support is amazing

**Comment by bkintanar** [comment]
@aBuder while waiting for the documentation @luceos stated, I'd like to share to you how I test my app. I've created a dusk.sh (I'm using Laravel Dusk) executable (chmod +x) file containing the following code:

```sh
#!/usr/bin/env bash

export APP_URL="https://tenant.domain.localhost"

php artisan dusk
```

This allows me to set Environment variables before running dusk. There are many ways to achieve this, mine is just one of them.

I hope this helps.

**Comment by luceos** [comment]
Moved to docs repo.
