### ISSUE TITLE
 the tenancy.json file is not created

### ISSUE THREAD

**Issue by kawarien** [hyn/multi-tenant#497]
Hello, I just started with this package it is super cool. i have a small problem when i do php artisan tenancy: install the migrations succeed but the file tenancy.json does not create at the root of my project

Information

hyn / multi-tenant version: 5.1.2
Laravel version: 5.6
database driver and version: MySQL
web server software and version: NgInx
php version: 7.1

**Comment by luceos** [comment]
No issue here. The json file has not been needed for a while now. I guess we need to update that in the docs.

**Comment by kawarien** [comment]
Ah OK !! it is better to update the docs, because often it is misleading. 
thank you  !!

**Comment by bkintanar** [comment]
@kawarien where in the docs is that located? As I have believed it has been removed from the docs for quite some time now.

https://laravel-tenancy.com/docs/hyn/5.x/installation

**Comment by kawarien** [comment]
@bkintanar I had seen here https://medium.com/@ashokgelal/a-full-featured-multi-tenant-app-with-laravel-part-1-4049a3cc229d

**Comment by luceos** [comment]
Tutorials are never up to date. @ashokgelal something to consider?

**Comment by ashokgelal** [comment]
I'll update it. Thanks for bringing it to my attention.

Edit: Now it's done (at least the tenancy.json part)!

**Comment by luceos** [comment]
@ashokgelal thank you! 🤗
