### ISSUE TITLE
Illuminate \ Contracts \ Container \ BindingResolutionException Target [Hyn\Tenancy\Contracts\CurrentHostname] is not instantiable.

### ISSUE THREAD

**Issue by kawarien** [hyn/multi-tenant#498]
Hello,

 Thank you for this package, it is great !. i have a small problem when i try to type on the browser www.nameblog.test it returns this error.

> Illuminate \ Contracts \ Container \ BindingResolutionException
Target [Hyn\Tenancy\Contracts\CurrentHostname] is not instantiable.

![capture](https://user-images.githubusercontent.com/36641497/41206275-0b6d8d48-6cf1-11e8-8b6e-d87a998168ab.png)

**Information**
operating system: linux ,
homestead version: 7.7
hyn / multi-tenant version: 5.*
Laravel version: 5.6
database driver and version: MySQL
php version: 7.2

**I must also say that migration succeeds !!**

Thank you in advance for your answer !

**Comment by luceos** [comment]
Could you possibly post your tenancy.php configuration file?

**Comment by kawarien** [comment]
@luceos 

```
<?php

/*
 * This file is part of the hyn/multi-tenant package.
 *
 * (c) Daniël Klabbers <daniel@klabbers.email>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @see https://laravel-tenancy.com
 * @see https://github.com/hyn/multi-tenant
 */

use Hyn\Tenancy\Database\Connection;

return [
    'models' => [
        /**
         * Specify different models to be used for the global, system database
         * connection. These are also used in their relationships. Models
         * used have to implement their respective contracts and
         * either extend the SystemModel or use the trait
         * UsesSystemConnection.
         */

        // Must implement \Hyn\Tenancy\Contracts\Customer
        'customer' => \Hyn\Tenancy\Models\Customer::class,

        // Must implement \Hyn\Tenancy\Contracts\Hostname
        'hostname' => \Hyn\Tenancy\Models\Hostname::class,

        // Must implement \Hyn\Tenancy\Contracts\Website
        'website' => \Hyn\Tenancy\Models\Website::class
    ],
    'website' => [
        /**
         * Each website has a short random hash that identifies this entity
         * to the application. By default this id is randomized and fully
         * auto-generated. In case you want to force your own logic for
         * when you need to have a better overview of the complete
         * tenant folder structure, disable this and implement
         * your own id generation logic.
         */
        'disable-random-id' => false,

        /**
         * The random Id generator is responsible for creating the hash as mentioned
         * above. You can override what generator to use by modifying this value
         * in the configuration.
         *
         * @warn This won't work if disable-random-id is true.
         */
        'random-id-generator' => Hyn\Tenancy\Generators\Uuid\ShaGenerator::class,

        /**
         * Enable this flag in case you're using a driver that does not support
         * database username or database name with a length of more than 32 characters.
         *
         * This should be enabled for MySQL, but not for MariaDB and PostgreSQL.
         */
        'uuid-limit-length-to-32' => env('LIMIT_UUID_LENGTH_32', false),

        /**
         * Specify the disk you configured in the filesystems.php file where to store
         * the tenant specific files, including media, packages, routes and other
         * files for this particular website.
         *
         * @info If not set, will revert to the default filesystem.
         */
        'disk' => null,

        /**
         * Automatically generate a tenant directory based on the random id of the
         * website. Uses the above disk to store files to override system-wide
         * files.
         *
         * @info set to false to disable.
         */
        'auto-create-tenant-directory' => true,

        /**
         * Automatically rename the tenant directory when the random id of the
         * website changes. This should not be too common, but in case it happens
         * we automatically want to move files accordingly.
         *
         * @info set to false to disable.
         */
        'auto-rename-tenant-directory' => true,

        /**
         * Automatically deletes the tenant specific directory and all files
         * contained within.
         *
         * @see
         * @info set to true to enable.
         */
        'auto-delete-tenant-directory' => env('AUTO_DELETE_TENANT_DIRECTORY', false),

        /**
         * Time to cache websites in minutes. Set to false to disable.
         */
        'cache' => 10,
    ],
    'hostname' => [
        /**
         * If you want the multi tenant application to fall back to a default
         * hostname/website in case the requested hostname was not found
         * in the database, complete in detail the default hostname.
         *
         * @warn this must be a FQDN, these have no protocol or path!
         */
        'default' => env('TENANCY_DEFAULT_HOSTNAME'),
        /**
         * The package is able to identify the requested hostname by itself,
         * disable to get full control (and responsibility) over hostname
         * identification. The hostname identification is needed to
         * set a specific website as currently active.
         *
         * @see src/Jobs/HostnameIdentification.php
         */
        'auto-identification' => env('TENANCY_AUTO_HOSTNAME_IDENTIFICATION', true),

        /**
         * In case you want to have the tenancy environment set up early,
         * enable this flag. This will run the tenant identification
         * inside a middleware. This will eager load tenancy.
         *
         * A good use case is when you have set "tenant" as the default
         * database connection.
         */
        'early-identification' => env('TENANCY_EARLY_IDENTIFICATION', false),

        /**
         * Abort application execution in case no hostname was identified. This will throw a
         * 404 not found in case the tenant hostname was not resolved.
         *
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-hostnameabort-without-identified-hostname
         */
        'abort-without-identified-hostname' => true,

        /**
         * Time to cache hostnames in minutes. Set to false to disable.
         */
        'cache' => 10,
    ],
    'db' => [
        /**
         * The default connection to use; this overrules the Laravel database.default
         * configuration setting. In Laravel this is normally configured to 'mysql'.
         * You can set a environment variable to override the default database
         * connection to - for instance - the tenant connection 'tenant'.
         *
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-dbdefault
         */
        'default' => env('TENANCY_DEFAULT_CONNECTION'),
        /**
         * Used to give names to the system and tenant database connections. By
         * default we configure 'system' and 'tenant'. The tenant connection
         * is set up automatically by this package.
         *
         * @see src/Database/Connection.php
         * @var system-connection-name The database connection name to use for the global/system database.
         * @var tenant-connection-name The database connection name to use for the tenant database.
         */
        'system-connection-name' => env('TENANCY_SYSTEM_CONNECTION_NAME', Connection::DEFAULT_SYSTEM_NAME),
        'tenant-connection-name' => env('TENANCY_TENANT_CONNECTION_NAME', Connection::DEFAULT_TENANT_NAME),

        /**
         * The tenant division mode specifies to what database websites will be
         * connecting. The default setup is to use a new database per tenant.
         * In case you prefer to use the same database with a table prefix,
         * set the mode to 'prefix'.
         *
         * @see src/Database/Connection.php
         */
        'tenant-division-mode' => env('TENANCY_DATABASE_DIVISION_MODE', 'database'),

        /**
         * The database password generator takes care of creating a valid hashed
         * string used for tenants to connect to the specific database. Do
         * note that this will only work in 'division modes' that set up
         * a connection to a separate database.
         */
        'password-generator' => Hyn\Tenancy\Generators\Database\DefaultPasswordGenerator::class,

        /**
         * The tenant migrations to be run during creation of a tenant. Specify a directory
         * to run the migrations from. If specified these migrations will be executed
         * whenever a new tenant is created.
         *
         * @info set to false to disable auto migrating.
         *
         * @warn this has to be an absolute path, feel free to use helper methods like
         * base_path() or database_path() to set this up.
         */
        'tenant-migrations-path' => database_path('migrations/tenant'),

        /**
         * Seeds the newly created tenant database based on this Seeder.
         *
         * @info requires tenant-migrations-path to be in use.
         *
         * @warn specify a valid fully qualified class name.
         * @example App\Seeders\AdminSeeder::class
         */
        'tenant-seed-class' => TenantDatabaseSeeder::class,

        /**
         * Automatically generate a tenant database based on the random id of the
         * website.
         *
         * @info set to false to disable.
         */
        'auto-create-tenant-database' => true,

        /**
         * Automatically rename the tenant database when the random id of the
         * website changes. This should not be too common, but in case it happens
         * we automatically want to move databases accordingly.
         *
         * @info set to false to disable.
         */
        'auto-rename-tenant-database' => true,

        /**
         * Automatically deletes the tenant specific database and all data
         * contained within.
         *
         * @info set to true to enable.
         */
        'auto-delete-tenant-database' => env('AUTO_DELETE_TENANT_DATABASE', false),
    ],
    'folders' => [
        'config' => [
            /**
             * Merge configuration files from the config directory
             * inside the tenant directory with the global configuration files.
             */
            'enabled' => true,

            /**
             * List of configuration files to ignore, preventing override of crucial
             * application configurations.
             */
            'blacklist' => ['database', 'tenancy', 'webserver'],
        ],
        'routes' => [
            /**
             * Allows adding and overriding URL routes inside the tenant directory.
             */
            'enabled' => true,

            /**
             * Prefix all tenant routes.
             */
            'prefix' => null,
        ],
        'trans' => [
            /**
             * Allows reading translation files from a trans directory inside
             * the tenant directory.
             */
            'enabled' => true,

            /**
             * Will override the global translations with the tenant translations.
             * This is done by overriding the laravel default translator with the new path.
             */
            'override-global' => true,

            /**
             * In case you disabled global override, specify a namespace here to load the
             * tenant translation files with.
             */
            'namespace' => 'tenant',
        ],
        'vendor' => [
            /**
             * Allows using a custom vendor (composer driven) folder inside
             * the tenant directory.
             */
            'enabled' => true,
        ],
        'media' => [
            /**
             * Mounts the assets directory with (static) files for public use.
             */
            'enabled' => true,
        ]
    ]
];
```

**Comment by luceos** [comment]
And also the log file of the trace, that would help identify where the exception is thrown.

**Comment by kawarien** [comment]
> [2018-06-08 23:48:26] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:181)
[stacktrace]
#0 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(115): Illuminate\\Log\\LogManager->resolve(NULL)
#1 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(103): Illuminate\\Log\\LogManager->get(NULL)
#2 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(519): Illuminate\\Log\\LogManager->driver()
#3 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(114): Illuminate\\Log\\LogManager->error('SQLSTATE[HY000]...', Array)
#4 /home/vagrant/code/app/Exceptions/Handler.php(39): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Doctrine\\DBAL\\Driver\\PDOException))
#5 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(186): App\\Exceptions\\Handler->report(Object(Doctrine\\DBAL\\Driver\\PDOException))
#6 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#7 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(915): call_user_func(Object(Closure))
#8 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(940): Illuminate\\Database\\Connection->getPdo()
#9 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(399): Illuminate\\Database\\Connection->getReadPdo()
#10 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(325): Illuminate\\Database\\Connection->getPdoForSelect(true)
#11 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from i...', Array)
#12 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#13 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select * from i...', Array, Object(Closure))
#14 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->select('select * from i...', Array)
#15 /home/vagrant/code/vendor/hyn/multi-tenant/src/Environment.php(59): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable('hostnames')
#16 /home/vagrant/code/vendor/hyn/multi-tenant/src/Environment.php(42): Hyn\\Tenancy\\Environment->installed()
#17 [internal function]: Hyn\\Tenancy\\Environment->__construct(Object(Illuminate\\Foundation\\Application))
#18 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): ReflectionClass->newInstanceArgs(Array)
#19 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\\Container\\Container->build('Hyn\\\\Tenancy\\\\Env...')
#20 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\\Container\\Container->resolve('Hyn\\\\Tenancy\\\\Env...', Array)
#21 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(740): Illuminate\\Container\\Container->make('Hyn\\\\Tenancy\\\\Env...', Array)
#22 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(900): Illuminate\\Foundation\\Application->make('Hyn\\\\Tenancy\\\\Env...')
#23 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(828): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#24 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->resolveDependencies(Array)
#25 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(253): Illuminate\\Container\\Container->build('Hyn\\\\Tenancy\\\\Web...')
#26 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(764): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#27 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\\Container\\Container->build(Object(Closure))
#28 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\\Container\\Container->resolve('Hyn\\\\Tenancy\\\\Web...', Array)
#29 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(740): Illuminate\\Container\\Container->make('Hyn\\\\Tenancy\\\\Web...', Array)
#30 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(900): Illuminate\\Foundation\\Application->make('Hyn\\\\Tenancy\\\\Web...')
#31 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(828): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#32 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->resolveDependencies(Array)
#33 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\\Container\\Container->build('Hyn\\\\Tenancy\\\\Lis...')
#34 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\\Container\\Container->resolve('Hyn\\\\Tenancy\\\\Lis...', Array)
#35 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(740): Illuminate\\Container\\Container->make('Hyn\\\\Tenancy\\\\Lis...', Array)
#36 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(154): Illuminate\\Foundation\\Application->make('Hyn\\\\Tenancy\\\\Lis...')
#37 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(140): Illuminate\\Events\\Dispatcher->resolveSubscriber('Hyn\\\\Tenancy\\\\Lis...')
#38 /home/vagrant/code/vendor/hyn/multi-tenant/src/Providers/Tenants/EventProvider.php(55): Illuminate\\Events\\Dispatcher->subscribe('Hyn\\\\Tenancy\\\\Lis...')
#39 [internal function]: Hyn\\Tenancy\\Providers\\Tenants\\EventProvider->boot()
#40 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#41 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#42 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#43 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#44 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(800): Illuminate\\Container\\Container->call(Array)
#45 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(783): Illuminate\\Foundation\\Application->bootProvider(Object(Hyn\\Tenancy\\Providers\\Tenants\\EventProvider))
#46 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Hyn\\Tenancy\\Providers\\Tenants\\EventProvider), 21)
#47 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(784): array_walk(Array, Object(Closure))
#48 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#49 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(206): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#50 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#51 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#52 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#53 /home/vagrant/code/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#54 {main}
"}

**Comment by kawarien** [comment]
@luceos  

if i   do php artisan config:cache   i have this  Impossible to create the root directory "/opt/lampp/htdocs/kawar/storage/app".

**Comment by luceos** [comment]
The error is related to misconfigured logging in Laravel, not this package. Fix the issue with Laravel first.

I can also suggest creating a website with Laravel first before using this package, just to get the hang of how Laravel works.

**Comment by kawarien** [comment]
hello, 

I solved the problem. for the case of homestead it is necessary to connect while making vagrant ssh to make the migrations. thanks.
