### ISSUE TITLE
The base url domain for registering new tenants.

### ISSUE THREAD

**Issue by mintunitish** [hyn/multi-tenant#502]
__Description of your feature__

In current scenario before installing the package, we can access the home route , i.e. welcome page. This page is an entry point to the app. The space can be used to make a base registration page for tenants.

---

__Proposed behavior__

I am proposing that even after installing the package the normal behaviour of the app should remain same. The base URL(/) home page can be used as a registration page of welcome page for new onboarding users. The home route should not be overridden.

__Current behavior__

In current scenario, after installing the package we are given a 404 error for the home route. And we add the new tenants via commands or other means. We can access the app at the sub-domains only.

__Information__

- hyn/multi-tenant version: 5.x
- laravel version: 5.6.x

**Comment by luceos** [comment]
Please read the `tenancy.php` configuration and/or documentation to configure the package to your needs. The documentation calls this the [`fallback`](https://laravel-tenancy.com/docs/hyn/5.1/fallback).

The 404 given is a configuration called `abort-without-hostname`, you can set it to false.

Please note that going through the configuration is highly recommended to make the package do what you need. It's a very flexible component that can be easily adjusted to do whatever you need.

If you have any additional questions, feel free to post or join us on Discord.

**Comment by mintunitish** [comment]
Well, the fallback option is there. But in my application I want a feature to host the `/` route for the welcome page and a different fallback page for hostnames that are not found. However, I am unable to achieve this. Why the routes in my core laravel application's web.php is not working?

**Comment by luceos** [comment]
Are you able to do this?

```php
Route::domain('domain.com')->group(function() {
});

$hostname = app(Hyn\Tenancy\Contracts\CurrentHostname::class);

if ($hostname) {
	Route::domain($hostname->fqdn)->group(function() {});
}
```

I'll see to it you can declare tenant routes inside a `routes/tenants.php` file and auto loading it for 5.2.
