### ISSUE TITLE
Rename Customers to Tenants

### ISSUE THREAD

**Issue by sarmad4444** [hyn/multi-tenant#512]
I've used this great plugin in 5 SaaS applications and there's one main confusion in this. Usually most of multi-tenant applications have a vision to provide software for multiple businesses which have their own clients/customers. Now the confusion that is particularly with new developers on an existing system I'm facing is the term "Customers". I've renaming my tenant's customers table to clients and on some I used the name Customers too.

But I wish the customers term in this plugin could be renamed to Tenants. So we also have the flexibility to create separate customers table for customer profiling etc.

---
- hyn/multi-tenant version: 5.1
- laravel version: 5.6

**Comment by fletch3555** [comment]
The "Customer" model (and related functionality) has been removed in the `5.x` branch in preparation for 5.2.  Additionally, There will be a `Tenant` interface, so you can use any method of tenant identification you wish.  I'm sure @luceos could go into more detail if you wish.

**Comment by luceos** [comment]
I agree that the subject of Tenancy is the Tenant and that by binding the Hostname as the single point of entry was a huge mistake. It's part of the legacy code base coming from the early 2.x code. The current version (5.1) uses Tenant nowhere to be less confusing and clearly [states in the documentation](https://laravel-tenancy.com/docs/hyn/5.1/concepts#introduction):

> A tenant is a website.

For version 5.2 the Customer object has been removed, it has always been a Model that was intended to simplify implementation, but I can imagine use cases it would not be used at all and thus linger around in the package code base. As such that specific model will be removed; an [upgrade path is available in the docs](https://laravel-tenancy.com/docs/hyn/5.2/upgrade-from-5.1).

After 5.2 my focus will go to the successor called tenancy/tenancy. A fundamental difference between hyn/multi-tenant (hyn) and tenancy/tenancy (tenancy) is that the subject of tenancy is no longer a fixed model. Whereas hyn uses the Website (and in 5.2 binds that to a Tenant contract), tenancy only offers a Tenant contract per default and will bind any object implementing the Tenant model to the Tenant contract based on an event dispatched.

PS @sarmad179 glad to hear you're using it in 5 SaaS applications, would you be willing to add your project to the [spotlight](https://github.com/tenancy/docs/tree/master/projects) and/or become a sponsor or backer on the [open collective](https://opencollective.com/tenancy) to support continued development?
