### ISSUE TITLE
Tenant db on separate aws RDS instances

### ISSUE THREAD

**Issue by maelga** [hyn/multi-tenant#517]
I am wondering whether system and tenant db connections can be configured to connect to separate aws RDS instances. 

This would be necessary where tenants' data must reside in different countries.

Any experience with that?

**Comment by luceos** [comment]
![image](https://user-images.githubusercontent.com/504687/41763361-5aa10050-75fe-11e8-9ac4-18230230d779.png)

I've asked him and someone else who is using RDS to reply here. Feel free to join us on discord at https://laravel-tenancy.com/chat 👍

**Comment by maelga** [comment]
Thank you for this great package and support on Discord @luceos @bkintanar 
Creating separate tenant connections is what I was looking for: https://laravel-tenancy.com/docs/hyn/5.1/repositories#managing-connection
