### ISSUE TITLE
New Tenant Division Mode: Multischema for PostgreSQL

### ISSUE THREAD

**Issue by xmarkclx** [hyn/multi-tenant#533]
__Description of your feature__
Allow mode to use multischema on 1 database for PostgreSQL.

https://www.citusdata.com/blog/2016/10/03/designing-your-saas-database-for-high-scalability/ says why it is preferable.
..

---

__Proposed behavior__
Add a new tenant-division-mode option, along with codes to create the schema, query based on it, etc.

..

__Current behavior__
There is no such option.

..

---
__Information__

- hyn/multi-tenant version: 5.2.*
- laravel version: 5.6.*

**Comment by luceos** [comment]
This would be great to have. But it doesn't have a high priority on my planning. A tested PR would be accepted.

**Comment by fletch3555** [comment]
Closing as #603 got merged.
