### ISSUE TITLE
User Model defaults to System connection automatically

### ISSUE THREAD

**Issue by adamthomason** [hyn/multi-tenant#534]
I'm implementing auth in my project, and have migrations to create the user tables on the tenant on creation. I'm also setting the connection based on the tenant I'm on.

My issue is that when registering, although I can confirm that the connection is set to use 'tenant', the user is created on the system database instead. I haven't defined anywhere that the User model should use the system connection, so am I right in thinking that there is some sort of override somewhere?

Or should I play it safe and have different user models for both the tenant and system?

**Comment by bkintanar** [comment]
@adamthomason are you using the UsesTenantConnection trait in the user model?

**Comment by adamthomason** [comment]
@bkintanar No, I'm not using any code or config to explicitly force a connection for models

**Comment by adamthomason** [comment]
I've worked out a fix for this by created my own Trait and attaching it to the User model. I'll post this below in case anybody has the same use case. Although if there is a more official way to do this, then I'm all ears!

```
<?php

namespace App\Traits;

use Hyn\Tenancy\Database\Connection;

trait DetermineConnection
{
    public function getConnectionName()
    {
        $hostname = app(\Hyn\Tenancy\Contracts\CurrentHostname::class);
    
        if ($hostname) {
            return app(Connection::class)->tenantName();
        } else {
            return app(Connection::class)->systemName();
        }
    }
}
```

**Comment by luceos** [comment]
@adamthomason this should be a PR against the package as TenantAwareConnection or TenantOptionalConnection trait 👍 

I like it!

**Comment by luceos** [comment]
merged
