### ISSUE TITLE
How to define tenant owner / creator

### ISSUE THREAD

**Issue by on3nx** [hyn/multi-tenant#539]
Hi,

I got a question, is there a function to define / set tenant creator (owner)?
i saw in the customers database that there is no "creator_id" (link to users db).

what i'm trying to achieve is:
i will have master users under master/main tenant that will be able to create tenant from the main website, and set/create a 'local' user for her/his newly created tenant - this master user will be known as the tenant creator / owner (for tenant management (edit/delete) and/or billing system for tenant, etc)

so to achieve this, can i just modify the customers table (by adding owner_id), or is there a mechanism that this framework has provided?

and second question is: is there a model and controller to manage customers db?

Thanks!

**Comment by luceos** [comment]
You can add another migration that adds the necessary columns you see fit to get your app up and running. Wildly assuming what each implementation needs and offering migrations, model, controllers and views only increases the weight of the package unnecessarily.

Please note Customers are dropped in 5.2; if you want to keep them I suggest moving the migrations and models over to your app codebase before upgrading.
