### ISSUE TITLE
How to Create Tenant in 5.2

### ISSUE THREAD

**Issue by on3nx** [hyn/multi-tenant#542]
Hi

I'm implementing 5.2.3 from 5.1
what i did was:
- composer update (`"hyn/multi-tenant": "^5.2.3",`)
- remove tenancy table and rerun `php artisan vendor:publish --tag=tenancy`
- docker-compose exec app php artisan migrate
- am i miss anything else here?

and i build artisan tenant:create as follow:

```
class CreateTenant extends Command
{
    protected $signature = 'tenant:create {name} {email}';
    protected $description = 'Creates a tenant with the provided name and email address e.g. php artisan tenant:create boise boise@example.com';
    public function handle()
    {
        $name = $this->argument('name');
        $email = $this->argument('email');
        if ($this->tenantExists($name, $email)) {
            $this->error("A tenant with name '{$name}' and/or '{$email}' already exists.");
            return;
        }
        $hostname = $this->registerTenant($name, $email);
        app(Environment::class)->hostname($hostname);

        // we'll create a random secure password for our to-be admin
        $password = str_random();
        $this->addAdmin($name, $email, $password);

        $this->info("Tenant '{$name}' is created and is now accessible at {$hostname->fqdn}");
        $this->info("Admin {$email} can log in using password {$password}");
    }
    private function tenantExists($name, $email)
    {
        return Hostname::where('fqdn', $name.env('TENANCY_DEFAULT_HOSTNAME'))->exists();
    }
    private function registerTenant($name, $email)
    {
        // create a customer
        // $customer = new Customer;
        // $customer->name = $name;
        // $customer->email = $email;
        // app(CustomerRepository::class)->create($customer);

        // associate the customer with a website
        $website = new Website;
        // $website->customer()->associate($customer);
        app(WebsiteRepository::class)->create($website);

        // associate the website with a hostname
        $hostname = new Hostname;
        $baseUrl = config('app.url_base');
        $hostname->fqdn = "{$name}.{$baseUrl}";
        // $hostname->customer()->associate($customer);
        app(HostnameRepository::class)->attach($hostname, $website);
        return $hostname;
    }
    private function addAdmin($name, $email, $password)
    {
        $admin = User::create(['name' => $name, 'email' => $email, 'password' => Hash::make($password)]);
        return $admin;
    }
}
```
it throw me error: 

```
In DatabaseManager.php line 115:                           
  Undefined index: driver  
```

this seems like missing database driver?

do I need to create tenant driver in database.php config file?

but in doc it said:
https://laravel-tenancy.com/docs/hyn/5.2/installation
> There is no need to configure the tenant connection in the database.php configuration file. This connection is set up automatically during runtime. Pre- configuring this connection may cause unwanted behaviour.

**Comment by fletch3555** [comment]
You don't need to configure that driver.  The error is telling you the driver doesn't exist, but that's because this package hasn't configured it yet, because it hasn't identified a tenant.  Since this is in a command, that must be done manually.

Until 5.2, that was done using the `Environment::hostname()` method.  In fact, your command already has that:
```
app(Environment::class)->hostname($hostname);
```

For 5.2+, however, there's a new method, `Environment::tenant()`, which handles this, since you're no longer required to use hostnames for tenant identification.  Since you are, it's an easy swap:
```
app(Environment::class)->tenant($hostname);
```

Please let us know if that doesn't work for you, but I suspect it will.

**Comment by on3nx** [comment]
Thanks, I did tried, now it giving me error:

> Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Hyn\Tenancy\Environment::tenant() must implement interface Hyn\Tenancy\Contracts\Website or be null, instance of Hyn\Tenancy\Models\Hostname given

**Comment by fletch3555** [comment]
Ah, my mistake.  It needs a Website object, not a Hostname.  You should change the `registerTenant` method to return `$website`, not `$hostname`.  That should work since they're already linked

**Comment by on3nx** [comment]
Awesome! that works
Thank you so much
