### ISSUE TITLE
database confusion between tenant and super admin

### ISSUE THREAD

**Issue by kawarien** [hyn/multi-tenant#543]
**Information**
operating system: linux ,
homestead version: 7.7
hyn / multi-tenant version: 5.1.2
Laravel version: 5.6
database driver and version: MySQL
php version: 7.1.3

**Description**

when I connect to a sub.domain.com tenant I create a user the user is not created in the tenant database.
user is created in the database of domaine.com why?

User.php
![us](https://user-images.githubusercontent.com/36641497/42522891-c9c09c1e-845b-11e8-800d-2d6aa9ead428.png)

**NB**

I have no error or woops, the problem the data is registered in the database domain.com and not sub.domaine.com database.

**Comment by fletch3555** [comment]
Didn't we answer this on Discord yesterday?

Did you change the BREAD configuration for `users` to use your `App\User` model instead of the default `TCG\Voyager\Models\User`?

**Comment by kawarien** [comment]
hello @fletch3555 
when I had changed  to App/User I had this

![err](https://user-images.githubusercontent.com/36641497/42526470-6be60d40-8465-11e8-9f7e-5547aca762f6.png)


now i just changed to `app\User` and it works. thank you very much



it was @luceos  told to me to open a issues on github and i see that his paid  lol ..
