### ISSUE TITLE
Error while creating a new tenant

### ISSUE THREAD

**Issue by femz12** [hyn/multi-tenant#547]
I got this error while trying to create a new tenant

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `5f0e7ad58c5e480da7a1e960ba71fe6e`@'127.0.0.1' IDENTIFIED BY 'd90d' at line 1 (SQL: CREATE USER IF NOT EXISTS `5f0e7ad58c5e480da7a1e960ba71fe6e`@'127.0.0.1' IDENTIFIED BY 'd90d8f6fb4e29fbfe06e25e7c5260e89')
```

MySQL version 14.14
Laravel Version 5.6
PHP version 7.1.16
OS: Ubuntu 14.04

function where it failed
```
public function createTenantWebsite($website_prefix)
    {
        $website = new Website();
        app(WebsiteRepository::class)->create($website);
        return $website;
    }
```

**Comment by luceos** [comment]
Which MySQL server version are you using, you posted the MySQL version your client was built against:

https://stackoverflow.com/questions/8645184/version-vs-distrib-number-of-mysql

**Comment by femz12** [comment]
Thanks for your response, I discovered I was using MySQL v5.5 and i guess that is the issue.

Please what is the best advise you can give me, because upgrading my MySQL version may be risky,

Thanks in advance

**Comment by luceos** [comment]
A few options crossed my mind;

- get us to implement a new event before doing actual mutations on the database where you can change the driver
- get us to introduce a version compatible mysql driver
- disable auto generation and listen to the events yourself to create, update and delete databases and users.

I'm not a huge fan of the actions we can take. I would still suggest upgrading MySQL.

**Comment by femz12** [comment]
Thank you!
