### ISSUE TITLE
UsesTenantConnection and UsesSystemConnection

### ISSUE THREAD

**Issue by mintunitish** [hyn/multi-tenant#548]
I have a situation where I want to use the same `User `model to authenticate the users in _tenant_ as well as _system_ connections. But adding the `UsesTenantConnection `makes it point directly to tenant database. There should be a way to use the same model for both the purposes, or there's is a way and I am missing it?

**Comment by luceos** [comment]
Would this [pr](https://github.com/hyn/multi-tenant/pull/537) solve your question?

Also, what commonly is the solution is to create two classes that extend User; the TenantUser and SystemUser, some might call those User vs Admin. Each of these would apply a different trait.

I'm closing this as this is a question more than an issue, feel free to continue commenting or re-open if you think we should take action from our side.

**Comment by mintunitish** [comment]
Yeah that PR will solve my problem.
