### ISSUE TITLE
Main Website use System Connection

### ISSUE THREAD

**Issue by on3nx** [hyn/multi-tenant#549]
I'm Installed and Running 5.2.4
upon installation my site giving me 404 at my main domain.com, until i setup/create a Tenant with below syntax:

```
$connection = 'system';
$fqdn = 'domain.com';

// associate the customer with a website
$website = new Website;
if($connection != 'default') $website->managed_by_database_connection = $connection;
app(WebsiteRepository::class)->create($website);

// associate the website with a hostname
$hostname = new Hostname;
$hostname->fqdn = $fqdn;
app(HostnameRepository::class)->attach($hostname, $website);

app(Environment::class)->tenant($website);
```

Above syntax will create a tenant and I'm able to access my main domain.com
however, this domain.com is created using tenant connection (it using website uuid database)
even-though I have set `managed_by_database_connection ` to system or blank.

I'm expecting:
- when I create main tenant (domain.com) --> this should use system connection, including users
- when i create tenant (tenant.domain.com) -->this should use tenant (uuid) connection, including users

how can I achieve this?

**Comment by fletch3555** [comment]
You don't need to create a tenant for `domain.com`, you only need a `Hostname` for it.  OR you can simply set `abort-without-identified-hostname` to `false` in your `config/tenancy.php`.  If you do this, you will need to add the domain to your routes so they don't affect actual tenants.

**Comment by on3nx** [comment]
but if I don't create tenant, my domain.com give me 404
I may missed something here, what do you mean by: "you only need a Hostname" ?

**Comment by fletch3555** [comment]
The `abort-without-identified-hostname` config is what determines whether non-existent hostnames result in a 404 Not Found response from this package or if it's left up to the app.  If set to true, it will throw a 404 if there is now Hostname record with a `fqdn` matching the requested domain (`domain.com` in your case).  This is exactly what you're experiencing.

You have 2 options.

1. Create a hostname entry (no need to create associated website) for `domain.com`
2. Set `abort-without-identified-hostname` to false

In either case, you will want to define your "main site" routes with [subdomain routing](https://laravel.com/docs/5.6/routing#route-group-sub-domain-routing).

**Comment by on3nx** [comment]
Thanks @fletch3555,
anyway, my `'abort-without-identified-hostname'`, is already false before i post this

and yes it still throw me 404 - unless i create the tenant domain.com, then if I access notexist.domain.com it will direct me back to domain.com

you said: "it will throw a 404 if there is no Hostname record with a fqdn matching the requested domain"
may I ask, where should i put/set Hostname record that will be matched with fqdn?

**Comment by fletch3555** [comment]
Well without seeing your code/config, I can only guess at the issue.  If you follow the [issue template](https://github.com/hyn/multi-tenant/blob/5.x/.github/ISSUE_TEMPLATE/Bug_report.md), it would provide most of the information we would need.

**Comment by on3nx** [comment]
let me post the issue template...

you said: "it will throw a 404 if there is no Hostname record with a fqdn matching the requested domain"
may I ask, where should i put/set Hostname record that will be matched with fqdn?

**Comment by on3nx** [comment]
---
name: Main hostname throw 404 upon installation
about: Main hostname throw 404 upon installation until i set tenant manually

---

__Description__

I Install 5.2.4, upon installation it throw me 404 at my main domain.com.

Note: my site is running on port 8080 so it is accessible at: http://domain.com:8080
not sure if this could be the issue

---

__Actual behavior__

return 404 on main domain.com port 8080 upon installation
access URL: http://domain.com:8080

__Expected behavior__

it should run main domain.com as master tenant (without any tenant creation)

---
__Information__

- hyn/multi-tenant version: 5.2.4
- laravel version: 5.6
- database driver and version: mysql 5.7
- webserver software and version: NGINX 1.15
- php version: 7.2.6-fpm

---

__tenancy.php config__

```php
<?php

use Hyn\Tenancy\Database\Connection;

return [
    'models' => [

        'hostname' => \Hyn\Tenancy\Models\Hostname::class,

        'website' => \Hyn\Tenancy\Models\Website::class
    ],
    'website' => [
        'disable-random-id' => false,

        'random-id-generator' => Hyn\Tenancy\Generators\Uuid\ShaGenerator::class,

        'uuid-limit-length-to-32' => env('LIMIT_UUID_LENGTH_32', false),

        'disk' => null,

        'auto-create-tenant-directory' => true,

        'auto-rename-tenant-directory' => true,

        'auto-delete-tenant-directory' => false,

        'cache' => 10,
    ],
    'hostname' => [
        'default' => env('TENANCY_DEFAULT_HOSTNAME'),
        'auto-identification' => env('TENANCY_AUTO_HOSTNAME_IDENTIFICATION', true),

        'early-identification' => env('TENANCY_EARLY_IDENTIFICATION', false),

        'abort-without-identified-hostname' => true,

        'cache' => 10,

        'update-app-url' => false,
    ],
    'db' => [
        'default' => env('TENANCY_DEFAULT_CONNECTION'),
        'system-connection-name' => env('TENANCY_SYSTEM_CONNECTION_NAME', Connection::DEFAULT_SYSTEM_NAME),
        'tenant-connection-name' => env('TENANCY_TENANT_CONNECTION_NAME', Connection::DEFAULT_TENANT_NAME),

        'tenant-division-mode' => env('TENANCY_DATABASE_DIVISION_MODE', 'database'),

        'password-generator' => Hyn\Tenancy\Generators\Database\DefaultPasswordGenerator::class,

        'tenant-migrations-path' => database_path('migrations/tenant'),

        'tenant-seed-class' => false,
//      eg an admin seeder under `app/Seeders/AdminSeeder.php`:
//        'tenant-seed-class' => App\Seeders\AdminSeeder::class,

        'auto-create-tenant-database' => true,

        'auto-create-tenant-database-user' => true,

        'auto-rename-tenant-database' => true,

        'auto-delete-tenant-database' => env('TENANCY_DATABASE_AUTO_DELETE', false),

        'auto-delete-tenant-database-user' => env('TENANCY_DATABASE_AUTO_DELETE_USER', false),

        'force-tenant-connection-of-models' => [
//            App\User::class
        ],
        'force-system-connection-of-models' => [
//            App\User::class
        ],
    ],

    'routes' => [
        'path' => base_path('routes/tenants.php'),

        'replace-global' => false,
    ],

    'folders' => [
        'config' => [
            'enabled' => true,

            'blacklist' => ['database', 'tenancy', 'webserver'],
        ],
        'routes' => [
            'enabled' => true,

            'prefix' => null,
        ],
        'trans' => [
            'enabled' => true,

            'override-global' => true,

            'namespace' => 'tenant',
        ],
        'vendor' => [
            'enabled' => true,
        ],
        'media' => [
            'enabled' => true,
        ],
        'views' => [
            'enabled' => true,

            'namespace' => null,

            'override-global' => true,
        ]
    ]
];

```

__webserver.php config__

```php
<?php

return [

    'apache2' => [
        'enabled' => false,

        'ports' => [
            /**
             * HTTP, non-SSL port.
             *
             * @default 80
             */
            'http' => 80,
            /**
             * HTTPS, SSL port.
             *
             * @default 443
             */
            'https' => 443
        ],

        /**
         * The generator taking care of hooking into the Apache services and files.
         */
        'generator' => \Hyn\Tenancy\Generators\Webserver\Vhost\ApacheGenerator::class,

        /**
         * The view that holds the vhost configuration template.
         */
        'view' => 'tenancy.generators::webserver.apache.vhost',

        /**
         * Specify the disk you configured in the filesystems.php file where to store
         * the tenant vhost configuration files.
         *
         * @info If not set, will revert to the default filesystem.
         */
        'disk' => null,

        'paths' => [

            /**
             * Location where vhost configuration files can be found.
             */
            'vhost-files' => [
                '/etc/apache2/sites-enabled/'
            ],

            /**
             * Actions to run to work with the Apache2 service.
             */
            'actions' => [
                /**
                 * Action that asserts Apache2 is installed.
                 */
                'exists' => '/etc/init.d/apache2',
                /**
                 * Action to run to test the apache configuration.
                 */
                'test-config' => 'apache2ctl -t',
                /**
                 * Action to run to reload the apache service.
                 */
                'reload' => 'apache2ctl graceful'
            ]
        ]
    ],

    /**
     * Nginx webserver support.
     *
     * @see http://nginx.org
     */
    'nginx' => [
        /**
         * Whether the integration with nginx is currently active.
         */
        'enabled' => false,

        /**
         * The php sock to be used.
         */
        'php-sock' => 'unix:/var/run/php/php7.1-fpm.sock',

        /**
         * Define the ports of your nginx service.
         */
        'ports' => [
            /**
             * HTTP, non-SSL port.
             *
             * @default 80
             */
            'http' => 80,
            /**
             * HTTPS, SSL port.
             *
             * @default 443
             */
            'https' => 443
        ],

        /**
         * The generator taking care of hooking into the nginx services and files.
         */
        'generator' => \Hyn\Tenancy\Generators\Webserver\Vhost\NginxGenerator::class,

        /**
         * The view that holds the vhost configuration template.
         */
        'view' => 'tenancy.generators::webserver.nginx.vhost',

        /**
         * Specify the disk you configured in the filesystems.php file where to store
         * the tenant vhost configuration files.
         *
         * @info If not set, will revert to the default filesystem.
         */
        'disk' => null,

        'paths' => [

            /**
             * Location where vhost configuration files can be found.
             */
            'vhost-files' => [
                '/etc/nginx/sites-enabled/'
            ],

            /**
             * Actions to run to work with the Nginx service.
             */
            'actions' => [
                /**
                 * Action that asserts nginx is installed.
                 */
                'exists' => '/etc/init.d/nginx',
                /**
                 * Action to run to test the nginx configuration.
                 */
                'test-config' => '/etc/init.d/nginx configtest',
                /**
                 * Action to run to reload the nginx service.
                 */
                'reload' => '/etc/init.d/nginx reload'
            ]
        ]
    ]
];

```

---

__Error log__

```text
NA
```

let me know if  you need any other information...

**Comment by luceos** [comment]
```
'abort-without-identified-hostname' => true,
```

Abort without hostname is still enabled.. It will enforce a 404 whenever no tenant was identified.

**Comment by on3nx** [comment]
That was because I'm troubleshooting, i could change back the value to false and see the result leter.

However, let me try to understand...
`'abort-without-identified-hostname' => true;` will send 404 if there is no tenant identified in the particular url that being accessed - am i correct?

That means:
If i have no tenant at all (fresh install and `'abort-without-identified-hostname' => true;` ), when i access notenant.domain.com it will send me 404 - this make sense

And I try to understand: will I still receive 404 when I access domain.com?

**Comment by fletch3555** [comment]
Yes that is correct in both cases, for the same reason.  However, I would caution you not to confuse "Hostname" with "tenant".  That config will throw a 404 is no _Hostname_ exists, whether its associated with a _tenant_("Website" by default) or not.

**Comment by on3nx** [comment]
@luceos and @fletch3555 
when i set `'abort-without-identified-hostname' => false`, it give me error: 

> Database [tenant] not configured
> (View: /var/www/resources/views/layouts/frontend/body.blade.php) (View: /var/www/resources/views/layouts/frontend/body.blade.php) (View: /var/www/resources/views/layouts/frontend/body.blade.php)

**Comment by on3nx** [comment]
ok, so let me run through what i did:

**case 1:**
i did fresh installed all database hostname and website are empty, i set `'abort-without-identified-hostname' => true`
**result**: 404

i set `'abort-without-identified-hostname' => false`
**result**: Database [tenant] not configured.

**case 2:** 
i set back again `'abort-without-identified-hostname' => true`
i set hostname db as below (manual / direct inject to DB):
![image](https://user-images.githubusercontent.com/22399095/42856877-bf8723ac-8a79-11e8-92be-326b3a4596e1.png)

**result**: Database [tenant] not configured.

i set `'abort-without-identified-hostname' => false`
**result**: Database [tenant] not configured.

**case 3:**
i set back again `'abort-without-identified-hostname' => true`
i set hostname db as below (manual / direct inject to DB):
![image](https://user-images.githubusercontent.com/22399095/42857014-83a1fbcc-8a7a-11e8-91bb-f66c5c40bb17.png)

i set website db as below (manual / direct inject to DB):
![image](https://user-images.githubusercontent.com/22399095/42857040-9c431c2e-8a7a-11e8-9c37-30e8ea3a4ff6.png)

**result**: Database [tenant] not configured.

i set `'abort-without-identified-hostname' => false`
**result**: Database [tenant] not configured.

case 4:
i set back again `'abort-without-identified-hostname' => true`
i clear all database back again
then i run:
```
$connection = 'system';
$fqdn = 'domain.com';

// associate the customer with a website
$website = new Website;
if($connection != 'default') $website->managed_by_database_connection = $connection;
app(WebsiteRepository::class)->create($website);

// associate the website with a hostname
$hostname = new Hostname;
$hostname->fqdn = $fqdn;
app(HostnameRepository::class)->attach($hostname, $website);

app(Environment::class)->tenant($website);
```
result:
it create database record as below:
![image](https://user-images.githubusercontent.com/22399095/42857740-c53ccfaa-8a7d-11e8-82cd-69efb31f7f2f.png)

![image](https://user-images.githubusercontent.com/22399095/42857753-d88674bc-8a7d-11e8-896d-6ee49fd20617.png)

and it create database:
![image](https://user-images.githubusercontent.com/22399095/42857777-f7834b7e-8a7d-11e8-9018-357ecfad44a2.png)

the website is up and i can access domain.com
and even if i go to test.domain.com it will throw 404 --> which understand able because: i set back again `'abort-without-identified-hostname' => true`
and even if i create user it will create user in the new created website database.

now if: i set `'abort-without-identified-hostname' => false`
when i access test.domain.com it show the website (BUT it didnt direct me to domain.com - it stay at test.domain.com)

**so what I'm trying to achieve is:**
I want to run domain.com under bytedb and my user is registered under bytedb database aswell.
while later when i create new tenant, it should create new website uuid DB and use that as tenant connection

*note: i'm not sure if there any cache in the system? i did case 1 to 4 in subsequent immediate action.
if there any cache, the result may not be accurate.

Please help me :)

**Comment by luceos** [comment]
@on3nx this is what I call Due Diligence and for that alone you deserve my respect!

Now let's get your train rolling:

- `abort-without-identified-hostname` let's call it `abort` for now. This will throw a 404 whenever the requested page did not find a Hostname based on the HTTP_HOST.
- The error `Database [tenant] not configured.` is thrown whenever an Eloquent model is being used to query the database with, which has been set to use the tenant connection; either by applying the `UsesTenantConnection` trait, by forcing it from the `tenancy.php` config or by setting the `tenant` connection as default. We cannot identify the cause without a trace!
- The above error is also often thrown while using artisan. A common mistake is to assume tenancy is able to identify what tenant you are trying to use. During cli/artisan usage we have no such way without the wrapper commands `tenancy:*`. During artisan calls there's no way for tenancy to automatically identify the tenant.

Reading what you are trying to achieve, the following:

- set abort to true
- add a hostname `domain.com` to hostnames table connected to the site (you create) bytedb
- use the repository instead of manually adding the hostname+website OR fire the event [Website\Created](https://github.com/hyn/multi-tenant/blob/5.x/src/Events/Websites/Created.php) manually to trigger database creation etc
- hit domain.com in your browser, you should now be on the tenant website

From the top of my head.

**Comment by on3nx** [comment]
Thanks @luceos 

pardon for my newbie-ness :)

following what you advise:

- set abort to true --> done
- add a hostname domain.com to hostnames table connected to the site (you create) bytedb
 i'm not clear about this: how?
do you mean manually adding to hostname DB?
and to "_hostnames table connected to the site bytedb_" --> how to connect hostname table to the site?
- use the repository instead of manually adding the hostname+website OR fire the event Website\Created manually to trigger database creation etc
how is this different with what I already did?
```
// This is Artisan Command

$connection = 'system';
$fqdn = 'domain.com';

// associate the customer with a website
$website = new Website;
if($connection != 'default') $website->managed_by_database_connection = $connection;
app(WebsiteRepository::class)->create($website);

// associate the website with a hostname
$hostname = new Hostname;
$hostname->fqdn = $fqdn;
app(HostnameRepository::class)->attach($hostname $website);

app(Environment::class)->tenant($website);
```
- hit domain.com in your browser, you should now be on the tenant website
this should be easy once above sort out :D

**Comment by luceos** [comment]
> hit domain.com in your browser, you should now be on the tenant website
this should be easy once above sort out :D

@on3nx did it work?

**Comment by on3nx** [comment]
@luceos 
I'm not quite understand your step 2 and 3 - I couldn't get it work as you advise...

however, I did manage to get a workaround, so what i did is:

1. I run: 
```
// This is Artisan Command

$connection = 'system';
$fqdn = 'domain.com';

// associate the customer with a website
$website = new Website;
if($connection != 'default') $website->managed_by_database_connection = $connection;
app(WebsiteRepository::class)->create($website);

// associate the website with a hostname
$hostname = new Hostname;
$hostname->fqdn = $fqdn;
app(HostnameRepository::class)->attach($hostname $website);

app(Environment::class)->tenant($website);
```

this command will make new tenant with new database and new user

2. I delete the database and the user of its DB
3. I change the hostname in websites DB to bytedb
4. I create bytedb user with pass that the package try to access to manage bytedb DB
4.a I found the pass by tracing the error - the trace will shown what pass the code try to access

so with that, i got what I want but, I dont think this is the correct way and I'm not sure what is the impact of this...

**Comment by luceos** [comment]
The code snippet you provided is valid. However you want to identify it with `bytedb` you can set the `uuid` on the `Website` model before sending it to the `create` method of the Website Repository to override that identifier:

```php
$website = new Website;
$website->uuid = 'bytedb';
if($connection != 'default') $website->managed_by_database_connection = $connection;
app(WebsiteRepository::class)->create($website);
```

You should now be able to visit `domain.com` depending on how your own environment is set up. In case you rely on the vhosts being generated, the files should exist now. The webserver should be reloaded, but only if you are running this code with a user that has the permission to do so.

As a note, there's a typo here:
```php
app(HostnameRepository::class)->attach($hostname, $website);
```

**Comment by on3nx** [comment]
@luceos 
I did try that before, for some reason, it show me some strange result like:

when i do:

```
$website = new Website;
$website->uuid = 'bytedb';
$this->info("Website UUID {$website->uuid}");
// until here it stil show bytedb uuid
app(WebsiteRepository::class)->create($website);
$this->info("Website UUID {$website->uuid}");
// after this, it print me a 'real' uuid e.g. "5cd4340cbcd447c88377643ddcfde6e6"
```

I guess there is something wrong there

**Comment by luceos** [comment]
That's a bug!

**Comment by luceos** [comment]
@on3nx please installed 5.2.6

**Comment by on3nx** [comment]
Thanks @luceos, I may be able to try tomorrow - it's late here :)

**Comment by on3nx** [comment]
@luceos Perfect! and Thanks!
this solved the issue.

just to clarify,,, so understanding this, it means:

after new install, I have to init tenant for my main domain.com? because otherwise it will throw 404
I didn't encounter this in 5.1 before...

just to share, so after installing your package, I need to run below to make my main domain.com works:

    // This is Artisan Command

        $connection = env('DB_CONNECTION','system');
        $fqdn = env('APP_FQDN_BASE','domain.com');

        // associate the customer with a website
        $website = new Website();
        $website->uuid = env('DB_DATABASE','database');
        $website->managed_by_database_connection = $connection;
        app(WebsiteRepository::class)->create($website);

        // associate the website with a hostname
        $hostname = new Hostname();
        $hostname->fqdn = $fqdn;
        app(HostnameRepository::class)->attach($hostname, $website);

        app(Environment::class)->tenant($website);

**Comment by luceos** [comment]
If you keep abort-without-hostname enabled and tenancy does not find a hostname match it will 404. You can circumvent this by adding the hostname of any domain you need into the table, you don't need to connect it to a website/tenant.

**Comment by bjsmasth** [comment]
if i add main domain (eg: abc.org) to hostname, it's not throwing 404 error for any non listed hostname(*.abc.org)
