### ISSUE TITLE
[Question] Use Package with API Style Application

### ISSUE THREAD

**Issue by johannesschobel** [hyn/multi-tenant#551]
Dear @luceos and community,

before starting of with my "how to" and "best practice" questions, let me start saying "thank you" for this awesome and very inspiring piece of code! :+1: 

I am currently evaluating this framework (i know that there is a spiritual successor "right around the corner") to be used in a project starting in about 3 months.. However, i would like to ask some questions regarding "best practice" and "how to (properly) use" this framework.

## Basic Assumptions
- Please note that the application i am going to develop is a **pure** API, meaning i am only proving data in JSON format. There will be NO user-interface (at least not within my laravel application).
- There will be different clients (e.g., mobile applications and web applications) connected to this API.

### 1) URI Structure
From another project, I developed (although it was not multi-tenancy style), I set up my server (apache) like so:
- `api.example.com` : This subdomain "hosts" the Laravel API
- `www.example.com` : This subdomain "hosts" an Angular application that consumes respective API
I found the "subdomain approach" quite appealing as it allowed for "moving" parts (api / angular client) of the application to different servers and so on.. 

However, what i read about `multi-tenant` so far, is, that it uses subdomains in order to "select" a specific tenant. So my first question would be:
> How would you set up the (sub)domains in this scenario?
I know, that this is most likely some kind of "it depends" answer - but i am very curious about your opinions on this.

I thought about using:
- `api.X.example.com` for the API, and
- `X.example.com` for the web UI (angular, vue, whatever)
where `X` would be the name of the tenant. Basically, in this case you would have 2 subdomains per tenant! (`2n` subdomains in total)

Or would it be better to go for an
- `api.core.example.com` : one single API endpoint for ALL tenants
- `X.example.com` : the UI for the client application
where `X` woul dbe the name of the tenant. This would result in `n+1` subdomains. This would, however, add additional "routing logic" to the API, because you would have one single endpoint to authenticate the user (e.g., `api.core.example.com/login`), which is used for **all** tenants. If the user logs in with his credentials, you would further need to "resolve" the tenant he wants to connect to - because it is not provided via the subdomain.
Possible solutions would be to add a `realm` parameter to the JSON request, or define the username like this : `realm/user` (e.g., `websiteA/admin@example.com`). If you apply `email` validation, however, this would not work, because this is not a valid mail-address..

### 2) Laravel Passport
My previous API uses `Laravel Passport` (for obvious reasons) to authenticate my users at the API.. However, I did not find any documentation on how to properly use `Passport` as authentication mechanism. In https://github.com/tenancy/tenancy/issues/6 @bkintanar quoted that it is currently not implemented / documentated.

### 3) Impersonate (Login as different User)
Is it possible to "login" as a different user? For example, a user has an issue with the developed application - and I, as an administrator - want to "connect" to his instance to reproduce and fix the issue. How (if possible) could something be managed?

### 4) Billing
How would you create a "billing" system based on the tenants? My initial idea (from what i understand so far) would be to add a `expires_at` attribute to the `Website` model and check in an additional `Middleware`, if this `Site` is expired and, therefore, invalid. However, then you would need to handle this "Exception" and re-route the user to a "renew your subscription" system?! Do you have some suggestions on this?

### 5) Different Application Structure
In my previous project, I used a different application structure than Laravel proposes. In my opinion, the Laravel structure becomes quite hard to maintain after a while. The structure, I am using separates the features into different "packages", rather than their "functionality".
For example, my structure looks like this:
```
app\
   Packages\
      Authentication\
      Project\
      User\
```

Further, each "package" itself contains the respective `config`, `migration`, `view`, `translation` files and so on.. This ensures, for example, that each package is self-contained (e.g., you can copy/paste the `Project` package to another package and it should (!) work out-of-the-box without additional configuration effort).

From what i read, the `Tenant Migration` needs to put into `/database/migrations/tenant` folder. However, my migration files are all scattered across the project (e.g., within the `User`, `Project`, ... package). 

---------

I am pretty sure, I will have additional questions regarding "best practice" and integration of this package :laughing: 
Thank you very much for providing answers (even if it is only for some of my questions)!
All the best

**Comment by luceos** [comment]
# URI

> However, what i read about multi-tenant so far, is, that it uses subdomains in order to "select" a specific tenant.

No it does not. It uses Hostnames (any hostname) connected to a Website (tenant). Hostnames identified from the request are auto resolved to a tenant which sets up the environment for multi tenancy.

You can use `api.tenant.your.app` and `tenant.your.app` for instance.

# Laravel passport

This should not be an issue, you have to decide where what lives and from then on most coding logic remains the same. I've heard others implement passport just fine.

# Impersonation

That's is up for you to build. What you have to keep in mind is where your users live, are they system wide or tenant specific. This decision applies to any eloquent model btw.

# Subscriptions

I've heard of people using spark successfully. Using your own subscription methodology should be no problem. You could use a `subscription_valid` flag or something and based on that show a view stating the website/portal is no longer active, allow login and renew subscriptions.

# App structure

Your Domain Driven directory layout is quite common; there's an interesting article that relates to this: https://medium.com/@munza/large-scale-laravel-application-9d52c3d38e51

> From what i read, the Tenant Migration needs to put into /database/migrations/tenant folder. However, my migration files are all scattered across the project (e.g., within the User, Project, ... package).

This is not required. You can put them anywhere you like, just make sure the code that runs migrations whenever a client was created call the migrations explicitly by using the realpath or path options..

---

Hope this helps 😂

**Comment by johannesschobel** [comment]
Hi there...
wow, thank you very much for this in-depth answers on my issues.. This really helps..
Yeah, my application structure is similar to the one in the linked article.. As far as i understood, I have to develop my own "collect all required migration files from my packages" logic, right?

i really like the idea of this package (and most likely the one from tenancy as well).. I think, i really need to play around with this a bit more.. For example, copy / paste my old application and try to integrate your package as well...

All th best

**Comment by luceos** [comment]
> "collect all required migration files from my packages" logic, right?

Yes.

Good luck!
