### ISSUE TITLE
[Hyn\Tenancy\Contracts\CurrentHostname] is not instantiable.

### ISSUE THREAD

**Issue by vireshtripathi** [hyn/multi-tenant#554]
I have install Tenancy and getting error.

    protected function notInstantiable($concrete)
    {
        if (! empty($this->buildStack)) {
            $previous = implode(', ', $this->buildStack);
 
            $message = "Target [$concrete] is not instantiable while building [$previous].";
        } else {
            $message = "Target [$concrete] is not instantiable.";
        }
 
        throw new BindingResolutionException($message);
    }
 

"Target [Hyn\Tenancy\Contracts\CurrentHostname] is not instantiable."

**Comment by luceos** [comment]
Please use the issue template, there are questions we'd like you to answer so that we can help you solve your problem in a time effective way (for you and us). This includes your config, the full backtrace from `/storage/logs/laravel.log` and much more.

Feel free to reopen when provided.

**Comment by vireshtripathi** [comment]
Target [Hyn\Tenancy\Contracts\CurrentHostname] is not instantiable
