### ISSUE TITLE
Functionality to restore soft deleted Website and Hostname

### ISSUE THREAD

**Issue by ametad** [hyn/multi-tenant#559]
__Description of your feature__

After soft deleting a Hostname or Website, it would be nice to be able to restore them. 

---

__Proposed behavior__

Restoring a Website would remove 'deleted_at' in the database. If necessary tenant directory-, tenant database- and virtualhost file(s) are recreated.

The same goes for Hostname.

__Current behavior__

Website and Hostname can be soft deleted, also corresponding database and tenant folder can be configured NOT to be deleted.

This cannot be restored automatically.

---
__Information__

- hyn/multi-tenant version: 5.2.4
- laravel version: 5.6.26

**Comment by luceos** [comment]
Perhaps the recreate command is sufficient?

**Comment by ametad** [comment]
Hi @luceos ,

Thank you for the reply. I am not sure what the recreate command exactly does. 

Would it be possible to remove the `deleted_at` and then run `artisan tenancy:recreate` ?

**Comment by luceos** [comment]
Have you tried soft deleting a website and then sending it through either `create` or `update` in the WebsiteRepository? Did something fail to work?

**Comment by ametad** [comment]
I did not ... Are you saying it already is working perfectly? :wink:

**Comment by ArlonAntonius** [comment]
@ametad It looks like it should yeah.
The create checks if the website already exists, if it does, it updates. So I recommend you to at least give it a try, if it does not work as expected, send us a message.
