### ISSUE TITLE
Option to set website identifier during setup

### ISSUE THREAD

**Issue by thijsvdanker** [hyn/multi-tenant#56]
I need to create two tenants:

 - customer-foo.example.com
 - customer-far.example.com

as the identifier is currently based on the first 10 characters of the domain name, both website ids will be _customer-f_
This will cause the setup to fail as the `websites->identifier` is a unique key in the database.

It would be nice if you could set an identifier during setup.

**Comment by thijsvdanker** [comment]
My current workaround is to use the unique id in the hostname while setting it up, and changing the hostname in the database to the real url after.

e.g.
```bash
sudo php artisan multi-tenant:setup --tenant=Tenant --email=info@example.com --hostname=custom-foo.example.com

mysql -u hyn -p
> UPDATE hostnames SET hostname='customer-foo.example.com' WHERE hostname='custom-foo.example.com';
```

**Comment by Luceos** [comment]
Or maybe the whole way of defining an identifier should be different?
