### ISSUE TITLE
Automatic tenant db switch

### ISSUE THREAD

**Issue by lucadello91** [hyn/multi-tenant#560]
Hi,

I've installed hyn/multi-tenant (v 5.2) on fresh laravel 5.6

I notice that the database connection is not switched automatically to `tenant` when an hostname is recognized.

I need to use both `system` and `tenant` connections.

I haven't the possibility to use Trais within models provided by other thid-party packages.

My solution is to implement a `TenantServiceProvider` that switch on `tenant` connection if an hostname is recognized. 
I put this Service Provider on top of `providers` array within config/app.php.

```
class TenantServiceProvider extends ServiceProvider
{

    public function boot()
    {
        $hostname = app(CurrentHostname::class);
        if ($hostname) {
            /** @var Connection $connection */
            $connection = app(Connection::class);

            Config::set('database.default',$connection->tenantName());
        }
    }
}
```

Shouldn't this switch be managed by hyn/multi-tenant by default?

The `tenant` connection parameters are configured up correctly but this connection is not set as current connection.

**Is correct what i've implemented or hyn/multi-tenant is not working properly?**

Regards

**Comment by steveerg** [comment]
Hi, i've also noticed the same issue and resolved it partially with the tutorial "enforceTenant" middleware on Auth::roles(). 
However, I've also taken for granted that the Hyn package would perform this switch for me, but not.

This is a little lack of clearness within the package docs (or i don't understand the docs at all) or something is broken or not working as expected?

Thank you

**Comment by luceos** [comment]
We don't promote using models which are both for the tenant and system. Because that makes your code harder to understand.

We do allow overriding third party package models using the override functionality, see tenancy.php db, force-tenant-connection-of-models for instance.

Functionality like you propose makes sense inside a Middleware. Perhaps we need to add that.

**Comment by lucadello91** [comment]
Thanks for your explanation

I'll try to fix my models (i thinks is only one at the end, `User`, that exist both on system and tenant connections)

I'll try to split it into two differents models using it into two different auth systems. I've never do it before but I don't think that is complicated (I hope)

For the third party packages i will use tenancy config (I had forgotten that configuration)

I don't know if I prefer to switch connection into a service provider or into a middleware. 
I have to think about it and try it in my application.

Best regards
