### ISSUE TITLE
Unauthorized problems for multitenancy api

### ISSUE THREAD

**Issue by oluomotoso** [hyn/multi-tenant#565]
__Description__
I have been working on Api with this very fantastic package and its been good. Using Tymondesigns/jwt, I have been able to register and get access token for the tenants. However, on attaching the token, I get 401 unathorized
..

---

__Actual behavior__

..

__Expected behavior__

..

---
__Information__

- hyn/multi-tenant version:5.2
- laravel version: 5.6
- database driver and version: 5.7
- webserver software and version:
- php version: 7.1

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by fletch3555** [comment]
Without code, config, or an error stacktrace (doesn't seem applicable to your issue), I'm not sure there's anything we'll be able to suggest.

**Comment by oluomotoso** [comment]
Fixed by changing auth in protected middleware under Http/kernel.php to Tymon/Jwt authenticate class
