### ISSUE TITLE
Schedule queue and avoid overlapping of job

### ISSUE THREAD

**Issue by engineerpros** [hyn/multi-tenant#567]
Lets say we have 2 Jobs
- Job1
- Job2

We have 2 tenants:
- TenantA
- TenantB

We have 2 process running using supervisor
- Laravel_Worker_1
- Laravel_Worker_2

We are using queue driver as datatabase

Now, schedule the queues for tenants, upto this it works fine. But the concern is that we need to avoid overlapping of queues for same jobs for same tenant. 

Ex:
Laravel_Worker_1 is executing JobA for Tenant1 
Now, at the same time Laravel_Worker_2 starts executing the JobA for tenant1 again. However, the JobA by Laravel_Worker_1 is not still complete. Now, there is overlap of same job for same tenant. 

Feature:
Ideally, Laravel_Worker_2 shall not execute the JobA for Tenant1 if Laravel_Worker_1 is already executing this JobA for Tenant1. 

Is this something we could achieve with this package?

**Comment by luceos** [comment]
What you are looking for is [Job Chaining](https://laravel.com/docs/5.6/queues#job-chaining), this feature is available in Laravel. This package adds multi tenancy support, using job chaining with tenancy should add any complications.

**Comment by xyrintech** [comment]
Thanks for your response. 
I am not looking for Job Chaining. 
Rather I want to have something like a queue to handle one tenant with respect to a job. 
Ex. if a JobA with Tenant1 is in queue and in progress then another queue worker shall not start the same JobA for same tenant Tenant!.

**Comment by luceos** [comment]
@xyrintech as long as you run one queue worker there won't be any overlap. You can create queues per tenant if you want, but then you would also need to set up a queue worker per tenant ..

**Comment by xyrintech** [comment]
Setting multiple queue workers will be like wasting too many server resources
