### ISSUE TITLE
[Feature Request] Console command tenancy:run

### ISSUE THREAD

**Issue by athiffau** [hyn/multi-tenant#568]
__Description of your feature__

Version 2.x of Hyn/multi-tenant had a command called _multi-tenant:run_  which could be used to run any artisan command on a specific tenant.

One usage scenario is for confirming tenant specific routes with the artisan _route:list_ command.

---

__Proposed behavior__

For version 5.x of Hyn\Multi-tenant I suggest the command tenancy:run having the following signature:
```
protected $signature = 'tenancy:run {tenantcommand}
        {--tenant= : The tenant(s) to apply on; use all|5,8 }
        {--arguments= : Arguments for the delegated command}
        {--options= : Options to pass on to the delegated command}
    ';
```

__Current behavior__

The feature is currently not supported/implemented.

---
__Information__

- hyn/multi-tenant version: 5.x
- laravel version: 5.6

**Comment by mintunitish** [comment]
@luceos Please look into the PR and suggest changes if required!

**Comment by DeveloperOnCall** [comment]
@mintunitish I too need this (asap) so I merged your code into my versions - problem is, I get errors when using it. 

 **ReflectionException  : Method Hyn\Tenancy\Commands\RunCommand::handle() does not exist**

So I change the method fire() to handle() and am presented with this error:

**Call to undefined method Hyn\Tenancy\Repositories\WebsiteRepository::all()**

I then tried to adapt the code to work within the command I am trying to run and that didn't work either.

Any advice on getting this to work would be most appreciated.

Daniel

**Comment by athiffau** [comment]
I tried the proposed PR and it does not "fully" work.  I had tried to port the 2.x command over as well and pretty much got the same result.

The issue I have is that some routes are missing when running `route:list` via this command.   I am comparing Laravel 5.6 with Hyn 5.1 to Laravel 5.3 with Hyn 2.x and not sure if this is due to Laravel changes.  The problem, I believe, is that with Laravel 5.6, the app isn't fully booted / bootstrapped when artisan runs.

I know that some routes are missing based on 1) the routes being accessible via URL and 2) installing this package: https://github.com/recca0120/laravel-terminal which show all of the routes described below.  

My setup customizes routes in three ways:

1 - conditional statements in routes\web.php
2 - tenant routes in storage\app\tenancy\tenants\XXXX\routes.php
3 - per tenant modules based on https://github.com/caffeinated/modules

Using tenancy:run with the code in this PR, 2 and 3 above are missing.  

These routes are displayed when using the laravel-terminal package.

These routes are displayed when using `multi-tenant:run` Laravel 5.3 + Hyn 2.x

**Comment by athiffau** [comment]
@DeveloperOnCall my hack to make the PR work was:

in RunCommand.php function getWebsitesFromOption():
- change `queryBuilder()` to `query()`

**temporary source hack**
in WebsiteRepository.php add:
```
    public function all()
    {
        return $this->website->all();
    }
```

**OR**
in RunCommand.php
- add `use Hyn\Tenancy\Models\Website;`
- change function getWebsitesFromOption():
  `return $repository->all();` to `return Website::all();`

**Comment by mintunitish** [comment]
@athiffau Is your hack working properly?? I am a little bit confused why the PR isn't working. I will incorporate your changes and will see where it goes. Thanks for the update! My bad for not incorporating tests in the PR.

**Comment by mintunitish** [comment]
I have incorporated the hack that was mention @athiffau . However I am running blind about how to incorporate tests for all the commands that Laravel has for the tenant.

**Comment by athiffau** [comment]
@mintunitish the hack is working as per my initial comment: not all routes are returned with the command `route:list`.  The hack only address issues preventing the PR to execute as intended.

Regarding tests; I'm not sure how to proceed either.

Glad to continue testing as the PR is WIP.  Also glad to contribute in developing tests if some we can come up with some sort of strategy/spec

**Comment by mintunitish** [comment]
Brainstorming on the tests. @luceos any tips?? 🤔

**Comment by luceos** [comment]
@mintunitish I'll take a look at the PR, thank you both for picking this up!

**Comment by luceos** [comment]
I took inspiration from the example PR and added a custom implementation.

It will be in 5.3.0.
