### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by eusouodaniel** [hyn/multi-tenant#569]
With this bundle is it possible to instantiate multiple domains?

**Comment by bkintanar** [comment]
Yes.

--
Bertrand Kintanar
bertrand.kintanar@gmail.com

**Comment by eusouodaniel** [comment]
And how would that be? I have an interface for this, would I save multiple domains in fqdn?

**Comment by bkintanar** [comment]
Yes. Just save multiple domains in fqdn.

--
Bertrand Kintanar
bertrand.kintanar@gmail.com

**Comment by fletch3555** [comment]
@eusouodaniel did you get this working?

In short, you just need to create multiple `Hostname` records, all connected to the same `Website` (or whatever your tenant model is) record.

If you get it working, please close this issue or let us know so we can close it for you.  If you have further issues, please let us know so we can continue to help.

**Comment by luceos** [comment]
Awaiting response, reopen if needed.
