### ISSUE TITLE
Question: Multiple Modules & Migrations

### ISSUE THREAD

**Issue by Nowi5** [hyn/multi-tenant#572]
Hi all,

I have a questions (support request), where do I need to start the enhance the migration command.
I would like to use caffeinated/modules which allow to have multiple migrations sources, this I have to split into normal and tenant related, for sure. But how do I extend the existing migrate command, so that he is also searching for migrations in the subfolders of modules /app/Modules/*/database/migration/*

Thank you for every suggestion.

**Comment by luceos** [comment]
The migrate command provided by this package can take the `realpath` option to point to specific directories. It cannot take multiple of those. The realpath option was added to Laravel itself.

If that doesn't help, I guess the only solution would be to write your own command that provides this functionality.

**Comment by DeveloperOnCall** [comment]
I believe the package ``` caffeinated/modules ``` allows to publish assets - I'd recommend/suggest that the migrations be part of that publish. That those files be published to ``` /database/migrations/tenant ```

Just my 2-cents...
D

**Comment by ArlonAntonius** [comment]
Closing this issue as it's inactive if you still need help please open it up again.
You can always contact us through our channel(s):
- [Discord](https://laravel-tenancy.com/chat)
