### ISSUE TITLE
Pass Data from System to Tenant

### ISSUE THREAD

**Issue by endrureza** [hyn/multi-tenant#573]
I have a case when there is a time system will generate tenant and need to pass some data into that just created tenant. Let's say, customer information like email in system being passed as user authentication data for tenant. 

What kind of solution that will work for such thing ? i mean, perhaps there will be more cases when system will pass data to tenant.

**Comment by luceos** [comment]
Can you explain the flow, either from the perspective of the user or the perspective from the system that describes what you are trying to implement. Although I understand the raw request, I am having a hard time offering suggestions as your explanation is rather vague.

**Comment by endrureza** [comment]
Let me show you a case by procedure

1. Customer registers by inputting information into system
2. System gives invoice to customer to pay for that registration
3. Customer pays the bill
4. System will then generate new tenant with the customer information (in this case: email) as username for authentication in their new tenant

That's the main point of procedure @luceos

**Comment by luceos** [comment]
Once the system receives the payment and marks the invoice payed, you can dispatch a job from the system with the email, stored in a system table somewhere (signups, users, invoice). If you dispatch the Job by setting the tenant correctly you can run queries inside the Job on the Tenant database..

Hope that makes sense 🙏

**Comment by endrureza** [comment]
alright, i'm going try that. I will close the comment, if that works. thanks mister @luceos
