### ISSUE TITLE
Question: Maintance Mode not for admin area.

### ISSUE THREAD

**Issue by Nowi5** [hyn/multi-tenant#575]
Hi,

I would like to allow the tenant admin to de/activate the maintenance mode. The issue is that as soon he activates, he can't deactivate due to the fact that the admin interface isn't reachable, too. How can I extend / overwrite your Middleware/HostnameActions.php?

Thanks for your support.

**Comment by luceos** [comment]
There are several solutions thinkable:

1. Extend the HostnameActions shipped with the package and enable it in your app (disable it in the tenancy.php). Then override the `maintenance` method to do whatever you want.
2. Use another property on the Hostname/Website to identify maintenance mode and built your own implementation.

**Comment by Nowi5** [comment]
Thank you. You are right, the second seems to be the best idea. Due to performance, can I deactivate your middleware easily so that they do not need to check the DB?

**Comment by luceos** [comment]
You can't disable/replace the complete Middleware; I'd gladly accept a PR for it though!

**Comment by Nowi5** [comment]
What should be the goal of the PR?
1. Set a contract for the middleware class and allow to replace the middleware class by config?
2. Allow a whitelist of maintainance mode via config?
3. Allow via config the deactivation of "under_maintenance_since" function?

Without a PR I would just ignore this field, extend the model by my own field and attach a own middleware in addition to the existing one.

**Comment by luceos** [comment]
Check this PR: https://github.com/hyn/multi-tenant/pull/579

**Comment by Nowi5** [comment]
This was quick. So means more or less Option 1, we can replace the middleware. Thank you :-)

**Comment by luceos** [comment]
The PR still needs to be modified and merged. After which a new version has to be released. I'll do so as soon as possible.

**Comment by Nowi5** [comment]
Will do the update soon and let you know. Thanks.

**Comment by luceos** [comment]
Middlewares are now configurable through the tenancy.php configuration file.
