### ISSUE TITLE
Ability to make 3rd party package jobs tenant aware

### ISSUE THREAD

**Issue by Plytas** [hyn/multi-tenant#576]
__Description of your feature__

I'm experimenting with https://github.com/spatie/laravel-medialibrary and they provide an option to generate image conversions through a queue worker. Unfortunately, there is no way to make their jobs tenant aware.

**Comment by luceos** [comment]
See https://github.com/spatie/laravel-medialibrary/pull/377#issuecomment-412487156

**Comment by Plytas** [comment]
This can be closed as my specific issue will be solved. Though I'm wondering if it's actually possible to somehow intercept jobs and add tenant information to them.

**Comment by luceos** [comment]
I'm leaving this open to increase integration with other packages. I'm not sure it's possible, but it's worth a shot.

**Comment by luceos** [comment]
This should be fixed with #711

**Comment by ArlonAntonius** [comment]
We just merged and tagged a new version that includes the feature discussed in this PR:
- Job Auto Tenancy

Also: Spatie's MediaLibrary package allows for overriding their jobs by your own.

If this doesn't actually solve your issue, you can always contact us through our channel(s):
- [Discord](https://laravel-tenancy.com/chat)
