### ISSUE TITLE
Invalid route action: [App\Http\Controllers\Hyn\Tenancy\Controllers\MediaController].

### ISSUE THREAD

**Issue by Nowi5** [hyn/multi-tenant#580]
Following your documentation https://laravel-tenancy.com/docs/hyn/5.2/structure, copy the coding to my web route:

```
Route::get('/media/{path}', \Hyn\Tenancy\Controllers\MediaController::class)
    ->where('path', '.+')
    ->name('tenant.media');
```

Beside the fact that I would recommend system links instead of this controller for performance reason, this throw an error:

> "Invalid route action: [App\Http\Controllers\Hyn\Tenancy\Controllers\MediaController]."

This does not show an error, maybe you like to update your documentation?

```
 Route::get('/media/{path}', '\Hyn\Tenancy\Controllers\MediaController')
     ->where('path', '.+')
     ->name('tenant.media');
```

---
__Information__
- hyn/multi-tenant version:
- laravel version:5.2
- database driver and version:mysql
- webserver software and version:apache
- php version:7.1

**Comment by luceos** [comment]
Feel free to send in a PR 👍
