### ISSUE TITLE
How to get Tenant directory path as string?

### ISSUE THREAD

**Issue by Nowi5** [hyn/multi-tenant#582]
Hi all,

is there any function to get the current Tenant directory base path.
When I use the prefix of the tenancy-directory I just get the /storage/app/tenancy/tenant/ but I miss the UUID. What do you think, should we add some function to the current file system?

I need the path as string a I need to set this as parameter to vendor packages.

Thank you.

---
__Information__

- hyn/multi-tenant version: latest
- laravel version: latest 5.6

**Comment by luceos** [comment]
Try this when a Tenant was identified

```php
app(\Hyn\Tenancy\Website\Directory::class)->path();
```

**Comment by cesarZaabra** [comment]
app(\Hyn\Tenancy\Website\Directory::class)->path();

Return is a boolean and i need the path

**Comment by fletch3555** [comment]
@cesarZaabra, no it doesn't: https://github.com/tenancy/multi-tenant/blob/5.x/src/Website/Directory.php#L78
