### ISSUE TITLE
Add ability to add prefix, namespace and middlewares when registering tenants.php route file

### ISSUE THREAD

**Issue by Plytas** [hyn/multi-tenant#583]
Right now, `routes\tenants.php` is registered as plain file. Would like to be able to register routes file with prefix, namespace and middlewares values set in config. Also I think `App\Http\Controllers` should be set as default namespace as it is in laravel it self.

Looked into it shortly and it seems easily doable. Might submit a PR once I find some time. I'm not sure about tests though.

---
__Information__

- hyn/multi-tenant version: 5.2
- laravel version: 5.6

**Comment by luceos** [comment]
Including the tenants file externally and forcing middleware, namespace, prefix etc make implementation harder. If you want to specify an API route for which the controller lives in `App\Http\Api` or something, you will need to implement your own solution again.

I very much dislike the suggestion, I would consider improved explanations of how to use the file.

@fletch3555 your opinion?

**Comment by Plytas** [comment]
My proposal would still include it the way it is right now, it would only add the parameters from config. It's a simple change in `RouteProvider.php`.

**Comment by Plytas** [comment]
Change like this is what I'm talking about.

```PHP
public function boot()
    {
        /** @var Repository $config */
        $config = $this->app->make(Repository::class);
        $path = $config->get('tenancy.routes.path');
        /** @var Router $router */
        $router = $this->app->make(Router::class);
        if ($path) {
            /** @var Hostname $hostname */
            $hostname = $this->app->make(CurrentHostname::class);
            if ($hostname && file_exists($path)) {
                $this->app->booted(function () use ($config, $router, $path) {
                    if ($config->get('tenancy.routes.replace-global')) {
                        $router->setRoutes(new RouteCollection());
                    }
                    $router->prefix($config->get('tenancy.routes.prefix'))
                        ->namespace($config->get('tenancy.routes.namespace'))
                        ->middleware($config->get('tenancy.routes.middleware'))
                        ->group($path);
                });
            }
        }
    }
```

**Comment by luceos** [comment]
Your solution would limit all routes contained in the tenants.php routes file to the given namespace, middleware and prefix. In case you would like to define both web and api routes you'd still have to do so manually.

I'm not convinced..

**Comment by Plytas** [comment]
I see.. To be fair I would only use namespace option as I am using different middlewares for different groups within the file.
