### ISSUE TITLE
Installed, now what?

### ISSUE THREAD

**Issue by paulcanning** [hyn/multi-tenant#585]
I have followed the installation guide, but now I'm stuck on the next steps.

I've looked through the rest of the docs and cannot find anything outlining how to actually add a new tenant.

I understand that tenant specific files can be added in their own folder in `storage` but how do I go about adding a tenant to the system?

**Comment by fletch3555** [comment]
To add tenants, you would use the Repository classes as noted in our documentation: https://laravel-tenancy.com/docs/hyn/5.2/repositories

**Comment by paulcanning** [comment]
OK, so I need to write a controller to create a site and attach a hostname to it?

Currently, my default web route is broken, why is that and how can I fix it, so I can actually get to a controller of my own?

```
Route::get('/', function () {
    return view('welcome');
}
```

**Comment by luceos** [comment]
You can configure your own controllers any way Laravel supports, check those docs for more information: https://laravel.com/docs/5.6/controllers

**Comment by henk23** [comment]
I'm sorry, but I have to ask again. I have a conroller and in the controller I have the code from https://laravel-tenancy.com/docs/hyn/5.2/repositories, creating a new website.

Now how can I reach this controller? The routes defined in routes/web.php don't seem to work:

    Route::get('/my-route', 'MyController@myAction');

But when I visit localhost:8000/my-route, it just says: "Sorry, the page you are looking for could not be found." - Of course I have no tenants, no websites and no hostnames set up yet. How can you setup your first/default tenant? Can't find anything about this in the docs.

**Comment by luceos** [comment]
@henk23 disable `abort-without-hostname`, please next time create an issue of your own.
