### ISSUE TITLE
Failed to reload Nginx

### ISSUE THREAD

**Issue by paulcanning** [hyn/multi-tenant#586]
Whilst experiencing issues with the nginx config test, I have disabled it in order to try and gain some headway. However, I am now getting a similar issue with reloading nginx.

```
The command "/etc/init.d/nginx reload" failed. Exit Code: 1(General error) Working directory: /home/vagrant/code/2018/multi-app/public Output: ================ Reloading nginx configuration (via systemctl): nginx.service failed! Error Output: ================ Failed to reload nginx.service: Interactive authentication required. See system logs and 'systemctl status nginx.service' for details.
```

**Comment by fletch3555** [comment]
`Interactive authentication required`

Seems it's looking for you to enter credentials when running that command, which obviously you won't be able to do.  This question is really best asked in our Discord chat so we can have quicker dialog.  We can attempt to work on it here if Discord is not an option for you, though I believe it would lead to a faster resolution.

Also, when opening issues here, please make sure to use [the issue template](https://github.com/hyn/multi-tenant/blob/5.x/.github/ISSUE_TEMPLATE/Bug_report.md) we have defined.  It collects most of the information we need to troubleshoot issues, including configs and such.

**Comment by paulcanning** [comment]
So how do I get around the authentication?

**Comment by luceos** [comment]
Answered https://github.com/hyn/multi-tenant/issues/347#issuecomment-414595210

Please stick to this issue from now on 👍

**Comment by paulcanning** [comment]
The issue is this part

> If it works you need to make sure the user running your app has the correct permissions to run the command by itself (eg adding it to the sudoers).

Currently running the app in Homestead, so no idea what to change and if i even should change it.

**Comment by luceos** [comment]
For local environments the best thing to do is use a wildcard subdomain and configure your homestead to accept them in your webserver set up. The webserver integration of this package is best left for the production environment (set up and forget about it).

**Comment by ArlonAntonius** [comment]
Closing this issue as it's inactive if you still need help please open it up again.
You can always contact us through our channel(s):
- [Discord](https://laravel-tenancy.com/chat)

**Comment by bugsworld85** [comment]
In case anyone bumped into this issue, here's how I solved it:
- I made sure `storage/app/tenancy` is owned by `www-data:www-data`
- I added this to `/etc/sudoers`:
`%sudo ALL=(ALL:ALL) NOPASSWD: /etc/inig.d/nginx reload,  NOPASSWD: /etc/init.d/nginx configtest, NOPASSWD: /usr/sbin/service nginx configtest, NOPASSWD: /usr/sbin/service nginx reload`
- In `webserver.php`, add this:
`'test-config' => 'sudo /etc/init.d/nginx configtest', 'reload' => 'sudo /etc/init.d/nginx reload'`

After this, I was able to run `php artisan tenancy:recreate`
This may not be the recommended solution, but it should get you going.
