### ISSUE TITLE
Nginx conf files are generated, but empty

### ISSUE THREAD

**Issue by paulcanning** [hyn/multi-tenant#587]
Possibly related to that fact the nginx configtest and reload commands do not work, but the conf files are being created, but are effectively empty.

I chmod'd the entire `storage` folder to `777` out of desperation, but it doesn't help.

**Comment by fletch3555** [comment]
Please refer to my comment here: https://github.com/hyn/multi-tenant/issues/586#issuecomment-414468579

**Comment by luceos** [comment]
Let's fix one issue at a time to prevent us from trying to solve different issues caused by the same cause.
