### ISSUE TITLE
Nova Tool to Manage Tenants

### ISSUE THREAD

**Issue by bkintanar** [hyn/multi-tenant#590]
__Description of your feature__

A Laravel Nova tool that would sit on the system / admin domain that would allow to manage models/resources across all tenants.

**Comment by balping** [comment]
Well, someone needs to buy Nova first to develop such a thing. And it's not the cheapest thing out there. But the biggest issue with Nova that it's not free/libre software.

**Comment by johannesschobel** [comment]
@bkintanar i would highly appreciate this feature

@balping : this would to be a dedicated (separate) package one could optionally use - this should not be required

**Comment by bkintanar** [comment]
@balping yeah, we have a copy of Nova.

@johannesschobel we'll figure something out in the weeks to come.

**Comment by johannesschobel** [comment]
that would be sooooooooooo awesome! thanks a lot @bkintanar

**Comment by nielsiano** [comment]
Anyone gave it a shot? Looking into doing this.

**Comment by johannesschobel** [comment]
they already started a repo for this: https://github.com/tenancy/hyn-nova
maybe you can contribute..

**Comment by luceos** [comment]
The above repo is pretty much done for system models. I hoped to also add a tenant switcher, but I guess that has to wait for now.

**Comment by SadeghPM** [comment]
Hi, any progress?

**Comment by ArlonAntonius** [comment]
@SadeghPM I don't think we'll do anything else on the Nova repo for now. Our main efforts are focused on T/T. Keep in mind that you can write your own Nova Tool based on our repo in order to get something great working.
