### ISSUE TITLE
Multi tenancy with Laravel Passport

### ISSUE THREAD

**Issue by pedzed** [hyn/multi-tenant#592]
There are basically two scenarios that a developer might stumble upon:

1. Passport must be integrated on system level (e.g. to grant access to tenants)
1. Passport must be integrated on tenant level (i.e. every tenant has its own Passport)

In regards to the first scenario, how can one set up Laravel Passport? 

### Specifically in my case
The system has `licenses` with each license containing a `key` and `mac_address`. If the key and MAC address are matching with the database record and `$license->isActive()`, you should be authenticated.

A `License` belongs to to a `Customer` which belongs to a `Company`, which has one `Tenant`. When and only when you are authenticated (i.e. the license is correct), you must be granted access to the related tenant. How can this be achieved, considering that `License` is not a traditional `User` model with `username` and `password`?

**Comment by luceos** [comment]
Can we make this issue about your specific use case for licenses? Otherwise we will get too much confusion in the long run.

---

Related to your set up, can you explain to me how the key and mac address are sent over? Eg header etc.

**Comment by pedzed** [comment]
> Related to your set up, can you explain to me how the key and mac address are sent over? Eg header etc.

Query string is fine, but I don't mind using headers either.

Something like this:
```
POST https://system.example.com/api/v1/auth?key=ABCDE-ABCDE-ABCDE&mac_address=00:00:00:00:00:00
```

**Comment by luceos** [comment]
What I did on one of my projects create a custom relation to the oauth_access_tokens table. Eg your licenses table could have a `oauth_access_token_id` field relating to licenses. Then once the auth endpoint is hit you can manually generate a token by using the PersonalAccessTokenFactory. Using a middleware you can check the token and set the currently active license.

I can share a snippet on Discord once you accepted the friend request.

**Comment by pedzed** [comment]
I gave up on Passport as it does not feel to be the right solution for my problem. Thanks anyway.

**Comment by johannesschobel** [comment]
Hey @pedzed , maybe you can follow the guide describing the integration of passport with hyn here? https://medium.com/@sadnub/hyn-tenancy-5-2-and-laravel-passport-a0d11c5a08eb

i just stumbled upon it by accident - and the tutorial looks quite extensive.. maybe this does in fact help you (even though you already closed the issue?!)
