### ISSUE TITLE
Barryvdh/laravel-ide-helper

### ISSUE THREAD

**Issue by BenaddiRar** [hyn/multi-tenant#596]
Hi,

There's a way to combine between this package and barryvdh/laravel-ide-helper package.

because for now i cant read from Model with Tenant Connection, and thQs for this great package

**Comment by fletch3555** [comment]
I don't see how that package could conflict with this one in any way.  Could you please further describe the issue you're having? Perhaps add some screenshots?

Also, we have an issue template and ask that you please use it.  It asks for relevant information upfront so we don't have to ask later and delay resolution.

**Comment by BenaddiRar** [comment]
Hi,

If a model use "UsesSystemConnection" : i can run 👍 

## php artisan ide-helper:models

and work fine

but whene a use "UsesTenantConnection"  : 

The result is : 
Exception: Database [tenant] not configured.
Could not analyze class App\Models\Tenant\XXXX.

**Comment by BenaddiRar** [comment]
any update ???

**Comment by Marko298** [comment]
```
class GenerateIdeMeta extends Command
{
    protected $signature = 'ide-helper:all {--tenant=1 : Tenant ID to use while scanning DB}';
    protected $description = 'Runs all ide-helper commands';

    public function handle(Environment $environment)
    {
        $environment->tenant(Website::first());
        Artisan::call('ide-helper:eloquent');
        Artisan::call('ide-helper:generate');
        Artisan::call('ide-helper:meta');
        Artisan::call('ide-helper:models', ['-N' => true]);
        echo Artisan::output();
    }


}
```
I use this walkaround

**Comment by luceos** [comment]
The tenant connection not found error is caused by having no tenant. Although not pretty @Marko298 offers a great solution ;)

**Comment by mepoohsta** [comment]
> 
> 
> The tenant connection not found error is caused by having no tenant. Although not pretty @Marko298 offers a great solution ;)

I'm using this code but it's not working for me :(

> /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle(Environment $environment)
    {
        $environment->tenant(Website::first());
        Artisan::call('ide-helper:eloquent');
        Artisan::call('ide-helper:generate');
        Artisan::call('ide-helper:meta');
        Artisan::call('ide-helper:models', ['--write'=> true]);
        echo Artisan::output();
>     }




> Could not analyze class App\Models\User.

**Comment by Marko298** [comment]
Do you have at least one tenant in db?

**Comment by Marko298** [comment]
> > The tenant connection not found error is caused by having no tenant. Although not pretty @Marko298 offers a great solution ;)
> 
> I'm using this code but it's not working for me :(
> 
> > /**
> > * Execute the console command.
> > *
> > * @return mixed
> > */
> > public function handle(Environment $environment)
> > {
> > $environment->tenant(Website::first());
> > Artisan::call('ide-helper:eloquent');
> > Artisan::call('ide-helper:generate');
> > Artisan::call('ide-helper:meta');
> > Artisan::call('ide-helper:models', ['--write'=> true]);
> > echo Artisan::output();
> > }
> 
> > Could not analyze class App\Models\User.

 Do you have at least one tenant in db?

**Comment by mepoohsta** [comment]
> 
> 
> > > The tenant connection not found error is caused by having no tenant. Although not pretty @Marko298 offers a great solution ;)
> > 
> > 
> > I'm using this code but it's not working for me :(
> > > /**
> > > 
> > > * Execute the console command.
> > > 
> > > * @return mixed
> > >   */
> > >   public function handle(Environment $environment)
> > >   {
> > >   $environment->tenant(Website::first());
> > >   Artisan::call('ide-helper:eloquent');
> > >   Artisan::call('ide-helper:generate');
> > >   Artisan::call('ide-helper:meta');
> > >   Artisan::call('ide-helper:models', ['--write'=> true]);
> > >   echo Artisan::output();
> > >   }
> > 
> > 
> > > Could not analyze class App\Models\User.
> 
> Do you have at least one tenant in db?

Yes. One hostname in hostnames table and one website in websites table. Tenant working when I use it in rest api.

**Comment by mepoohsta** [comment]
Exception: Class 'mixin' not found.
Could not analyze class App\Models\Location.
Exception: Class 'mixin' not found.
Could not analyze class App\Permission.
Exception: Class 'mixin' not found.
Could not analyze class App\Models\Role.
Exception: Class 'mixin' not found.
Could not analyze class App\Models\User.

**Comment by mepoohsta** [comment]
I think it about laravel-ide-helper problem.

**Comment by Marko298** [comment]
> Exception: Class 'mixin' not found.
> Could not analyze class App\Models\Location.
> Exception: Class 'mixin' not found.
> Could not analyze class App\Permission.
> Exception: Class 'mixin' not found.
> Could not analyze class App\Models\Role.
> Exception: Class 'mixin' not found.
> Could not analyze class App\Models\User.

Try to delete @mixin from phpdocs

**Comment by mepoohsta** [comment]
> @mixin



> 
> 
> > Exception: Class 'mixin' not found.
> > Could not analyze class App\Models\Location.
> > Exception: Class 'mixin' not found.
> > Could not analyze class App\Permission.
> > Exception: Class 'mixin' not found.
> > Could not analyze class App\Models\Role.
> > Exception: Class 'mixin' not found.
> > Could not analyze class App\Models\User.
> 
> Try to delete @mixin from phpdocs

I don't have it in my model, but if I adding it i have the same issue :(

**Comment by Marko298** [comment]
> > @mixin
> 
> > > Exception: Class 'mixin' not found.
> > > Could not analyze class App\Models\Location.
> > > Exception: Class 'mixin' not found.
> > > Could not analyze class App\Permission.
> > > Exception: Class 'mixin' not found.
> > > Could not analyze class App\Models\Role.
> > > Exception: Class 'mixin' not found.
> > > Could not analyze class App\Models\User.
> > 
> > 
> > Try to delete @mixin from phpdocs
> 
> I don't have it in my model, but if I adding it i have the same issue :(

You deleted the whole row or just @mixin?

**Comment by Marko298** [comment]
also, try to update ide-helper to the lastest version
