### ISSUE TITLE
multiple tenant migration path

### ISSUE THREAD

**Issue by vortechron** [hyn/multi-tenant#598]
it will be very great if we can do something like this

``` 
"tenant-migrations-path" => [
database_path('migrations/tenant1'), database_path('migrations/tenant2')
]
```

instead of just single path
```
"tenant-migrations-path" => database_path('migrations/tenant'),
```

**Comment by vortechron** [comment]
reason:

my application has mutliple modules in form of laravel package,

i want the developer to have an ability to add their tenant specific migration path in their module ServiceProvider.

**Comment by johannesschobel** [comment]
try using wildcards, e.g., `migrations/tenants/*`.. This should work!

**Comment by vortechron** [comment]
thats not only the case, here another example:

```
"tenant-migrations-path" => [
      database_path('migrations/tenant'), 
      module_path('Shop/Database/migrations')
]

```

**Comment by johannesschobel** [comment]
my migration files were "scattered" across different modules as well.. like: `app/Modules/XXX/Database/Migrations/...` and it worked when setting the `module name` (e.g., `XXX`) as a wildcard..

However, this only works, if all "paths" have the same structure.. In your case above, this does not work, you are right..
