### ISSUE TITLE
I would like to abort non idenfied tenant and igore some subdomain.

### ISSUE THREAD

**Issue by ghost** [hyn/multi-tenant#608]
__Description__

I would like to abort non idenfied tenant and igore some subdomain.

---
__Expected behavior__

I would like something like:

Hyn\Tenancy\Middleware\HostnameActions

```php
    /**
     * @param Request $request
     * @param Closure $next
     * @return RedirectResponse
     */
    public function handle(Request $request, Closure $next)
    {
       
        $hostname  = config('tenancy.hostname.auto-identification')
            ? app(CurrentHostname::class)
            : null;

        if ($this->ignores($request)) {
            return $next($request);
        } else if ($hostname != null) {
            $this->setAppUrl($request, $hostname);

            if ($hostname->under_maintenance_since) {
                return $this->maintenance($hostname);
            }

            if ($hostname->redirect_to) {
                return $this->redirect($hostname);
            }

            if (!$request->secure() && $hostname->force_https) {
                return $this->secure($hostname, $request);
            }
        } else {
            $this->abort($request);
        }

        return $next($request);
    }

    ...

     /**
     * Ignore the subdomain on configuration to the tenant hostname.
     *
     * @param Request  $request
     */
    public function ignores(Request $request)
    {
        $subdomain =  explode('.', $request->getHost())[0];
        $ignores   = config('tenancy.hostname.ignores');

        if (in_array($subdomain, $ignores)) {
            return true;
        }

        return false;
    }
```

---
__tenancy.php config__

```php
     'ignores' => [
            'www', 'api'
        ]
```

**Comment by fletch3555** [comment]
Why not just create Hostname records for `www` and `api`, so it's allowed through the `abort-without-identified-hostname` config?  Then you get what you want.

I would also keep all tenant-specific routes in `routes/tenants.php`, and keep your `www` or `api` routes in `routes/web.php` and `routes/api.php` respectively, but wrapped in a subdomain route group (like below).  Also, enable the `replace-global` config(https://github.com/hyn/multi-tenant/blob/5.x/assets/configs/tenancy.php#L305) so your www/api routes don't conflict with tenant routes.

```
Route::subdomain('www.yourdomainhere.com')->group(function() {
    // your routes here
});
```

**Comment by ghost** [comment]
I can't to do that. I'm using folklore/graphql package and the your routes is in a package provider. I created a middleware and boot on application service provider prepend on laravel middlwares.

**Comment by fletch3555** [comment]
I'm not very familiar with that package.  I'm guessing you want these routes to live under `api`.  It looks like you can simply disable their routes(https://github.com/Folkloreatelier/laravel-graphql/blob/develop/src/config/config.php#L31) and add them manually in your project.  I don't see why this wouldn't work with what I said before.

Just disable routes in that package's config, then `require()` their routes in your subdomain group.  Something like this:
```
Route::subdomain('api.yourdomain.com')->group(function() {
    require('vendor/folklore/graphql/src/Folklore/GraphQL/routes.php');
});
```

Same can be done in your `tenants.php` file if you want it tenant-specific

**Comment by johannesschobel** [comment]
maybe you can register a new custom middleware, that checks for "subdomains to be ignored", BEFORE actually trying to authenticate the user through the tenant middleware? @flaviodevelop 

what do you think?

**Comment by ghost** [comment]
I'd it. I added a ignores field on hostnames in tenancy config file and this data on validator with a not in.
