### ISSUE TITLE
Tenant pointing to System database for password_reset

### ISSUE THREAD

**Issue by nettsite** [hyn/multi-tenant#619]
Hi,

I have installed and configured version 5.2, and it is working well up to logging in to a tenant website.

However, when I test the "Reset Password" bit, I get the following error:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table '**devjd_tenancy**.password_resets' doesn't exist (SQL: delete from `password_resets` where `email` = fred@nettsite.co.za)
```

"devjd_tenancy" is the system database, not the tenant database.

I have modified config/auth.php as follows:

```
'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
            **'connection' => 'tenant',**
        ],
    ],
```

This was suggested elsewhere. 

The "User" model is using "UsesTenantConnection".

Any help would be appreciated.

**Comment by luceos** [comment]
Updating the configuration did not help, you still run into the same error? If so make sure you haven't cached your config `php artisan config:clear`

**Comment by nettsite** [comment]
That was it, thank you. Working like a charm.

**Comment by mikebronner** [comment]
@NettSite Thank you for providing the `password > users > connection` configuration info! That fixed my problem like a charm. :)
