### ISSUE TITLE
Databases on multiple hosts

### ISSUE THREAD

**Issue by eusouodaniel** [hyn/multi-tenant#626]
Hello good afternoon! Would I be able to put the databases on multiple servers, or would it only be on a single host?

**Comment by luceos** [comment]
By using multiple "managing connections" you can put the databases of tenants on any server. The main/global database will remain on the primary system database.

see: https://laravel-tenancy.com/docs/hyn/5.3/creating-tenants#managing-connection

**Comment by marcondesdddi** [comment]
Hi, what file inside the project can I include these settings?

**Comment by luceos** [comment]
You need to configure a second system connection in `config/database.php` and then when creating a website - before sending it to the WebsiteRepository - set the property `managed_by_database_connection` on website to the new/secondary system connection, eg:

```php

$website->managed_by_database_connection = 'system.asia';

app(WebsiteRepository::class)->create($website);
```

The docs should clarify this.

**Comment by marcondesdddi** [comment]
Thank you very much, I will study the documentation.
