### ISSUE TITLE
protect param to make extending possible

### ISSUE THREAD

**Issue by ametad** [hyn/multi-tenant#628]
__Description of your feature__

Make `multi-tenant/src/Database/Connection.php` extendable (some more).
    

---

__Proposed behavior__

```php
    /**
     * @var DatabaseManager
     */
    private $db;
```

Should be

```php
    /**
     * @var DatabaseManager
     */
    protected $db;
```

To make `$this->db` accessible, if I don't overlook the reason why it is private in the first place...

__Current behavior__

In the class extionsion `$this->db` is not accessible.

---
__Information__

- hyn/multi-tenant version: 5.3.0
- laravel version: 5.6

**Comment by luceos** [comment]
Where's the PR? 😊

**Comment by ametad** [comment]
One moment :wink:

**Comment by ametad** [comment]
Thank you!

**Comment by luceos** [comment]
No, Thank you!
