### ISSUE TITLE
Tenants website not working

### ISSUE THREAD

**Issue by chigam** [hyn/multi-tenant#632]
__Description__

Hello! I have installed this package successful and followed this tutorial https://blog.usejournal.com/writing-a-full-featured-multi-tenant-laravel-app-from-scratch-a0e1a7350d9d. I can't get the tenant website working, i don't know if it is a vhost(apache2) issue .
I have left webserver with default settings expect for apache2 enable which is true.
 Any help would be highly appreciated, thanks!

---

__Actual behavior__

..

__Information__

- hyn/multi-tenant version:5.2
- laravel version:5.6
- database driver and version:mysql
- webserver software and version:apache2
- php version:7

---

__tenancy.php config__

```php




```

__webserver.php config__

```php

```

---

__Error log__

Description: Unable to locate the server named "boise1.tenants.blazebytes.com" --- the server does not have a DNS entry. Perhaps there is a misspelling in the server name, or the server no longer exists. Double-check the name and try again.

**Comment by fletch3555** [comment]
Seems to work fine for me: http://boise1.tenants.blazebytes.com/

Perhaps you have a hosts file entry for that domain pointing at the wrong IP?

**Comment by chigam** [comment]
> Seems to work fine for me: http://boise1.tenants.blazebytes.com/
> 
> Perhaps you have a hosts file entry for that domain pointing at the wrong IP?

No, the vhost file is OK. What do u mean it works fine for you?

**Comment by chigam** [comment]
OK sir, seems the DNS propagation was the issue. now it works . Thanks!!!
