### ISSUE TITLE
Tenant Database and Main Database

### ISSUE THREAD

**Issue by harbrinderdebut** [hyn/multi-tenant#635]
I have App/User.php which use Hyn\Tenancy\Traits\UsesTenantConnection, so when my hostname is a tenanat then it authenticates from tenant's database users table.

Now what I want when the host is not a tenant I want to use App/User.php master database's users table not tenant's database users table. How to use one App/User model for both tenant and system database by identify if host tanant or not.

How to achieve this.

Thanks for your help in advance.

**Comment by fletch3555** [comment]
Short answer is "don't".  The best option is to use 2 different models (they're representing different things, right?), "Admin" and "User" (or whatever you'd like to call them).  Give them each the appropriate "Uses___Connection" trait, then update the auth guards to use the right model class at the right time.

Also, we have issue templates for a reason.  They help ensure the correct information is provided as early as possible so we can properly debug issues.  Please use them in the future.
