### ISSUE TITLE
Testing tenant API with laravels built-in functionality

### ISSUE THREAD

**Issue by pascalresch** [hyn/multi-tenant#640]
__Description__
I wanted to write some tests for my tenant API endpoints. In the setup method of the TestCase I'm creating a tenant and after that I'm switching the environment to that. First I test some not API related things, like if a user in the tenant DB is created, or if the tenant database was seeded correctly. These tests pass all. Now I'm testing some API endpoints. Firstly for their response status code.

---

__Actual behavior__
When using Laravels built-in testing functionality like
`$response = $this->json('GET', 'api/test');` 
`$response->assertStatus(200);` 
there is a 404 response.

After a little while of debugging I found out, that the base url of the request was still the default domain, not the tenant one. But even if I overwrite the base url with the correct one of the tenant, it still doesn't work.

---

__Expected behavior__
When hitting the endpoint with guzzlehttp/guzzle everything works fine and I'm getting a 200 status code back. If I create a tenant manually and hit the endpoints with postman everything works fine, too.
So the same should work with Laravels built-in functionality, right?

---
__Information__

- hyn/multi-tenant version: 5.3
- laravel version: 5.7
- database driver and version: mysql 5.7.23
- webserver software and version: nginx
- php version: 7.2.10

**Comment by Sti3bas** [comment]
You should call `boot` method of `RouteProvider` after you set the hostname to register tenant routes, you can find more details in my other comment: https://github.com/hyn/multi-tenant/pull/627#issuecomment-427492644

**Comment by sadnub** [comment]
Check this out.
https://medium.com/@sadnub/laravel-multi-tenant-testing-part-3-a37901054ec6

I was able to get this working a while back and wrote a post about it. I have it working with passport, but it should also work with web auth

**Comment by ArlonAntonius** [comment]
Closing this issue as it's inactive if you still need help please open it up again.
You can always contact us through our channel(s):
- [Discord](https://laravel-tenancy.com/chat)
