### ISSUE TITLE
How to define more tables while creating new tenant

### ISSUE THREAD

**Issue by Akash-laravel** [hyn/multi-tenant#645]
Hi!
I'm creating new tenant using this library which works fine, however i would like to add somewhere in it, to create more tables while creating new tenant. I'm using voyager template in my laravel, but when i'm creating new tenants it doesn't create voyager tables in new tenant database.
any guess or fixes to make it work.
Thanks in advance!

**Comment by bkintanar** [comment]
Hello there,

You need to add the migrations to `/database/migrations/tenant` directory. When creating tenant, hyn reads all the migrations in this directory and migrates the newly created tenant databases with the migration files present in this directory.

**Comment by Akash-laravel** [comment]
> Hello there,
> 
> You need to add the migrations to `/database/migrations/tenant` directory. When creating tenant, hyn reads all the migrations in this directory and migrates the newly created tenant databases with the migration files present in this directory.

You mean i can define more tables here, and it will be created while running migration command?
Also, after adding migrations to suggested directory, do i need to add run any other command?

**Comment by bkintanar** [comment]
Check the `tenancy.php` config file. It reads:

```php
/**
 * The tenant migrations to be run during creation of a tenant. Specify a directory
 * to run the migrations from. If specified these migrations will be executed
 * whenever a new tenant is created.
 *
 * @info set to false to disable auto migrating.
 *
 * @warn this has to be an absolute path, feel free to use helper methods like
 * base_path() or database_path() to set this up.
 */
'tenant-migrations-path' => database_path('migrations/tenant'),
```

**Comment by Akash-laravel** [comment]
> Check the `tenancy.php` config file. It reads:
> 
> ```
> /**
>  * The tenant migrations to be run during creation of a tenant. Specify a directory
>  * to run the migrations from. If specified these migrations will be executed
>  * whenever a new tenant is created.
>  *
>  * @info set to false to disable auto migrating.
>  *
>  * @warn this has to be an absolute path, feel free to use helper methods like
>  * base_path() or database_path() to set this up.
>  */
> 'tenant-migrations-path' => database_path('migrations/tenant'),
> ```

can i define here tables of voyager template?

**Comment by bkintanar** [comment]
@Akash-laravel 	I'm not sure about that.

@fletch3555 care to comment? You've got more experience with Voyager than any of us here. 😄

**Comment by Akash-laravel** [comment]
> @Akash-laravel I'm not sure about that.
> 
> @fletch3555 care to comment? You've got more experience with Voyager than any of us here.

ok, thanks, can you please tell the path and way to define a new migrations to tenant folder. I'm new to laravel and stuck in this problems for days now. If you can paste here the file and path where to add to it. would be great for me. Thanks in advance.

**Comment by luceos** [comment]
> I'm new to laravel

Please read our [requirements](https://laravel-tenancy.com/docs/hyn/5.3/requirements). 

I now this sounds harsh but grasping the full concepts of this package is much, much easier if you know the basics of Laravel properly. As proposed in our docs doing one project with Laravel before jumping on this package will considerably be easier. 

Also I'd rather not see this issue tracker grow into a support tool for  basic Laravel questions. If you need such level of support join our discord and ask in the #coding channel. This issue tracker is for this package, for specific issues in its use and possibly (not preferably) for support questions.

Thank you for your consideration.

**Comment by Akash-laravel** [comment]
@bkintanar thanks, for you help. 
@luceos thanks for the information. When you get into the developement of new framework, it doesn't mean you have to have knowlege of it before, for just to use a library. We develop the system as per the requirements. It doesn't mean that i have to start with basics for a library. Anyways, thanks for your reply.
