### ISSUE TITLE
Add doc for unit testing (phpunit)

### ISSUE THREAD

**Issue by PtyMatt** [hyn/multi-tenant#647]
__Description of your feature__

In the `Tenant Aware` or `Tutorials` section of the [docs](https://laravel-tenancy.com/docs/hyn/5.3/), there should be an article explaining how to make tests "tenant aware".

__Current behavior__

[This complete but outdated tuto (v5.1)](https://medium.com/@ashokgelal/a-full-featured-multi-tenant-app-with-laravel-part-2-unit-tests-96d6dfbf0617) explains very well how to make tests "tenant aware".
But since the `tenancy:install` artisan command no longer exists, this doesn't work anymore.

Issues like #640 or [#627 (comment)](https://github.com/hyn/multi-tenant/pull/627#issuecomment-427492644) doesn't really help me, I'm not an expert of this package nor phpunit config!

__Information__

- hyn/multi-tenant version: 5.3
- laravel version: 5.7
- php: 7.2.11
- MariaDB: 10.2.18

**Comment by PtyMatt** [comment]
@luceos do you have any schedule or milestone for this doc?

I will be willing to give any feedback on it :)

**Comment by luceos** [comment]
> do you have any schedule or milestone for this doc?

Not really no.

Feel free to send in a PR if you want.

**Comment by vpratfr** [comment]
I have something for a start at https://github.com/tenancy/docs/pull/74

Regards,

**Comment by PtyMatt** [comment]
Closing it as this [pull request](https://github.com/tenancy/docs/pull/74) is almost answering what I need :)
