### ISSUE TITLE
Performance and scalability

### ISSUE THREAD

**Issue by pczartoryski** [hyn/multi-tenant#648]
Hi,
First of all - great stuff!
I would like to ask about efficiency when it comes to higher number of instances - e.g. over 2000 - (with low traffic). Does anybody tested what is the limit?
Can anybody tell how this is working in such (big) projects ?
I also did not find an answer to these questions, maybe someone could help:

1. Is there possible to have directory structure something similar like this: storage/app/tenancy/tenants/123/12345 for ID 12345 ? The point is - when you have big amount of accounts - it will be hard to store them in just one directory.

2.  Is it possible to have additional accounts in project (e.g. freemiums) which will not have own subdomains - just sign in on main project domain - and then based on that - load specific tenant configuration ?

Thanks

**Comment by luceos** [comment]
In terms of scalability, hyn currently offers:

- ability to use multiple database servers using the [managing connection](https://laravel-tenancy.com/docs/hyn/5.3/creating-tenants#managing-connection).
- in terms of disk/file system storage, I personally believe that 2000 subdirectories shouldn't be much of a problem as long as you don't try to read a directory list, also read [here](https://serverfault.com/questions/360973/how-does-the-number-of-subdirectories-impact-drive-read-write-performance-on-l) and [here](https://serverfault.com/questions/796665/what-are-the-performance-implications-for-millions-of-files-in-a-modern-file-sys).
- you can roll your own tenant identification, in fact this has been done before by identifying based on path. But consider the pain of supporting it versus just allowing freemiums their own subdomain..

There are several projects running in production already, check the Spotlight section on our homepage.

**Comment by josegus** [comment]
@luceos , first of all, great job with the package. Would be great if developers or companies could send you his own showcases using this package (like meteor does). 

I must admit, at first i didn't trust at all that this package do all that in my application. I searched laravel applications using this package but didn't find one.

**Comment by josegus** [comment]
About this issue, i'm currently facing the same doubt. Any idea how can we generate automatically N numbers of tenants with low effort?

**Comment by luceos** [comment]
Check the spotlight section on the site which mentions a few apps in production or ask on the discord server, plenty of people are already using it.
