### ISSUE TITLE
Relationships between Tenants and System

### ISSUE THREAD

**Issue by chigam** [hyn/multi-tenant#650]
Hello,
I am building an exam system for companies. Each company(tenant) has employees who will do the exams. For security purposes, the exams will be on System database. If a company has paid for the exam, then its employees can do the exam. How do I create a relationship between the Tenant model and the system model for this scenario? Or if there is any other solution to this issue. 
Thanks in advance.

**Comment by bkintanar** [comment]
can you check my comment on [here](https://github.com/tenancy/docs/issues/55#issuecomment-431299085) and see if that'll help.

**Comment by chigam** [comment]
Thanks @bkintanar!
Can u please elaborate more on that example or expand it to my use case as I have not understood it yet!

**Comment by f0reclone** [comment]
This issue should help you figure it out #426 .

**Comment by luceos** [comment]
Indeed it should, thanks @f0reclone
