### ISSUE TITLE
[Question] How to setup the project for monitoring site + tenant sites + main site

### ISSUE THREAD

**Issue by vpratfr** [hyn/multi-tenant#652]
Thanks a lot for the package, this seems to be well thought. I spent already two days playing with it and started to port our current MVP to a multi-tenant approach.

One thing I cannot figure out though : our project will consist in basically 3 parts. 

- http://example.com =  the product website. This would not really need any access to the tenant data and could be considered a separate project. No worries.
- http://acme.example.com = the tenant websites themself. Where our customers find the tools, get billed, etc. This is covered by your package where I have setup subdomain identification + multiple database with your package
- http://admin.example.com = the monitoring / admin / reporting website. This would need to access tenant data. We need to share all models, domain logic, etc. that we develop from the tenant sites. However we do not need any of the tenant features. 

I would like to keep a single project for part 2 and 3. I still cannot figure out how to isolate the admin from other regular tenants.

Would you have any experience regarding this in past projects?

**Comment by bkintanar** [comment]
You could achieve this in number of ways. One of which is that you could add a domain specific routes for the admin and a subdomain route group for the other tenants.

```php
Route::group(['domain' => 'admin.example.com'], function () {
    // Put all your admin routes here.
});

Route::group(['domain' => '{subdomain}.'.config('app.domain')], function () {
    // Put all your tenant routes here.
});
php

**Comment by vpratfr** [comment]
So this part 

    Route::group(['domain' => '{subdomain}.'.config('app.domain')], function () {
        // Put all your tenant routes here.
    });

will pick-up all subdomains but admin, right?

**Comment by bkintanar** [comment]
not really. it will pick up any subdomain, but the previous code block catches the admin subdomain first.

**Comment by vpratfr** [comment]
Thanks for the idea. I will try to setup some minimal code to test this out. Will get back here in case something else pops up.

**Comment by luceos** [comment]
Another way of setting up a global admin site is by adding the hostname to the hostnames table and then use the route group (as @bkintanar points out) to route for that domain only. Nothing else is needed in that situation, because you do not need any immediate auto resolving for tenants. The added benefit is that the domain can no longer be claimed by a tenant.

**Comment by vpratfr** [comment]
Looks good. 

Do you think there would be an easy way to integrate the main website within the same project? (routes which should not match any subdomain)?

**Comment by vpratfr** [comment]
I mean define routes which will not be matched when on a subdomain:

    http://example.com/blog would work

    http://acme.example.com/blog would 404

**Comment by vpratfr** [comment]
Maybe 

    Route::group(array('domain' => 'example.com'), function() {
        // root domain specific route I guess?
    });

**Comment by fletch3555** [comment]
tenant sites (`<tenant>.example.com`): routes in tenants.php, with the appropriate configs set (https://github.com/hyn/multi-tenant/blob/5.x/assets/configs/tenancy.php#L296).

main website (`www.example.com`): routes in web.php, within a `Route::domain()->group()`

admin website (`admin.example.com`): routes in admin.php, within a `Route::domain()->group()`. method added to RouteServiceProvider to handle new route file (mimic others)


Just make sure all exist in the hostnames table and you'll be able to keep this config (https://github.com/hyn/multi-tenant/blob/5.x/assets/configs/tenancy.php#L148) set to `true`.
