### ISSUE TITLE
tenant connection username/password overwritten

### ISSUE THREAD

**Issue by Broutard** [hyn/multi-tenant#655]
__Description__
In my case, each tenant database can be on a different server. 
So, I use `$website->managed_by_database_connection` to point to a specific connection for each website.

It seems it is caused by Hyn\Tenancy\Database\Connection:317
```
$clone['username'] = $clone['database'] = $website->uuid;
$clone['password'] = $this->passwordGenerator->generate($website);
```

If `managed_by_database_connection` is used, why the username/password are overwritten ?! (`auto-create-tenant-database-user=false` in my config).

Moreover, you have miss the master/slave configuration : https://laravel.com/docs/5.7/database#read-and-write-connections

---

__Actual behavior__

When I try to create a new website, the migration failed with a 
```
SQLSTATE[HY000] [1045] Access denied for user 'dev'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = tenant1 and table_name = migrations)
```
note: the user `dev` is my desired user, it is used here because laravel use the `write` configuration.

Dump of my `tenant`connection ($clone) :
```
array:13 [
  "driver" => "mysql"
  "host" => "127.0.0.1"
  "port" => 3306
  "write" => array:2 [
    "username" => "dev"
  ]
  "read" => array:2 [
    "username" => "dev-ro"
  ]
  "sticky" => true
  "database" => "tenant1"
  "password" => "043024691323c4bc453fa7228c25d6e5"
  "charset" => "utf8mb4"
  "collation" => "utf8mb4_unicode_ci"
  "prefix" => ""
  "strict" => true
  "uuid" => "tenant1"
  "username" => "tenant1"
]
```

---
__Information__

- hyn/multi-tenant version: 5.3
- laravel version: 5.6

---

__tenancy.php config__

```php
'auto-create-tenant-database-user' => false,
```
__database.php config__

```php
'tenant1' => [
        'driver' => 'mysql',
        'host' => '127.0.0.1',
        'write' => [
            'username' => 'dev'
            'port' => 3306,
        ],
        'read' => [
            'username' => 'dev-ro'
            'port' => 3307,
         ],
        'sticky'    => true,
        'database' => 'tenant1',
        'password' => 'secret',
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
        'prefix' => '',
        'strict' => true,
    ],
```

**Comment by luceos** [comment]
As explained on discord:

the `managed_by_database_connection` indicates the system connection that manages this tenant database; creates, updates and deletes the tenant database and user. Setting that property on the website model does not imply that the website/tenant will use that connection from then on.

If you want to force a specific connection to be used on the tenant you can listen to the Database\ConfigurationLoading or Database\ConfigurationLoaded events to change the logic, see https://laravel-tenancy.com/docs/hyn/5.3/events#database

Please note that the tenant connection configuration is adopted from the system connection configuration, including read/write information.

**Comment by Broutard** [comment]
@luceos thank you for these clarifications on `managed_by_database_connection` (I've taken that off for now). 

But there is still a migration problem when I set my `system-connection-name` to an exisiting connection configured like this
``` 
'admin' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', ''),
            'write' => [
                'username' => 'dev'
                'port' => 3306,
            ],
            'read' => [
                'username' => 'dev-ro'
                'port' => 3307,
            ],
            'database' => 'admin',
            'password' => env('DB_PASSWORD', 'secret'),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
        ],
```
PS: I have some load-balanced master/slave mysql servers configured with differents port/username.

Try to setup your `system` connection like this (and `auto-create-tenant-database-user=false`), it will failed with an error `Access denied for user ...`

**Comment by Broutard** [comment]
Actually, I think it is due to `auto-create-tenant-database-user=false` and my `tenant-migrations-path`.

When a website is seeded, hyn create the tenant database and try to migrate it with a wrong generated username/password (for the tenant connection) instead of using my default username/password

**Comment by Broutard** [comment]
finally I managed to do what I wanted by adding a listener on `ConfigurationLoaded`

```
public function handle(ConfigurationLoaded $event)
{
    $tenantConnection = config(sprintf(
        'database.connections.%s',
        $event->configuration['uuid']
    ));
    $tenantConnection['uuid'] = $event->configuration['uuid'];

    $event->configuration = $tenantConnection;
}
```

but it's really a problem that it's not natively possible to use an existing connection for each tenant.

**Comment by rubensrocha** [comment]
> finally I managed to do what I wanted by adding a listener on `ConfigurationLoaded`
> 
> ```
> public function handle(ConfigurationLoaded $event)
> {
>     $tenantConnection = config(sprintf(
>         'database.connections.%s',
>         $event->configuration['uuid']
>     ));
>     $tenantConnection['uuid'] = $event->configuration['uuid'];
> 
>     $event->configuration = $tenantConnection;
> }
> ```
> but it's really a problem that it's not natively possible to use an existing connection for each tenant.

Can you tell me how you defined this listener?

**Comment by Broutard** [comment]
@rubensrocha 
You have to add your listener class to your EventServiceProvider like this
```
protected $listen = [
        'Hyn\Tenancy\Events\Database\ConfigurationLoaded' => [
            'App\Listeners\ConfigureTenantDatabase',
        ],
    ];
```

https://laravel.com/docs/5.7/events#registering-events-and-listeners

**Comment by kynetiv** [comment]
Broutard's listener workaround seems fine for artisan commands (migrate, etc), but other times the listener is registered too late (or there is some issue with the EventServiceProvider and TenancyProvider order). See related [#566](https://github.com/hyn/multi-tenant/issues/566#issuecomment-415670494).
