### ISSUE TITLE
php artisan passport:client --password per tenent

### ISSUE THREAD

**Issue by pcfjojo** [hyn/multi-tenant#659]
`php artisan tenancy:run passport:client --option="password=1"  --tenant=1`

I tried to run this command but i run migration for system database instead of tenent.

**Comment by luceos** [comment]
Can you post the exact output when running this command you posted, please append `-vvv` for a full trace. That makes it easier to find a solution.

**Comment by pcfjojo** [comment]
`php artisan tenancy:run passport:client --option="password=1"  --tenant=1 -vvv`

Password grant client created successfully.
Client ID: 19
Client Secret: rxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**it is creates the token in system table instead of tenent 1 database.**

**Comment by vpratfr** [comment]
- Did you publish the migration and stick it in the database/migrations/tenant folder?
- Is there any way to specify the connection to passport (so that it uses the tenant connection instead of system)?

**Comment by d8vjork** [comment]
> * Did you publish the migration and stick it in the database/migrations/tenant folder?
> * Is there any way to specify the connection to passport (so that it uses the tenant connection instead of system)?

[https://laravel.com/docs/master/passport#overriding-default-models](https://laravel.com/docs/master/passport#overriding-default-models)

I think he's trying to say that if is possible to specify the tenant on the Passport commands, but this isn't possible, anyway you can override commands or create your own using the Passport's models (link above).
