### ISSUE TITLE
`GRANT ALL` on Amazon RDS with MariaDB does not work

### ISSUE THREAD

**Issue by mnapoli** [hyn/multi-tenant#660]
**Description**

Creating a new tenant with `auto-create-tenant-database-user = true` does not work on Amazon RDS with MariaDB.

*Per the discussion below it seems this problem only appears with MariaDB, not with MySQL.*

The problem is because the root MySQL user doesn't have `SUPER` privileges (see https://stackoverflow.com/a/44441811/245552).

> You can't grant SUPER privilege on RDS, so you can't use the ALL PRIVILEGES shortcut.
>
> Sorry, you must name the privileges you want to grant explicitly, even if it means listing every privilege except SUPER.

This piece of code fails because of the `GRANT ALL`:

https://github.com/hyn/multi-tenant/blob/37cf25b9810123643aa3f24f6bb9e8420ab13e42/src/Generators/Webserver/Database/Drivers/MariaDB.php#L52

Here is the official RDS documentation mentioning the privilege limits: https://aws.amazon.com/fr/premiumsupport/knowledge-center/duplicate-master-user-mysql/

```
mysql> SHOW GRANTS FOR 'master_user';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'master_user'@'%' IDENTIFIED BY PASSWORD '' WITH GRANT OPTION
```

---

__Actual behavior__

MySQL error.

__Expected behavior__

User is created and has the correct privileges.

---
__Information__

- hyn/multi-tenant version: 5
- laravel version: 5.6
- database driver and version: RDS, MariaDB
- webserver software and version: AWS Lambda / [Bref](https://github.com/mnapoli/bref)
- php version: 7.2

---

**Suggested solution**

I don't think the created users need all those privileges. We could fix this problem and increase security at the same time by listing the privileges actually needed.

**Do you know which privileges we should give the created users?**

In the meantime as a workaround we'll create the users manually with the specific privilege list (as explained [here](https://aws.amazon.com/fr/premiumsupport/knowledge-center/duplicate-master-user-mysql/)).

**Comment by mnapoli** [comment]
Opened #663 with the list of privileges that exist on RDS. We could restrict that list further if you are sure we don't need one of those privileges.

**Comment by kynetiv** [comment]
FWIW, I'm using RDS with MySQL 5.6... Now 5.6 is not supported (so I've learned!), however, I'm able to create a user and `GRANT ALL` with the following command.
```php
return $connection->statement("GRANT ALL ON `{$event->config['database']}`.* TO `{$event->config['username']}`@'{$event->config['host']}' IDENTIFIED BY '{$event->config['password']}'");
```
I'm wondering if perhaps the OP's error was related to a missing/necessary `IDENTIFIED BY` cause?

**Comment by mnapoli** [comment]
@kynetiv thank you for the heads up! It seems the `IDENTIFIED BY` is not present in the code here, do you mean that you are making this package work with AWS RDS? Are you changing anything in the code (are you adding `IDENTIFIED BY` manually)?

ping @HpiGuillaume for information

**Comment by kynetiv** [comment]
@mnapoli Hope I can clarify some. I hooked into the `Hyn\Tenancy\Events\Database\Creating` event to essentially bypass what the MariaDB database driver does to make it work for MySQL 5.6 (5.6 doesn't have `CREATE USER`). Here's a [gist](https://gist.github.com/kynetiv/b16de900a5d1d624b6283bf0d95b169a) of my event listener. I have not looked into it too closely just yet but it my workaround does succeed in creating a user and the database.

This leads me to believe this package's `GRANT ALL` statement may not be working without out the `IDENTIFIED BY` clause. This package separates creating the user and then granting the user permissions in two steps where as my modification does it in one step, which is necessary for MySQL 5.6.

**Comment by ArlonAntonius** [comment]
Can someone verify that this summary is accurate:

> Using an Amazon RDS is not possible without modification
> Amazon RDS is not creating the User with privileges correctly due to the "GRANT ALL" option not being available
> You can fix this by setting the privileges that you can specify in the config

If this is wrong or something is missing, please post it here.

**Comment by kynetiv** [comment]
@ArlonAntonius @mnapoli As I mentioned previously, I was using RDS MySQL 5.6 (not supported by this package) and the modifications I made in an event listener (posted above) allowed me to create a user and GRANT ALL privileges to that user.

Now, I tested a new MySQL 5.7.23 instance on RDS, and have not encountered any issue with creating users and granting them ALL privileges as the package does currently in v5.3.1.

 I'll confirm I have `auto-create-tenant-database` & `auto-create-tenant-database-user` both set to `true`.

 I'm not sure what I'm doing differently but in my experience I'm not having this permissions issue on RDS.

**Comment by HpiGuillaume** [comment]
Hi !
I've re-tested on MariaDB 10.3 (Free Tier AWS)
The same error raise:
```
SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'master_user_rds'@'%' to database 'tenant_my_tenant' (SQL: GRANT ALL ON `tenant_my_tenant`.* TO `tenant_my_tenant`@'%')
```

But when I change the tenancy config with:
```
'tenant-database-user-privileges' => 'SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER', 
```
It's works ;)

with:
-     "laravel/framework": "5.7.*",
-     "hyn/multi-tenant": "5.x-dev",

So for me, It's important to keep this `tenant-database-user-privileges` option in config ;)
Thanks !
G.

**Comment by luceos** [comment]
Not sure if we need a DB driver for AWS RDS here.. It might be a good solution and it allows separation of that configuration..

In the end being able to configure user permissions is already helpful.

**Comment by kynetiv** [comment]
What is interesting here is that the issue appears to be specific to MariaDB on RDS whereas MySQL on RDS is not affected.  After @HpiGuillaume re-test, I did a quick search and came across this [blog post](https://www.culturefoundry.com/cultivate/technology/creating-multiple-database-users-for-maria-db-rds) that also confirms this permissions issue specific to MariaDB on RDS.

Perhaps updating the issue title/description is enough since the configurable permissions is in place already.

**Comment by mnapoli** [comment]
@kynetiv good call! I've updated the title and description, let me know if I made a mistake.

**Comment by arshadasgar** [comment]
@HpiGuillaume I am using 5.3 of multi-tenant and I don't see the config option `tenant-database-user-privileges` anywhere? Could you please help?

**Comment by luceos** [comment]
@arshadasgar that might be part of 5.4:

https://github.com/tenancy/multi-tenant/commit/503d5d8ea776eb2847804aaf563f940ba6e94d08

**Comment by ElijahLynn** [comment]
Somehow this issue came up in my searches for this issue of `GRANT ALL` not working anymore on MariaDB engine 10.5 whereas it does with 10.2 on RDS. 

Dunno why, the user doing the GRANT has the same privileges but something definitely seems up with 10.5 or somewhere in between. It does appear it isn't possible anymore. Also see https://forums.aws.amazon.com/thread.jspa?messageID=950604 for same issue.
