### ISSUE TITLE
Automatically setting the subdomain when calling route(...)

### ISSUE THREAD

**Issue by vpratfr** [hyn/multi-tenant#664]
I have routing for tenants setup like that (in order to not create those routes on the main website):

```
Route::domain('{subdomain}.example.com')
    ->get('/connexion')->name('login.create')->uses('LoginController@create');

// ... and so on
```

When inside a tenant view, I need to generate links to such routes. Using named routes:

```
{{ route('login.create') }}
```

Of course, Laravel complains that a parameter (`subdomain`) is missing. And obviously, I would not like to manually specify the subdomain each time I want to generate a route.

What is the easy way to solve this? Is anything included in the package?

**Comment by fletch3555** [comment]
Why not just use this: https://laravel-tenancy.com/docs/hyn/5.3/fallback#tenant-routes-override? Then set the config to override global routes.

This way, the tenant routes are only loaded when a tenant has been identified (i.e. a `subdomain` exists, but you're not required to make it a route parameter), and your other routes (main site) won't bleed into your tenants.



Also, please use our issue templates.  They help us with troubleshooting your issues by prompting you to enter the necessary information, such as version numbers.

**Comment by vpratfr** [comment]
Because I have some other subdomains and I need route generation to be specific to some domains.

I could solve the issue by subclassing the UrlGenerator and binding it into the container.

Here is a way to automatically fill the subdomain route parameter if someone needs to do that too.

### The custom UrlGenerator class

```
class UrlGenerator extends \Illuminate\Routing\UrlGenerator
{

    public function formatParameters($parameters)
    {
        $parameters = parent::formatParameters($parameters);

        $subdomain = $this->request->route('subdomain', null);
        if (!empty($subdomain) && !\array_has($parameters, 'subdomain'))
        {
            $parameters['subdomain'] = $subdomain;
        }
        else if (app()->environment() === 'testing')
        {
            // There may not be a subdomain available in tests, fake it
            $parameters['subdomain'] = 'testing';
        }

        return $parameters;
    }
}
```

### The code to insert in the RouteServiceProvider

```
    public function boot()
    {
        parent::boot();

        $this->app->bind('url', function () {
            return new UrlGenerator(Route::getRoutes(), app(Request::class));
        });
    }
```
