### ISSUE TITLE
Laravel 5.5 Support

### ISSUE THREAD

**Issue by excel-vba-course** [hyn/multi-tenant#666]
Hi,

I have an existing web app written on L5.5 and not expected to move to L5.6 in the short term - what are my options ofr using Tenancy ? Is there a prior release I can use ? If so, what are the implications ?

Additionally if this is not possible, what would be the main impacted areas of a L5.5 app that would need to be considered to use the current release version ?

Thanks for any and all pointers :-)

Steve

**Comment by luceos** [comment]
The best option is to use laravel shift and do the upgrade to laravel 5.7. Once you stop upgrading it becomes harder with every release. Aside from that this package offers a version that is compliant with 5.5 but aside from security patches isn't actively maintained.

**Comment by excel-vba-course** [comment]
Understood thanks for the input, appreciated.

Steve

**Comment by excel-vba-course** [comment]
Actually, can you please advise on documentation for using version compatibke with L5.5 ? Having trouble locating instructions / documentation.

Thanks in advance
Steve

**Comment by fletch3555** [comment]
simply installing with composer will get the most appropriate version based on your other dependencies.  Then you can see what version was installed and read our docs specific to that version.

**Comment by excel-vba-course** [comment]
Ah ok thanks vm for the assistance 😊

Steve

**Comment by excel-vba-course** [comment]
Hi,

Still have an issue with this. Simply requiring it tries the latest Tenancy package which doesn't work. Have got a screenshot for context but not sure how to upload.

Thanks for continued assistance.

Steve

**Comment by jamby77** [comment]
Hi all, attached the screenshot of simply doing composer `composer require hyn/multi-tenant`
![screenshot](https://user-images.githubusercontent.com/162916/48312546-01ff0200-e5b9-11e8-8c23-42d9605e4ed0.png)
 
```
> php artisan -V                                                           
Laravel Framework 5.5.38
```

**Comment by Sti3bas** [comment]
`5.0.17` is the latest version supporting Laravel 5.5. You can install it with `composer require hyn/multi-tenant:5.0.17`

**Comment by jamby77** [comment]
@Sti3bas thanks, that worked as expected
