### ISSUE TITLE
Multiple Host Names

### ISSUE THREAD

**Issue by sherkhanz** [hyn/multi-tenant#67]
After going through the documentation, I found it quite easy to implement but I have a few issues which I don't understand.

1st  one is what is the purpose of the user created in first step? Should that user be my client who will own the host-name? What else functionality is provided by that specific user table? Or should I do not care at all about that?

2nd one, for multiple host-name configurations, should I use the same user's tenant->id ? and also in other tables, should i derive the tenant id from the user i created in the first step or should I get the id from host-name

Thanks in advance :)

**Comment by sherkhanz** [comment]
Also can i use the same tables but a tenant_id on tables to differentiate host data?

**Comment by Luceos** [comment]
1. The user/email is used for the customer not for a user. These customers are owners of both websites and hostnames. Some customers can have the admin boolean set to be able to do more.
2. Multiple hostnames are possible, they can be property of a customer and can be assigned to different or the same website.
3. You can use one database for multiple tenants, but these tenants are split up using a different table prefix; see [this faq item](https://hyn.readme.io/docs/frequently-asked-questions#section-can-i-use-the-same-database-with-tenants-using-a-prefix-). Using a table column to differentiate in the current package would be too complicated to maintain and isn't in the scope of my target audience who require database differentiation and security.

Hope the above answers your questions, if not please let me know by re-opening.
