### ISSUE TITLE
Laravel 5.7 + Multi-Tenant 3.5

### ISSUE THREAD

**Issue by mauxtin** [hyn/multi-tenant#679]
Does anyone have an empty/dummy installation with Laravel 5.7 and Multi-Tenant 3.5? I am trying to get them to work together but I am constantly having problems with the connections. 

An empty repository with only the very basics would be awesome. The only think similar that I found was this https://github.com/hyn/dummy-tenant-website but it haven't been updated for years. It would be really helpful for people starting to use this package.

Of course there are many guides online but none of the uses the 3.5 version of this package nor Laravel 5.7

**Comment by luceos** [comment]
https://github.com/peartreedigital/boilerplate

and then upgrade to 5.3 if it isn't at that version yet
