### ISSUE TITLE
Run multi-tenant tests on CircleCI 

### ISSUE THREAD

**Issue by mauxtin** [hyn/multi-tenant#690]
I was wondering if someone has already tried running their tests on CircleCI.

I am having difficulties with setting the environment (nginx configurations, users etc) in the container so if someone has a config.yml that works it would be awesome.

**Comment by fletch3555** [comment]
This package already uses CircleCI (https://circleci.com/gh/hyn/multi-tenant), so perhaps you could reference that configuration?

Also, this question is best asked in our Discord chat.  Github is generally reserved for package issues and feature requests.

**Comment by mauxtin** [comment]
Hi @fletch3555, I actually saw that but couldn't find out how the whole subdomain thing works in the official circleci config. 
Maybe I am missing something?
