### ISSUE TITLE
How To Query Tenant Database Without Model

### ISSUE THREAD

**Issue by boldstar** [hyn/multi-tenant#691]
Hyn/Multitenant Version 5.3
Laravel Version 5.7

I would like to know how I can query a Tenants database with out `UsesTenantConnection`. I can succesfully query the system database for the current enviroment and hostname. And if I use the trait `UsesTenantConnection` and query the model on the current connection it works great, but what if I want to query a tabel that doesn't have a model?

For instance I am using passport for authentication and it comes with table migrations but there is not an actual model to apply the `UsesTenantConnection` trait to.

So if wanted to do a query like 
```
$oauth = DB::table('oath_clients')->where('id', 2)->get();
```
How could I do that with out having access to using the trait?

**Comment by boldstar** [comment]
So after playing around in the code some more I realized that I could just wrap the `Route::` that I was accessing in my middleware which made the ability to query the Tenant of that instance. Here is some sample code with a query directly in the api.php route

```
Route::middleware('tenancy.enforce')->get('/oauth', function (Request $request) {
   $passport = DB::table('oauth_clients')->where('id', 2)->first(); 
   return response()->json($passport->secret);
});
```

**Comment by fletch3555** [comment]
Just for the record, you should be able to simplify your query with `DB::table('oauth_clients')->find(2)`

Now for your issue... Why not just use `DB::connection('tenant')`?
