### ISSUE TITLE
What is the best approach for a SASS?

### ISSUE THREAD

**Issue by azeos** [hyn/multi-tenant#696]
First of all merry christmas and thanks for the package.

I'm building an administrative SASS for schools and I'm not quite sure how to use this package.

* Each school should have his own database
* Each school should have his own URL (I'm thinking in subdomains)
* A user should login directly into a school (subdomain)

For example:
* schoolapp.com: the SASS website where we offer the service
* school-name1.schoolapp.com: the login page for the school "School Name1"
* school-name1.schoolapp.com/students: the students list of the school "School Name1"
* school-name2.schoolapp.com: the login page for the school "School Name2"
* school-name2.schoolapp.com/students: the students list of the school "School Name2"
* admin.schoolapp.com: the admin page where we administrate all the schools

I need separated databases for security concerns. Each school will have his own users (teachers, students, etc) and his own assets.

For what I could try, this package creates a database for each _website_ but I need a database per _hostname_.

Will I encounter a problem if I create a _website_ for each school where all the FQDNs will be just subdomains of the same domain?

I've read this questions (#652 & #425), but they are not exactly what I'm looking for.

What do you recommend?

**Comment by fletch3555** [comment]
A website is a tenant.  A website could (but does not need to) have multiple hostnames.  This will still work for your needs.

So far you've described the basic functionality of this package, so yes it'll work fine.  It almost sounds like you're overthinking it a bit.  Have you tried to build anything yet?

**Comment by azeos** [comment]
Thanks for the reply.

Yes, I'm building something, got all the website and hostnames creation working with migrations and seeders. I wasn't sure if having multiple _websites_ with one _hostname_ each was correct.

But you are probably correct, I'm overthinking it. Will continue with the tests.

Thanks again.

**Comment by rabiibrahimi** [comment]
Hi Azeos, 

we are trying to a saas application but iam confused on how to swtich using all these entry points, first when i installed the package i can create new tenant through an artisan command line but when i visit the application base url e.g app.test and try to loggin a tenant it does give me error, database {name} not configured, are you able to give some insight on how to do it, just looking around and could not find anything helpful.

many thanks

**Comment by azeos** [comment]
@RabiCodie I followed this guide [A full-featured multi-tenant app with Laravel](https://medium.com/@ashokgelal/a-full-featured-multi-tenant-app-with-laravel-part-1-4049a3cc229d) and the [docs](https://laravel-tenancy.com/docs/hyn/5.3/installation).

You just create the _system_ DB and everything else is managed by the artisan commands from that guide. Check if a DB is being created when you create a new _website_.
