### ISSUE TITLE
How to setup overrides for config & views?

### ISSUE THREAD

**Issue by londoh** [hyn/multi-tenant#700]
I have a basic test install of multi-tenant 5.3 on L5.6.
Very simple, nothing else installed, no mods or hacks.

I have a console command that will create a tenant/websites and hostnames - this is working ok.
Tenant websites are accessible. Basic display of users, posts etc.from tenant db is working as expected.

I want to use the local disk for tenant storage.
The only config change is that config('tenancy.website.disk') is set to 'local'

Tenant dirs are created correctly eg: storage/app/tenancy/tenants/{uuid}
I have created tenant config and view dirs, and associated config and view files under tenants/{uuid}
These are enabled in tenancy config as per default.

The problem is these override files arent being accessed.

How to enable config/view file overrides please?

(I've seen this related issue: https://github.com/hyn/multi-tenant/issues/454 )

tenancy.php
```<?php
use Hyn\Tenancy\Database\Connection;
return [
    'models' => [
        // Must implement \Hyn\Tenancy\Contracts\Hostname
        'hostname' => \Hyn\Tenancy\Models\Hostname::class,
        // Must implement \Hyn\Tenancy\Contracts\Website
        'website' => \Hyn\Tenancy\Models\Website::class
    ],
    'middleware' => [
        // The eager identification middleware.
        \Hyn\Tenancy\Middleware\EagerIdentification::class,
        // The hostname actions middleware (redirects, https, maintenance).
        \Hyn\Tenancy\Middleware\HostnameActions::class,
    ],
    'website' => [
        'disable-random-id' => false,
        'random-id-generator' => Hyn\Tenancy\Generators\Uuid\ShaGenerator::class,
        'uuid-limit-length-to-32' => env('LIMIT_UUID_LENGTH_32', false),
        'disk' => 'local',
        'auto-create-tenant-directory' => true,
        'auto-rename-tenant-directory' => true,
        'auto-delete-tenant-directory' => false,
        'cache' => 10,
    ],
    'hostname' => [
        'default' => env('TENANCY_DEFAULT_HOSTNAME'),
        'auto-identification' => env('TENANCY_AUTO_HOSTNAME_IDENTIFICATION', true),
        'early-identification' => env('TENANCY_EARLY_IDENTIFICATION', true),
        'abort-without-identified-hostname' => env('TENANCY_ABORT_WITHOUT_HOSTNAME', false),
        'cache' => 10,
        'update-app-url' => false,
    ],
    'db' => [
        'default' => env('TENANCY_DEFAULT_CONNECTION'),
        'system-connection-name' => env('TENANCY_SYSTEM_CONNECTION_NAME', Connection::DEFAULT_SYSTEM_NAME),
        'tenant-connection-name' => env('TENANCY_TENANT_CONNECTION_NAME', Connection::DEFAULT_TENANT_NAME),
        'tenant-division-mode' => env('TENANCY_DATABASE_DIVISION_MODE', 'database'),
        'password-generator' => Hyn\Tenancy\Generators\Database\DefaultPasswordGenerator::class,
        'tenant-migrations-path' => database_path('migrations/tenant'),
        'tenant-seed-class' => false,
        'auto-create-tenant-database' => true,
        'auto-create-tenant-database-user' => true,
        'auto-rename-tenant-database' => true,
        'auto-delete-tenant-database' => env('TENANCY_DATABASE_AUTO_DELETE', false),
        'auto-delete-tenant-database-user' => env('TENANCY_DATABASE_AUTO_DELETE_USER', false),
        'force-tenant-connection-of-models' => [
//            App\User::class
        ],
        'force-system-connection-of-models' => [
//            App\User::class
        ],
    ],
    'routes' => [
        'path' => base_path('routes/tenants.php'),
        'replace-global' => false,
    ],
    'folders' => [
        'config' => [
            'enabled' => true,
            'blacklist' => ['database', 'tenancy', 'webserver'],
        ],
        'routes' => [
            'enabled' => true,
            'prefix' => null,
        ],
        'trans' => [
            'enabled' => true,
            'override-global' => true,
            'namespace' => 'tenant',
        ],
        'vendor' => [
            'enabled' => true,
        ],
        'media' => [
            'enabled' => true,
        ],
        'views' => [
            'enabled' => true,
            'namespace' => null,
            'override-global' => true,
        ]
    ]
];

**Comment by fletch3555** [comment]
I'm just going to render a guess, since I've spent a grand total of 30 seconds on this... But config and views can both be cached, so my guess would be that the cache is blocking it.  Try clearing the config and view caches, then access that page directly on that tenant (i.e. don't give it the opportunity to cache that page from another tenant first)

**Comment by londoh** [comment]
thanks very much for reply and (educated) guess.
I should have mentioned that I've tried already clearing all caches/compiled/anything. This makes no difference

Also: I was just going to post an update that I remembered I have a console command that runs under tenancy:run and which pulls info from config files in tenancy/tenant/{uuid} perfectly well.

So there must be some discrepancy somewhere.

Typically when using  a local disk what should tenancy.website.disk be set to?
I have it set to 'local' - which is as per laravel default. Should that work ok?
Otherwise what does that filesystem. config entry need to look like?
Does it need a separate 'tenant' entry to set root to tenancy/tenant?

**Comment by londoh** [comment]
OK so, if I set filesystems config like this:
```
    'disks' => [
        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],
      ...
        'tenant' => [
            'driver' => 'local',
            'root' => storage_path('app/tenancy/tenants'),
        ],
    ],
```
And set tenancy.website disk to 'tenant' it works! yay! - In this test install, which I setup to resolve/debug this issue.

However, in the main project I am working on I have spatie.media-library installed 
This has the media dir setup as per hyn/multitenant spatie docs and is(was) working ok

But with that filesystem/disk option it starts throwing an error when resolving urls:
> Storage path `/home/londoh/.../laravel/storage/app/tenancy/tenants` is not part of public path

doh!

**Comment by londoh** [comment]
closed. Issue was due to config error causing incorrect resolution of tenant.

**Comment by Muetze42** [comment]
> closed. Issue was due to config error causing incorrect resolution of tenant.

It's still not working for me. I'm still getting reports that it's not public property. What setting did you change?

**Comment by londoh** [comment]
I'm sorry friend but that was a year ago and I honestly cant remember, I did get it working and its still functioning well. 
If you don't find a quick or easy solution I'd suggest opening up your own issue with info as requested. The devs on this project are very knowledgeable and responsive.

regards
l.
