### ISSUE TITLE
DB::table problem

### ISSUE THREAD

**Issue by yassinino** [hyn/multi-tenant#701]
Hi everyone,

when i use DB::table, laravel tenancy don't know the table in database , can you help me please ?

thank you

**Comment by luceos** [comment]
`DB::connection('tenant')`

This is documented on the laravel docs.

**Comment by yassinino** [comment]
ss

**Comment by yassinino** [comment]
i dont understand :/

**Comment by fletch3555** [comment]
You have to explicitly tell it what connection to use.  Instead of `DB::table(...)->......`, you would use `DB::connection('tenant')->table(...)->......`
