### ISSUE TITLE
Nova image wrong path

### ISSUE THREAD

**Issue by mauxtin** [hyn/multi-tenant#702]
I have a problem when using the Image field in Nova. 

filesystems.php
```
'stores' => [
     'driver' => 'local',
     'root'   => storage_path('app'.DIRECTORY_SEPARATOR.'stores'),
],
```

tenancy.php
```
'disk' => 'stores',
```

Using this field:
```
 Image::make('Image', 'image', 'tenant'),
```

I can store the image successfully in the correct directory (e.g. storage\app\stores\19ebee220e8d45b2a35ef3226565a80a\image.jpg) but the generated path for the image and thumbnail are wrong when viewed in nova.

By inspecting the nova request I can see the paths to be
![image](https://user-images.githubusercontent.com/40521145/51090782-3e520880-178a-11e9-893b-d239c210fe70.png)

which are wrong. (The correct form should have included the store uuid, right?)

Any suggestions on what is going wrong here?

**Comment by luceos** [comment]
Looks like it is not using the correct disk.. Have you tried in the stores disk configuration to add another slash at the end?

**Comment by mauxtin** [comment]
I just tried with a slash at the end but nothing changed.

```
'stores' => [
     'driver' => 'local',
     'root'   => storage_path('app'.DIRECTORY_SEPARATOR.'stores'.DIRECTORY_SEPARATOR),
],
```

Anything else I could try?

**Comment by mauxtin** [comment]
For the record, I solved this by using `resolveUsing`.
```
Image::make('Image', 'image', 'tenant')->resolveUsing(function($filename) {
   return 'stores/'.\Hyn\Tenancy\Facades\TenancyFacade::website()->uuid.'/'.$filename;
}),
```

I will however leave this open till a proper solution is found.

**Comment by luceos** [comment]
Looks like we might need to set the `url` key on the disk when it's marked to be public, not sure if we're even able to do so. In the meantime you can manually set the url key by listening to the Identified event.

https://laravel.com/docs/5.7/filesystem#file-urls

**Comment by ArlonAntonius** [comment]
I hope you were able to fix this issue yourself, if not, please let us know.
