### ISSUE TITLE
Tests in PHPUnit

### ISSUE THREAD

**Issue by eusouodaniel** [hyn/multi-tenant#705]
Hello!

I'm developing a multi tenant application and I can not create automated tests for it, I'm having difficulties running the migrations on the tenant. I'm using PHPUnit

**Comment by Sti3bas** [comment]
Check https://github.com/hyn/multi-tenant/pull/627 and https://github.com/hyn/multi-tenant/pull/656 PRs.

**Comment by marcondesdddi** [comment]
@Sti3bas hi, as I am new to this world, could you give an example, I say TenantAwareTestCase and a Feature test? In my case I need to access a route from the tenant, but before I need to create one for later I access this route with logged in user.
Thank you very much.

**Comment by marcondesdddi** [comment]
SqliteDriver.php

<?php

namespace Tests\Support;

use Hyn\Tenancy\Contracts\Webserver\DatabaseGenerator;

class SqliteDriver implements DatabaseGenerator
{
    public function created(Created $event, array $config, Connection $connection) : bool
    {
        return true;
    }

    public function updated(Updated $event, array $config, Connection $connection) : bool
    {
        return true;
    }

    public function deleted(Deleted $event, array $config, Connection $connection) : bool
    {
        return true;
    }
}

<?php

namespace Tests;

use Tests\TestCase;
use Tests\Support\SqliteDriver;
use Hyn\Tenancy\Models\Website;
use Hyn\Tenancy\Repositories\WebsiteRepository;
use Hyn\Tenancy\Models\Hostname;
use Hyn\Tenancy\Contracts\Repositories\HostnameRepository;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Hyn\Tenancy\Providers\Tenants\RouteProvider;
use Hyn\Tenancy\Contracts\CurrentHostname;

TenantAwaretestCase.php
class TenantAwaretestCase extends TestCase
{
    use RefreshDatabase;

    protected $hostname = 'app.lms.local';

    public function setUp()
    {
        parent::setUp();

        app('tenancy.db.drivers')->put('sqlite', SqliteDriver::class);

        config(['tenancy.db.tenant-division-mode' => 'bypass']);

        $website = new Website;
        app(WebsiteRepository::class)->create($website);

        $hostname = new Hostname;
        $hostname->fqdn = $this->hostname;
        $hostname = app(HostnameRepository::class)->create($hostname);
        app(HostnameRepository::class)->attach($hostname, $website);

        app()->singleton(CurrentHostname::class, function () use ($hostname) {
            return $hostname;
        });

        (new RouteProvider(app()))->boot();
    }
}

HomeTest.php
<?php

namespace Tests\Feature;

use Tests\TenantAwareTestCase;

class HomeTest extends TenantAwareTestCase
{
    /** @test */
    public function it_works_with_tenant_routes()
    {
        $this->get('/tenant')
            ->assertStatus(200)
            ->assertSee('Tenant');
    }

    /** @test */
    public function it_works_with_global_routes()
    {
        $this->get('/global')
            ->assertStatus(200)
            ->assertSee('Global');
    }
}

Error run phpunit:
Fatal error: Declaration of Tests\Support\SqliteDriver::created(Tests\Support\Created $event, array $config, Tests\Support\Connection $connection): bool must be compatible with Hyn\Tenancy\Contracts\Webserver\DatabaseGenerator::created(Hyn\Tenancy\Events\Websites\Created $event, array $config, Hyn\Tenancy\Database\Connection $connection): bool in /var/www/html/tests/Support/SqliteDriver.php on line 7

**Comment by Sti3bas** [comment]
@marcondesdddi import the classes:

```php
use Hyn\Tenancy\Database\Connection;
use Hyn\Tenancy\Events\Websites\Created;
use Hyn\Tenancy\Events\Websites\Deleted;
use Hyn\Tenancy\Events\Websites\Updated;
```

**Comment by marcondesdddi** [comment]
@Sti3bas thanks for answering. Now another migration error has occurred.

Fatal error: Cannot declare class CreateUsersTable, because the name is already in use in /var/www/html/database/migrations/tenant/2014_10_12_000000_create_users_table.php on line 39

I have to create the User table for both System and Tenant.

**Comment by Sti3bas** [comment]
@marcondesdddi that's because system and tenant migrations are in the same global space, so you can't have duplicate class names. Just rename your tenant migration to e.g. `CreateTenantUsersTable`.
