### ISSUE TITLE
Media alias not working on localhost Mamp

### ISSUE THREAD

**Issue by Krato** [hyn/multi-tenant#71]
Hi, I'm just testing your awesome package, but get some problems to run on localhost with MAMP on my MAC.

I follow all instructions, and tenant connection with DB is working right. But `media`folder alias doesn't work.

I have this structure on `storage/sites`:

```
* site1
  * media
    * image.jpg
* site2
  * media
    * image.jpg
```

And this is my apache webserver conf for site 1:

```config
#
#   Auto generated Apache configuration
#       @time: 15:20:16 12-05-2016
#       @author: hyn-me/webserver
#       @website: 1 "starter-on"
#

#
#   Hostnames with certificate
#

#
#   Hostnames without certificate
#
    <VirtualHost *:80>
            ServerAdmin webmaster@starter.on
    
                                        ServerName starter.on
                        
    # public path, serving content
    DocumentRoot /Applications/MAMP/htdocs/tenant/public
    # default document handling
    DirectoryIndex index.html index.php

    
            # media directory
        alias "/media/" "/Applications/MAMP/htdocs/tenant/storage/sites/1-starter-on/media/"
    
    # allow cross domain loading of resources
    Header set Access-Control-Allow-Origin "*"

    # logging
    ErrorLog /Applications/MAMP/htdocs/tenant/storage/logs/apache-1-starter-on.error.log
    CustomLog /Applications/MAMP/htdocs/tenant/storage/logs/apache-1-starter-on.access.log combined
</VirtualHost>




<Directory "/Applications/MAMP/htdocs/tenant">
    Options Indexes Includes FollowSymLinks  
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>
```

And this is for site2:
```conf
#
#   Auto generated Apache configuration
#       @time: 15:20:16 12-05-2016
#       @author: hyn-me/webserver
#       @website: 2 "prueba"
#

#
#   Hostnames with certificate
#

#
#   Hostnames without certificate
#
    <VirtualHost *:80>
            ServerAdmin webmaster@prueba.on
    
                                        ServerName prueba.on
                        
    # public path, serving content
    DocumentRoot /Applications/MAMP/htdocs/tenant/public
    # default document handling
    DirectoryIndex index.html index.php

    
            # media directory
        alias "/media/" "/Applications/MAMP/htdocs/tenant/storage/sites/2-prueba/media/"
    
    # allow cross domain loading of resources
    Header set Access-Control-Allow-Origin "*"

    # logging
    ErrorLog /Applications/MAMP/htdocs/tenant/storage/logs/apache-2-prueba.error.log
    CustomLog /Applications/MAMP/htdocs/tenant/storage/logs/apache-2-prueba.access.log combined
</VirtualHost>




<Directory "/Applications/MAMP/htdocs/tenant">
    Options Indexes Includes FollowSymLinks  
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>
```

The problem is that always get first media alias.

If I visit: `http://starter.on/media/a.jpg` I get first site photo. This is ok.

But if I visit `http://prueba.on/media/a.jpg`it returns same photo of site1.

Please, how can I fix it?

Thanks

**Comment by Luceos** [comment]
I'm not seeing anything wrong in the code snippets you provide. I guess you're sure the images are not identical? :grin:

**Comment by Krato** [comment]
Sure mate. Are not the same. But I don't know why Is not working. I'm a little bit frustrated :(

**Comment by Luceos** [comment]
> I need to add this to my hosts file yes?

If you're running your application locally, that might be the case, but it depends on the OS you run on. But you seem to hit the application, so it should be fine.

Some things we could do to debug:

- Try creating a third tenant site and add another image, check which image file it hits now.
- Try renaming the image file so they are not identical.

I understand the frustration, this package is a complex whole, so please have some patience. We'll work towards a solution.

**Comment by Luceos** [comment]
Browsing through some Mamp related alias issues I wouldn't be surprised if the Alias directive is badly implemented in Mamp.

**Comment by Krato** [comment]
Ok, thanks. I'm installing a Virtual Machine with Ubuntu in my MAC for testing. I will give you feedback about this issue.

Just a question. Did you thing about add a custom `.env`file for each tenant?

Thanks for this amazing package.

**Comment by Luceos** [comment]
That actually crossed my mind, but I wondered how that would look if you had 200 of them :grinning:

**Comment by Krato** [comment]
Yes, but if you need some configuration you need to create config files inside each tenant config folder. So, is the same not?

**Comment by Luceos** [comment]
I could allow env files to be read from the tenant directory. If you want that feature, feel free to open an issue ;)

**Comment by Krato** [comment]
Well about this topic I found a little solution. If I merge all conf files in one config file and call from `httpd.conf`, alias works fine. So I think I will do that while working on localhost.

**Comment by Luceos** [comment]
I'm unsure whether this is a package issue, it certainly has to do with Apache and MAMP in that sense. If this issue arises outside of a localhost environment onto a production environment I'll consider further investigation.
