### ISSUE TITLE
How to setup php-sock to connect to ip and port?

### ISSUE THREAD

**Issue by albertosgz** [hyn/multi-tenant#714]
Hi.

How can I setup config/webserver.php in laravel to connect to php-fpm by TCP socket instead of unix socket as you suggests?
In my case, I'm using laradock, which keeps nginx and php-fpm in separate docker containers, so (if I'm not wrong), botch process are in separate networks.
The line `include <path>/*.conf;` in nginx.conf is already setup.

Regards.

**Comment by luceos** [comment]
Inside webserver.php change `php-sock` to point to the listen address you configured in php-fpm, eg:

`127.0.0.1:9000`

This should work without any other change. Love to hear whether you run into any issues with this.

**Comment by albertosgz** [comment]
Hi. I try but it didn't work.
Bu tit looks like event try to reload nginx or something similiar. For example, the nginx configuration file for the new website, the vvhost.conf, is not created.
Do you know a way to log the library to check out if is working properly or I am missing an step?
Thank you.

**Comment by luceos** [comment]
Have you configured the other options in the webserver.php configuration?

**Comment by albertosgz** [comment]
I'm using the default configuration that comes with the package, and
changing only the socket to localhost:9000

**Comment by luceos** [comment]
If I'm not mistaken `localhost` in Linux will first try to use the sock before trying TCP sock, use `127.0.0.1`

**Comment by albertosgz** [comment]
I see that the base URL, i.e.: `laravel.test`, is getting a 404 by nginx access logs, but browsing my tenant url, i.e.: `demo.laravel.test`, nothing is logging, in fact I've received a 404 error fron nginx,not from laravel.
I'm afraid of I'm not generating the necessary vhost file for nginx, even before to try to reload the nginx by the package itself (I supposed it is how the library works to take into accout the new tenant), because there is no vhost file at all in the `storage/app/tenancy/webserver/nginx` folder (according the [documentation web, nginx section](https://laravel-tenancy.com/docs/hyn/5.3/nginx)).
There is a point in which I can logging?

**Comment by albertosgz** [comment]
OMG I've found out the problem!!!!! I had to setup the nginx configuration to `true`!!!! No way!!!! 
Now I have another issue, which can't find the nginx process since it is in another container, but that is another problem.
Thanks a lot for your time @luceos
