### ISSUE TITLE
Change or remove tenant

### ISSUE THREAD

**Issue by ayman-elmalah** [hyn/multi-tenant#717]
How to remove or change tenant host name

**Comment by ArlonAntonius** [comment]
@ayman-elmalah What you can do is simply delete the Hostname or edit it?
The default models used are just [Eloquent Models](https://laravel.com/docs/5.7/eloquent) so you can use basic [Eloquent queries](https://laravel.com/docs/5.7/eloquent#updates) on them.

You can find the models by looking at your config:
config/tenancy.php

**Comment by ayman-elmalah** [comment]
I know, but i just asked for package function to do that

**Comment by ArlonAntonius** [comment]
Well, we don't really need to provide that as Eloquent simply provides that?
What you can do though is use the HostnameRepository in order to update your hostnames.

**Comment by luceos** [comment]
You can load the hostname model you want to change and then update the `fqdn` field. Once you changed that property, use the HostnameRepository::update method to trigger necessary cache flushes etc.

There's nothing else to it. Don't overthink it ;)

**Comment by ayman-elmalah** [comment]
So when i update the hostname, how can i tell server to add it at hosts to make the host watch the domain ?

**Comment by ArlonAntonius** [comment]
@ayman-elmalah What exactly do you mean?
