### ISSUE TITLE
Artisan commands to create tenants

### ISSUE THREAD

**Issue by ametad** [hyn/multi-tenant#719]
__Description of your feature__

[![asciicast](https://asciinema.org/a/jStpBaiWAO1apY86SjCJ9UDuz.svg)](https://asciinema.org/a/jStpBaiWAO1apY86SjCJ9UDuz)

---

__Proposed behavior__

Create Website- and Hostname instances for tenants.

__Current behavior__

Currently there are no artisan commands to create tenants.

---
__Information__

- hyn/multi-tenant version: 5.3
- laravel version: 5.7

**Comment by luceos** [comment]
It's not part of this package and we're not going to offer that because functionality for everyone is different.

**Comment by ametad** [comment]
It can be potential getting in the way of loose coupling, I understand. 

Some time ago I thought I have seen some questions from within the Tenancy community about a demo app, to see how it all could work together. Could [this project](https://github.com/ametad/laravel-app-multi-tenant-demo) be shared to who wants to see Tenancy in action?

**Comment by ArlonAntonius** [comment]
@ametad I don't think it's smart to provide a repo demo that we don't own ourselves.
I appreciate the effort, just not a smart move.

**Comment by ametad** [comment]
"Recht door zee", I like that :)
