### ISSUE TITLE
Define which routes shouldn't be flushed

### ISSUE THREAD

**Issue by josegus** [hyn/multi-tenant#720]
__Description of your feature__

Hability to set which routes should be flushed ("replace-global"), because this remove routes used by laravel-debugbar. I haven't try other request interceptors (like laravel telescope o clockwork), but i think the result is the same. 

---

__Proposed behavior__

Set a key in tenancy.php with an array of route files that shouldn't be flushed.

__Current behavior__

The "replace-global" value in tenancy.php replace ALL other routes in the app.

---
__Information__

- hyn/multi-tenant version: 5.3
- laravel version: 5.7

**Comment by luceos** [comment]
Can't you create a shared routes file that both the web.php and tenant.php routes file load?

**Comment by josegus** [comment]
> Can't you create a shared routes file that both the web.php and tenant.php routes file load?

Yes, I can, I've already solve my problem.

What I was trying to say is that enabling "replace-global" in tenancy.php make all other routes not available (like routes from laravel-debugbar).

Please close this issue if you think this is unnecesary
