### ISSUE TITLE
Permission denied to create a FK on schema (postgresql)

### ISSUE THREAD

**Issue by zarpelon** [hyn/multi-tenant#721]
**Description:** 

When creating a new schema in the database (postgresql), the package creates a database user and assigns the privileges to that new schema, a new schema, and applies the migrations. The problem is that if I have some foreign key relationship with the public schema, that user does not have permission, generating a denied permission error.

**Actual behavior:**

Today I have this method on Hyn\Tenancy\Generators\Webserver\Database\Drivers\PostgresSchema;

```
    protected function grantPrivileges(IlluminateConnection $connection, array $config)
    {
            return $connection->statement("GRANT ALL PRIVILEGES ON SCHEMA \"{$config['schema']}\" TO \"{$config['username']}\"");
 
    }
```

**Expected behavior:** 

What I had to do temporarily to fix the problem:

`    protected function grantPrivileges(IlluminateConnection $connection, array $config)
    {
       
        if ($connection->statement("GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO \"{$config['username']}\"")) {
            $connection->statement("GRANT ALL PRIVILEGES ON SCHEMA \"{$config['schema']}\" TO \"{$config['username']}\"");
            return $connection->statement("REVOKE ALL PRIVILEGES ON SCHEMA public FROM \"{$config['username']}\"");
        }
    }
` 
..

---
__Information__

- hyn/multi-tenant version: 5.3 
- laravel version: 5.7
- database driver and version: pgsql / PostgreSQL 11.2
- webserver software and version: Apache 2.4
- php version: 7.3

---

__tenancy.php config__

        'tenant-division-mode' => env('TENANCY_DATABASE_DIVISION_MODE', 'schema'),

```php

```

__webserver.php config__

```php

```

---

__Error log__

```
SQLSTATE[42501]: Insufficient privilege: 7 ERRO: permission denied to relation "company" (in public schema)

```

**Comment by luceos** [comment]
https://github.com/hyn/multi-tenant/blob/d2998b33378103b8f3dbc4f1a140728f258fafab/assets/configs/tenancy.php#L249-L260
