### ISSUE TITLE
Issue with AWS migration

### ISSUE THREAD

**Issue by eusouodaniel** [hyn/multi-tenant#726]
Hello good afternoon!
I am having trouble running the tenant application on aws, using ecs, the database is being created, but at the time of running the migrations (when connecting), of the exception. I'm not understanding the problem, I was previously hosted on a whm server and it was normal. What would be the problem?

**Comment by ArlonAntonius** [comment]
Could you provide us with more information regarding this?
Please use our [Issue Template](https://github.com/hyn/multi-tenant/blob/5.x/.github/ISSUE_TEMPLATE/Bug_report.md), otherwise, it's hard for us to help you.
Providing a stack trace helps as well.

**Comment by fletch3555** [comment]
Please provide the requested information then this can be reopened.
