### ISSUE TITLE
Separate front-end application Vue.js for Tenant's UI.

### ISSUE THREAD

**Issue by shahzad-sarwar** [hyn/multi-tenant#727]
Hi, Any help would be really appropriated on how to achieve this.

I have currently three separate applications, two front-ends running with vue.js and one backend app, with laravel tenancy, only serving API's, no front-end.

The main base URL or the backend url is set to example.com, this is the tenancy application. It auto-generate URL subdomain.example.com for tenants & databases, as the tenancy package works.

Another domain setup for secure.example.com that points to the another vue application, where we register. Works perfectly well.

Now I have a third application on vue.js, for the tenant's, that points to anything to *.example.com,
and the way the tenancy works, is that wildcards & directory must be set to the main application where tenancy is installed, for the tenancy to work with subdomains.

I cannot create *.example.com & point it to the vue application, as the API calls, then go to vue application not to the back-end, as the sub-domain *.example points to vue application

The whole point is to separate the Tenant UI entirely using a frontend framework like vue.js from the back-end.

**Comment by athiffau** [comment]
What I do is simply detect the domain in my routes/web.php and routes/api.php.  Based on this, I load a set of routes for my default domain (secure.example.com in your case) and a different set of routes if its not my default domain.  Then, if a specific tenant or set of tenants need special routes you can do that in the tenants routes file.

Hope that helps

**Comment by shahzad-sarwar** [comment]
Hi, thank you for your response,.I have updated the question, please do review it again.

**Comment by athiffau** [comment]
Some thing...

If you take a look at the docs here: https://laravel-tenancy.com/docs/hyn/5.3/identification

One way of implementing your routes/web.php could be something like this:

```
// Get current Hostname
 $hostname  = app(\Hyn\Tenancy\Environment::class)->hostname();
 
 // Get FQDN (Fully-Qualified Domain Name) by current hostname
 $fqdn      = $hostname->fqdn;

if ($fqdn !== config('app.url')) {
   Route::get('/account/{vue?}', 'TeanantController@app)->where('vue', '[\/w\.-]*')->name('tenant');
}

if ($fqdn === config('app.url')) {
   Route::get('/admin/{vue?}','AdminController@app)->where('vue','[\/w\.-]*')->name('backend');
}
```

This is just a basic example.  

Another way could be using a middleware somewhat like shown here:
https://medium.com/@ashokgelal/a-full-featured-multi-tenant-app-with-laravel-part-4-tenancy-aware-authentication-e0ee37270bc8

**Comment by shahzad-sarwar** [comment]
Thank you Alain for sharing your knowledge. What we actually want to do is to host the entire front-end on a different server, with tenant aware sub-domains,

**Comment by ArlonAntonius** [comment]
If you want to separate servers, I think you should look at separating Laravel & Vue first, using Laravel as an API and Vue as the front end.
Then it should just be a matter of telling Vue to use that Tenant specific API?

**Comment by luceos** [comment]
No response, closing. I think there are multiple methods to solve this and it really depends on the actual app what makes most sense.
