### ISSUE TITLE
Twice make of Environment seems not OK

### ISSUE THREAD

**Issue by HpiGuillaume** [hyn/multi-tenant#728]
__Description__

I think I've found an error here:
`.../vendor/hyn/multi-tenant/src/Providers/Tenants/QueueProvider.php:32`
```
-             $environment = $this->app->make(Environment::class);
+            $environment = app(Environment::class);
```

---

__Actual behavior__

I've make tests for my new feature about queue/job to send mail.
When I play one test, is good, when I play more than one tests, I got this error:
`Target [Illuminate\Contracts\Foundation\Application] is not instantiable while building [Hyn\Tenancy\Environment].`

Make twice the Environment seems not OK. So I've proposed to use `app(...)` instead of `$this->app->make`.

What do you think ?

---
__Information__

- hyn/multi-tenant version: 5.x-dev
- laravel version: 5.7
- database driver and version: mariadb latest
- php version: 7.3

---

**Comment by HpiGuillaume** [comment]
In case of it's interesting for you, here the PR #729

**Comment by ArlonAntonius** [comment]
Could you provide your tests here as an example?
It seems a bit weird that our tests would be failing while we had working tests for this?

**Comment by fletch3555** [comment]
I fail to see how `app(Environment::class)` is any different than `$this->app->make(Environment::class)`, when that's exactly what `app(.....)` is doing: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/helpers.php#L121

**Comment by HpiGuillaume** [comment]
Here the tests generate the error:
```php
class ResetPasswordTest extends TestCase
{
    /**
     * @group test
     */
    public function test_reset_password_admin_with_good_email()
    {
        //switch to a random tenant
        Config::set('database.default', 'tenant');
        app(Environment::class)->tenant(<WEBSITE_RANDOM>);

        $response = $this->postJson('/path/to/reset_password', ["some" => "values"])
            ->decodeResponseJson();

        //some asserts
        $this->assertTrue(array_key_exists('request_reset_password', $response['data']));
        $this->assertTrue($response['data']['request_reset_password']);
    }

    /**
     * @group test
     */
    public function test_reset_password_supervisor_with_good_email()
    {
        //switch to system connection
        Config::set('database.default', 'system');
        app(Environment::class)->tenant(null);

        $response = $this->postJson('/path/to/reset_password', ["some" => "values"])
            ->decodeResponseJson();

        //some asserts
        $this->assertTrue(array_key_exists('request_reset_password', $response['data']));
        $this->assertTrue($response['data']['request_reset_password']);
    }
}
```

Here my phpunit config:
```xml
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="MAIL_DRIVER" value="array"/>
    </php>
```

I've tested right now and raise my the same error.
An extract from the stacktrace:

```
[2019-02-28 09:39:11] testing.ERROR: Target [Illuminate\Contracts\Foundation\Application] is not instantiable while building [Hyn\Tenancy\Environment]. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target [Illuminate\\Contracts\\Foundation\\Application] is not instantiable while building [Hyn\\Tenancy\\Environment]. at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:945)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(785): Illuminate\\Container\\Container->notInstantiable('Illuminate\\\\Cont...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\\Container\\Container->build('Illuminate\\\\Cont...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\\Container\\Container->resolve('Illuminate\\\\Cont...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(759): Illuminate\\Container\\Container->make('Illuminate\\\\Cont...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(912): Illuminate\\Foundation\\Application->make('Illuminate\\\\Cont...')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(840): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(807): Illuminate\\Container\\Container->resolveDependencies(Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\\Container\\Container->build('Hyn\\\\Tenancy\\\\Env...')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\\Container\\Container->resolve('Hyn\\\\Tenancy\\\\Env...', Array)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(759): Illuminate\\Container\\Container->make('Hyn\\\\Tenancy\\\\Env...', Array)
#10 /var/www/html/vendor/hyn/multi-tenant/src/Providers/Tenants/QueueProvider.php(32): Illuminate\\Foundation\\Application->make('Hyn\\\\Tenancy\\\\Env...')
#11 [internal function]: Hyn\\Tenancy\\Providers\\Tenants\\QueueProvider->Hyn\\Tenancy\\Providers\\Tenants\\{closure}('sync', 'mail', Array)
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(219): call_user_func(Object(Closure), 'sync', 'mail', Array)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(131): Illuminate\\Queue\\Queue->withCreatePayloadHooks('mail', Array)
.......
```

If you need more information do not hesitate !

**Comment by luceos** [comment]
Sounds more like the Environment is trying to be instantiated way too fast, before the Environment is even bound into ioc.

**Comment by HpiGuillaume** [comment]
Hello @luceos I'm noob in Laravel, can you give me more explanation about your impression ?
And, if any, have you suggests about what to change ?

**Comment by mauxtin** [comment]
I am having the same problem. Did you manage to solve this @HpiGuillaume?

**Comment by ArlonAntonius** [comment]
## Note
So far all reports related to this involve tests that follow the following criteria:
- Ran multiple tests at a time
- Tests that fail don't include tenant identification

If you find more info on this, please reply on the issue as this is something that has my attention.

(Last Update: 13/03/2019)

**Comment by bastien-phi** [comment]
thanks @ArlonAntonius, you gave me a clue to find out what is happening : 
> Ran multiple tests at a time

It is a little bit tricky, I will do my best to explain correctly.

As @HpiGuillaume said, problem comes from `Hyn\Tenancy\Providers\Tenants\QueueProvider`.

Let's say I have 2 tests using the queue (to send email for example). During application bootstrap (in `Tests\CreatesApplication::createApplication`), `Hyn\Tenancy\Providers\Tenants\QueueProvider` is booted and adds a callback to the queue  : 
```php
$this->app['queue']->createPayloadUsing(function (...) {
   // ...
   /** @var Environment $environment */
   $environment = $this->app->make(Environment::class);
   // ...
});
```
`$this->app` refers to the current application, having for example the reference `#001`.
Doing `$this->app['queue']->createPayloadUsing($callback)` adds the callback to the static array `$createPayloadCallbacks` of the queue (https://github.com/laravel/framework/blob/5.8/src/Illuminate/Queue/Queue.php#L198)

At this time, `Queue::$createPayloadCallbacks` contains a single callback, with something like ;
```php
[
    function (...) {
       // ...
       /** @var Environment $environment */
       $environment = #001->make(Environment::class);
       // ...
    })
]
```
Test runs, using the queue and calling the `createPayloadCallbacks`. All good, first test passes successfully.
In the `tearDown` of the test, the application is reset.

Second test starts, application is bootstrapped (again in `Tests\CreatesApplication::createApplication`) and again,  `Hyn\Tenancy\Providers\Tenants\QueueProvider` is booted and adds a callback to the queue driver : 
```php
$this->app['queue']->createPayloadUsing(function (...) {
   // ...
   /** @var Environment $environment */
   $environment = $this->app->make(Environment::class);
   // ...
});
```
`$this->app` now refers the newly created application, having the reference `#002`.
The callback is added to `Queue::$createPayloadCallbacks` and it now contains **2** callbacks : 
```php
[
    function (...) {
       // ...
       /** @var Environment $environment */
       $environment = #001->make(Environment::class);
       // ...
    }),
    function (...) {
       // ...
       /** @var Environment $environment */
       $environment = #002->make(Environment::class);
       // ...
    })
]
```
Test runs, using the queue and calling the `createPayloadCallbacks`. Exception is raised in the first one. The application `#001` was reset and not able anymore to instanciate `Environment::class`.

## How to fix this

### First solution : modifying the `QueueProvider`

Changing the callback to 
```php
$this->app['queue']->createPayloadUsing(function (...) {
   // ...
   /** @var Environment $environment */
   $environment = app(Environment::class);
   // ...
});
```
can solve the problem. Indeed, the callbacks in `Queue::$createPayloadCallbacks` will become : 
```php
[
    function (...) {
       // ...
       /** @var Environment $environment */
       $environment = app(Environment::class);
       // ...
    }),
    function (...) {
       // ...
       /** @var Environment $environment */
       $environment = app(Environment::class);
       // ...
    })
]
```
The application is resolved at runtime, so no more reference to an old reset application. Problem is, if we start 600 tests at a time, there will be 600 callbacks in the array, all run when testing the queue...
Not the best idea in my opinion.

### Second solution : reset  `Queue::$createPayloadCallbacks` manually

`$createPayloadCallbacks` can be reset calling ` \Illuminate\Queue\Queue::createPayloadUsing(null);`

It can be done in `tearDown` of `Test\TestCase` of your project : 
```php
protected function tearDown(): void
{
    \Illuminate\Queue\Queue::createPayloadUsing(null);
    parent::tearDown();
}
```
or using `beforeApplicationDestroyed` in `setUp` : 
```php
protected function setUp(): void
{
    parent::setUp();
    $this->beforeApplicationDestroyed(function () {
        \Illuminate\Queue\Queue::createPayloadUsing(null);
    });
}
```

### Solution 3 : Add solution 2 to Laravel 

Maybe it could be added to `Illuminate\Foundation\Testing\TestCase::tearDown` directly...

@luceos : I don't know if there would be a solution to add this to `hyn/multi-tenant` directly. Maybe you have a solution for this...

I hope this helps !

**Comment by mauxtin** [comment]
Thanks @bastien-phi for the detailed analysis 👍 

I can confirm that adding either of the two snippets (_setUp_ or _tearDown_) in "**Second solution**" in my TestCase solves the issue

**Comment by HpiGuillaume** [comment]
What an explanation @bastien-phi ! Thanks a lot !!

I've implemented your solution 2 and it works.

But doesn't work when I put it in the `TestCase::tearDown()` or `TestCase::setUp()` instead of the dedicated test class of tests on Queue.

Thank you again @bastien-phi !!!

**Comment by luceos** [comment]
That is one kick ass research @bastien-phi!

Frankly, I've been moving towards the convention to always use `resolve()` instead of IoC resolving the container nowadays. This is visible in tenancy/tenancy. I'd gladly accept a PR that removes these dreadful `$this->app->make()` calls.

**Comment by ArlonAntonius** [comment]
Can you guys confirm that this is not an issue anymore with the latest dev branch?

**Comment by mauxtin** [comment]
I can confirm this works fine, can we please release a new version with this fix? :)

**Comment by luceos** [comment]
5.4.1
