### ISSUE TITLE
Artisan multi-tenant:setup with Interface always setup

### ISSUE THREAD

**Issue by Krato** [hyn/multi-tenant#73]
Hi again.

I found maybe a bug on `multi-tenant:setup` command.

If you create users with `cli`instead a `controller` and you have `ManagementInterface` installed, always runs the `ManagementInterface` setup. I think that is ok if you don't have a user. But if you have a administrator user should not run setup again.

Is that ok?

Thanks

**Comment by Luceos** [comment]
Hi, the setup is meant to be ran once to setup everything. It's in no way meant to be used to add additional users, although I've heard before that it's been used that way. If you've installed the management interface why not simply use that to add new tenants?

**Comment by Krato** [comment]
Ok. I wanted to know if I will be able to create tenants from cli. Ok, I will do it from Controller.
You can close this issue.
Thanks!

**Comment by Luceos** [comment]
No problem. Yes you can but I haven't created anything for that yet.
