### ISSUE TITLE
Update OpenCollective Bot

### ISSUE THREAD

**Issue by maticzav** [hyn/multi-tenant#736]
Hey 👋,

Thank you for using the OpenCollective Bot. We are rolling out an update which introduces breaking changes. Please check out the new documentation, I am sure you'll love the update.

https://github.com/maticzav/opencollective-bot/tree/next

**Comment by luceos** [comment]
@maticzav thank you, what a lovely update. The explanation on the different options of the config are vague now though, my questions:

- Is the root `labels` still functional? Would be awesome to keep that so that issues in that label only get a reply, although I never confirmed it worked when re-labelling after issue creation.
- How does the message key work under tiers?


based on my pushed change: https://github.com/hyn/multi-tenant/commit/91fff28def1837507b44b1ce15cac7d4e1554644

**Comment by maticzav** [comment]
@luceos, hey! No, we've dropped the root `labels` functionality because we liked the new one much better. The PR looks great 🎉(sadly it's not configured correctly, let me help 😄).

1.) We've replaced `opencollective` with `collective`. The slug looks perfect.
2.) The invitation is also great.
3.) Tiers config, however, has some issues.

First, please do let me know if the documentation is too vague in the repo. Secondly, let me explain how the new version works; as you've guessed `opencollective-bot` messages issues whose authors are not yet backers of your project with a friendly message that you've configured. Furthermore, you can create custom messages for each of the tiers defined in your collective. `tiers` accepts a list of messages configurations that you can assign to a particular tier in your collective, or use `*` to apply it to every tier. Based on your tier configuration, `opencollective-bot` will try to determine which messages it should post to your issue - if, for example, a `Sponsor` opens an issue, you might configure it to receive priority support because they donate more money than a regular backer. Nevertheless, you can set up the bot so that it differentiates only between backers and non-backers.

I have attached the corrected version of the config below (be sure to let me know if anything seems odd).

```yml
collective: tenancy
tiers:
  - tiers: "*"
    labels: ["backer"]
    message: |
      Hey <author>,

      Thank you for backing our package :heart:. 

      Issues opened by backers of our Open Collective will automatically labelled with
      the "backer" tag for priority response and resolve times :tada:.

      <link>
invitation: |
  Hey :wave:,

  Thank you for using our package. 

  We firmly believe that open sourcing our code improves the developer experience.
  In a pursuit to continue our work, help us by donating to our collective! :heart:

  Issues opened by backers of our Open Collective will automatically labelled with
  the "backer" tag for priority response and resolve times.

  <link>
```

PS.: The new version comes with a validator tool https://opencollective-bot.now.sh/validate

**Comment by luceos** [comment]
Hello @maticzav,

Thanks for the clarification Matic. This makes perfect sense and yes the documentation could use such an example (or links to some working versions). 

I've used the same message for every tier on purpose, there's no mistake there. Thanks for providing an improved version, it looks much simpler than before.

As to the validator, I looked at it but didn't understand how to actually use it. It mentions using CURL, which I get, but where exactly do you add the GitHub path/url? Having a validator which is a form accepting a GitHub URL would be much more pleasant and easier to work with.

Thanks for your efforts, did you open an Open Collective for the bot already?

**Comment by maticzav** [comment]
`opencollective-bot` is now officially part of the OpenCollective. Therefore, there's no collective for it.

Regarding the validator, I thought it would make more sense to have it validate the config file itself, not the Github repository. The `--data-binary` with the path to your config does the job of uploading the file.

**Comment by luceos** [comment]
That makes sense, thank you.

It's working perfectly, great job!
