### ISSUE TITLE
[Feature Request] Support Laravel 5.8.*

### ISSUE THREAD

**Issue by oanhnn** [hyn/multi-tenant#742]
__Description of your feature__

Laravel 5.8 is released. Please support it.

---

__Proposed behavior__

Support Laravel 5.8.*

__Current behavior__

```bash
$ composer require hyn/multi-tenant:5.3.*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install hyn/multi-tenant 5.3.1
    - Conclusion: remove laravel/framework v5.8.2
    - Installation request for hyn/multi-tenant 5.3.* -> satisfiable by hyn/multi-tenant[5.3.0, 5.3.1].
    - Conclusion: don't install laravel/framework v5.8.2
    - hyn/multi-tenant 5.3.0 requires laravel/framework 5.6.* | 5.7.* -> satisfiable by laravel/framework[5.6.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.8.2].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.8.2].
    - Installation request for laravel/framework (locked at v5.8.2, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.2].


Installation failed, reverting ./composer.json to its original content.
```
---
__Information__

- hyn/multi-tenant version: 5.3.1
- laravel version: 5.8.*

**Comment by ArlonAntonius** [comment]
L5.8 Compatibility is something that we have been working on. We already merged several PR's to the dev-master that should fix L5.8 compatibility, but want to push a few more things before we actually tag a new version.

You can stay tuned about new updates by joining [our Discord](https://laravel-tenancy.com/discord).

**Comment by ArlonAntonius** [comment]
@oanhnn We just tagged a [Beta Release](https://github.com/hyn/multi-tenant/tree/5.4.0-beta) for L5.8 compatibility and add quite some other things.
