### ISSUE TITLE
Get current website on command 

### ISSUE THREAD

**Issue by oluomotoso** [hyn/multi-tenant#746]
__Description__
I am using the tenancy:run to run some commands on all the tenants.
I can't seem to access the current website.
..

---

__Actual behavior__
Tenancy::website() is returning null
..

__Expected behavior__
Tenancy::website() is supposed to return the website object of the current tenant where the command is been carried out
..

---
__Information__

- hyn/multi-tenant version:
- laravel version:
- database driver and version:
- webserver software and version:
- php version:

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by Plytas** [comment]
Try getting tenant from `app(Environment::class)->tenant()`

**Comment by oluomotoso** [comment]
Thank you... Working Perfectly now
