### ISSUE TITLE
Memory Leak when using Queue 

### ISSUE THREAD

**Issue by oluomotoso** [hyn/multi-tenant#747]
__Description__
All the Jobs queue php processes after completing a job doesnt get terminated. This ends up crashing our server as there are a lot of php services eating up the memory as a result of this. I've used beanstalked and currently I'm using Redis with Horizon and I still experience the same.
Thanks
..

---

__Actual behavior__
All queued php processes doesn't get terminated after finishing job
..

__Expected behavior__
All queued php processes should terminate after finishing
..

---
__Information__

- hyn/multi-tenant version:
- laravel version:
- database driver and version:
- webserver software and version:
- php version:

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by luceos** [comment]
I'm not sure where this is coming from, have you done further research? Is this even proven to be related to this package for example?
