### ISSUE TITLE
Add custom .env file

### ISSUE THREAD

**Issue by Krato** [hyn/multi-tenant#75]
Will be great to add custom `.env` for each tenant website.

Thanks!

**Comment by luceos** [comment]
Hello @Krato i've added some code that should take care of that. Haven't been able to write a test yet because the env file should be picked up right during instantiation of the application. Let me know whether this works out for you.

**Comment by Krato** [comment]
Perfect. I will try. Thanks!

**Comment by luceos** [comment]
Please note if the .env file exists in the tenant directory, the one in the base path won't be used. At least that's how I implemented it for now and that's what I assume might happen.

**Comment by Krato** [comment]
What version should I install? Because if I make `composer update`nothing is installed

**Comment by luceos** [comment]
use version `2.x-dev` i think also make sure you have
- prefer-stable: true
- minimum-stability: dev

in your composer file.

**Comment by luceos** [comment]
@Krato it seems this is not working, at least that's what @bkintanar has reported. Can you confirm, because I also think the env file needs to be loaded during the boot phase of the Application, which might be a hard thing to do at this point seeing the cycle tenancy takes (does most of it's things after boot).

**Comment by Krato** [comment]
Yeah, it seems don't working. No problem about that. I made this touching core of laravel (`boostrap/app.php`), not from a package.

Thank you anyway!

**Comment by luceos** [comment]
reverted the code implemented for now
