### ISSUE TITLE
5.4 Upgrade - Need help

### ISSUE THREAD

**Issue by xalunda** [hyn/multi-tenant#752]
Good afternoon

Following the [upgrade guide](https://laravel-tenancy.com/docs/hyn/5.4/upgrade-from-5.3), I added the `key` into `config/tenancy.php` file:
```
'key' => env('TENANCY_KEY', env('APP_KEY')),
```
Changed the following on my `composer.json`:
```
"require": {
    ...
    "hyn/multi-tenant": "5.4.0",
    "laravel/framework": "5.8.*",
    ...
},
```

I'm correctly on php 7.2.1

---

The main hostname `example.com` works fine.
Whenever I try a tenant website `sub.example.com`, I get this error that I can't seem to debug.
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd3442a527d7b4b08a8053755b87151f1.users' doesn't exist (SQL: select * from `users` where `id` = 1 limit 1)
```
Looks like some middleware is trying to authenticate the user through it's own database.

__Information__

- hyn/multi-tenant version: 5.4.0
- laravel version: v5.8.4
- database driver and version: MySQL 5.7.24
- webserver software and version: Apache/2.4.33 (Unix) (Via MAMP PRO 4.5)
- php version: 7.2.1

---

__tenancy.php config__

```
<?php
use Hyn\Tenancy\Database\Connection;

return [
    'key' => env('TENANCY_KEY', env('APP_KEY')),

    'models' => [
        // Must implement \Hyn\Tenancy\Contracts\Hostname
        'hostname' => \App\Models\Hostname::class,

        // Must implement \Hyn\Tenancy\Contracts\Website
        'website' => \App\Models\Project::class
    ],
    'middleware' => [
        // The eager identification middleware.
        \Hyn\Tenancy\Middleware\EagerIdentification::class,

        // The hostname actions middleware (redirects, https, maintenance).
        \Hyn\Tenancy\Middleware\HostnameActions::class,
    ],
    'website' => [
        'disable-random-id' => false,
        'random-id-generator' => Hyn\Tenancy\Generators\Uuid\ShaGenerator::class,
        'uuid-limit-length-to-32' => env('LIMIT_UUID_LENGTH_32', false),
        'disk' => 'local-tenant',
        'auto-create-tenant-directory' => true,
        'auto-rename-tenant-directory' => true,
        'auto-delete-tenant-directory' => false,
        'cache' => 10,
    ],
    'hostname' => [
        'default' => env('TENANCY_DEFAULT_HOSTNAME'),
        'auto-identification' => env('TENANCY_AUTO_HOSTNAME_IDENTIFICATION', true),
        'early-identification' => env('TENANCY_EARLY_IDENTIFICATION', true),
        'abort-without-identified-hostname' => env('TENANCY_ABORT_WITHOUT_HOSTNAME', false),
        'cache' => 10,
        'update-app-url' => false,
    ],
    'db' => [
        'default' => env('TENANCY_DEFAULT_CONNECTION'),
        'system-connection-name' => env('TENANCY_SYSTEM_CONNECTION_NAME', Connection::DEFAULT_SYSTEM_NAME),
        'tenant-connection-name' => env('TENANCY_TENANT_CONNECTION_NAME', Connection::DEFAULT_TENANT_NAME),
        'tenant-division-mode' => env('TENANCY_DATABASE_DIVISION_MODE', 'database'),
        'password-generator' => Hyn\Tenancy\Generators\Database\DefaultPasswordGenerator::class,
        'tenant-migrations-path' => database_path('migrations/tenants'),
        'tenant-seed-class' => TenantDatabaseSeeder::class,
        'auto-create-tenant-database' => true,
        'auto-create-tenant-database-user' => true,
        'tenant-database-user-privileges' => null,
        'auto-rename-tenant-database' => true,
        'auto-delete-tenant-database' => env('TENANCY_DATABASE_AUTO_DELETE', false),
        'auto-delete-tenant-database-user' => env('TENANCY_DATABASE_AUTO_DELETE_USER', false),
        'force-tenant-connection-of-models' => [
           // App\AccountingGroupAccount::class
        ],
        'force-system-connection-of-models' => [
            //App\User::class
        ],
    ],
    'routes' => [
        'path' => base_path('routes/tenants.php'),
        'replace-global' => false,
    ],
    'folders' => [
        'config' => [
            'enabled' => true,
            'blacklist' => ['database', 'tenancy', 'webserver'],
        ],
        'routes' => [
            'enabled' => true,
            'prefix' => null,
        ],
        'trans' => [
            'enabled' => true,
            'override-global' => true,
            'namespace' => 'tenant',
        ],
        'vendor' => [
            'enabled' => true,
        ],
        'media' => [
            'enabled' => true,
        ],
        'views' => [
            'enabled' => true,
            'namespace' => null,
            'override-global' => true,
        ]
    ]
];
```

__webserver.php config__

```
<?php
return [
    'apache2' => [
        'enabled' => true,
        'ports' => [
            'http' => 80,
            'https' => 443
        ],
        'generator' => \Hyn\Tenancy\Generators\Webserver\Vhost\ApacheGenerator::class,
        'view' => 'tenancy.generators::webserver.apache.vhost',
        'disk' => null,

        'paths' => [
            'vhost-files' => [
                'storage/app/tenancy/webserver/apache2/'
            ],
            'actions' => [
                'exists' => '/etc/init.d/apache2',
                'test-config' => true,
                'reload' => null
            ]
        ]
    ],
    'nginx' => [
        'enabled' => false,
        'php-sock' => 'unix:/var/run/php/php7.1-fpm.sock',
        'ports' => [
            'http' => 80,
            'https' => 443
        ],
        'generator' => \Hyn\Tenancy\Generators\Webserver\Vhost\NginxGenerator::class,
        'view' => 'tenancy.generators::webserver.nginx.vhost',
        'disk' => null,

        'paths' => [
            'vhost-files' => [
                '/etc/nginx/sites-enabled/'
            ],
            'actions' => [
                'exists' => '/etc/init.d/nginx',
                'test-config' => '/etc/init.d/nginx configtest',
                'reload' => '/etc/init.d/nginx reload'
            ]
        ]
    ]
];
```

---

**Comment by Plytas** [comment]
Can you confirm that database `d3442a527d7b4b08a8053755b87151f1` exists and it fully migrated?

**Comment by xalunda** [comment]
Hi,

Thanks for your fast reply

Yes everything is correct. All I did was change the composer and `composer
update`

**Comment by Plytas** [comment]
Try running `php artisan tenancy:key:update` command.

**Comment by xalunda** [comment]
Got no output
The key did not change
The error remains

**Comment by xalunda** [comment]
That's the content of `Hyn\Tenancy\Commands\UpdateKeyCommand.php`
```
class UpdateKeyCommand extends Command
{
    use DispatchesEvents;

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'tenancy:key:update';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Update tenant users passwords.';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->emitEvent(new KeyUpdated());
    }
}
```

This doesn't do anything

**Comment by Plytas** [comment]
That command simply iterates over all tenants and updates their database user password. What's weird to me that the error doesn't complain about wrong password, but it says, that it can't find users table inside the tenant database.

**Comment by Plytas** [comment]
Can you post a screenshot of that database in question and tables?

**Comment by xalunda** [comment]
Here is the database screenshot
![Screen Shot 2019-03-15 at 1 27 32 PM](https://user-images.githubusercontent.com/2316221/54434427-2533ec80-4726-11e9-9add-5bfe2e838920.png)
I'm not allowed to post the tables, sorry. Is there something specific to check about it ?

**Comment by Plytas** [comment]
If you are sure that `users` table exist on that database, can you post a full trace of the error?

**Comment by xalunda** [comment]
The `d3442a527d7b4b08a8053755b87151f1` is a `tenant` database.
My `users` table has always been in the `system` database. There is no `users` table in my tenants databases

**Comment by Plytas** [comment]
That makes more sense now. Does your user model have `UsesSystemConnection` trait?

**Comment by xalunda** [comment]
HOLY MOLLY!

It did not! It works now!
Wondering how it worked until then though.

You absolutely made my day! Thanks a lot 🥇

**Comment by Plytas** [comment]
Did you change any other config options, like `tenancy.db.default`?

**Comment by xalunda** [comment]
`tenancy.db.default => env('TENANCY_DEFAULT_CONNECTION')`

`.env` file:
`TENANCY_DEFAULT_CONNECTION=tenant`

I did not change those values

**Comment by xalunda** [comment]
Looks like laravel Passport also needs to be told to use the correct database:
```
'd3442a527d7b4b08a8053755b87151f1.oauth_personal_access_clients'
```
Any idea were to do that ?

**Comment by bkintanar** [comment]
@xalunda you can extend the passport related models and add the `UsesTenantConnection` to the extended models and then read [here on how to override default models](https://laravel.com/docs/5.7/passport#overriding-default-models)

or add this to your AppServiceProvider's boot method

```php
$env = app(Environment::class);

if ($fqdn = optional($env->hostname())->fqdn) {
    config(['database.default' => 'tenant']);
}
```

**Comment by Plytas** [comment]
By specifying `tenant` as default it forces every model to use tenant connection. Not sure why it worked for you before. I would set the default connection to `system` and then add `UsesTenantConnection` to your models that need to connect to tenant database.

Otherwise you could try forcing 3rd party model connection through config: https://github.com/hyn/multi-tenant/blob/458fc0220420ecfe6fd11818098c442c48aa910f/assets/configs/tenancy.php#L292-L304
Though I see there's a reported issue on that #751

**Comment by xalunda** [comment]
So, I can set default to `system` in the AppServiceProvider?
Every single tenant model is set like in the docs:
```
use Hyn\Tenancy\Abstracts\TenantModel;

class SomeTable extends TenantModel {}
```
Would this work?

**Comment by Plytas** [comment]
Just set it in config, not in the provider.

**Comment by bkintanar** [comment]
as per @Plytas I also set my default connection to `system` in the .env file, and just change the connection to tenant if `app(Environment::class)` resolves anything.

**Comment by Plytas** [comment]
@bkintanar as I understand it wouldn't let you use both system and tenant connections at the same time if you are just switching the connection instead of specifying them per model?

**Comment by bkintanar** [comment]
@Plytas I have set my .env file to `system` by default, but when the app boots, it checks if it is actually accessing a fqdn, and then I forcefully sets the connection to `tenant` with the code above.

**Comment by xalunda** [comment]
I've also set the `TENANCY_DEFAULT_CONNECTION=system`
I don't have @bkintanar 's code to force tenant connection though. Seems like `Hyn\Tenancy\Abstracts\TenantModel` does its job.

**Comment by Plytas** [comment]
Good to hear. If your issue is solved, feel free to close it :)

**Comment by xalunda** [comment]
Thanks everyone! That was lighting fast and very effective. 👍

**Comment by bkintanar** [comment]
Yeah, it was one of the solution most people used if they don't want to put the `UsesTenantConnection` trait.

One use case not to use the trait is that if you want to reuse your model in `system` and `tenant` connection

**Comment by xalunda** [comment]
> One use case not to use the trait is that if you want to reuse your model in system and tenant connection

Yeah that's smart!
