### ISSUE TITLE
Possibility to change 'root' key for filesystem

### ISSUE THREAD

**Issue by lucadello91** [hyn/multi-tenant#762]
__Description of your feature__

I need to set the key for the root path of the single tenant instead of the default value hard-coded in the code. 
Some filesystems require this value but with a different key

---

__Proposed behavior__

Add a configuration key in "tenancy.website.disk-root" config file, 

__Current behavior__

At the moment the default hadcoded key is 'root'

---
__Information__

- hyn/multi-tenant version: 5.4
- laravel version: 5.7

**Comment by luceos** [comment]
I can't make sense of your request. Would you be able to clarify what exactly you're struggling with?
