### ISSUE TITLE
tenancy:run not loading latest websites

### ISSUE THREAD

**Issue by oluomotoso** [hyn/multi-tenant#764]
__Description__
I noticed that after I have created new tenants or deleted some tenants. Running tenancy:run doesn't run expectedly. It's retrieving updated lists of websites
..

---

__Actual behavior__

..

__Expected behavior__

..

---
__Information__

- hyn/multi-tenant version:
- laravel version:
- database driver and version:
- webserver software and version:
- php version:

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by ArlonAntonius** [comment]
We really need more information than the info you provided.
What are you trying to do?
Why are you using tenancy:run for in your case?
Can you actually provide is with the exact current behavior and how it should behave according to you.
