### ISSUE TITLE
Force tenants databases to use default user to access the database

### ISSUE THREAD

**Issue by oluomotoso** [hyn/multi-tenant#766]
I need to enable the package to use a single user to access all the tenants databases. I checked out the tenancy config but couldn't see how to tweak this. 
Every Assistance I can get will be appreciated.

**Comment by ArlonAntonius** [comment]
Hi there,

I don't think this is actually possible at this moment unless you use the "prefix" division mode.
Which will simply adjust the prefix of the connection in order to separate databases.

You can adjust the division mode in the tenancy.php config.

I hope this helps you out.

**Comment by xalunda** [comment]
Hi @oluomotoso 

Here is how I did it, might be a workaround for you too:

- I created a [custom model](https://laravel-tenancy.com/docs/hyn/5.4/custom-models) for my websites.
- The `website` model has a `user_id` column
- When the user connects through the main `domain.com`, I can list all websites he has access to (`a.domain.com, b.domain.com, ...`)
- I then created a Gate implemented into a middleware to check if the user has indeed access to the website he is going on:
```
Gate::define(
    'has-access-website',
    function () {
        // Get current Website
        $currenWebsite = app(Environment::class)->tenant();

        $authUserWebsites = Auth::user()->websites;

        return $authUserWebsites->firstWhere('id', $currenWebsite->id);
    }
);
```

Hope this helps

**Comment by Punksolid** [comment]
Hi, I did exactly that, multi-tenant use a lot of events that could be modified trough listeners. I explained how I did it here 
https://github.com/hyn/multi-tenant/issues/722

**Comment by luceos** [comment]
Listen to the ConfigurationLoaded event and update the username and password of the configuration array.

see https://github.com/hyn/multi-tenant/blob/5.x/src/Database/Connection.php#L333

**Comment by oluomotoso** [comment]
Thanks @Punksolid and @luceos . I was able to achieve this using by listening to the ConfigurationLoaded event.
