### ISSUE TITLE
MediaController - Images not working

### ISSUE THREAD

**Issue by xalunda** [hyn/multi-tenant#767]
Good afternoon,

I'm trying to implement the `media` route for my tenants.
Here are my configurations:

---

`routes/tenants.php`:
```
// MEDIA
Route::get('/media/{path}', '\Hyn\Tenancy\Controllers\MediaController')
->where('path', '.+')
->name('tenant.media');
```

---

`storage`:
```
/storage/app/public/tenancy/d3442a527d7b4b08a8053755b87151f1/media/files/
```
where `d3442a527d7b4b08a8053755b87151f1` is my tenant's uuid

---
__My Issue__:

The `/media` route doesn't seem to work with images.
I tested `.png`, `.jpeg`, `.jpg` and `.svg`.
However, it works fine with `.pdf` files.

---

__Image Test__:
I have an image `example.jpeg`

Here are the response headers received from `https://tenant.domain.local/media/files/example.jpeg`:

```
Cache-Control: no-cache, private
Connection: Keep-Alive
Content-Type: image/jpeg
Date: Wed, 27 Mar 2019 16:34:42 GMT
Keep-Alive: timeout=5, max=100
Server: Apache
Transfer-Encoding: chunked
X-Powered-By: PHP/7.2.1
```
This method sends a broken image, whatever the image is:
![image](https://user-images.githubusercontent.com/2316221/55094810-041cb580-50af-11e9-95fb-b58e735522c9.png)

Here are the response headers accessing the file directly `https://tenant.domain.local/storage/tenancy/d3442a527d7b4b08a8053755b87151f1/media/files/example.jpeg`:

```
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Length: 4960688
Content-Type: image/jpeg
Date: Wed, 27 Mar 2019 16:36:06 GMT
ETag: "2018c7a9f-4bb1b0-5572d22e2ff80"
Keep-Alive: timeout=5, max=100
Last-Modified: Sun, 20 Aug 2017 10:50:54 GMT
Server: Apache
Vary: User-Agent
```
This sends correctly the image.

I also tried to modify `MediaController` so that it includes the missing headers. No luck.
```
public function __invoke(string $path)
{
    $path = "media/$path";
    if ($this->directory->exists($path)) {
        $file = $this->directory->get($path);
        return response($file)
            ->header('Content-Type', Storage::disk('tenant')->mimeType($path))
            ->header('Accept-Ranges', 'bytes')
            ->header('Content-Length', strlen($file));
    }
    return abort(404);
}
```

---

__PDF Test__:
I have a PDF `example.pdf`

Both methods shows the pdf.

---

__Information__

- hyn/multi-tenant version: 5.4.0
- laravel version: v5.8.4
- database driver and version: MySQL 5.7.24
- webserver software and version:  Apache 2.2.34 through MAMP Pro 4.5(9701)
- php version: 7.2.1

Did I miss something?
Thanks

**Comment by xalunda** [comment]
After more tests using Laravel's [`FileSystem->download()`](https://laravel.com/docs/master/filesystem#downloading-files); and with a cleared mind this morning, found out that my output was ruined by Laravel itself, which added some whitespaces.

MediaController can make sure that this does not matter to it, by adding an `ob_end_clean()` right before its return.

Can be closed with PR [#769 - MediaController - Images not working](https://github.com/hyn/multi-tenant/pull/769)

**Comment by luceos** [comment]
`ob_end_clean()` might solve it, but I'm curious where laravel is introducing the white space. Using the given function seems like a rude hack to forcefully fix something which should not even happen in the first place..

**Comment by xalunda** [comment]
Hi @luceos ,
I also agree. I'm trying to pinpoint where this appends as we speak.
Feel free to reject my PR

**Comment by Miguel-Serejo** [comment]
This may be related to https://github.com/laravel/framework/issues/27996

**Comment by luceos** [comment]
@36864 we know about this issue, the MediaController doesn't use a view, maybe the Response object does behind the curtains, but I doubt it.

**Comment by xalunda** [comment]
Found it. I had a new line on a config file before the `<?php` tag..
I really feel bad now.

**Comment by luceos** [comment]
No need to feel bad. This stuff happens to the best of us. Glad I forced you to investigate further ✌️
