### ISSUE TITLE
Specified key was too long

### ISSUE THREAD

**Issue by bubblemedialtd** [hyn/multi-tenant#77]
When running the setup, I am getting an error that the specified key was too long

![image](https://cloud.githubusercontent.com/assets/9167994/15430284/8a4316a6-1e9c-11e6-9780-291b67dfc37b.png)

I notice that it is placing a key on 2 VARCHAR(255) columns. Why is this? Is this a bug?

**Comment by Luceos** [comment]
It's not in fact a primary key, it's an index. What database do you use? And have you tried this with a clean database, seeing you already ran into the problem of the tables being present (and as such the indices as well).

**Comment by bubblemedialtd** [comment]
Hi,

I did try it with a clean database, it had the same issue. I had to change the collation to 'latin1_general_ci' to utf8 wouldn't accept it.

I have a few other questions which I'll query in a little while. So far I'm very impressed with the framework!

Thank you
