### ISSUE TITLE
Throw an exception when updating website and/or hostname

### ISSUE THREAD

**Issue by sasokovacic** [hyn/multi-tenant#772]
__Description of your feature__

In the update method of the WebsiteRepository you create a new website it it doesn't exist instead of throwing an exception. The same applies to hostnames

---

__Proposed behavior__

I would like to get an exception so I can decide what to do after catching it. I don't want to create a new website and/or hostname automatically. I want to add them manually later if there will be a need to do so...

---
__Information__

- hyn/multi-tenant version: 5.4
- laravel version: 5.8

**Comment by luceos** [comment]
Bind your own repository implementation into the service container. There's absolutely no reason to change behavior of existing code when you are the one sending a website model into the repository and are able to check whether it exists up front.

**Comment by sasokovacic** [comment]
I know that I can do that but what is the reason behind this logic? It's not a common practice to create something on update if it doesn't exist. I have to implement the whole update() method just because of this one line. What about making it optional through env configuration?

Btw. I'm not the only one with this request. My friend also noticed this but he didn't post a request.

**Comment by luceos** [comment]
Feel free to send in a PR with the suggested change. I'll let the team decide on whether to move forward with it.
