### ISSUE TITLE
Unable to retrieve hostname() after version upgrade from 5.3 t0 5.4

### ISSUE THREAD

**Issue by vishalmandora** [hyn/multi-tenant#773]
__Description__

I'm trying to retrieve current hostname object inside Laravel Job. so for that I tried using app(\Hyn\Tenancy\Environment::class)->hostname(); but unfortunately it returns null instead of hostname object. Earlier in the older version, I was using TenantAwareJob. but in the newer version, TenantAwareJob has been removed completely so how can laravel application get to know that on which tenant job should be processed & most important thing is how to retrieve current fqdn?

*🗒Another thing is I'm using `Redis` as a queue driver.*

---

__Actual behavior__

null

__Expected behavior__

xyz.domain.com

---
__Information__

- hyn/multi-tenant version: ^5.4
- laravel version: ^5.8
- database driver and version: mysql and 5.7.23
- webserver software and version:
- php version: ^7.1.3

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by Plytas** [comment]
#781 should've fixed the issues with queue provider. 5.4.4 has been tagged.

Jobs will now automatically identify tenants (website). If you want to get fqdn from hostname you will need to retrieve that manually.

**Comment by luceos** [comment]
In addition the method to retrieve the tenant changed, this is no longer `hostname()` but either `tenant()` (preferred) or `website()`. The hostname method will only return a value in case an http request found a matching FQDN in the hostnames table.
