### ISSUE TITLE
Tenant Database Connection

### ISSUE THREAD

**Issue by bubblemedialtd** [hyn/multi-tenant#78]
When visiting a tenant website, how does one query the tenant database rather than the global 'hyn_multi_tenancy' database?

It automatically assumes the 'hyn_multi_tenancy' database.

**Comment by Luceos** [comment]
There are two Models shipped along to be used the TenantModel and the SystemModel, read more about those: https://hyn.readme.io/docs/eloquent-facade-tenant-system-model

**Comment by bubblemedialtd** [comment]
Thank you, I've done some reading on it. Using one of the examples there, I am experiencing the following issue when running the migrate option.

`Migrating for 1: tenant-exa

                                                                                             
  [PDOException]                                                                             
  SQLSTATE[HY000] [1045] Access denied for user '1-tenant-exa'@'localhost' (using password:  
   YES)`

I believe the part that sets the password is:

`$clone['password'] = md5(Config::get('app.key').$this->website->id);`

I have attempted to manually md5 the key & website ID, to get the password - but it still won't allow access.

**Comment by Luceos** [comment]
You manually set the database user password? And it didn't help? Can you tell me where you expected the tenant connection to be made with; eg server, username etc.

**Comment by bubblemedialtd** [comment]
No, I didn't manually set the database user password, but I generated the md5 hash based on:

`md5(Config::get('app.key').$this->website->id);`

The tenant connection was to be made on the localhost, with the username in the format of:

{website ID}-{website-identifier}

I can see that the user has been created, looking in MySQL. I attempted to connect to the local MySQL server using the credentials, but it is denying access.

**Comment by bubblemedialtd** [comment]
I have just created a new instance of Laravel with Hyn/Multi-Tenant.

Added a new user, then tenant, then website.

Attempted to log in to MySQL using the tenant database username/credentials etc. Still not allowing it.

**Comment by Luceos** [comment]
Interesting, because this suggests that either the password encoding goes wrong or the server does something unexpected. Can you give me OS, PHP and MySQL versions?

**Comment by bubblemedialtd** [comment]
Of course,

OS: CentOS release 6.7 (Final)
PHP: PHP 5.6.21 (cli) (built: Apr 28 2016 07:47:46)
MySQL: 5.1.73

**Comment by Luceos** [comment]
@bubblemedialtd have you been able to move forward? I'm not sure whether this is an edge case, would you be able to reproduce this on a fresh instance running the 2.x-dev version?

**Comment by Luceos** [comment]
Please re-open. Tests indicate this should not be an issue.
