### ISSUE TITLE
Connection to tenant database fails during migration.

### ISSUE THREAD

**Issue by ccmelas** [hyn/multi-tenant#780]
Connection to tenant database fails during migration.

Error: The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = dbname and table_name = migrations)
The server requested authentication method unknown to the client [caching_sha2_password]

I believe this error is due to **MySQL 8**

Possible Solution will be to add "WITH mysql_native_password" to the database user creation string

**Comment by ccmelas** [comment]
So MySQL 8 uses the caching_sha2_password plugin for authentication. This error occurs when your client does not support this.

A fix would be to add this to MySQL configuration file (usually my.cnf).
```
default-authentication-plugin=mysql_native_password
```

https://mysqlserverteam.com/upgrading-to-mysql-8-0-default-authentication-plugin-considerations/

Thanks

**Comment by matthewmnewman** [comment]
@ccmelas This is indeed related to MYSQL 8 and the caching_sha2_password plugin.

Furthermore, you can also modify the MYSQL User installation query to use mysql_native_password as another alternative to the above. 

```
CREATE DATABASE IF NOT EXISTS tenancy;
CREATE USER IF NOT EXISTS tenancy@localhost IDENTIFIED WITH mysql_native_password BY 'someRandomPassword';
GRANT ALL PRIVILEGES ON *.* TO tenancy@localhost WITH GRANT OPTION;
```
Thanks
