### ISSUE TITLE
Is Load Balancing on Forge possible with multi-tenant?

### ISSUE THREAD

**Issue by kinsaz** [hyn/multi-tenant#784]
Is it possible to set-up Forge Load Balancing using multi-tenant? I have used Forge with Digital Ocean servers in the past to set up load balancing and a multi-server environment without complications when I was not using multi-tenant. 

Now using this great package, I am able to set-up a db server, worker server etc. - no problem. I  set up a load balance server and 1 App server that runs nginx and serves the app  - everything works great. 

The problem is when I add a second App2 server (keeping the same LB and App1 servers untouched - other than adding the Forge network connection checkbox from the lb to App2). I now start getting NGINX 404 Not Found errors sporadically. I believe App1 is working still but when the load balancer servers App2 it does not recognize the subdomain. I have configured both App1 & 2 NGINX web servers the same to use my correct subdomains (and I've even tried wildcard subdomains but still the same). If I uncheck App2 on the server/network page on Forge (on the load balancer server) and leave App1 and save it everything works perfectly again. I just can't get App2 working.

Also, for more details on the server configuration or the multi-server setup (too much to write here), I followed the instructions on the free and paid portions of Scaling Laravel on Servers For Hackers https://courses.serversforhackers.com/scaling-laravel. 

I would appreciate any advice on how to go about fixing this issue. Thanks in advance for your help.

**Comment by luceos** [comment]
You would have to write the nginx vhost files on both servers. For that to work you'd have to add some command/logic yourself. As example you could have a scheduled task on each server check whether a new Tenant exists in the database, if so regenerate the vhost file.

**Comment by CodeSkills** [comment]
Well I have a wild domain configured on Forge and run the whole example above with no problem. Exactly as you. Don't forget to allow access for the Load Balancer for both servers (firewall in Forge). And you have enabled wild card sub-domains on both App1 and App2 and both Tenant Apps are on those configured wild card sub-domains.

**Comment by kinsaz** [comment]
Thanks - putting the vhost files on both servers and making sure they both have enabled wild card sub-domains did the trick! I still need to create a scheduled task on each server  to check whether a new Tenant exists in the database  so that it will continue to work with new tenants but it works perfectly now. Thanks again!!!
