### ISSUE TITLE
Tenant migration database Schema

### ISSUE THREAD

**Issue by bubblemedialtd** [hyn/multi-tenant#79]
When a new tenant is created in the management interface, how can I set up a default Schema for the new database?

I understand it's a Schema?

**Comment by Luceos** [comment]
It's a database, and for now there is no such option unless you do it yourself. You might simply queue some Job to be scheduled a minute after Tenant creation. Easiest way to do that is to listen to the WebsiteObserver.

**Comment by Luceos** [comment]
No reply anymore, closing.

**Comment by bubblemedialtd** [comment]
Has there been any movement towards my request? Ideally I'd like to create certain table structures once the tenant has been created. Would a Job be the best way to carry out this task?

**Comment by Luceos** [comment]
At this point there is no such functionality. Version 3, if I get to it, might include this functionality. Feel free to create a PR for any needed logic though.
