### ISSUE TITLE
Users table not found for regular users

### ISSUE THREAD

**Issue by ftennali** [hyn/multi-tenant#792]
Hi,

I'm facing problem to create an user from my main domain (i.e. for main website). but when i submit the form. it gave me below error.

My Main DB Name: **tenantdb**

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tenantdb.users' doesn't exist (SQL: select count(*) as aggregate from `users` where `email` = rsingh2@katalysttech.com)

I need to develop a system to work like below.
Master Domain: http://maindomain.com
Client Domain: http://c1.maindomain.com

I need to create account from Master Domain. but i am facing above problem.

**Comment by luceos** [comment]
A master domain is called a fallback in the docs. You'd best create two user classes, one for master and one for tenants.

**Comment by ftennali** [comment]
Thanks @luceos 
I have already done the same.
