### ISSUE TITLE
[Help Needed] - Webserver.php config on Plesk?

### ISSUE THREAD

**Issue by xalunda** [hyn/multi-tenant#795]
Hi everyone!

Does anyone has ever configured a `multi-tenant` project on `Plesk`?
I'm approaching the end of my project and I have to set it up on a Plesk server.

I can't find any information regarding this.

Thanks :)

**Comment by fletch3555** [comment]
Plesk is just a control panel for a webhost, not a webserver.  Under the hood, it's simply using apache or nginx (not sure offhand, though I _think_ it could be either depending on your host).

Short answer is that there should be no issue running this package in such an environment, though shared hosts often have limitations that are difficult to overcome.

Also, questions like this are best asked in our Discord chat or on our new forum(https://discuss.laravel-tenancy.com/).  We try to reserve github issues for actual code issues in the package, not help requests and questions.
