### ISSUE TITLE
Switch back to system database/environment

### ISSUE THREAD

**Issue by Punksolid** [hyn/multi-tenant#797]
Hi
I have manual tenant identification by header and middleware. But there is a specific case use that I want to use a global notifications table. The table works okey, but in a place a need to use one element from a tenant and then put it back again in the global notifications table. 

I tried some ways to reset the tenant specification without success. 
```php
        $account = Account::whereUuid($tenant_uuid)->firstOrFail();
// this notification works fine because accounts are global and notifications too
        \Notification::send($account, new WialonWebhookNotification("Check unit {$request->get('unit')}", $request->all())); 

// Then I enter to find an element, which It works too, and retrieves the element
        $environment = app(\Hyn\Tenancy\Environment::class);
        $environment->tenant($account);
        $device = Trip::findOrFail($trip_id)->truck->device;

        config(['database.connections.tenant.database' => 'mydatabasename']);
// Here it fails because dont switch back to system environment
        $device->notify(new WialonWebhookNotification("Check unit {$request->get('unit')}", $request->all()));
```

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'f1b45786af864c1f813187bb0b18f540.notifications' doesn't exist (SQL: insert into `notifications` (`id`, `type`, `data`, `read_at`, `notifiable_id`, `notifiable_type`, `updated_at`, `created_at`) values (71f274e1-33a4-4331-9d79-0d4a47892294, App\Notifications\WialonWebhookNotification, {"message":"Check unit PTS003","unit":"PTS003","timestamp":"2019-05-02 "X-Tenant-Id":"f1b45786af864c1f813187bb0b18f540","trip_id":"49","device":"6"}, ?, 6, App\Device, 2019-05-02 07:55:49, 2019-05-02 07:55:49))
```

Any idea?

Thanks

**Comment by fletch3555** [comment]
Please follow the issue template.  It prompts you to provide much of the information we need to best support you.  Questions are better asked on our discord chat or forums.

The system connection is always available, regardless of whether a tenant has been identified or not.  Just use the `UsesSystemConnection` trait.

Also, I'm not sure why you're setting the config directly.  Please refer to the docs on how to manually identify tenants.

**Comment by Gadeoli** [comment]
@Punksolid If you have any lucky can you share the solution?
