### ISSUE TITLE
Framework version. No commands folder

### ISSUE THREAD

**Issue by Krato** [hyn/multi-tenant#80]
Hi!

Your package requires hyn/framework. But if you install, framework package has not `command`f older and files inside command folder because of tagged version.

Can you take a look?

Thanks

**Comment by Luceos** [comment]
Sure

**Comment by Luceos** [comment]
Tagged a new version 0.6.2. Sorry this should have been done earlier.

**Comment by Krato** [comment]
Thank! Thats the error I couldn't find it xD
