### ISSUE TITLE
Tenant creation erros "The command "apache2ctl graceful" failed. Exit Code: 1(General error) "

### ISSUE THREAD

**Issue by devrsingh2** [hyn/multi-tenant#801]
Hi,
I have created a UI to create tenant, and earlier it was working fine when I was adding subdomain manually in `/etc/hosts` file.
but when I deployed it to server. I am not able to create a tenant. please check below issue.

`The command "apache2ctl graceful" failed. Exit Code: 1(General error) Working directory: /var/www/html Output: ================ httpd not running, trying to start Action 'graceful' failed. The Apache error log may have more information. Error Output: ================ (13)Permission denied: AH00072: make_sock: could not bind to address [::]:80 (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80 no listening sockets available, shutting down AH00015: Unable to open logs
`
I'm using PHP7.2 LARAVEL 5.4 & APACHE2
hyn/multi-tenant 5.4

Please help me to resolve this problem

**Comment by luceos** [comment]
Make sure you configure the webserver.php file to match binary location of apache among other.

**Comment by joaquimpsoares** [comment]
Mine is giving the same error:

**Webserver.php configurations:**
```
           'vhost-files' => [
                '/etc/apache2/sites-enabled/'
            ],

            /**
             * Actions to run to work with the Apache2 service.
             */
            'actions' => [
                /**
                 * Action that asserts Apache2 is installed.
                 */
                'exists' => '/etc/init.d/apache2',
                /**
                 * Action to run to test the apache configuration.
                 *
                 * @set to a boolean to force the response of the test command.
                 * @info true succeeds, false fails
                 */
                'test-config' => 'apache2ctl -t',
                /**
                 * Action to run to reload the apache service.
                 *
                 * @info set to null to disable reloading.
                 */
                'reload' => 'apache2ctl graceful'
```


**Full error message:**

```
Working directory: /var/www/tenancy/public

Output:
================
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.


Error Output:
================
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
 at /var/www/tenancy/vendor/symfony/process/Process.php:256)
```

**Comment by luceos** [comment]
A normal web user cannot reload apache. That's a command only an elevated user can run (eg root). In order to allow it  you need to configure your server to allow that, eg adding the command to /etc/sudoers.d or something. Google this in combination with your server OS.

**Comment by joaquimpsoares** [comment]
> A normal web user cannot reload apache. That's a command only an elevated user can run (eg root). In order to allow it you need to configure your server to allow that, eg adding the command to /etc/sudoers.d or something. Google this in combination with your server OS.

I'm googlenig it, but not working also gave www-data user and group premisions in sudoers file, but with no success, gave ALL the permissions (I know it's a security risk) but only if it would work.

But thanks I'll keep investigating.

**Comment by luceos** [comment]
Which process is trying to reload apache? If running in queue what user is the queue running as?

**Comment by kumarrahul-rkv** [comment]
Ensure apache2 enabled 'false' in webserver.php

![image](https://user-images.githubusercontent.com/19572222/62273836-227b2f00-b45c-11e9-908e-cf6ec3533ffc.png)

**Comment by vahidalvandi** [comment]
i  have same problem

**Comment by vahidalvandi** [comment]
> A normal web user cannot reload apache. That's a command only an elevated user can run (eg root). In order to allow it you need to configure your server to allow that, eg adding the command to /etc/sudoers.d or something. Google this in combination with your server OS.

please help me how to restart apache in non sudo user ?

i switch to root for create tenant , do this correct ? 
` sudo su -
`

**Comment by fletch3555** [comment]
@vahidalvandi that answer is easily found with a quick google search.  Your application is running as a certain non-root user (most likely `httpd`, `nginx`, or `www-data`, whatever your webserver/php-fpm process is configured as).  In order to run a process as root, you need sudo access.  It's extremely insecure to give the webserver user complete sudo access, so it's typically limited by listing allowed commands in your /etc/sudoers file.

That should give you enough info to find your answer.

Also, please don't revive old closed threads.  We welcome questions in our discord chat or forum
