### ISSUE TITLE
How to migrate an alter migration to reflect in all tenant's database

### ISSUE THREAD

**Issue by ftennali** [hyn/multi-tenant#802]
I have implemented a multi-tenant project and created multiple tenant with their respected database.
now I want to add new feature to the current project that should reflect to all tenants and their database.

My Question is, How can I migrate that new tables to all existing tenant's databases.
is there any command available or any extra configuration i need to do?

**Comment by mauxtin** [comment]
There is `tenancy:migrate`. More here: https://laravel-tenancy.com/docs/hyn/5.4/migrations

**Comment by ftennali** [comment]
Thanks for your quick support.
