### ISSUE TITLE
Website deletion problem in test environment. Phpunit test is not responding.

### ISSUE THREAD

**Issue by karthiksekarnz** [hyn/multi-tenant#803]
I upgraded Laravel from 5.6 to 5.8 and upgraded multi-tenancy package to 5.4.
The application works fine in the local environment but having issues with the test environment.

I have ``TenancyTest.php`` class which is a duplicate of ``Test.php`` from the package.
Tenant database is getting created but during tearDown in ``cleanupTenancy`` function in ``InteractsWithTenancy`` trait there is issue with `` $this->websites->delete($website, true);``

When I debug phpunit command it waits forever in WebsiteRepository delete function at `` $this->emitEvent(new Events\Deleted($website));`` and there is no feedback on screen like in the image 
![Screen Shot 2019-05-21 at 2 35 19 PM](https://user-images.githubusercontent.com/2171885/58064338-be272e00-7bd5-11e9-9400-b1337142c434.png)

**Comment by luceos** [comment]
Does it time out? Any error? Do you have any listeners to that event?

And please provide the information we ask for in the issue template.
