### ISSUE TITLE
hostname don't work in my browser

### ISSUE THREAD

**Issue by difrankode** [hyn/multi-tenant#806]
When i create a new tenant, i can't access by browser.

i use:
multi-tenan version: 5.3
laravel: 5.8
server: largon
php: 7.2

i'm creating it with a seeder

```php
public function run()
{
        $uuid = env('DB_DATABASE').'_example';
        /**
         * Website
         */
        $website = new Website(['uuid' => $uuid]);
        app(WebsiteRepository::class)->create($website);

        /**
         * Hostname
         */
        $hostname = new Hostname(['fqdn' => 'example.'.env('APP_URL_BASE')]);
        $hostname = app(HostnameRepository::class)->create($hostname);
        app(HostnameRepository::class)->attach($hostname, $website);

        /**
         * Switch to new tenant
         */
        $tenancy = app(Environment::class);
        $tenancy->hostname($hostname);
        $tenancy->tenant($website);
}
```

**Comment by fletch3555** [comment]
It sounds like you may have misunderstood how that works.  I recommend reading my post here: https://medium.com/@fletch3555/networking-your-multi-tenant-app-24a340310883

**Comment by luceos** [comment]
As @fletch3555 mentions you need to allow the domain to resolve to your laragon set up. In addition using environment variables outside of configuration files isn't recommended as they won't be accessible when the config is cached.
