### ISSUE TITLE
How to retrieve the current hostname data in a controller

### ISSUE THREAD

**Issue by dougmackenzie** [hyn/multi-tenant#81]
I can see in the dummy website view you use $_tenant['hostname']->hostname to retrieve data on the current hostname but I can't work out how to get that information when working in a controller. I'm guessing I'm lacking in some specific Laravel knowledge but perhaps it would be useful to include an example of how to do this in the documentation?

**Comment by Luceos** [comment]
I'll close this as I haven't heard back from you, but the above should solve your issue.
