### ISSUE TITLE
5.4 breaks hostnames with custom ports

### ISSUE THREAD

**Issue by isecchin** [hyn/multi-tenant#812]
__Description__

This issue has been discussed previously on #750, more specifically on [this comment](https://github.com/tenancy/multi-tenant/issues/750#issuecomment-473258854), but since it was a different issue, we decided that it would be better to separate it into a new one.

But the reason for this is that since version 5.4, any hostname hosted on a custom port (other than 443 and 80) don't get recognized as expected.

---

__Actual behavior__

Can't access any hostname that are hosted in a custom port (other than 443 and 80).

__Expected behavior__

Be able to access any hostname hosted in any port (such as 8080 or 8443, for example).

---
__Information__

- hyn/multi-tenant version: 5.4
- laravel version: 5.8

---

__Debugging__

The issue arose with the introduction of this piece of code:

https://github.com/tenancy/multi-tenant/blob/81c52238225d95dc5ea32913efe9ba507d048fac/src/Listeners/URL/UpdateAppUrl.php#L49

And although we could solve it by checking if the request's port is a custom port and adding it manually on the `forceRootUrl` call, maybe there's a nicer approach (if the `forceRootUrl` call is actually necessary).

**Comment by luceos** [comment]
For regular use cases using a non-publicly available port is unnecessary. Having said that you can disable that functionality with the config key `tenancy.hostname.update-app-url`. Not sure this is what you're looking for?

**Comment by Plytas** [comment]
@isecchin Have you managed to solve this issue?

**Comment by isecchin** [comment]
Hi @Plytas, if I'm not mistaken, I think removing that line from the UpdateAppUrl listener solve this port problem, but I'm not 100% sure what else does this imply, I don't know if it breaks something else since I haven't stumbled into any other issue with it since then.
I'd suggest you fork this repo and try that if you need to use custom ports on and see if it works for you.

**Comment by Plytas** [comment]
I think the best way to do this would be to set `tenancy.hostname.update-app-url` to `false` as luceos said before. If you actually need the config value for `app.url` to be updated on tenant identification, you could re implement this listener.

I'm gonna go ahead and close it. If you require any other assistance, feel free to reopen or create a new issue.
