### ISSUE TITLE
Queued notifications not receiving Pusher settings

### ISSUE THREAD

**Issue by adam-baliatico** [hyn/multi-tenant#816]
I'm trying to send queued notifications using Laravel's built in pusher driver. I need to set different Pusher settings based on which tenant is active. The queued jobs are receiving the proper website_id. However, it appears that the Pusher constructor is called prior to any events that I've tried to listen for in order to set the settings (I have tested Queue::before(JobProcessing $event), Database\ConfigurationLoaded, Websites\Identified, Websites\Switched). 

Any suggestions would be most appreciated.

**Comment by ArlonAntonius** [comment]
Hi there,

Is this still an issue or were you able to figure this out? :)

**Comment by adam-baliatico** [comment]
I was forced to extend Illuminate\Broadcasting\Broadcasters\PusherBroadcaster, which I've added below. I then listen for the Hyn\Tenancy\Events\Websites\Switched event, update the config to match the new tenant and call forceResolve.

```
use Pusher\Pusher;
use Illuminate\Broadcasting\Broadcasters\PusherBroadcaster as BasePusherBroadcaster;

class PusherBroadcaster extends BasePusherBroadcaster
{
    public function forceResolve()
    {
        $config = config('broadcasting.connections.pusher');
        $this->pusher = new Pusher(
          $config['key'], $config['secret'],
          $config['app_id'], $config['options'] ?? []
      );
    }
}
```

**Comment by ArlonAntonius** [comment]
Hmmm that's really a shame.

I would not know a direct solution from the top of my head to be completely honest. Is this something we should really look at it are you oke with closing this?

**Comment by adam-baliatico** [comment]
It's just a function of the PusherBroadcaster only loading the configuration upon instantiation, which in a single tenant set up makes plenty of sense. No issue with closing this, although I might suggest adding an item to the docs under "Tenant Aware WebSockets" or similar. It was somewhat hard to diagnose and I imagine others may run into it as well.

**Comment by ArlonAntonius** [comment]
Feel free to PR something to the docs repo related to this :)
Additional information is always welcome.

**Comment by juhasev** [comment]
We solved this problem by prefixing channels with tenant UUIDs. Unless you absolutely need to have separate pusher account for each tenant I think this solution is more elegant.
