### ISSUE TITLE
Database [tenant] not configured.

### ISSUE THREAD

**Issue by muhammad-umair-brainx** [hyn/multi-tenant#817]

**Comment by muhammad-umair-brainx** [comment]
Sorry! I got my issue fixed.

**Comment by MuskChan** [comment]
How did you solve it? Thank you ♪(·ω·)ノ

**Comment by ArlonAntonius** [comment]
@MuskChan Most of the time this is caused by you trying to access something (like a model) that uses the tenant connection, while no tenant is identified.

**Comment by muhammad-umair-brainx** [comment]
@MuskChan I use a middleware that enforces the tenancy. I can share my code with you If you want.

**Comment by MuskChan** [comment]
Thank you for your kind help.
I have solved the problem.
I think you can leave the solution below
@ArlonAntonius
@muhammad-umair-brainx
