### ISSUE TITLE
Problem when creating tenant

### ISSUE THREAD

**Issue by snsz** [hyn/multi-tenant#818]
Hi,
I want to integrate hyn with my project so every users have their own site and database. My assumption is when user is register at main website, hyn will automatically create sub domain and database for that user. User will redirect to his sub domain to login. So, I have 2 user table at system database and also in tenant database. Now my problem is when user register at main website, website and host name is created but that user is not store in user table either in system database or tenant database. How can I solve my problem?How can I connect between user in system and user in tenant?Btw I'm student and this is my first multi tenant project.

**Comment by drbyte** [comment]
You can find an example Tenant helper class in this [article by Alex Elkins](https://medium.com/@alexleeelkins/multi-tenant-laravel-on-ubuntu-18-04-with-nginx-mariadb-and-php-7-3-a09377ef440f) which discusses the multitenant implementation quite well IMO.
(article was apparently inspired from various sources, including an [older series of articles](https://blog.usejournal.com/writing-a-full-featured-multi-tenant-laravel-app-from-scratch-a0e1a7350d9d?) where parts 1 and 5 talk about the concepts of the tenant helper class, written for an older version)

Additionally, this [older article for an older version](https://medium.com/@edu_96787/building-a-multi-tenancy-laravel-app-with-multi-database-using-hyn-multi-tenant-4f1cdbf99de) discusses a few concepts for accessing data between system/tenant, which may or may not be relevant to your needs (and might need updating).

**Comment by bkintanar** [comment]
I believe this case can be closed now.
