### ISSUE TITLE
How to upgrade from hyn tenancy?

### ISSUE THREAD

**Issue by solofeed** [hyn/multi-tenant#819]

**Comment by luceos** [comment]
Are you interested in upgrading hyn/multi-tenant to tenancy/tenancy?

It would be very much appreciated if you'd invest as much time into asking an answerable question as we invest into trying to support everyone, even questions like these.

**Comment by solofeed** [comment]
@luceos
Sorry

Yes, you wrote that you will make the full upgrade guide for migration from old hyn package to tenancy/tenancy

Is this guide already done?

**Comment by luceos** [comment]
No it is not. The package isn't finished yet, so it would be horrible having to change such a guide for every change we still make.

Feel free to join our discord, one of our staff can add you to a role that gets status updates on our progress.

**Comment by solofeed** [comment]
ok, thanks)
