### ISSUE TITLE
Accessing common table between tenants

### ISSUE THREAD

**Issue by piterog** [hyn/multi-tenant#823]
Guys, I have a table called cities, in tenant main db... is common by every tenant.. my user migration was something like:

```
public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->unsignedInteger('city_id');
            $table->timestamps();

            $table->foreign('city_id')->references('id')->on('cities');
        });
    }
```

How can I link city_id with the main table cities?

**Comment by PsyLogic** [comment]
I don't know if cross database is allowed here but in MySQL (innoDB) is allowed
you can try

```php
use Illuminate\Database\Query\Expression;
use DB;

$db = DB::connection(config('tenancy.system-connection-name'))->getDatabaseName();
$table->foreign('city_id')->references('id')->on(new Expression($db.'cities'));
```
and in the User Model

```php
use DB;
Class User extends Model {
 ...
 public function city() {
  $db = DB::connection(config('tenancy.system-connection-name'))->getDatabaseName();
  return $this->belongsTo('App\City', $db.".cities");
 }
}
```

You can use this code as a hint I didn't try it yet..

**Comment by piterog** [comment]
Hello @PsyLogic 
My bad, I'm using postgres, I have tried this code but postgres believes that $db was an schema, and not a database :(

Thank you

**Comment by PsyLogic** [comment]
@piterog 

Well you have to use **EXTENSION dblink** , but it will be complicated to maintain and handling

**Comment by piterog** [comment]
Thank you @PsyLogic

**Comment by fletch3555** [comment]
Just for the record, Eloquent will handle accessing data/querying across multiple connections just fine without foreign key integrity being enforced by the database itself.
