### ISSUE TITLE
Getting Invalid Schema name error

### ISSUE THREAD

**Issue by cybbsam-ayuda** [hyn/multi-tenant#836]
__Description__

Am trying to create a new tenant. Unfortunately I keep getting

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[3F000]: Invalid schema name: 7 ERROR:  schema "activities" does not exist at character 14")
      /var/www/html/ayuda/api_multi_tenant/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119

I understand the error means I have to create the schemas. But I need this done automatically so I don't have to keep doing it manually all the time. Is there a way to do this? 
Thanks

---

- hyn/multi-tenant version:
- laravel version: 5.3
- database driver and version: postgresql
- webserver software and version: apache
- php version: 7.2

---
---

__Error log__

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[3F000]: Invalid schema name: 7 ERROR:  schema "activities" does not exist at character 14")
      /var/www/html/ayuda/api_multi_tenant/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119

  2   PDOException::("SQLSTATE[3F000]: Invalid schema name: 7 ERROR:  schema "activities" does not exist at character 14")
      /var/www/html/ayuda/api_multi_tenant/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117

  3   PDOStatement::execute()
      /var/www/html/ayuda/api_multi_tenant/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117

  4   Doctrine\DBAL\Driver\PDOStatement::execute()
      /var/www/html/ayuda/api_multi_tenant/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  5   Illuminate\Database\Connection::Illuminate\Database\{closure}("create table "activities"."service_requests_flex" ("service_request_flex_id" serial primary key not null, "service_request_number" varchar(255) null, "speciality" varchar(255) null, "service_request_date" timestamp(0) with time zone not null, "fulfilment_date" timestamp(0) with time zone null, "description" text null, "latitude" varchar(255) null, "longitude" varchar(255) null, "address" text null, "user_id" integer null, "system_user_id" integer null, "worker_id" integer null, "down_payment_amount" decimal(10, 0) null, "offer_amount" decimal(10, 0) null, "service_request_charge_price" decimal(10, 0) null, "status" varchar(255) not null, "users_name" varchar(255) null, "assigned_workers_name" varchar(255) null, "created_at" timestamp(0) with time zone null, "updated_at" timestamp(0) with time zone not null)", [])
      /var/www/html/ayuda/api_multi_tenant/vendor/laravel/framework/src/Illuminate/Database/Connection.php:657

  6   Illuminate\Database\Connection::runQueryCallback("create table "activities"."service_requests_flex" ("service_request_flex_id" serial primary key not null, "service_request_number" varchar(255) null, "speciality" varchar(255) null, "service_request_date" timestamp(0) with time zone not null, "fulfilment_date" timestamp(0) with time zone null, "description" text null, "latitude" varchar(255) null, "longitude" varchar(255) null, "address" text null, "user_id" integer null, "system_user_id" integer null, "worker_id" integer null, "down_payment_amount" decimal(10, 0) null, "offer_amount" decimal(10, 0) null, "service_request_charge_price" decimal(10, 0) null, "status" varchar(255) not null, "users_name" varchar(255) null, "assigned_workers_name" varchar(255) null, "created_at" timestamp(0) with time zone null, "updated_at" timestamp(0) with time zone not null)", [], Object(Closure))
      /var/www/html/ayuda/api_multi_tenant/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
...

**Comment by drbyte** [comment]
Sounds like you're not putting your tenant-specific migrations into the `database/migrations/tenant` subdirectory so that they automatically run when provisioning a new tenant.
See: https://tenancy.dev/docs/hyn/5.4/migrations

**Comment by cybbsam-ayuda** [comment]
> Sounds like you're not putting your tenant-specific migrations into the `database/migrations/tenant` subdirectory so that they automatically run when provisioning a new tenant.
> See: https://tenancy.dev/docs/hyn/5.4/migrations

Thanks for your help. I have solved the issue. All I did was to add the following in the first tenant migration file
"DB::statement('CREATE SCHEMA activities');"

before calling 
Schema::create('activities.xxxxxxx, function(Blueprint $table)
		{
			$table->integer('id', true);
			$table->integer('service_request_id');
			$table->string('message');
			$table->integer('user_id')->nullable();
			$table->integer('worker_id')->nullable();
			$table->timestamps();
		});

So it creates the schema before creating the table
