### ISSUE TITLE
Tenant Route not resolving 

### ISSUE THREAD

**Issue by agbeterseer** [hyn/multi-tenant#848]
I need your help

I get the error while trying to reset a tenants password ?

**Route [password.request] not defined.** 

Here is my tennant.php file
`
use Illuminate\Support\Facades\Route;

Route::middleware(['web','tenancy.enforce'])
    ->namespace('App\Http\Controllers')
    ->as('tenant.') 
    ->group(function () {

    Route::get('login', '\Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

    Route::get('/', function () {
        return view('welcome');
    });`

**Comment by bkintanar** [comment]
can you make sure it's tenants.php not tennant.php?

**Comment by agbeterseer** [comment]
My bad, that was a typo. Its actually tenants.php

**Comment by Miguel-Serejo** [comment]
You've defined a route name prefix of "tenant." for these routes. Try `route('tenant.password.request')` or remove the call to `->as('tenant.')`

**Comment by agbeterseer** [comment]
@36864 Thanks for your suggestions, I have removed the prefix "tenant." and as well as ->as('tenant.') 

and I now get this new error    **Route [register] not defined.**

**Comment by Miguel-Serejo** [comment]
Probably because you haven't defined any route with that name in your file, and at least one of the files you're using is trying to call `route('register')`.

**Comment by agbeterseer** [comment]
Thank you very much @36864 I had to define the `route('register'). `
So its working now.
