### ISSUE TITLE
Microservices architecture

### ISSUE THREAD

**Issue by Geocole** [hyn/multi-tenant#850]
Is there a way to use the library in a microservice architecture?

I have a large scale monolithic application made with tenancy.
But i decide to move to a microservices  architecture. So i'm planning to have multiple services depending on the features in the monolithic architecture. 
My problem is how can i implement this architecture with tenancy?

**Comment by Plytas** [comment]
@Geocole I see this has been responded to on our forums https://discuss.tenancy.dev/d/40-hello-thank-for-this-awesome-library
Do you have any other questions or issues?
