### ISSUE TITLE
Laravel Vapor SQS queue payload "attempts" missing

### ISSUE THREAD

**Issue by jedimdan** [hyn/multi-tenant#855]
__Description__

When a queued job throws an exception, Laravel Vapor tries to update a vapor-specific `attempts` key in the payload that seems to have been removed. After contacting the Laravel Vapor team for help, we were told that it is likely that someone has removed the custom keys that https://github.com/laravel/vapor-core adds to jobs. After doing some investigation, there isn't anything else that might have touched the payload accept this package, so I wanted to find some help if anyone might be able to figure out what might be happening.

Laravel Vapor assigns the payload keys here: https://github.com/laravel/vapor-core/blob/9a486ab614e92c01cbd2d089b01cc0124c8eff0a/src/Queue/VaporQueue.php#L41

This package modifies the payload here: https://github.com/tenancy/multi-tenant/blob/5.x/src/Providers/Tenants/QueueProvider.php#L29

I don't really know how the `createPayloadUsing` or the `createPayloadArray` methods work, so I'm a bit stuck in figuring out where to look. 

---

__Actual behavior__

When a job throws an exception on an app that's powered by Laravel Vapor, the job should recognise that it's failed, but the `attempts` key in the job payload is missing, possibly due to multi-tenant's queue provider.

__Expected behavior__

Additional keys added to a job payload should not be removed.

---
__Information__

- hyn/multi-tenant version: 5.5.0
- laravel version: 6.2.0
- database driver and version: MySQL 8.0
- webserver software and version: Laravel Vapor
- php version: 7.3? Not sure exact version Vapor is running, but minimum

---

__Error log__

```text
vendor/laravel/vapor-core/src/Queue/VaporJob.php:21
Undefined index: attempts
```

I understand that there currently is no expectation for this package to work with Laravel Vapor, but would love to pick on the community's brain on how I may potentially resolve this.

Thanks in advance!

**Comment by ArlonAntonius** [comment]
I personally am not sure how much we'll do in order to make this package "Vapor ready" as I think we'd rather make Tenancy/Tenancy stable and Vapor ready :)
What I'm most interested in is the full backtrace of this error, this shouldn't happen at all, not even with the "middleware" we use.

Could you provide us with:
- The exact code you run in order to do this
- The full backtrace of this error

And please check if your job would work without the package.

**Comment by jedimdan** [comment]
Thanks @ArlonAntonius and I totally get that. So I appreciate your interest in hoping to understand what may be happening here. I hope that if there indeed is an issue we uncover, it would be something would help Tenancy in general.

## Reproducing the error with and without Tenancy
I hadn't thought about reproducing the error without the package so I went ahead and started a brand new Laravel project. I created the following job:

https://github.com/jedimdan/vapor-tenancy-queue-test/blob/master/app/Jobs/TestFailedJob.php
```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class TestFailedJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        throw new \Exception('simulate failed job');
    }
}
```
Here's the exception on Vapor on a blank Laravel project:
```text
simulate failed job
/var/task/app/Jobs/TestFailedJob.php:32
:
--
/var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32
/var/task/vendor/laravel/framework/src/Illuminate/Support/helpers.php:522
/var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90
/var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34
/var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php:591
/var/task/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:94
/var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130
/var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105
/var/task/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:98
/var/task/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:83
/var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130
/var/task/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105
/var/task/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:85
/var/task/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:59
/var/task/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:88
/var/task/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:348
/var/task/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:294
/var/task/vendor/laravel/vapor-core/src/Queue/VaporWorker.php:20
/var/task/vendor/laravel/vapor-core/src/Console/Commands/VaporWorkCommand.php:90
:
/var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32
/var/task/vendor/laravel/framework/src/Illuminate/Support/helpers.php:522
/var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90
/var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34
/var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php:591
/var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php:202
/var/task/vendor/symfony/console/Command/Command.php:255
/var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php:189
/var/task/vendor/symfony/console/Application.php:934
/var/task/vendor/symfony/console/Application.php:273
/var/task/vendor/symfony/console/Application.php:149
/var/task/vendor/laravel/framework/src/Illuminate/Console/Application.php:90
/var/task/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:131
/var/task/vendor/laravel/vapor-core/src/Runtime/Handlers/QueueHandler.php:59
/var/task/cliRuntime.php:66
/var/task/vendor/laravel/vapor-core/src/Runtime/LambdaRuntime.php:53
/var/task/cliRuntime.php:68
/var/task/runtime.php:26
/opt/bootstrap.php:6
```

Here's the same job on Vapor after Tenancy is installed (https://github.com/jedimdan/vapor-tenancy-queue-test/commit/4946b2ad425787119b0fac982210a8a0f9486bb2):
```
Undefined index: attempts
/var/task/vendor/laravel/vapor-core/src/Queue/VaporJob.php:21
--
/var/task/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:394
/var/task/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:352
/var/task/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:294
/var/task/vendor/laravel/vapor-core/src/Queue/VaporWorker.php:20
/var/task/vendor/laravel/vapor-core/src/Console/Commands/VaporWorkCommand.php:90
:
/var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32
/var/task/vendor/laravel/framework/src/Illuminate/Support/helpers.php:522
/var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90
/var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34
/var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php:591
/var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php:202
/var/task/vendor/symfony/console/Command/Command.php:255
/var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php:189
/var/task/vendor/symfony/console/Application.php:934
/var/task/vendor/symfony/console/Application.php:273
/var/task/vendor/symfony/console/Application.php:149
/var/task/vendor/laravel/framework/src/Illuminate/Console/Application.php:90
/var/task/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:131
/var/task/vendor/laravel/vapor-core/src/Runtime/Handlers/QueueHandler.php:59
/var/task/cliRuntime.php:66
/var/task/vendor/laravel/vapor-core/src/Runtime/LambdaRuntime.php:53
/var/task/cliRuntime.php:68
/var/task/runtime.php:26
/opt/bootstrap.php:6
```

So from this experiment, it does look like Tenancy has somehow undone the job's payload.

If you would like to see the full project, I've put the entire project here: https://github.com/jedimdan/vapor-tenancy-queue-test

**Comment by luceos** [comment]
Perhaps Laravel stopped merging payload and started allowing mutating that argument. Can you try changing the QueuProvider to merge new payload with the old and see whether that fixes it @jedimdan ?

https://github.com/tenancy/multi-tenant/blob/571cf446ee94dbd0a4c9c6ade67368c053b214a1/src/Providers/Tenants/QueueProvider.php#L36

**Comment by jedimdan** [comment]
@luceos I just tried that, but I'm still getting the same exception, unfortunately.

https://github.com/jedimdan/multi-tenant/blob/630ed3bf9dd8aaf57c46548ef69024cbe8eccfd3/src/Providers/Tenants/QueueProvider.php#L36

**Comment by jedimdan** [comment]
@luceos After your suggestion, I decided to try a bit of logging. Interestingly `attempts` wasn't in the original payload by this point (or maybe it hasn't been added yet ¯\_(ツ)_/¯);

Here's the payload I got from logging just before this line https://github.com/tenancy/multi-tenant/blob/571cf446ee94dbd0a4c9c6ade67368c053b214a1/src/Providers/Tenants/QueueProvider.php#L30

Payload:
```
{
    displayName: "App\Jobs\TestFailedJob",
    job: "Illuminate\Queue\CallQueuedHandler@call",
    maxTries: null,
    delay: null,
    timeout: null,
    timeoutAt: null,
    data: {
        commandName: {
            connection: null,
            queue: null,
            chainConnection: null,
            chainQueue: null,
            delay: null,
            middleware: [],
            chained: []
        },
        command: {
            connection: null,
            queue: null,
            chainConnection: null,
            chainQueue: null,
            delay: null,
            middleware: [],
            chained: []
        }
    }
}
```

I'll try to keep digging to see where `attempts` got removed.

**Comment by jedimdan** [comment]
I just had a very interesting discovery.

Laravel Vapor adds `attempts` into the payload at this point https://github.com/laravel/vapor-core/blob/9a486ab614e92c01cbd2d089b01cc0124c8eff0a/src/Queue/VaporQueue.php#L38, so I decided to [log this code](https://github.com/jedimdan/vapor-core/commit/f5077a90f86f55dec0e6fd053f8dae2b151534dd#diff-6ceb4eaaf0812c58f8ef1659de8f35a4R43) with my own `vapor-core` fork.

It seems that when tenancy is installed, the `createPayloadArray` method no longer executed. Once I removed tenancy from the app, `createPayloadArray` was executed once again.

**Comment by ArlonAntonius** [comment]
@jedimdan If I make a branch here, would you be able to try it out? :)

**Comment by jedimdan** [comment]
@ArlonAntonius yes I can :)

**Comment by ArlonAntonius** [comment]
@jedimdan Could you try this specific branch?
https://github.com/tenancy/multi-tenant/tree/aa/test-vapor

**Comment by jedimdan** [comment]
@ArlonAntonius Just did! Unfortunately, it's still getting the same error. I double-checked my lock file to confirm that I've got the right commit hash installed too just in case. 

Been trying to understand how everything works to see if I can figure out the problem myself, and learning more about Laravel's internals along the way. In reference to https://github.com/tenancy/multi-tenant/issues/855#issuecomment-544670028, I continued the digging, and now know that `createPayloadUsing` actually happens within `createPayloadArray`, so for Vapor's `createPayloadArray` to run, Vapor extended SqsQueue class, and Tenancy's `createPayloadUsing` just hooks inside. So right now, I'm guessing that something stopped `VaporQueue` from swapping successfully and the original SqsQueue class is running instead.

**Comment by jedimdan** [comment]
Oh and this also explains why we won't see `attempts` within the payload here https://github.com/tenancy/multi-tenant/issues/855#issuecomment-544659461, because Vapor doesn't use hooks to add that key, but rather the `attempts` key is manually added to the array after all the hooks finish running.

**Comment by edwinencomienda** [comment]
Was this fixed?

**Comment by jedimdan** [comment]
@edwinencomienda I've not had time to continue investigating this, but I still have this problem on a production app of mine now. Are you experiencing the same thing?

**Comment by edwinencomienda** [comment]
Yes @jedimdan we are in the same shoes. When my jobs are failing i can’t get the correct error because of the attempts issue of vapor

**Comment by jedimdan** [comment]
@edwinencomienda are you already on the latest version of Vapor core, Laravel and Multi-tenant? If I were to restart my investigations, that would have been my first step, to see if anything has changed in the last couple of months.

**Comment by edwinencomienda** [comment]
I’m sure im in the latest versions @jedimdan. This is very problem in my end because i can’t see why my queues and jobs are failing.

**Comment by jedimdan** [comment]
@edwinencomienda unfortunately, at this point it's up to us to figure it out. I've dug quite far but I ran out of time to continue digging. Are you open to continue where I left off?

**Comment by ArlonAntonius** [comment]
We've gotten a fix through T/T, we expect this to also work for this package.

PR incoming this week.

**Comment by jedimdan** [comment]
Awesome news @ArlonAntonius!

**Comment by jtomek** [comment]
Wonderful news. I'd like to ask those who have already been testing Vapor+Hyn. Once this problem is solved, do you see any other showstoppers? I'm running Hyn on Forge and would love to forget about my servers. :-) 

Offtopic: Would you know if there is a basic tutorial/advice for Hyn/Vaport somewhere? I looked at Vapor, saw that the provisioning works with subdomains and thought to myself, oh oh, this will be a lot of effort to implement.

**Comment by jedimdan** [comment]
@jtomek I've actually been running Vapor+Hyn in a production environment since November 2019 and haven't seen any issues apart from this one. That said, I don't use Hyn with subdomains and have implemented a custom way of switching tenants (for reasons unrelated to running with Vapor).

**Comment by jtomek** [comment]
> We've gotten a fix through T/T, we expect this to also work for this package.
> 
> PR incoming this week.

This "PR incoming this week" was so exciting I finally took courage and subscribed to Vapor. 😁

**Comment by ArlonAntonius** [comment]
Sorry, have not quite gotten to it yet, really prioritize the work that needs to be done on T/T.

If someone feels up for it, you can create a PR that aligns the Queue related code with the one in T/T.

**Comment by jtomek** [comment]
No worries, I haven't managed to get to the Queues yet :-)

It's actually quite some effort to make a Laravel+Angular app packaged in the /public folder work with Vapor. The most problematic is the issue that the command "vapor deploy" takes very long and I can't iterate fast. I actually asked my girlfriend to give me her laptop with more RAM and faster processor so I wouldn't have to spend 20 minutes on one iteration but only 10. And then there are there particular AWS services and their settings, Websockets, File uploads, splitting the app into smaller pieces, redesigning interfaces, etc.. The Queues are one of my last problems actually :-) 

But I think (hope) the effort is worth it!

**Comment by jedimdan** [comment]
> Sorry, have not quite gotten to it yet, really prioritize the work that needs to be done on T/T.
> 
> If someone feels up for it, you can create a PR that aligns the Queue related code with the one in T/T.

I'll give it a try!

**Comment by bradley-r-martin-pt** [comment]
It looks like this issue has been patched with the above PR, Any idea when this will be merged ?

**Comment by bkintanar** [comment]
@bradley-r-martin-pt PR merged. Issue closed.

**Comment by bkintanar** [comment]
@bradley-r-martin-pt PR merged. Issue closed.

Thank you @jedimdan for the efforts.

**Comment by jedimdan** [comment]
Thanks, @ArlonAntonius and @sniper7kills for the solution haha.

unfortunately, because this is going to be on 5.6.x which has a minimum requirement of Laravel 7, I won't be able to benefit from it until my app is upgraded to Laravel 7 :(

**Comment by bradley-r-martin-pt** [comment]
@jedimdan I too have a project that wont be updated to Laravel 7 anytime soon. In the meantime this is the hack i've used implement this fix quickly

in my composer.json i add this to the autoload and then create QueueProvider.php. How this helps you.

`"autoload": {
    "exclude-from-classmap": [
      "vendor/hyn/multi-tenant/src/Providers/Tenants/QueueProvider.php"
    ],
    "files": [
      "app/Overrides/QueueProvider.php"
    ]
  }`
