### ISSUE TITLE
tenancy:key:update for 5.3

### ISSUE THREAD

**Issue by fernandocoronatomf** [hyn/multi-tenant#860]
__Description of your feature__

I'd like to know if there's a way to update the keys for version 5.3?
I am going to upgrade a huge application and if anything goes wrong and I have to roll it back, there's no tenancy:key:update on version 5.3

---

__Proposed behavior__

Being able to run tenancy:key:update on 5.3

__Current behavior__

We can't run tenancy:key:update

---
__Information__

- hyn/multi-tenant version: 5.3
- laravel version: 5.7

**Comment by ArlonAntonius** [comment]
Hi @fernandocoronatomf,

I personally don't think there's a need to backport that exact command to 5.3. You will be much better off upgrade to 5.4+ in a lot of cases.

**Comment by fernandocoronatomf** [comment]
@ArlonAntonius but that's the thing... I am upgrading it.
The problem is if something goes wrong and i have to rollback the code, the version 5.3 loses access to the DB after I rotated on 5.4

**Comment by ArlonAntonius** [comment]
@fernandocoronatomf Not sure from the top of my head, but don't think that's actually the case.
Please read our Upgrade Guide regarding upgrading from 5.3
https://tenancy.dev/docs/hyn/5.4/upgrade-from-5.3

**Comment by Plytas** [comment]
@fernandocoronatomf I understand this is a late response, but as they say: better late then never, right? That said, I don't think that we will backport this to 5.3. You should be able to recreate the command yourself.

Make sure you have backups before upgrading. Up until 5.4 we used `APP_KEY` to generate tenant database passwords, so make sure you have a copy if anything goes south.
Also it's possible to reuse the old way of generating passwords using `APP_KEY`, by having `tenancy.key` config value as `null`.
https://github.com/tenancy/multi-tenant/blob/5.x/src/Generators/Database/DefaultPasswordGenerator.php#L41-L48

I'm gonna go ahead and close this issue. If you still require any assistance, feel free to reopen or create a new issue.

**Comment by fernandocoronatomf** [comment]
Yeah, thanks.
I ended up creating the command myself but did not have to rollback as everything went smoothly. 

Thanks
