### ISSUE TITLE
Multi Schema instead of multi database

### ISSUE THREAD

**Issue by xyrintech** [hyn/multi-tenant#864]
__Description of your feature__

Assumptions: Using Postgres Databases

It would be great if we can have a concept of multi-schema within one database with this package. This way server resources can be utilized more efficiently. 

---

__Proposed behavior__

Creating new tenant will create a new schema in a Postgres database.

__Current behavior__

Currently it create a new database.

---
__Information__

- hyn/multi-tenant version: 5.x
- laravel version: 5.8

**Comment by ArlonAntonius** [comment]
Hi @xyrintech,

I really appreciate your feedback on our packages.
Have you seen our tenant-division-mode key? It might be what you're looking for.
https://github.com/tenancy/multi-tenant/blob/5558965f8c54e7839aa9ffe285e3185d83d11616/assets/configs/tenancy.php#L200

**Comment by xyrintech** [comment]
Yes, this is what I am looking for.
