### ISSUE TITLE
How to create a new tenant using multi-tenant 5.5

### ISSUE THREAD

**Issue by andytriboletti** [hyn/multi-tenant#869]
How do I go about creating a new tenant using multi-tenant 5.5 and Laravel 6+?

**Comment by andytriboletti** [comment]
I went with the stancl library. Thank you.

**Comment by fletch3555** [comment]
Sorry to hear that.  In the future, it would help if you described your issue in more detail.  Also, you may get a faster response for questions like this if you ask in our discord chat
