### ISSUE TITLE
Creating a new tenant runs the tenant's migrations on the system database connection

### ISSUE THREAD

**Issue by emidiotorre** [hyn/multi-tenant#871]
Hi,
I have recently upgraded from 5.3 to 5.4 I don't know if it may be related but I'm facing this strange problem that is driving me crazy.. basically i run migrate:fresh and then db:seed where in the DatabaseSeeder I am creating a Tenant, using the standard procedure described here: https://tenancy.dev/docs/hyn/5.4/creating-tenants

What happens is that the tenant's database is created, the migrations table is created correctly inside it, but **the actual migrations are run on the system database**.

I have checked what happens under the hood and in fact the database.default is set to the tenant connection which is correctly set to the current tenant.

I am using a pretty standard configuration, with only a custom Website model that extends directly the package's Website model.

I really don't know where to dig to debug this, maybe there is some other package interfering with multi-tenant and there is a listener resetting the connection to 'system'?

Any help is greatly appreciated, if you need more info i will post the files needed.

**Comment by bougsid** [comment]
I was just about posting the same issue, waiting for any help.

**Comment by luceos** [comment]
Did anything change in terms of how laravel sets the connection on those commands? I'd have to dive into this to know for sure.

**Comment by bkintanar** [comment]
hmm.. I've been using 5.4 for quite some time now in my CI/CD setup, but all seems to be working just fine. I'm not sure if it's related but are you using a command to create the tenant?

**Comment by bougsid** [comment]
After spending a day debugging, my issue was because of calling `Schema::defaultStringLength(191)` from the boot method of AppServiceProcider, when I remove it it worked just great, honestly, I don't know why this method caused the issue, maybe it initializes the connection to the system somewhere.

**Comment by emidiotorre** [comment]
Thanks! Anyway I have rebuilt the app with the latest versions of Laravel and multi-tenant and everything is working as expected :) so i'm closing the issue!
