### ISSUE TITLE
[Workaround – Tutorial] Tenancy:run schedule:run

### ISSUE THREAD

**Issue by xalunda** [hyn/multi-tenant#873]
__Description__

This is __not an issue__. This is a workaround / tutorial I found to get tenants identified with 
```
php artisan tenancy:run schedule:run
```
What `schedule` run does, it basically loops through every scheduled commands, and creates a process for each one.

---

__Example__

* First lets create our ExampleCommand:
```shell
php artisan make:command ExampleCommand
```

* We are going to make this command Tenant Aware. Let's change the signature to accept a `website_id` option
```php
protected $signature = 'example:command {--website_id=}';
```

* We will take tenant awereness example from [Tenant Aware Tinker Command](https://tenancy.dev/docs/hyn/5.4/commands#tenant-aware-tinker-command). The `ExampleCommand` should look like this:

<details><summary>app/Console/Commands/ExampleCommand.php</summary>
<p>

```php
namespace App\Console\Commands;

use Illuminate\Console\Command;
use Hyn\Tenancy\Contracts\Repositories\WebsiteRepository;
use Hyn\Tenancy\Database\Connection;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Symfony\Component\Console\Exception\RuntimeException;

class ExampleCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'example:command {--website_id=}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Example Command - Tenant Aware';

    /**
     * @var Connection
     */
    private $connection;

    /**
     * @var WebsiteRepository
     */
    private $websites;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
        $this->websites = app(WebsiteRepository::class);
        $this->connection = app(Connection::class);
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $website_id = $this->option('website_id');
        try{
            $website = $this->websites->query()->where('id', $website_id)->firstOrFail();
            $this->connection->set($website);
            $this->info('Running Command on website_id: ' . $website_id);

            $this->commandHandle();
            
            $this->connection->purge();
        } catch (ModelNotFoundException $e) {
            throw new RuntimeException(sprintf('The tenancy website_id=%d does not exist.', $website_id));
        }
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function commandHandle()
    {
        // You are now Tenant Aware
    }
}
```

</p>
</details>

* Then we need to register our schedule into `app/Console/Kernel.php`:
```php
protected function schedule(Schedule $schedule)
{
    $schedule
    ->command(ExampleCommand::class)
    ->daily();
}
```

* Finally, we need to inject the `website_id` option to the command's options. We will use the `before` helper to modify the called command:
```php
$schedule
->command(ExampleCommand::class)
->daily()
->before(function (Schedule $schedule) {
    $tenant = app(\Hyn\Tenancy\Environment::class)->tenant();
    $event  = $schedule->events()[0];
    $event->command .= sprintf(" --website_id=%d", $tenant->id);
});
```

---

There we go! Feel free to try it and tell me if it works or you have issues with it.

---

__Information__
- hyn/multi-tenant version: 5.5.0
- laravel version: 6.6.2
- php version: > 7.2

### Warning: This has been tested with only one scheduled task. Behaviour with multiple tasks is unknown. Feel free to try it :)

**Comment by ArlonAntonius** [comment]
Like I said before, thank you for providing this information :)

Closing this, for now, wanted this as documentation in an issue, might be added to our actual docs someday.

**Comment by xalunda** [comment]
Thanks :)
I actually found a way to use it with multiple tasks, I'm using this with 10+ tasks now.
Let me know if I should make a PR on the docs.

**Comment by ArlonAntonius** [comment]
@xalunda If you actually tested that with 10+ tasks, please create a PR to the docs.

That would be amazing ❤️ Think it will help quite some people out.

**Comment by sasokovacic** [comment]
@xalunda I've copied the code from your tutorial and it's not working for me. Tenant is not resolved in the schedule method of the Kernel class. The `if (app(\Hyn\Tenancy\Environment::class)->tenant()) {` is never executed. A tenant can only be resolved inside of the before method.

See the code below 

    protected function schedule(Schedule $schedule)
    {
        $schedule
            ->command(RemindUsersAboutEntityControlDeadlineCommand::class)
            ->everyMinute()
            ->before(function (Schedule $schedule) {
                $tenant = app(\Hyn\Tenancy\Environment::class)->tenant();
                dump($tenant->id); // Here a tenant is resolved
            });

        // app(\Hyn\Tenancy\Environment::class)->tenant() always returns null
        if (app(\Hyn\Tenancy\Environment::class)->tenant())
        {            
            // This is never executed
        } else {
            // This is always executed
        }
    }

**Comment by breaktag** [comment]
@sasokovacic Using this approach, are you able to specify the frequency inside the before hook?

In my situation I have a scheduled command which runs once a week on each tenant but it can be at a different day/time specified by the user so I need to be able to access the tenant database and specify which day and time to execute the command

thanks
