### ISSUE TITLE
User registration on tenant site 

### ISSUE THREAD

**Issue by tarkumar** [hyn/multi-tenant#880]
**Description**

I am able to login to tenant user but when i am trying to register it will trying to insert data in system database on in tenant.
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tenancy.users' doesn't exist (SQL: select count(*) as aggregate from `users` where `email` = tar@gmail.com)`

**Comment by bkintanar** [comment]
Can you check my 3rd video here: https://youtu.be/Cni51r7DxQA

--
Bertrand Kintanar
bertrand.kintanar@gmail.com

**Comment by fletch3555** [comment]
Please make sure to include all of the data asked for in the issue template.  It helps us with debugging and ensuring we're mimicking your environment as best we can when trying to reproduce your issue.

**Comment by tarkumar** [comment]
Thank You @bkintanar 
Its working fine.
