### ISSUE TITLE
One client to own multi tenant and have access to them over one backend

### ISSUE THREAD

**Issue by AhmadHamdiAhmad** [hyn/multi-tenant#900]
One client to own multi tenant and have access to them over one backend
Actual behavior
Each client just has one tenant and can access only one
Expected behavior
To be able to have just one domain like examle.com which be able to connect multi tenant this client linked to it
Information
- hyn/multi-tenant version:5.4
- laravel version:6.18
- database driver and version:mysql 5.8
- webserver software and version:nginx
- php version:7.2
tenancy.php config
Default

**Comment by ArlonAntonius** [comment]
Hi there,

I feel like there's some information missing here. I don't completely understand what type of approach you're trying to take here. If you still need help, please try to explain the way you want your setup as good as possible ❤️

**Comment by AhmadHamdiAhmad** [comment]
I have multi clients so i need to create sperate database foreach one of them.
Example as follow
I have domain called example.com
First client has a.example.com
Second client has b.example.com
Third client has c.example.com, d.example.com and e.example.com

Current setup working fine with first and second client,
Third client need to have access for the three domains he own from one backend, that's the issue.

**Comment by ArlonAntonius** [comment]
Hi there,

I think you need to rethink what your tenants are and how you would like to identify them. In this scenario a client is not actually a client, it sounds like the client is one person who can have 3 separate instances.
In that case you should create custom identification in order to make this work properly.

**Comment by AhmadHamdiAhmad** [comment]
Hi ArIonAntonius,

Thanks for support i just was confirming that plugin doesn't support this issue

**Comment by ArlonAntonius** [comment]
Indeed, this is not something that is supported by the package by default.
