### ISSUE TITLE
Argument 1 passed to Hyn\Tenancy\Listeners\Database\FlushHostnameCache::saved() must be an instance of Hyn\Tenancy\Models\Hostname

### ISSUE THREAD

**Issue by catalinbuletin** [hyn/multi-tenant#915]
Hello,
First of all I want to thank you for your effort to build this package. Really good job!

__Description__

I have a dedicated model for the Hostname that `implements \Hyn\Tenancy\Contracts\Hostname`
I have just upgraded from version 5.5 to 5.6 and i got an issue when creating a new Hostname.

Before the upgrade all was working ok.

---

__Actual behavior__

I get the following error 
```Argument 1 passed to Hyn\Tenancy\Listeners\Database\FlushHostnameCache::saved() must be an instance of Hyn\Tenancy\Models\Hostname, instance of App\Models\System\Hostname given```

I think best would be that the `FlushHostnameCache::saved()` method to have the `\Hyn\Tenancy\Contracts\Hostname` contract as argument not the concrete implementation.

---
__Information__

- hyn/multi-tenant version: 5.6
- laravel version: 7.2.2
- database driver and version: mysql 5.7
- webserver software and version:
- php version: 7.4.1

**Comment by lengletremy** [comment]
Same problem for me

**Comment by KazutakaYamane** [comment]
I got same problem and solve it,
tenancy/multi-tenant do **NOT** cause this error,  we need upgrade our code follow by [this part](https://laravel.com/docs/7.x/upgrade#symfony-5-related-upgrades) of laravel 7.x upgrade guide.

**Comment by id1385** [comment]
Same problem for me

**Comment by fletch3555** [comment]
For anyone having this issue, can you confirm whether your Hostname class `extends Hyn\Tenancy\Models\Hostname`? (If not, it should)

**Comment by catalinbuletin** [comment]
Hi @fletch3555,

I was not extending the `Hyn\Tenancy\Models\Hostname`. I was implementing the `\Hyn\Tenancy\Contracts\Hostname`.

By extending the model as you said it's working fine. But i'm not so sure we should have to extend the model when the package also provides in interface for it.

Thanks for the support.
