### ISSUE TITLE
whereJsonContains method is not working in model

### ISSUE THREAD

**Issue by ayman-elmalah** [hyn/multi-tenant#916]
__Description__
I'm using this package for single database and multi domains
i need to use whereJsonContains query method with model
i do the query Model::whereJsonContains('field', value)->get();

in main domain it's working good
in tenant domain it's not working

..

---

__Actual behavior__
Not the same response on system and tenant
..

__Expected behavior__
The same response on system and tenant
..

---
__Information__

- hyn/multi-tenant version: 5.5.*
- laravel version: 6.2
- database driver and version:
- webserver software and version:
- php version:

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by ArlonAntonius** [comment]
Hi there,

I guess you already solved this? :)
