### ISSUE TITLE
Composer require 5.6, but there is no documentation

### ISSUE THREAD

**Issue by magarrent** [hyn/multi-tenant#921]
When you run:

`composer require hyn/multi-tenant`

It downloads the version 5.6, but there is no **Documentation** for that version, either "5.5", I supose that is similar to the 5.4. If there is no documentation yet, please in the 5.4 docs put the version in the composer require

**Comment by anwarx4u** [comment]
I agree with your advice. I also got the same problem!

**Comment by Bibendus83** [comment]
They should be the same but 5.5 supports laravel 6.0 while 5.6 supports laravel 7.0

**Comment by fletch3555** [comment]
Apologies for the delay in (official) response.  @Bibendus83 is correct.  We're 100% slacking on the docs side, I will admit that.  The good news is that other than a couple small bugfixes and the version updates, there were no changes between 5.4 and 5.6.  5.5 added support for Laravel 6, and 5.6 added support for Laravel 7.  We'll get to the docs at some point.
