### ISSUE TITLE
how to manage tenant hosting plan (control resources usage) ?

### ISSUE THREAD

**Issue by id1385** [hyn/multi-tenant#922]
hi
i am creating chat tenant app with this package and laravel.
i want to control tenant usage of h.d.d , cpu  , ram how can do it ?
example tenant one buy plan X that have 5 GB hdd and tenant cant use more that 5 gb
how can ? tnx

**Comment by ArlonAntonius** [comment]
Hi there,

That feels like something really outside the scope of this package. You would really have to look at creating some of your own custom logic for such a thing.

**Comment by id1385** [comment]
> That feels like something really outside the scope of this package. You would really have to look at creating some of your own custom logic for such a thing.

yes i know but i need this because we use one app instance and cant make container for every user
Have an idea ? or help

**Comment by ArlonAntonius** [comment]
Sorry, like I said this is really something outside of the scope of this package.

I recommend you to look for packages outside of this one to that case of that specific part.
