### ISSUE TITLE
General error: 1805 Column count of mysql.user is wrong. Expected 45, found 48. The table is probably corrupted

### ISSUE THREAD

**Issue by amirakbulut** [hyn/multi-tenant#923]
I installed the package and tried to create my first website using the following code:

```
use Illuminate\Support\Facades\Route;
use Hyn\Tenancy\Models\Website;
use Hyn\Tenancy\Contracts\Repositories\WebsiteRepository;

Route::get('/add', function () {
    $website = new Website;
    app(WebsiteRepository::class)->create($website);
    dd($website->uuid); // Unique id
});

```

Then I got the error:

```
SQLSTATE[HY000]: General error: 1470 String '0daaa7d2-97be-4b41-914a-83d6fc9ef37d' is too long for user name (should be no longer than 32) (SQL: CREATE USER IF NOT EXISTS `0daaa7d2-97be-4b41-914a-83d6fc9ef37d`@'127.0.0.1' IDENTIFIED BY 'b40b7a76226d0ae4922123dc79cdc3f9')

```

I solved it by setting `LIMIT_UUID_LENGTH_32` to `true` in my ENV file. But now I get the following error:

https://flareapp.io/share/KPg3edPa#F57

Anyone that knows what I'm missing or doing wrong?

**Comment by amirakbulut** [comment]
Anyone?

**Comment by drbyte** [comment]
All my googling for `1805 Column count of mysql.user is wrong.` points to posts that indicate where authors say that their mysql database software version had been upgraded but their mysql database content had not, and that running the script provided by MySQL resolved it for them.

I don't think this specific error has anything to do with this package, but rather is a reflection of a problem condition in your local/server database.

**Comment by amirakbulut** [comment]
> All my googling for `1805 Column count of mysql.user is wrong.` points to posts that indicate where authors say that their mysql database software version had been upgraded but their mysql database content had not, and that running the script provided by MySQL resolved it for them.
> 
> I don't think this specific error has anything to do with this package, but rather is a reflection of a problem condition in your local/server database.

Thank you. Updated my mysql version (moved from using Xampp to Laragon), and it's working now!
