### ISSUE TITLE
Tenants not resolved inside of the App\Console\Kernel@schedule method 

### ISSUE THREAD

**Issue by sasokovacic** [hyn/multi-tenant#927]
__Description__

I want to run scheduled tasks for tenants. I've copied code from the documentation (https://tenancy.dev/docs/hyn/5.4/laravel-scheduler) and it's not working. Tenant is not resolved in the schedule() method of the App\Console\Kernel class.

---

__Actual behavior__

The if (app(\Hyn\Tenancy\Environment::class)->tenant()) { is never executed because tenant() method returns null. A tenant is only resolved inside of the before() method.

    protected function schedule(Schedule $schedule)
    {
        $schedule
            ->command(RemindUsersAboutEntityControlDeadlineCommand::class)
            ->everyMinute()
            ->before(function (Schedule $schedule) {
                $tenant = app(\Hyn\Tenancy\Environment::class)->tenant();
                dump($tenant->id); // Here a tenant is resolved
            });

        // app(\Hyn\Tenancy\Environment::class)->tenant() always returns null
        if (app(\Hyn\Tenancy\Environment::class)->tenant())
        {            
            // This is never executed
        } else {
            // This is always executed
        }
    }

__Expected behavior__

Tenants should be resolved inside the App\Console\Kernel@schedule method as shown in the documentation.

---
__Information__

- hyn/multi-tenant version: 5.4.5
- laravel version: 5.8.37
- database driver and version: MariaDB 10.4.12
- webserver software and version: Nginx 1.16.1
- php version: 7.4.2

**Comment by Bibendus83** [comment]
You should post your stack trace or it's difficult to find what's the problem.

**Comment by fletch3555** [comment]
You're not identifying a tenant before your `if` conditional.  The `before()` is only called before the command listed in `$schedule->command()` is run.  They run in different contexts.

**Comment by bkintanar** [comment]
Closing this issue. If you are still having issues with the package, please create a new issue. Thank you
