### ISSUE TITLE
Error in SQL

### ISSUE THREAD

**Issue by Technocraftindustries** [hyn/multi-tenant#929]
__Description__

..Error while generation key. 

---

__Actual behavior__

..I am trying to run command " php artisan key:generate ". After running this command key should be generated but I am getting error. 

__Expected behavior__

.. While running the command to generate key following error I am getting,
" In DatabaseManager.php line 140:
  Database [MariaDB] not configured "

---
__Information__

- hyn/multi-tenant version:
- laravel version:
- database driver and version:
- webserver software and version:
- php version:

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by Bibendus83** [comment]
I think that's unrelated to hyn.
Check that you correctly configured your `config\database.php` file that probably contains a misconfigured key named `MariaDB`.

**Comment by fletch3555** [comment]
That error means you have something in your code looking for a connection named "MariaDB".  As @Bibendus83 said, it's likely unrelated to this package.  Also, you haven't provided any version info or configs, so we can't help you there.  If you need further help, please ask on our discord
