### ISSUE TITLE
delete database + hostnames + tenant folder when website deleted

### ISSUE THREAD

**Issue by id1385** [hyn/multi-tenant#930]
hi 
i use last version of this package 

When I delete a record from websites, the information on that website, which includes the database and files and dbuser and ..., is not deleted 

`        Website::query()->findOrFail(request('website_id'))->delete();
`
I saw in the settings that there is a place for auto delete db and user db not not woking ...

did I make a mistake?

**Comment by fletch3555** [comment]
https://github.com/tenancy/multi-tenant/blob/5.x/src/Repositories/WebsiteRepository.php#L143 will solve this.
