### ISSUE TITLE
Output buffer problem on website Created event

### ISSUE THREAD

**Issue by sasokovacic** [hyn/multi-tenant#934]
When I create a new tenant and the WebsiteEvent event is emitted, the script outputs a string of 8 characters. After I return the created website in the json response, the json payload is not parsed because of this string.

This happens in the Hyn\Tenancy\Repositories@create method on the line where the Created event is emitted:
`
    $this->emitEvent(
        new Events\Created($website)
    );
`

If I clean the output buffer after the event, everything works as it should

     ob_start();

     $this->emitEvent(
        new Events\Created($website)
    );

    $output = ob_get_contents();
    
    ob_end_clean();

    var_dump($output); # Here I get this output: string(8) "        "

---
__Information__

- hyn/multi-tenant version: 5.4.*
- laravel version: 5.8.*
- database driver and version: mariadb-10.4
- webserver software and version: nginx-stable
- php version: 7.4.2

**Comment by sasokovacic** [comment]
Sorry guys... My mistake. One migration file had spaces before the <?PHP tag.
This one was hard to find. Spend a few hours to find out.

**Comment by ArlonAntonius** [comment]
Glad you figured it out 😊
