### ISSUE TITLE
Manage Tenancy database form system admin

### ISSUE THREAD

**Issue by cptiwari20** [hyn/multi-tenant#935]
__Description of your feature__
Is there any way that I can fetch the data from the tenancy databases. I failed to find any features or queries regarding this?

I am trying to fetch the tenancy database data using laravel APIs, but the problem is that the API needs some kind of authentication for responding and sending the required data. 

- hyn/multi-tenant version:^5.5
- laravel version:7.0

**Comment by fletch3555** [comment]
Manually identify the tenant, then run your queries.
