### ISSUE TITLE
How to remove/uninstall tenancy from Laravel application?

### ISSUE THREAD

**Issue by sunnyshingala** [hyn/multi-tenant#936]
__Description__

How to remove this module from Laravel application?
..

---
__Information__

- hyn/multi-tenant version: 5.4
- laravel version: 7
- database driver and version: 
- webserver software and version: 
- php version: 7.3

---

**Comment by fletch3555** [comment]
There's nowhere near enough information provided here.  Please ask questions like this in our discord or forum
