### ISSUE TITLE
move to another hosting

### ISSUE THREAD

**Issue by prg-hussam** [hyn/multi-tenant#950]
Hello

We have moved to a new hosting and we have export all database 
but we facing a problem in tenants databases 
Access denied for user 'd5a53392a8a644929b583fbaead0e3d7'@'localhost' (using password: YES) (SQL: select * from `settings` where `key` = default_locale limit 1) 

Is there a place where you store databases credentials ? 

thanks

**Comment by bkintanar** [comment]
db credentials are being generated automatically on the fly. and it takes into consideration your APP_KEY or TENANCY_KEY. so if you've changed that between host, i think it's best to copy the old key and try if you can access the db.

**Comment by prg-hussam** [comment]
THNAKS

**Comment by bkintanar** [comment]
lol! did it work?

**Comment by prg-hussam** [comment]
yes its working thanks :) 😊

**Comment by bkintanar** [comment]
thanks for confirming!

**Comment by bkintanar** [comment]
by the way https://github.com/tenancy/tenancy has been released, maybe you could check it out some time.
