### ISSUE TITLE
Separating Database from Application is giving Issues.

### ISSUE THREAD

**Issue by Lordwales** [hyn/multi-tenant#957]
We currently use tenancy package for one of our application and we would like to separate our database server from our Application but Hyn wont allow that. Something like this
![download](https://user-images.githubusercontent.com/16002388/90127691-7c941d00-dd5d-11ea-8451-a052a3da2ca4.png)
. Is there a work around for this? 

Thanks in advance .

**Comment by johnzon** [comment]
I had similar problem. Migration is filing because HNY is creating the tenant user with the IP address of the database server causing a permission issue. HNY should create user as 'user@%'

**Comment by fletch3555** [comment]
Apologies for the delay.  This has been asked and answered a few times now (here's one example #932, though not a thorough explanation there).  Hyn supports it, but with an extra step.  Not great, but we're not putting a ton of effort into hyn right now.

**Comment by marnickmenting** [comment]
I added some sample code here: https://github.com/tenancy/multi-tenant/pull/932
