### ISSUE TITLE
Add support for Laravel 8

### ISSUE THREAD

**Issue by crjhoan** [hyn/multi-tenant#960]
__Description of your feature__

Laravel 8 includes some very good improvements and new features, it would be nice to be able to update our projects that include hyn/multi-tenant to Laravel 8

---

__Proposed behavior__

Works with Laravel 8

__Current behavior__

Not compatible with laravel 8

__Information__

- laravel version: 8.0

**Comment by ArlonAntonius** [comment]
Would love to see a PR for this, but at this moment we're first updating tenancy/tenancy

**Comment by mikebronner** [comment]
@ArlonAntonius Asked and given :)
