### ISSUE TITLE
SQL error during installation

### ISSUE THREAD

**Issue by simonvirag** [hyn/multi-tenant#971]
Hi!

I try to intsall athe package to my laravel page but got the next erro during the installation:

```

> Migrating: 2019_09_15_000010_create_tenants_table
> 
>    Illuminate\Database\QueryException
> 
>   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null) default character set utf8 collate 'utf8_unicode_ci'' at line 1 (SQL: create table `tenants` (`id` varchar(191) not null, `created_at` timestamp null, `updated_at` timestamp null, `data` json null) default character set utf8 collate 'utf8_unicode_ci')
> 
>   at E:\ebrepo\Ebnyilvantarto\vendor\laravel\framework\src\Illuminate\Database\Connection.php:678
>     674▕         // If an exception occurs when attempting to run a query, we'll format the error
>     675▕         // message to include the bindings with SQL, which will make this exception a
>     676▕         // lot more helpful to the developer instead of just the database's errors.
>     677▕         catch (Exception $e) {
>   ➜ 678▕             throw new QueryException(
>     679▕                 $query, $this->prepareBindings($bindings), $e
>     680▕             );
>     681▕         }
>     682▕
> 
>   1   E:\ebrepo\Ebnyilvantarto\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDO\Exception.php:18
>       Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null) default character set utf8 collate 'utf8_unicode_ci'' at line 1")
> 
>   2   E:\ebrepo\Ebnyilvantarto\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:83
>       Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
> 


My configuration is:
        "php": "^7.3|^8.0",
        "coreui/coreui": "3.2.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "jeroennoten/laravel-adminlte": "^3.5",
        "laravel/framework": "^8.12",
        "laravel/jetstream": "^1.6",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.1",
        "livewire/livewire": "^2.0",
        "stancl/tenancy": "^3.4"


Thank you in advance!
Virag
```
__Actual behavior__

..

__Expected behavior__

..

---
__Information__

- hyn/multi-tenant version:
- laravel version:
- database driver and version:
- webserver software and version:
- php version:

---

__tenancy.php config__

```php

```

__webserver.php config__

```php

```

---

__Error log__

```text

```

**Comment by drbyte** [comment]
You didn't post your `database driver and version` details.

Seems like perhaps you're using a very old MySQL version, or other database engine, that doesn't support JSON fields?

**Comment by simonvirag** [comment]
Hi!

I changed the tenant migration file, and the default charset null solved the problem

> > class CreateTenantsTable extends Migration
> >      public function up(): void
> >     {
> >          Schema::create('tenants', function (Blueprint $table) {
> >              $table->string('id')->primary();
> >  
> >              // your custom columns may go here
> >  
> >              $table->timestamps();
> >              $table->json('data')->charset(null)->nullable();
> >          });
> >      }
> >  
> >      /**
> >       * Reverse the migrations.
> >       *
> >       * @return void
> >       */
> >      public function down(): void
> >      {
> >         Schema::dropIfExists('tenants');
> >      }
> >  }
> 

Thank you!

**Comment by drbyte** [comment]
That feels like a "bandage" instead of a proper "fix".  Be careful about using that in production.

**Comment by simonvirag** [comment]
Ok, tank you, I will investigate it later.

**Comment by drbyte** [comment]
Tip: If you feel this issue is resolved, please click "Close" below to make things easier for the github project owner!
