### ISSUE TITLE
Environment Class is stuck on Tenant

### ISSUE THREAD

**Issue by publicdesigners** [hyn/multi-tenant#982]
Hi All,

Firstly what a great package really enjoyed working with it.
I have seemed to have broken my app by forcing the app to use the tenant connection:

https://tenancy.dev/docs/hyn/5.6/identification
https://tenancy.dev/docs/hyn/5.6/connections

I would like to get the app back to how it was on the default install i.e. using the system connection then switch automatically to the tenants. I know the app has now bound the environment class to the Laravel container "tenant" how would i go about switching it back to "system"?

I know i will have to call a boot function in the AppServiceProvider.php but from the documentation i can't figure out the code to switch it to system?

Thanks

**Comment by ogunsakin01** [comment]
Hi, I think you should remove the force identification and allow auto identification in your config/tenancy.php. Also separate your tenant and system models into different folders and make use of UsesSystemConnection or UsesTenantConnection traits on your system or tenant models accordingly.

**Comment by publicdesigners** [comment]
Hi, Thanks for the reply. This is the issue i have removed the force identification and the auto identification is set to true. But the app still uses tenant instead of system?

**Comment by ogunsakin01** [comment]
When you say uses tenant, do you mean the routes or database connection or both? If you were previously forcing the tenant connection in you AppServiceProvider, you will need to run cache:clear and config:cache command afterwards.

**Comment by publicdesigners** [comment]
Yes cleared app caches multiple times including browser, just found something out! The app works normally in chrome, firefox but its only safari that i'm getting this issue!!!! Launched the app to a live environment and that works in all browsers too.

I expect it might be session or an issue with safari caching localhost (swapping browser for now) but thanks for you input and help OgunsakinDamilola

**Comment by ogunsakin01** [comment]
Oh,great. I am glad it's all good now.
