### ISSUE TITLE
An argument with name "class" already exists.

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [hyn/multi-tenant#987]
Latest release of `laravel/framework` introduced a bug when `tenancy/multi-tenant` is in use.

The specific PR that caused this bug: https://github.com/laravel/framework/pull/36513

Locking Laravel to v8.30.1 resolves the issue.

Running any Artisan command will result in:

__Actual behavior__
```
An argument with name "class" already exists.
```

__Expected behavior__

Artisan completes successfully.

__Information__

- hyn/multi-tenant version: 5.7.0
- laravel version: 8.32.1
- database driver and version: MySQL 
- webserver software and version:
- php version: 7.4

**Comment by bkintanar** [comment]
Fixed by #989
