### ISSUE TITLE
Problem When Creating a Tenant

### ISSUE THREAD

**Issue by WellingtonCarneiroBarbosa** [hyn/multi-tenant#994]
I am getting this exception: 
\n
   BadMethodCallException \n
\n
  Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database()\n
\n
  at C:\server\htdocs\barber-premium-rest-api\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:50\n
     46▕      * @throws \BadMethodCallException\n
     47▕      */\n
     48▕     protected static function throwBadMethodCallException($method)\n
     49▕     {\n
  ➜  50▕         throw new BadMethodCallException(sprintf(\n
     51▕             'Call to undefined method %s::%s()', static::class, $method\n
     52▕         ));\n
     53▕     }\n
     54▕ }\n
\n
  • Bad Method Call: Did you mean Stancl\Tenancy\Database\Models\Tenant::update() ? \n
\n
  1   C:\server\htdocs\barber-premium-rest-api\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:36\n
      Illuminate\Database\Eloquent\Model::throwBadMethodCallException("database")\n
\n
  2   C:\server\htdocs\barber-premium-rest-api\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1890\n
      Illuminate\Database\Eloquent\Model::forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), "database", [])\n
"""

while i am trying to run \App\Models\Tenant::create(); command

PHP 7.3.27

LARAVEL 8.x

**Comment by IsaacHatilima** [comment]
I am having the same issue. I followed the quick start
